### ISSUE TITLE
Enable SpotBugs in Google Cloud Platform (GCPIO) module

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18115]
Imported from Jira [BEAM-6889](https://issues.apache.org/jira/browse/BEAM-6889). Original Jira may contain additional context.
Reported by: iemejia.
Subtask of issue #18114

**Comment by Abacn** [comment]
already enabled: https://ci-beam.apache.org/job/beam_PreCommit_Java_GCP_IO_Direct_Cron/1564/spotbugs/
