### ISSUE TITLE
Update Jenkins to provide granular signals for python sdk

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18146]
clean separation of tests. Just as post-commits are separate, there's work to get multiple signals in pre-commit, run them only if a particular component changed (i.e., don't run stuff unnecessarily, etc.).

Imported from Jira [BEAM-1364](https://issues.apache.org/jira/browse/BEAM-1364). Original Jira may contain additional context.
Reported by: altay.

**Comment by Abacn** [comment]
Obsolete. Migrating Jenkins to GitHub Action
