### ISSUE TITLE
Maven should be able to build and run tests across multiple languages

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18143]
We are working on splitting python sdk into multiple packages and it'll be a good time to invest in getting a central build tool to work across languages so that we can share common test specs, common proto etc.

PS: Please revert the spec duplication https://github.com/apache/beam/pull/1964 once it can be shared.

Imported from Jira [BEAM-1449](https://issues.apache.org/jira/browse/BEAM-1449). Original Jira may contain additional context.
Reported by: sb2nov.

**Comment by Abacn** [comment]
obsolete. beam repo has been migrated to use gradle
