### ISSUE TITLE
Need Jenkins tests run outside of Google environments

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18252]
Now that TravisCI no longer runs, we no longer have coverage for running tests which execute outside of a Google environment which means that application default credentials and google project will always be found and we will never test code paths for developers who have never setup any kind of Google cloud integration on their development machine.

Imported from Jira [BEAM-2131](https://issues.apache.org/jira/browse/BEAM-2131). Original Jira may contain additional context.
Reported by: lcwik.

**Comment by Abacn** [comment]
Jenkins tasks obsolete for now
