### ISSUE TITLE
Python SDK should support SQL connector like JDBC IO

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18286]
It would be great if SQL support could be added to Python SDK similar to JDBC IO in Java SDK.

May be SQLAlchemy Core could be used to support multiple databases and dialects to provide unified API analogous to JDBC?

Imported from Jira [BEAM-2097](https://issues.apache.org/jira/browse/BEAM-2097). Original Jira may contain additional context.
Reported by: rajas.abhyankar.

**Comment by Abacn** [comment]
did by xlang sql transform
