### ISSUE TITLE
Tests on MacOS

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18283]
After removal of Travis testing, we lost the ability to test on Macs. I am wondering if this is possible on Jenkins. A simple web search for "cloud macos" shows many promising results.

cc: [~davor]

Imported from Jira [BEAM-2121](https://issues.apache.org/jira/browse/BEAM-2121). Original Jira may contain additional context.
Reported by: altay.

**Comment by Abacn** [comment]
exercised by github actions
