### ISSUE TITLE
DatastoreIO.Write fails multiple mutations of same entity

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18521]
When streaming messages from a source that doesn't guarantee once-only-delivery, but has at-least-once-delivery, then the DatastoreIO.Write will throw an exception which leads to Dataflow retrying the same commit multiple times before giving up. This leads to a significant bottleneck in the pipeline, with the end-result that the data is dropped. This should be handled better.

There are a number of ways to fix this. One of them could be to drop any duplicate mutations within one batch. Non-duplicates should also be handled in some way. Perhaps a use NON-TRANSACTIONAL commit, or make sure the mutations are commited in different commits.

```

com.google.datastore.v1.client.DatastoreException: A non-transactional commit may not contain multiple
mutations affecting the same entity., code=INVALID_ARGUMENT
        com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:126)

       com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:169)
        com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:89)

       com.google.datastore.v1.client.Datastore.commit(Datastore.java:84)
        org.apache.beam.sdk.io.gcp.datastore.DatastoreV1$DatastoreWriterFn.flushBatch(DatastoreV1.java:1288)

       org.apache.beam.sdk.io.gcp.datastore.DatastoreV1$DatastoreWriterFn.processElement(DatastoreV1.java:1253)


```

Imported from Jira [BEAM-3039](https://issues.apache.org/jira/browse/BEAM-3039). Original Jira may contain additional context.
Reported by: routsi.

**Comment by Abacn** [comment]
The issue still present. Increase to P2 and trying to fix.

**Comment by Abacn** [comment]
.take-issue
