### ISSUE TITLE
Fn API merging window support

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18590]
The Fn API should support merging windows. Detailed design TBD.

Once design is ready, expand subtasks similarly to BEAM-2822.

Imported from Jira [BEAM-2914](https://issues.apache.org/jira/browse/BEAM-2914). Original Jira may contain additional context.
Reported by: herohde.

**Comment by kennknowles** [comment]
The following subtask(s) are associated with this issue: #18591

**Comment by y1chi** [comment]
This should have been resolved.

**Comment by y1chi** [comment]
See https://github.com/apache/beam/blob/59d5e9b24e378a4d3efc4b00093e6a95dc308668/model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/beam_runner_api.proto#L313

and 
https://github.com/apache/beam/blob/59d5e9b24e378a4d3efc4b00093e6a95dc308668/model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/beam_runner_api.proto#L1000
