### ISSUE TITLE
Make type inference compatible with Python 3.6

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18612]
Starting in Python 3.6, instructions always use two bytes. As the Python SDKs implementation of trivial type inference relies on these disassembled instructions, typehints/trivial_inference.py should be updated to be compatible with this change. This can be done by comparing https://github.com/python/cpython/blob/3.6/Lib/dis.py to https://github.com/python/cpython/blob/3.5/Lib/dis.py

Imported from Jira [BEAM-3380](https://issues.apache.org/jira/browse/BEAM-3380). Original Jira may contain additional context.
Reported by: luke-zhu.

**Comment by Abacn** [comment]
.close-issue not_planned
