### ISSUE TITLE
Some errors related to GCP in pip install -e .[gcp]

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18779]
When installing Beam with GCP options from source, the following errors pop out:

https://pastebin.com/vrWWvF9y

The installation goes through, but the errors are confusing, and may confuse users and contributors.

Imported from Jira [BEAM-4487](https://issues.apache.org/jira/browse/BEAM-4487). Original Jira may contain additional context.
Reported by: pabloem.

**Comment by Abacn** [comment]
.close-issue not_planned
