### ISSUE TITLE
Non-working Python 3 versions are installable on PyPI

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18844]
Beam does not currently support Python 3, however, it's possible to install _some versions_ from PyPI / Warehouse under Python 3 today.  (It appears the config was fixed after 2.2.0 - https://github.com/apache/beam/commit/807b4bcefd877440c12f7fc3b401446e21899904.)

This affects the following 5 versions:
```

$ pip3 install apache-beam==-1
Collecting apache-beam==-1
 Could not find a version that satisfies
the requirement apache-beam==-1 (from versions: 0.6.0, 2.0.0, 2.1.0, 2.1.1, 2.2.0)
No matching distribution
found for apache-beam==-1
```

This is a confusing experience for users (customers) to discover that it's incompatible only on import after installing the package (and not reading the docs) via the error message:
```

RuntimeError: The Apache Beam SDK for Python is supported only on Python 2.7. It is not supported on
Python [sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)].
```

Since it's not compatible anyway, it's confusing that the non-working package versions are installable.

I don't think there's an easy way to remove just the Python 3 build from the wheels or in the PyPI GUI.  As far as I can tell, this would require rebuilding **** re-uploading the Python 2 wheels for affected versions.

Imported from Jira [BEAM-4025](https://issues.apache.org/jira/browse/BEAM-4025). Original Jira may contain additional context.
Reported by: tedmiston.

**Comment by CAM-Gerlach** [comment]
This is presumably no longer a valid issue, now that Apache Beam has supported Python 3 for a number of years and dropped Python 2 support a couple years ago, so presumably it should be closed, no?

**Comment by kennknowles** [comment]
Thanks for noticing!

**Comment by CAM-Gerlach** [comment]
Sure! If the milestone needs to be set, maybe it should be set to 2.14.0, which is the first version with Python 3 support?

**Comment by kennknowles** [comment]
Good thought. I guess we never created milestones going back. I think we can just close without a milestone, as it is old enough people are probably not reviewing those release notes much.

**Comment by CAM-Gerlach** [comment]
I figure it's harmless, but just in case—after commenting on this issue I got two GH Actions failure notifications:

* https://github.com/apache/beam/actions/runs/4169541700
* https://github.com/apache/beam/actions/runs/4169541699
