### ISSUE TITLE
Increase test coverage of Perfkit benchmark for Python case

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18985]
Perfkit benchmark is defined in PerfKitBenchmarker repo (mostly [here](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/beam_benchmark_helper.py) and [here](https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/linux_benchmarks/beam_integration_benchmark.py)) but not enough test coverage to verify changes to the benchmark or it's utils. Breakage can be surfaced only when scheduled Beam Postcommit job runs which will directly affect performance measurement.

We want to add more tests starting from unit tests to cover missing branches and utils like Python benchmark.

Imported from Jira [BEAM-5329](https://issues.apache.org/jira/browse/BEAM-5329). Original Jira may contain additional context.
Reported by: markflyhigh.

**Comment by Abacn** [comment]
performance test has been migrated out from perfkitbenchmarker
