### ISSUE TITLE
runMobileGamingJavaDirect Aborted after 100 minutes

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18989]
[https://builds.apache.org/job/beam_PostRelease_NightlySnapshot/350/](https://builds.apache.org/job/beam_PostRelease_NightlySnapshot/350/)

[https://builds.apache.org/job/beam_PostRelease_NightlySnapshot/342/console](https://builds.apache.org/job/beam_PostRelease_NightlySnapshot/342/console)

[https://builds.apache.org/job/beam_PostRelease_NightlySnapshot/340/](https://builds.apache.org/job/beam_PostRelease_NightlySnapshot/340/)

[https://builds.apache.org/job/beam_PostRelease_NightlySnapshot/337/](https://builds.apache.org/job/beam_PostRelease_NightlySnapshot/337/)

 

 
 bq query SELECT table_id FROM beam_postrelease_mobile_gaming.__TABLES_SUMMARY__
 Build timed out (after 100 minutes). Marking the build as aborted.
 Build was aborted
 Finished: ABORTED

Imported from Jira [BEAM-5242](https://issues.apache.org/jira/browse/BEAM-5242). Original Jira may contain additional context.
Reported by: apilloud.

**Comment by Abacn** [comment]
close as obsolete
