### ISSUE TITLE
runMobileGamingJavaDirect FAILED SocketException: Connection reset

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#18991]
[https://builds.apache.org/job/beam_PostRelease_NightlySnapshot/349/](https://builds.apache.org/job/beam_PostRelease_NightlySnapshot/349/)

[https://builds.apache.org/job/beam_PostRelease_NightlySnapshot/347/](https://builds.apache.org/job/beam_PostRelease_NightlySnapshot/347/)

 *04:19:41* \> Task :beam-runners-direct-java:runMobileGamingJavaDirect FAILED*04:19:41* Aug 23, 2018 11:19:32 AM org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$DatasetServiceImpl createTable*04:19:41* INFO: Trying to create BigQuery table: apache-beam-testing:beam_postrelease_mobile_gaming.leaderboard_DirectRunner_user*04:19:41* bq query SELECT table_id FROM beam_postrelease_mobile_gaming.__TABLES_SUMMARY__*04:19:41* [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project word-count-beam: An exception occured while executing the Java class. java.net.SocketException: Connection reset -\> [Help 1]

Imported from Jira [BEAM-5241](https://issues.apache.org/jira/browse/BEAM-5241). Original Jira may contain additional context.
Reported by: apilloud.

**Comment by Abacn** [comment]
stale issue
