### ISSUE TITLE
[beam_PostCommit_Java_GradleBuild][org.apache.beam.examples.subprocess.ExampleEchoPipelineTest.testExampleEchoPipeline][Flake] .sh script: text file busy.

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19101]
Sample failure: [https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/1375/testReport/junit/org.apache.beam.examples.subprocess/ExampleEchoPipelineTest/testExampleEchoPipeline/](https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/1375/testReport/junit/org.apache.beam.examples.subprocess/ExampleEchoPipelineTest/testExampleEchoPipeline/)

Sample relevant log:

org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.Exception: java.io.IOException: Cannot run program "/tmp/test-Echoo1519764280436328522/test-EchoAgain3143210610074994370.sh": error=26, Text file busy

Imported from Jira [BEAM-5286](https://issues.apache.org/jira/browse/BEAM-5286). Original Jira may contain additional context.
Reported by: boyuanz.

**Comment by damccorm** [comment]
Closing since it doesn't seem like this postcommit suite even exists anymore
