### ISSUE TITLE
Move DataflowRunnerHarness class underneath org.apache.beam namespace

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19114]
com/google/cloud/dataflow/worker/DataflowRunnerHarness.class should appear underneath the org.apache.beam.runners.dataflow.worker namespace.

Imported from Jira [BEAM-6137](https://issues.apache.org/jira/browse/BEAM-6137). Original Jira may contain additional context.
Reported by: lcwik.

**Comment by Abacn** [comment]
obsolete, JRH has been teardown (#24515)
