### ISSUE TITLE
Seed Job Sometimes Fails With "No Such Property" error

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19149]
E.g.

https://builds.apache.org/job/beam_SeedJob/2775/console

Processing DSL script job_PreCommit_Go.groovy
ERROR: (PrecommitJobBuilder.groovy, line 106) No such property: ghprbPullId for class: javaposse.jobdsl.dsl.helpers.step.GradleContext
Sending e-mails to: dev@beam.apache.org
Setting status of ccd2ec12dd473f7701ea08b83684920c0b41c8d4 to FAILURE with url https://builds.apache.org/job/beam_SeedJob/2775/ and message: 'FAILURE
 '

https://builds.apache.org/job/beam_SeedJob/2778/console

Sending e-mails to: dev@beam.apache.org
Setting status of f30b603a2fedea0a883af3b84bc4f0cf03776b8b to FAILURE with url https://builds.apache.org/job/beam_SeedJob/2778/ and message: 'FAILURE
 '

https://builds.apache.org/job/beam_SeedJob/2780/console

ERROR: (PrecommitJobBuilder.groovy, line 106) No such property: binding for class: javaposse.jobdsl.dsl.helpers.step.GradleContext
Sending e-mails to: dev@beam.apache.org
Setting status of e8dd90c71101bc532f384cf60ec890160bb055af to FAILURE with url https://builds.apache.org/job/beam_SeedJob/2780/ and message: 'FAILURE

Imported from Jira [BEAM-5877](https://issues.apache.org/jira/browse/BEAM-5877). Original Jira may contain additional context.
Reported by: herohde.

**Comment by Abacn** [comment]
no longer see
