### ISSUE TITLE
Optimise GCSFilesystem rename implementation

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19172]
`GCSFileSystem` implements a `rename()` with a `copy` and `delete` operation.

However, GCS has an [Objects: rewrite](https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite) which looks like it would be a metadata operation only and therefore has the potential to be much quicker.

Once BEAM-5036 is fixed IOs that write files will make use of a `rename` operation.

Imported from Jira [BEAM-5429](https://issues.apache.org/jira/browse/BEAM-5429). Original Jira may contain additional context.
Reported by: timrobertson100.

**Comment by Abacn** [comment]
.close-issue not_planned
Function already there. Outdated.
