### ISSUE TITLE
beam-runners-flink_2.11-job-server:validatesPortableRunner  failing due to "insufficient memory"

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19186]
For example,

[https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/231/](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/231/)

[https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/232/](https://builds.apache.org/job/beam_PostCommit_Java_PVR_Flink/232/)

 
*05:23:50* Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00007fb1b0689000, 12288, 0) failed; error='Cannot allocate memory' (errno=12)*05:23:50* Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00007fbce69aa000, 12288, 0) failed; error='Cannot allocate memory' (errno=12)*05:23:50* #*05:23:50* # There is insufficient memory for the Java Runtime Environment to continue.*05:23:50* # Native memory allocation (mmap) failed to map 12288 bytes for committing reserved memory.*05:23:50* # An error report file with more information is saved as:*05:23:50* # There is insufficient memory for the Java Runtime Environment to continue.*05:23:50* # /home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_PVR_Flink/src/runners/flink/job-server/hs_err_pid24488.log

 

Ankur, did something change recently that would cause Flink portable runner to OOM when running these tests ?

Imported from Jira [BEAM-5998](https://issues.apache.org/jira/browse/BEAM-5998). Original Jira may contain additional context.
Reported by: chamikara.

**Comment by Abacn** [comment]
obsolete
