### ISSUE TITLE
beam_PostCommit_Java_GradleBuild timing out (4 hours)

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19207]
I believe that this PR is the culprit: https://github.com/apache/beam/pull/7175
Example log: https://builds.apache.org/job/beam_PostCommit_Java_GradleBuild/2041/

Imported from Jira [BEAM-6171](https://issues.apache.org/jira/browse/BEAM-6171). Original Jira may contain additional context.
Reported by: udim.

**Comment by damccorm** [comment]
This job doesn't exist anymore and the postcommit has generally been split apart so we can safely close here
