### ISSUE TITLE
GCS path not working on extra packages

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19212]
GCS path was working in extra_packages option in 2.4.0 but when we upgraded to 2.7.0, it stopped working.  Looking at the code, it looked like extra_packages no longer support GCS.

 

This was the earlier commit that added GCS support:

https://github.com/apache/beam/commit/223543f5ed6b565c0754c41354244eb673fb1bc2

Imported from Jira [BEAM-5746](https://issues.apache.org/jira/browse/BEAM-5746). Original Jira may contain additional context.
Reported by: rajeshhegde.

**Comment by Abacn** [comment]
is duplicated by BEAM-11275 and fixed

.close-issue
