### ISSUE TITLE
Deduplicate constants

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19220]
apache_beam/runners/dataflow/internal/names.py
apache_beam/runners/portability/stager.py

has same constants defined in both files.

Imported from Jira [BEAM-5939](https://issues.apache.org/jira/browse/BEAM-5939). Original Jira may contain additional context.
Reported by: altay.

**Comment by yyy1000** [comment]
Could we close this issue because these two PRs have resolved it? (https://github.com/apache/beam/pull/13142) and (https://github.com/apache/beam/pull/6976)

**Comment by ZhengLin-Li** [comment]
> Could we close this issue because these two PRs have resolved it? (#13142) and (#6976)

I agree with you.
