### ISSUE TITLE
Slow DownloaderStream when reading from GCS

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19238]
DownloaderStream inherits io.RawIOBase, which by defaults reads io.DEFAULT_BUFFER_SIZE chunks in .readall(). This is causing extremely slow performance when invoking read() on handles returned by GcsIO().open().

The following code can take ~60 seconds to download a single 2MB file:

```

gcs = GcsIO()
t = time.time()
path = 'gs://my-bucket/my-2MB-file'
with gcs.open(path) as f:
  
 f.read()
duration = time.time() - t

```

This monkey patch makes the same download code take <1 second:

```

from apache_beam.io.gcp import gcsio
from apache_beam.io.filesystemio import DownloaderStream

def
downloader_stream_readall(self):
    """Read until EOF, using multiple read() call."""
    res = bytearray()

   while True:
        data = self.read(gcsio.DEFAULT_READ_BUFFER_SIZE)
        if not data:
   
        break
        res += data
    if res:
        return bytes(res)
    else:
        return
data

DownloaderStream.readall = downloader_stream_readall

```

Imported from Jira [BEAM-6027](https://issues.apache.org/jira/browse/BEAM-6027). Original Jira may contain additional context.
Reported by: andreasjansson.

**Comment by Abacn** [comment]
BEAM-6027 is fixed in #8553

.close-issue
