### ISSUE TITLE
PR 7130 causes transforms/util_test to fail

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19235]
http://github.com/apache/beam/pull/7130 seems to cause transforms/util_test to fail.

\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==
ERROR: test_reshuffle_sliding_window (__main__.ReshuffleTest)
\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--
BeamAssertException: Failed assert: [(1, [1, 2, 4]), (1, [1, 2, 4]), (2, [1, 2]), (2, [1, 2]), (3, [1]), (3, [1])] \== [(1, [1]), (1, [1]), (1, [2]), (1, [2]), (1, [4]), (1, [4]), (2, [1]), (2, [1]), (2, [2]), (2, [2]), (3, [1]), (3, [1])] [while running 'before_reshuffle/Match']

Imported from Jira [BEAM-6153](https://issues.apache.org/jira/browse/BEAM-6153). Original Jira may contain additional context.
Reported by: ccy.

**Comment by Abacn** [comment]
already fixed
