### ISSUE TITLE
Infrequent build timeout on beam7

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19269]
Found this issue when running Python ValidatesContainer test multiple times. Always timeout on beam7 when building docker image but pass on other nodes. see https://builds.apache.org/job/beam_PostCommit_Py_ValCont_PR/

From history of beam7 (https://builds.apache.org/computer/beam7/builds), builds that're in state aborted because of timeout and belong to different tests. Console output shows Gradle process was stuck without any error and job reach to Jenkins timeout at the end.

cc [~yifanzou]

Imported from Jira [BEAM-6570](https://issues.apache.org/jira/browse/BEAM-6570). Original Jira may contain additional context.
Reported by: markflyhigh.

**Comment by Abacn** [comment]
obsolete
