### ISSUE TITLE
beam_PreCommit_Python_Cron (test_error_traceback_includes_user_code) fails on fn_api_runner

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19285]
[https://builds.apache.org/job/beam_PreCommit_Python_Cron/806/consoleFull](https://builds.apache.org/job/beam_PreCommit_Python_Cron/806/consoleFull)

 
*04:31:26*     self.assertIn('second', message)*04:31:26* AssertionError: 'second' not found in 'Traceback (most recent call last):\n  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/apache_beam/runners/portability/fn_api_runner_test.py", line 466, in test_error_traceback_includes_user_code\n    p | beam.Create([0]) | beam.Map(first)  # pylint: disable=expression-not-assigned\n  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/apache_beam/pipeline.py", line 425, in __exit__\n    self.run().wait_until_finish()\n  File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/apache_beam/runners/portability/portable_runner.py", line 316, in wait_until_finish\n    self._job_id, self._state, self._last_error_message()))\nRuntimeError: Pipeline job-bac26fa2-acdc-4ee2-b2f3-d97b6dae6492 failed in state FAILED: start <DataInputOperation receivers=[ConsumerSet[Create/Read/Impulse.out0, coder=WindowedValueCoder[BytesCoder], len(consumers)=1]]\>\n'

Imported from Jira [BEAM-6400](https://issues.apache.org/jira/browse/BEAM-6400). Original Jira may contain additional context.
Reported by: altay.

**Comment by TheNeuralBit** [comment]
There are no instances of this in Jenkins history right now.
