### ISSUE TITLE
Java PreCommit failed continually owing to OOM on beam6

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19291]
[https://builds.apache.org/job/beam_PreCommit_Java_Cron/788/](https://builds.apache.org/job/beam_PreCommit_Java_Cron/788/)

[https://builds.apache.org/job/beam_PreCommit_Java_Cron/789/](https://builds.apache.org/job/beam_PreCommit_Java_Cron/789/)

[https://builds.apache.org/job/beam_PreCommit_Java_Cron/790/](https://builds.apache.org/job/beam_PreCommit_Java_Cron/790/)

[https://builds.apache.org/job/beam_PreCommit_Java_Cron/791/](https://builds.apache.org/job/beam_PreCommit_Java_Cron/791/)

[https://builds.apache.org/job/beam_PreCommit_Java_Cron/792/](https://builds.apache.org/job/beam_PreCommit_Java_Cron/792/)

https://builds.apache.org/job/beam_PreCommit_Java_Cron/793/

Imported from Jira [BEAM-6376](https://issues.apache.org/jira/browse/BEAM-6376). Original Jira may contain additional context.
Reported by: boyuanz.

**Comment by Abacn** [comment]
.close-issue not_planned
