### ISSUE TITLE
Python streaming test failed because cannot cancel the job

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19323]
apache_beam.examples.streaming_wordcount_it_test.StreamingWordCountIT

[https://builds.apache.org/job/beam_PostCommit_Python_Verify/6968/](https://builds.apache.org/job/beam_PostCommit_Python_Verify/6968/)

https://builds.apache.org/job/beam_PostCommit_Python_Verify/6955/

Failed to cancel this streaming job since it was not ready to cancel. After checking the console log, seems like the runner harness is waiting for sdk.

Imported from Jira [BEAM-6338](https://issues.apache.org/jira/browse/BEAM-6338). Original Jira may contain additional context.
Reported by: boyuanz.

**Comment by Abacn** [comment]
obsolete
