### ISSUE TITLE
GroupIntoBatches transform for Python SDK

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19356]
Add a PTransform that batches inputs to a desired batch size. Batches will contain only elements of a single key.

It should offer the same API as its Java counterpart: https://github.com/apache/beam/blob/11a977b8b26eff2274d706541127c19dc93131a2/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/GroupIntoBatches.java

Unlike BatchElements transform (https://github.com/apache/beam/blob/11a977b8b26eff2274d706541127c19dc93131a2/sdks/python/apache_beam/transforms/util.py#L461) GroupIntoBatches will use state to batch across bundles as well.

Imported from Jira [BEAM-6696](https://issues.apache.org/jira/browse/BEAM-6696). Original Jira may contain additional context.
Reported by: altay.

**Comment by Abacn** [comment]
already exists
