### ISSUE TITLE
./gradlew :beam-runners-google-cloud-dataflow-java:validatesRunner fails due to invalid GCS path

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19360]
The default root is gs://temp-storage-for-end-to-end-tests/ and the code adds a slash and then the test case name, so it results in two slashes in a row, rejected by the filesystem implementation.

Imported from Jira [BEAM-6715](https://issues.apache.org/jira/browse/BEAM-6715). Original Jira may contain additional context.
Reported by: kenn.

**Comment by Abacn** [comment]
fixed by #7901
