### ISSUE TITLE
Logs include exception="None\n" when there is no exception

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19385]
All python SDK logs emit an exception field even when there is no exception. Weirdly, the field is "None\n" with a trailing newline that does not appear in any other field. This field should be omitted when there is no exception, so that searches for "exception" will not return so many spurious results

Example from stackdriver logging in a python job using dataflow runner:

 jsonPayload: {
    exception: "None
" 
    job: "2019-03-28_18_01_16-4563580283031363654" 
    logger: "root:cloud_logging.py:EmitLogMessages" 
    message: "baz" 
    stage: "s01" 
    step: "EmitLogs" 
    thread: "132:139730156779264" 
    worker: "df2-cloud-logging-python\--03281801-ilme-harness-7sw5" 
}

Imported from Jira [BEAM-6941](https://issues.apache.org/jira/browse/BEAM-6941). Original Jira may contain additional context.
Reported by: edre.

**Comment by Abacn** [comment]
no longer observed. And this is handled in Dataflow but not Beam sdk

.close-issue
