### ISSUE TITLE
Remove oauth2client dependency

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19396]
This dependency is deprecated with a suggested upgrade path of: google-auth and oauthlib.

However, other dependencies (e.g. google-apitools and googledatastore) also depends on it.

Imported from Jira [BEAM-7352](https://issues.apache.org/jira/browse/BEAM-7352). Original Jira may contain additional context.
Reported by: altay.

**Comment by fpopic** [comment]
I believe this can be closed since https://github.com/apache/beam/pull/15004 was merged?
