### ISSUE TITLE
Allow for setMaxRetryJobs in BigQueryIO to be configurable

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19421]
The [BigQueryIO setMaxRetryJobs](https://github.com/apache/beam/blob/c02af609c49f268366cdecf680621e907700e59b/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.java#L2171) value is hard coded to 1000. It would be useful to have the 1000 set as default and add a method allowing the user to configure this value as desired. 

Imported from Jira [BEAM-7280](https://issues.apache.org/jira/browse/BEAM-7280). Original Jira may contain additional context.
Reported by: Ali T.

**Comment by dannikay** [comment]
.take-issue
