### ISSUE TITLE
beam-sdks-python-test-suites-tox-py35:sdist FAILED on clean branch

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19451]
Repro:
./gradlew lint :beam-sdks-python:docs
 
I tested this on a branch I just rebased from master, and the same issue is occurring. I also recreated the virtual env.
https://gradle.com/s/lnlmhu2cggreg
 
I deleted the build directories, but it still generates multiple files and fails. 

\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\--\---
\> Task :beam-sdks-python-test-suites-tox-py35:sdist FAILED
 
FAILURE: Build completed with 2 failures.
 
1: Task failed with an exception.
\--\--\--\--\---
* What went wrong:
Execution failed for task ':beam-sdks-python:sdist'.
\> Expected directory '/usr/local/google/home/ajamato/go/src/github.com/apache/beam/sdks/python/build' to contain exactly one file, however, it contains more than one file.
 
* Try:
Run with \--stacktrace option to get the stack trace. Run with \--info or \--debug option to get more log output. Run with \--scan to get full insights.
\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==
 
2: Task failed with an exception.
\--\--\--\--\---
* What went wrong:
Execution failed for task ':beam-sdks-python-test-suites-tox-py35:sdist'.
\> Expected directory '/usr/local/google/home/ajamato/go/src/github.com/apache/beam/sdks/python/test-suites/tox/py35/build' to contain exactly one file, however, it contains more than one file.
 
* Try:
Run with \--stacktrace option to get the stack trace. Run with \--info or \--debug option to get more log output. Run with \--scan to get full insights.
\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==\==
 
* Get more help at https://help.gradle.org
 
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '\--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings
 
BUILD FAILED in 17s
4 actionable tasks: 4 executed
 
Publishing build scan...
https://gradle.com/s/lnlmhu2cggreg

Imported from Jira [BEAM-6835](https://issues.apache.org/jira/browse/BEAM-6835). Original Jira may contain additional context.
Reported by: ajamato@google.com.

**Comment by Abacn** [comment]
.close-issue not_planned
