### ISSUE TITLE
Cleanup stale Jenkins jobs on UI

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19466]
Some Jenkins jobs are stale (in disable status) for a while due to many reasons (rename, one-time-testing, manually created). We can still see them on Jenkins UI (https://builds.apache.org/view/A-D/view/Beam/). Can anyone with permission make a cleanup?

According to [Apache Jenkins doc](https://cwiki.apache.org/confluence/display/INFRA/Jenkins#Jenkins-HowdoIgetanaccount), only people in hudson-jobadmin group can have account and do such things, and seems Kenn (as a PMC member) is already in the group. [~kenn] Can you help on this. Or if you add me ([~markflyhigh]) to the group, I'm happy to do the cleanup.

Few stale jobs that known to me:
	beam_PerformanceTests_Python
	beam_PerformanceTests_Python35

Imported from Jira [BEAM-7384](https://issues.apache.org/jira/browse/BEAM-7384). Original Jira may contain additional context.
Reported by: markflyhigh.

**Comment by Abacn** [comment]
did another round of cleanup.
