### ISSUE TITLE
apache_beam.io.parquetio_test.TestParquet is very flaky

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19473]
Hi [~heejong], I think you added these tests - could you please take a look?

Symptoms:
```

07:47:19 ======================================================================
07:47:19 ERROR: test_sink_transform_compressed_0
(apache_beam.io.parquetio_test.TestParquet)
07:47:19 ----------------------------------------------------------------------
07:47:19
Traceback (most recent call last):
07:47:19   File "/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Commit/src/sdks/python/apache_beam/io/parquetio_test.py",
line 105, in tearDown
07:47:19     shutil.rmtree(self.temp_dir)
07:47:19   File "/usr/lib/python2.7/shutil.py",
line 239, in rmtree
07:47:19     onerror(os.listdir, path, sys.exc_info())
07:47:19   File "/usr/lib/python2.7/shutil.py",
line 237, in rmtree
07:47:19     names = os.listdir(path)
07:47:19 OSError: [Errno 2] No such file
or directory: '/tmp/tmpEXNCgA'

```

Examples:
 [https://builds.apache.org/job/beam_PreCommit_Python_Commit/5186/consoleFull](https://builds.apache.org/job/beam_PreCommit_Python_Commit/5186/consoleFull)
 [https://builds.apache.org/job/beam_PreCommit_Python_Commit/5185/consoleFull](https://builds.apache.org/job/beam_PreCommit_Python_Commit/5185/consoleFull)

 

CC: [~Juta], [~boyuanz], [~udim]

Imported from Jira [BEAM-6871](https://issues.apache.org/jira/browse/BEAM-6871). Original Jira may contain additional context.
Reported by: tvalentyn.

**Comment by TheNeuralBit** [comment]
No flakes in Jenkins history currently, marking this fixed.
