### ISSUE TITLE
Upgrade some Beam dependencies

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19519]
Some dependencies need to be upgraded.

Imported from Jira [BEAM-7278](https://issues.apache.org/jira/browse/BEAM-7278). Original Jira may contain additional context.
Reported by: echauchot.

**Comment by kennknowles** [comment]
The following subtask(s) are associated with this issue: #19520, #19521, #19522

**Comment by lukecwik** [comment]
Closing parent task
