### ISSUE TITLE
[beam_PostCommit_Java] [PubsubReadIT.testReadPublicData] Timeout waiting on Sub

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19557]
_Use this form to file an issue for test failure:_
 * [Jenkins Job](https://builds.apache.org/job/beam_PostCommit_Java/2796/testReport/junit/org.apache.beam.sdk.io.gcp.pubsub/PubsubReadIT/testReadPublicData/)
 * [Gradle Build Scan](https://scans.gradle.com/s/3s4lnjovurqdi)
 * [Test source code](https://github.com/apache/beam/blame/b953645ed6db837d24284d7fe1fe091e7309f821/sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubReadIT.java)

Initial investigation:

java.lang.AssertionError: Did not receive signal on projects/apache-beam-testing/subscriptions/start-subscription-313044384168895769 in 300s at org.apache.beam.sdk.io.gcp.pubsub.TestPubsubSignal.pollForResultForDuration(TestPubsubSignal.java:269) at org.apache.beam.sdk.io.gcp.pubsub.TestPubsubSignal.lambda$waitForStart$0(TestPubsubSignal.java:218) at org.apache.beam.vendor.guava.v20_0.com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120) at org.apache.beam.sdk.io.gcp.pubsub.PubsubReadIT.testReadPublicData(PubsubReadIT.java:54) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498)
\--\--
_After you've filled out the above details, please [assign the issue to an individual](https://beam.apache.org/contribute/postcommits-guides/index.html#find_specialist). Assignee should [treat test failures as high-priority](https://beam.apache.org/contribute/postcommits-policies/#assigned-failing-test), helping to fix the issue or find a more appropriate owner. See [Apache Beam Post-Commit Policies](https://beam.apache.org/contribute/postcommits-policies)._

Imported from Jira [BEAM-6804](https://issues.apache.org/jira/browse/BEAM-6804). Original Jira may contain additional context.
Reported by: Ardagan.

**Comment by damccorm** [comment]
I'm going to close this one since its very old and I don't see a failure like this for a long time back - https://ci-beam.apache.org/job/beam_PostCommit_Java/
