### ISSUE TITLE
Unit test for edge cases for null checks in Row.equals

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#19561]
After [BEAM-5866](https://issues.apache.org/jira/browse/BEAM-5866) and [BEAM-7125](https://issues.apache.org/jira/browse/BEAM-7125) Row has duplicated null value checks.

Imported from Jira [BEAM-7699](https://issues.apache.org/jira/browse/BEAM-7699). Original Jira may contain additional context.
Reported by: naheonk.

**Comment by yyy1000** [comment]
Want to help with this :)

**Comment by yyy1000** [comment]
.take-issue

**Comment by Abacn** [comment]
It was found the original nul checks were not duplicated, though there is still some thing could do for unit testing (see https://github.com/apache/beam/pull/24773#issuecomment-1374187076 for the context)

**Comment by jon-esperanza** [comment]
.take-issue
