### ISSUE TITLE
Jenkins config: migrate off of ghprb-plugin

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19643]
ghprb-plugin is going away and Beam needs to migrate off of it.

Some background in https://issues.apache.org/jira/browse/BEAM-7723 (see the wiki page linked there)

Imported from Jira [BEAM-7725](https://issues.apache.org/jira/browse/BEAM-7725). Original Jira may contain additional context.
Reported by: udim.

**Comment by Abacn** [comment]
This would also eliminate the random number of spamming comments "Can one of the admins verify this patch?" in every PR when openeed...
