### ISSUE TITLE
Loosen Python dependency restrictions: httplib2, oauth2client

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19671]
The Beam Python SDK's current pinned dependencies create dependency conflict issues for my team at Twitter.

I'd like the following expansions of the Python SDK's dependency ranges:
 * oauth2client\>=2.0.1,<*4* to at least oauth2client\>=2.0.1,<=*4.1.2*
 * httplib2\>=0.8,<=*0.12.0* to at least httplib2\>=0.8,<=*0.12.3*

I understand, from pull request [8653](https://github.com/apache/beam/pull/8653) by [~altay], that the latter is blocked in turn by googledatastore.

Imported from Jira [BEAM-8158](https://issues.apache.org/jira/browse/BEAM-8158). Original Jira may contain additional context.
Reported by: jinnovation.

**Comment by jinnovation** [comment]
For context, I am no longer with the Twitter team I wrote this ticket on behalf of. It is possible it is no longer an issue. Feel free to close 😁
