### ISSUE TITLE
Improve checkpoints documentation

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19708]
UnboundedSource.CheckpointMark should mention that implementations it should be encodable (have an associated Coder). Also maybe it is a good idea to explain a bit more the checkpointing semantics on Beam.

Imported from Jira [BEAM-7691](https://issues.apache.org/jira/browse/BEAM-7691). Original Jira may contain additional context.
Reported by: iemejia.

**Comment by DevPJ9** [comment]
Hello @damccorm. I would like to contribute to this task.

**Comment by damccorm** [comment]
Hey @DevPJ9 sounds good - if you'd like to take this issue, just comment `.take-issue` and you will be autoassigned the issue (it may take a bit since its based on GitHub Actions with limited quota)

**Comment by DevPJ9** [comment]
.take-issue

**Comment by DevPJ9** [comment]
Hey @damccorm, I have not any previous experience with documentation, can you please guide me through the initial steps.

**Comment by damccorm** [comment]
Hey, this particular issue involves updating the javadoc for UnboundedSource.CheckpointMark (https://github.com/apache/beam/blob/aeebe56720be4bf0442e923618fc712431fb82b0/sdks/java/core/src/main/java/org/apache/beam/sdk/io/UnboundedSource.java#L104). It should require updating the comment there to mention that implementations should be encodable (have an associated Coder).

@iemejia might be able to help more here as well

**Comment by DevPJ9** [comment]
Ok I Kind of understood the requirement, I have to add `<p>Note that: The implementations of this interface should be encodable (have an associated Coder)`. 
Am I right @damccorm
cc : @iemejia.

**Comment by damccorm** [comment]
Yep, something like that should work!
