### ISSUE TITLE
Allow to parametrize the ClientConfiguration and ApacheHttpClient for AWSv2 operations

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19718]
Hand tuning of Http connections and Client Configuration has been divided in two different objects for AWS SDK for Java 2. We need to expose this as part of AWSOptions so users that require to refine connections or other client details may use them.

Imported from Jira [BEAM-7652](https://issues.apache.org/jira/browse/BEAM-7652). Original Jira may contain additional context.
Reported by: iemejia.

**Comment by mosche** [comment]
Support to configure `ProxyConfiguration` and `HttpClientConfiguration` via `AwsOptions` has been added some while back

[https://github.com/apache/beam/blob/5520fe064fc3b7196998d4597746119691eb6681/sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/options/AwsOptions.java#L139-L156](https://github.com/apache/beam/blob/5520fe064fc3b7196998d4597746119691eb6681/sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/options/AwsOptions.java#L139-L156)

[https://github.com/apache/beam/blob/5520fe064fc3b7196998d4597746119691eb6681/sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/options/AwsOptions.java#L160-L170](https://github.com/apache/beam/blob/5520fe064fc3b7196998d4597746119691eb6681/sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/options/AwsOptions.java#L160-L170)
