### ISSUE TITLE
WatchTest.testMultiplePollsWithManyResults flake: Outputs must be in timestamp order (sickbayed)

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19734]
_Use this form to file an issue for test failure:_
 * [Jenkins Job]([https://builds.apache.org/job/beam_PreCommit_Java_Phrase/1258/testReport/junit/org.apache.beam.sdk.transforms/WatchTest/testMultiplePollsWithManyResults/)]

Initial investigation:

java.lang.AssertionError: Drop timestamped input/Values/Map/ParMultiDo(Anonymous).output: Outputs must be in timestamp order
\--\--
_After you've filled out the above details, please [assign the issue to an individual](https://beam.apache.org/contribute/postcommits-guides/index.html#find_specialist). Assignee should [treat test failures as high-priority](https://beam.apache.org/contribute/postcommits-policies/#assigned-failing-test), helping to fix the issue or find a more appropriate owner. See [Apache Beam Post-Commit Policies](https://beam.apache.org/contribute/postcommits-policies)._

Imported from Jira [BEAM-8035](https://issues.apache.org/jira/browse/BEAM-8035). Original Jira may contain additional context.
Reported by: Ardagan.

**Comment by damondouglas** [comment]
.add-label beam-fixit

**Comment by damondouglas** [comment]
.add-labels beam-fixit
