### ISSUE TITLE
Java Validates DirectRunner: testTeardownCalledAfterExceptionInFinishBundleStateful flaky

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19812]
See: [https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Direct/663/](https://builds.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Direct/663/)

another run on the same master state was successful. As I see the job's history, the test fails from time to time. 

 

 

Imported from Jira [BEAM-7752](https://issues.apache.org/jira/browse/BEAM-7752). Original Jira may contain additional context.
Reported by: ŁukaszG.

**Comment by damccorm** [comment]
I'm going to close this one since it is very old and I don't see this anywhere in the job's current history - https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Direct/

**Comment by kennknowles** [comment]
Ah I was just deflaking #19814 which is the same but includes Spark and Flink. Linking them via this comment.

**Comment by kennknowles** [comment]
Ah, I see one is startbundle the other is finishbundle. Surely it is a common root cause anyhow.
