### ISSUE TITLE
:sdks:python:test-suites:portable:py2:installGcpTest is flaky due to "No such file or directory"

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19880]
Seems like this failed a couple of times today.

 

[https://scans.gradle.com/s/ohpjfppgy3nme/console-log?task=:sdks:python:test-suites:portable:py2:installGcpTest](https://scans.gradle.com/s/ohpjfppgy3nme/console-log?task=:sdks:python:test-suites:portable:py2:installGcpTest)

[https://scans.gradle.com/s/rizexjbqqmbzm/console-log?task=:sdks:python:test-suites:direct:py2:installGcpTest](https://scans.gradle.com/s/rizexjbqqmbzm/console-log?task=:sdks:python:test-suites:direct:py2:installGcpTest)

 

    ERROR: Command errored out with exit status 1:     ERROR: Command errored out with exit status 1:      command: /home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/build/gradleenv/45127155/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/sdks/python/setup.py'"'"'; __file__='"'"'/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/sdks/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info          cwd: /home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/sdks/python/     Complete output (27 lines):     /home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/sdks/python/setup.py:198: UserWarning: You are using Apache Beam with Python 2. New releases of Apache Beam will soon support Python 3 only.       'You are using Apache Beam with Python 2. '     Traceback (most recent call last):       File "<string\>", line 1, in <module\>       File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/sdks/python/setup.py", line 260, in <module\>         'test': generate_protos_first(test),       File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/build/gradleenv/45127155/local/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup         _install_setup_requires(attrs)       File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/build/gradleenv/45127155/local/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires         dist.fetch_build_eggs(dist.setup_requires)       File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/build/gradleenv/45127155/local/lib/python2.7/site-packages/setuptools/dist.py", line 720, in fetch_build_eggs         replace_conflicting=True,       File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/build/gradleenv/45127155/local/lib/python2.7/s ite-packages/pkg_resources/__init__.py", line 794, in resolve         new_requirements = dist.requires(req.extras)[::-1]       File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/build/gradleenv/45127155/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2736, in requires         dm = self._dep_map       File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/build/gradleenv/45127155/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3023, in _dep_map         self.__dep_map = self._compute_dependencies()       File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/build/gradleenv/45127155/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _compute_dependencies         for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:       File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/build/gradleenv/45127155/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3014, in _parsed_pkg_info         metadata = self.get_metadata(self.PKG_INFO)       File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/build/gradleenv/45127155/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1420, in get_metadata         value = self._get(path)       File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/build/gradleenv/45127155/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1616, in _get         with open(path, 'rb') as stream:     IOError: [Errno 2] No such file or directory: '/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python2/src/sdks/python/.eggs/pytest_runner-5.2-py2.7.egg/pytest_runner-5.2.dist-info/METADATA'

 

 

Mark, seems like you updated relevant files few months back but not sure how familiar you are with this error. Any idea ?

Imported from Jira [BEAM-8631](https://issues.apache.org/jira/browse/BEAM-8631). Original Jira may contain additional context.
Reported by: chamikara.

**Comment by Abacn** [comment]
obsolete. py2 no longer supported
