### ISSUE TITLE
Update TestStreamPayload to use timestamp protos.

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19891]
Currently the timestamp fields are all int64, with no indication of whether the units are seconds, milliseconds, or microseconds. 

https://github.com/apache/beam/blob/release-2.16.0/model/pipeline/src/main/proto/beam_runner_api.proto#L502

Imported from Jira [BEAM-8373](https://issues.apache.org/jira/browse/BEAM-8373). Original Jira may contain additional context.
Reported by: robertwb.

**Comment by vineetg3** [comment]
Hi @damccorm , the latest version seems to have a comment mentioning that the data type is inferred in milliseconds.
```
 // Advances the watermark to the specified timestamp.
    message AdvanceWatermark {
      // (Required) The watermark in millisecond to advance to.
      int64 new_watermark = 1;

      // (Optional) The output watermark tag for a PCollection. If unspecified
      // or with an empty string, this will default to the Main PCollection
      // Output
      string tag = 2;
    }
```
Is this what this issue is expecting?

**Comment by damccorm** [comment]
Yep, looks like this can be closed - thanks!
