### ISSUE TITLE
test_streaming_pipeline_returns_expected_user_metrics_fnapi_it  failed on latest PostCommit Py36 

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19890]
https://builds.apache.org/job/beam_PostCommit_Python36/731/

Imported from Jira [BEAM-8413](https://issues.apache.org/jira/browse/BEAM-8413). Original Jira may contain additional context.
Reported by: boyuanz.

**Comment by Abacn** [comment]
.close-issue not_planned
