### ISSUE TITLE
Support Spark 3 on Spark Structured Streaming Runner 

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19914]
Spark Structured Streaming Runner uses currently non stable Spark APIs for its Source translation, the DataSourceV2 API was changed on Spark 3. We need probably a new class or a new compatibility layer to support this for Spark 3.

Imported from Jira [BEAM-8827](https://issues.apache.org/jira/browse/BEAM-8827). Original Jira may contain additional context.
Reported by: iemejia.

**Comment by mosche** [comment]
Obsolete
