### ISSUE TITLE
Python PreCommit Failures: Could not copy file '/some/path/file.egg'

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19946]
Several precommits fail due to "Could not copy file '/some/path/file.egg'"

Examples

[https://scans.gradle.com/s/ihfmrxr7evslw/failure?openFailures=WzFd&openStackTraces=WzZd#top=0](https://scans.gradle.com/s/ihfmrxr7evslw/failure?openFailures=WzFd&openStackTraces=WzZd#top=0)

[https://scans.gradle.com/s/ihfmrxr7evslw](https://scans.gradle.com/s/ihfmrxr7evslw)

```

> Cannot create directory '/home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/test-suites/tox/py37/build/srcs/sdks/python/.eggs/timeloop-1.0.2-py3.7.egg'
as it already exists, but is not a directory

```

Imported from Jira [BEAM-8831](https://issues.apache.org/jira/browse/BEAM-8831). Original Jira may contain additional context.
Reported by: lcwik.

**Comment by Abacn** [comment]
.close-issue not_planned

Not seen for a while, obsolete
