### ISSUE TITLE
Failing test in UTC+8 timezone

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19951]
The [SchemaUtilTest.testBeamRowMapperDateTime()](https://github.com/apache/beam/blob/5a7bd66174e43ebedd6b5b4d7835e11309505b33/sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/SchemaUtilTest.java#L227) test case is failing because the *date_col* value is one day later than the expected value.

The problem comes from [SchemaUtil.createDateExtractor()](https://github.com/apache/beam/blob/5a7bd66174e43ebedd6b5b4d7835e11309505b33/sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/SchemaUtil.java#L277). The implementation converts the date to ZonedDateTime first and then gets the start time of the date.

Being in Singapore the timezone adjustments increments the day on the test case's timestamp which leads to an assertion failure.

Imported from Jira [BEAM-8358](https://issues.apache.org/jira/browse/BEAM-8358). Original Jira may contain additional context.
Reported by: Kauker.

**Comment by Abacn** [comment]
.close-issue not_planned

dup #22738
