### ISSUE TITLE
Support for enhanced fan-out in KinesisIO.Read

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19967]
Add support for reading from an enhanced fan-out consumer using KinesisIO.

Imported from Jira [BEAM-8511](https://issues.apache.org/jira/browse/BEAM-8511). Original Jira may contain additional context.
Reported by: jfarr.

**Comment by mosche** [comment]
@psolomin could you assign this issue to yourself, pls... just comment:
```
.take-issue
```

**Comment by psolomin** [comment]
.take-issue
