### ISSUE TITLE
Optimize translation when Schema information is available in Spark Structured Streaming runner

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19989]
Spark Structured Streaming runner supports Datasets that already have Schema information. This is used by Spark to optimize jobs (via Catalyst). This issue is to implement optimized translations of the transforms for the runner so we can benefit of the performance improvements internally done by Spark.

Notice that we also may need to map Beam's core internal representations like WindowedValue so we can have intermediary optimizations.

Imported from Jira [BEAM-9451](https://issues.apache.org/jira/browse/BEAM-9451). Original Jira may contain additional context.
Reported by: iemejia.

**Comment by mosche** [comment]
Fixed with https://github.com/apache/beam/issues/22445
