### ISSUE TITLE
Put windows inside the key to avoid having all values for the same key in memory

### ISSUE THREAD

**Issue by damccorm** [apache/beam#19999]
On both group by key and combinePerKey.

Like it was done for the current runner.

See: [https://www.youtube.com/watch?v=ZIFtmx8nBow&t=721s](https://www.youtube.com/watch?v=ZIFtmx8nBow&t=721s) min 10

Imported from Jira [BEAM-9307](https://issues.apache.org/jira/browse/BEAM-9307). Original Jira may contain additional context.
Reported by: echauchot.

**Comment by mosche** [comment]
Fixed with https://github.com/apache/beam/issues/22445
