### ISSUE TITLE
BIP-1: Beam Schema Options

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20022]
Introduce the concept of Options in Beam Schema’s to add extra context to fields and schemas. In contrast to the current Beam metadata that is present in a FieldType, options would be added to fields, logical types and schemas. The schema convertors (ex. Avro, Proto, …) can add options/annotations/decorators that were in the original schema to the Beam schema with these options. These options, that add contextual metadata, can be used in the pipeline for specific transformations or augment the end schema in the target output.

Imported from Jira [BEAM-9275](https://issues.apache.org/jira/browse/BEAM-9275). Original Jira may contain additional context.
Reported by: alexvanboxel.

**Comment by damccorm** [comment]
The following subtask(s) are associated with this issue: #20023

**Comment by TheNeuralBit** [comment]
Given there's just one sub-task left let's go ahead and close this.
