### ISSUE TITLE
Make MonotonicWatermarkEstimator configurable for whether to ignore late timestamp.

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20041]
Current implementation of MonotonicWatermarkEstimator throws error and stop the pipeline  when there is a late timestamp. But there are more potential options like:
(1) Suppress the error and emit the item as possibly late data.
(2) Move the timestamp forward to respect the watermark.
We should consider making MonotonicWatermarkEstimator configurable with these options, or  providing different types of MonotonicWatermarkEstimator  to handle different options.

Imported from Jira [BEAM-9312](https://issues.apache.org/jira/browse/BEAM-9312). Original Jira may contain additional context.
Reported by: boyuanz.

**Comment by iht** [comment]
[In Java, the monotonic watermark estimator](https://github.com/apache/beam/blob/243128a8fc52798e1b58b0cf1a271d95ee7aa241/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/splittabledofn/WatermarkEstimators.java#L120-L127) just updates the watermark if the last observed timestamp is after the watermark. I think we should also do the same implementation in Python, for a consistent behavior across different SDKs.

The estimator has not do do anything with the data, just update the value of the watermark. It should not change the timestamps of the messages either, the incoming messages should not be altered, and the timestamps of the output messages in the splittable DoFn should be decided by the user of that DoFn.

The current implementation of MonotonicWatermarkEstimator throws an exception with late data, which makes it unusable unless you can guarantee the order of messages.
