### ISSUE TITLE
SortValues should fail if SecondaryKey coder is not deterministic

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20109]
`SortValues` transform uses lexicographical sorting on encoded binaries and might not work correctly if the coder is not deterministic.

Imported from Jira [BEAM-8985](https://issues.apache.org/jira/browse/BEAM-8985). Original Jira may contain additional context.
Reported by: sinisa_lyh.

**Comment by kennknowles** [comment]
@reuvenlax FYI since I know you work with sortvalues a bit

**Comment by TheNeuralBit** [comment]
Is this actually a P1 _and_ a good first issue?

**Comment by kennknowles** [comment]
Ha. Good point. Independently, both statements are true:

 - It is pretty straightforward to go in to the transform and add the check.
 -  It is a data loss risk if the coder is nondeterministic.
