### ISSUE TITLE
Hadoop Downloader Range not correct

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20110]
I found that the `HdfsDownloader.get_range(self, start, end)' get range {color:#ff0000}[start, end]{color} rather than {color:#ff0000}[start, end){color}. This will cause an error while reading hdfs file.

 

File "/data/anaconda3/envs/tfdv1.15/lib/python3.7/site-packages/apache_beam/io/tfrecordio.py", line 127, in read_record
 buf = file_handle.read(buf_length_expected)
 File "/data/anaconda3/envs/tfdv1.15/lib/python3.7/site-packages/apache_beam/io/filesystemio.py", line 123, in readinto
 b[:len(data)] = data
 ValueError: memoryview assignment: lvalue and rvalue have different structures

Imported from Jira [BEAM-9152](https://issues.apache.org/jira/browse/BEAM-9152). Original Jira may contain additional context.
Reported by: Benjzhou.

**Comment by chamikaramj** [comment]
@Abacn will you be able to look into this ?

**Comment by Abacn** [comment]
.take-issue
