### ISSUE TITLE
Switch to google-api-python-client instead of using deprecated google-apitools

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20147]
Imported from Jira [BEAM-9823](https://issues.apache.org/jira/browse/BEAM-9823). Original Jira may contain additional context.
Reported by: tvalentyn.

**Comment by BjornPrime** [comment]
.take-issue

**Comment by BjornPrime** [comment]
.close-issue

https://github.com/apache/beam/issues/19073 is more recent and general and will be resolved using [Python Client for Cloud Storage API](https://github.com/googleapis/python-storage) instead.
