### ISSUE TITLE
Support TestStream in Spark Structured Streaming Runner

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20158]
The TestStream transform is useful to validate streaming based tests on Beam so worth to have it.

Imported from Jira [BEAM-9938](https://issues.apache.org/jira/browse/BEAM-9938). Original Jira may contain additional context.
Reported by: iemejia.

**Comment by mosche** [comment]
Streaming support is not feasible at the moment https://github.com/apache/beam/issues/20241
