### ISSUE TITLE
Update "Managing Python Pipeline Dependencies" page

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20228]
Update https://beam.apache.org/documentation/sdks/python-pipeline-dependencies/ with concrete examples and make it easier to use.

Additional items to cover in this page:
- pickling / managing main session
- containers to rescue how it could help with this, how to run containers locally (links?)

Imported from Jira [BEAM-9497](https://issues.apache.org/jira/browse/BEAM-9497). Original Jira may contain additional context.
Reported by: altay.

**Comment by svetakvsundhar** [comment]
.take-issue

**Comment by svetakvsundhar** [comment]
> I see some typos in the PR, if I don't add comments or follow up with a PR myself, please ping me.

Could you elaborate on this? Would be happy to push a new PR to rectify.
