### ISSUE TITLE
Document how to run a Java (xlang) pipeline on the Spark portable runner

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20224]
While users will probably still prefer the classic Spark runner for most Java pipelines, the Spark portable runner enables cross-language transforms. We can start by providing instructions for plain Java, then add cross-language (Java -\> Python).

Imported from Jira [BEAM-10151](https://issues.apache.org/jira/browse/BEAM-10151). Original Jira may contain additional context.
Reported by: ibzib.

**Comment by mosche** [comment]
Duplicate of https://github.com/apache/beam/issues/20224
