### ISSUE TITLE
AWS - add possibility for multiple region client

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20239]
### What?

I recently had an use case that I can not fulfill due to actual AWS Writer limitation.

What I want to do is to be able to save dynamically element into S3 buckets which are in different regions. 

For now the region for AWS is passed only on application start and it is required.
This region is used by `AWSClient` with each of write to S3. Unfortunatelly in case of writing to bucket in different region there is 400 response code.
 
What would be nice in my opinion it would be to have possibility for creating dynamically `AWSClients` based on some kind of `RegionResolver`(?) 

It could be done as it is done for `AWSCredentialsProvider` option. 
 [https://beam.apache.org/releases/javadoc/2.5.0/org/apache/beam/sdk/io/aws/options/AwsOptions.html#setAwsCredentialsProvider-com.amazonaws.auth.AWSCredentialsProvider-](https://beam.apache.org/releases/javadoc/2.5.0/org/apache/beam/sdk/io/aws/options/AwsOptions.html#setAwsCredentialsProvider-com.amazonaws.auth.AWSCredentialsProvider-)

So user declares custom class for resolving region (by key value from e.g. `dynamicWriting`) and this function is used to create `AWSClient` with each of write request. By default it could just return provided in options `regionName` (which could be optional in that case)

I am just thinking loudly about my idea but you as creators knows the best :)
### Why?

To give possibility to dynamically select region for writing

Imported from Jira [BEAM-10133](https://issues.apache.org/jira/browse/BEAM-10133). Original Jira may contain additional context.
Reported by: Kabool.

**Comment by mosche** [comment]
This can already be done using a custom `S3ClientBuilderFactory`:
```
public class GlobalAccessS3ClientBuilderFactory extends DefaultS3ClientBuilderFactory {
  @Override
  public AmazonS3ClientBuilder createBuilder(S3Options s3Options) {
    return super.createBuilder(s3Options).enableForceGlobalBucketAccess();
  }
}
```
and configured using pipeline options (`S3Options`):
```
--s3ClientFactoryClass=my.GlobalAccessS3ClientBuilderFactory;
```
