### ISSUE TITLE
Support Streaming in Spark Structured Streaming Runner

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20241]
The current version of the Spark Structured Streaming Runner only support Bounded IO. This ticket is to address the support of full Streaming.

This issue is blocked because of issues on Spark with multiple aggregations SPARK-26655

Imported from Jira [BEAM-9933](https://issues.apache.org/jira/browse/BEAM-9933). Original Jira may contain additional context.
Reported by: iemejia.

**Comment by mosche** [comment]
Might become an option later in 2023 again once [Project Lightspeed](https://databricks.com/blog/2022/06/28/project-lightspeed-faster-and-simpler-stream-processing-with-apache-spark.html) is completed, closing for now
