### ISSUE TITLE
Install docker-credential-gcloud on Jenkins VMs

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20328]
See BEAM-7405 (test failure currently resolved with an inelegant workaround) for motivation.

> 
>  Install docker-credential-gcloud.
> is requires updating the VM image, which requires too much effort for me at this time.
> 

Imported from Jira [BEAM-10193](https://issues.apache.org/jira/browse/BEAM-10193). Original Jira may contain additional context.
Reported by: bhulette.

**Comment by damccorm** [comment]
Unable to assign user @dannymartinm. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by dannymartinm** [comment]
.take-issue
