### ISSUE TITLE
Add Apache Iceberg IO connector

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20327]
Apache Iceberg is an open table format layer on top of different filesystems.

Beam could support it in the form of an IO connector ideally integrating with Beam's own system for SQL support.

Inspiration can be taken from the ongoing effort to support Iceberg on Flink:
https://github.com/apache/iceberg/issues/788
https://docs.google.com/document/d/1idTjQCubhOCea8LkKJ_5aMTV4V_Wf1n0aYhabGsLQZc/edit

Imported from Jira [BEAM-10160](https://issues.apache.org/jira/browse/BEAM-10160). Original Jira may contain additional context.
Reported by: iemejia.

**Comment by gabrywu** [comment]
any updates?

**Comment by yupbank** [comment]
any updates?

**Comment by yeshvantbhavnasi** [comment]
any updates ?

**Comment by brucearctor** [comment]
@gabrywu , @yupbank , @yeshvantbhavnasi -- nobody is assigned [ therefore potentially not being worked on ], so not clear how quickly this will progress.  That said, it is also open, and therefore something that anyone could work on and contribute.  Contributions welcome!  :-)

**Comment by pabloem** [comment]
hi folks - I am taking a look at this...

**Comment by jotarada** [comment]
Hey folks, is there any plans regarding this?

**Comment by kellen** [comment]
@pabloem ping from Spotify

**Comment by chadlagore** [comment]
Affirm interested in this  👀  cc @lydian

**Comment by aromanenko-dev** [comment]
CC: @mosche

**Comment by iemejia** [comment]
There was some work on Sink for iceberg by @Fokko 
https://github.com/apache/iceberg/pull/1972

@Fokko do you have any info about this, has someone tried to build on your work to get Beam + Iceberg working together?

**Comment by Fokko** [comment]
That was some early work, and probably I would just start from scratch. I would take inspiration from the Kafka-connect repository: https://github.com/tabular-io/iceberg-kafka-connect

**Comment by gabrywu** [comment]
we use iceberg low-level API adding data files directly

**Comment by RPasecky** [comment]
Wanted to check in on this, is beam prioritizing this?

**Comment by tav1nald3rs0n** [comment]
No chance guys unless google have plans.

**Comment by brucearctor** [comment]
@RPasecky -- it is less 'beam' prioritizing, and a question of whether any individuals are prioritizing.  I'd love for this to exist, but can't devote the time.  Hopefully someone will.  Contributions welcomed!  :-)

**Comment by kennknowles** [comment]
Added in #30797 and released in version 2.56.0

**Comment by Fokko** [comment]
Awesome! This is a great milestone! Thanks for working on this 🎉
