### ISSUE TITLE
org.apache.beam.sdk.io.mongodb.MongoDbIOTest.testReadWithAggregate is flaky

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20331]
[https://builds.apache.org/job/beam_PreCommit_Java_Phrase/1831/testReport/junit/org.apache.beam.sdk.io.mongodb/MongoDbIOTest/testReadWithAggregate/](https://builds.apache.org/job/beam_PreCommit_Java_Phrase/1831/testReport/junit/org.apache.beam.sdk.io.mongodb/MongoDbIOTest/testReadWithAggregate/)

Imported from Jira [BEAM-9480](https://issues.apache.org/jira/browse/BEAM-9480). Original Jira may contain additional context.
Reported by: echauchot.

**Comment by kennknowles** [comment]
Could not reproduce flake

```
for i in `seq 1 1000` ; do (
  echo "RUN $i"
  ./gradlew :sdks:java:io:mongodb:cleanTest --quiet
  ./gradlew :sdks:java:io:mongodb:test --tests MongoDbIOTest.testReadWithAggregate --quiet
) 2>/dev/null
done
```

And do not see it any time recently at https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/test_results_analyzer/
