### ISSUE TITLE
beam_PerformanceTests_Kafka_IO failing due to " provided port is already allocated"

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20333]
For example,

[https://builds.apache.org/view/A-D/view/Beam/view/PerformanceTests/job/beam_PerformanceTests_Kafka_IO/514/console](https://builds.apache.org/view/A-D/view/Beam/view/PerformanceTests/job/beam_PerformanceTests_Kafka_IO/514/console)

 

18:55:33 Error from server (Invalid): error when creating "/home/jenkins/jenkins-slave/workspace/beam_PerformanceTests_Kafka_IO/src/.test-infra/kubernetes/kafka-cluster/04-outside-services/outside-0.yml": Service "outside-0" is invalid: spec.ports[0].nodePort: Invalid value: 32400: provided port is already allocated
18:55:33 Error from server (Invalid): error when creating "/home/jenkins/jenkins-slave/workspace/beam_PerformanceTests_Kafka_IO/src/.test-infra/kubernetes/kafka-cluster/04-outside-services/outside-1.yml": Service "outside-1" is invalid: spec.ports[0].nodePort: Invalid value: 32401: provided port is already allocated
18:55:33 Error from server (Invalid): error when creating "/home/jenkins/jenkins-slave/workspace/beam_PerformanceTests_Kafka_IO/src/.test-infra/kubernetes/kafka-cluster/04-outside-services/outside-2.yml": Service "outside-2" is invalid: spec.ports[0].nodePort: Invalid value: 32402: provided port is already allocated
1

 

Seems like we tried three ports but they were being used. Probably we should update code to find an unused port dynamically.

Imported from Jira [BEAM-9482](https://issues.apache.org/jira/browse/BEAM-9482). Original Jira may contain additional context.
Reported by: chamikara.

**Comment by damccorm** [comment]
Unable to assign user @benWize. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by benWize** [comment]
Working on this one. Associated PR is https://github.com/apache/beam/pull/17727

**Comment by benWize** [comment]
> 

Hi @Abacn, I think the current failures could be related to a problem with the availability of resources on the shared cluster(io-datastores). The Kubernetes console for kafka-1 pods shows a message: `Cannot schedule pods: Insufficient memory.`
We could provide more resources or double-check if some of the running workloads aren't terminated correctly (none of them are related to Kafka tests).
There are multiple namespaces created 11d ago, with the format: `beam-performancetests-*` that could be starving the resources.

**Comment by Abacn** [comment]
Thanks @benWize cleaned up those namespaces and along with other fixes kafka performance test now works

**Comment by Abacn** [comment]
.close-issue
