### ISSUE TITLE
beam_PreCommit_PythonLint_Commit takes 50+ minutes to execute

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20378]
The beam_PreCommit_PythonLint_Commit phase takes 50**** minutes to execute as seen here:

 

[https://builds.apache.org/job/beam_PreCommit_PythonLint_Commit/4252/](https://builds.apache.org/job/beam_PreCommit_PythonLint_Commit/4252/) (53 minutes)

[https://builds.apache.org/job/beam_PreCommit_PythonLint_Commit/4253/](https://builds.apache.org/job/beam_PreCommit_PythonLint_Commit/4253/) (52 minutes)

 

According to the build blame report the mean time is ~10 minutes ([https://builds.apache.org/job/beam_PreCommit_PythonLint_Commit/buildTimeBlameReport/](https://builds.apache.org/job/beam_PreCommit_PythonLint_Commit/buildTimeBlameReport/))

Imported from Jira [BEAM-10255](https://issues.apache.org/jira/browse/BEAM-10255). Original Jira may contain additional context.
Reported by: tysonjh.

**Comment by Abacn** [comment]
not observed for a while
