### ISSUE TITLE
Give an option to override the default number of shards in BQ streaming inserts

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20420]
As per [https://github.com/apache/beam/pull/12485](https://github.com/apache/beam/pull/12485) there's no way to override it, though Java does have one: 
[https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryOptions.java#L58](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryOptions.java#L58)
 
 
Let's add a good way to override this.

Imported from Jira [BEAM-10680](https://issues.apache.org/jira/browse/BEAM-10680). Original Jira may contain additional context.
Reported by: pabloem.

**Comment by dannikay** [comment]
.take-issue
