### ISSUE TITLE
Add BigQuery Avro logical type support on read

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20491]
Currently on read Avro GenericRecords are not supporting LogicalTypes; reading DATE, TIME fields will be read as STRING.

 

Supporting logical types should be doable by just enabling support on _JobConfigurationExtract_

 
```

new JobConfigurationExtract()
 .setSourceTable(table)
 .setDestinationFormat("AVRO")
 .setUseAvroLogicalTypes(useAvroLogicalTypes)

.setDestinationUris(ImmutableList.of(destinationUri));

```

 

Imported from Jira [BEAM-10649](https://issues.apache.org/jira/browse/BEAM-10649). Original Jira may contain additional context.
Reported by: regadas.

**Comment by RustedBones** [comment]
Looked to be resolved in https://github.com/apache/beam/pull/12479
