### ISSUE TITLE
SpannerIO tests don't actually assert anything.

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20529]
These all have the format

```

p = Pipeline()
...
p.run()
assert_that(...)

```

Imported from Jira [BEAM-10569](https://issues.apache.org/jira/browse/BEAM-10569). Original Jira may contain additional context.
Reported by: robertwb.

**Comment by Abacn** [comment]
There is a cross-language spanner io (apache_beam.io.gcp.spanner) and this native implementation is less actively supported and may be deprecated in the future. May decrease the priority of this issue.
