### ISSUE TITLE
Support for coder argument in WriteToBigQuery

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20532]
When using WriteToBigQuery to transfer data to BigQuery, non-ascii characters are replaced with replacement characters.

This was due to the RowAsDictJsonCoder being set as the coder for the BigQueryBatchFileLoads called inside WriteToBigQuery.

I want to add coder to the argument of WriteToBigQuery so that I can set a coder other than RowAsDictJsonCoder.

If no problem, I will create a Pull Request next weekend.

Imported from Jira [BEAM-10785](https://issues.apache.org/jira/browse/BEAM-10785). Original Jira may contain additional context.
Reported by: chanyou.

**Comment by damccorm** [comment]
Unable to assign user @harrydrippin. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by harrydrippin** [comment]
@damccorm Thank you for opening this issue. Please assign me and I will comment some progress on this soon.
