### ISSUE TITLE
 fileIO issue on  latest version of apache-beam to 2.23.0

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20557]
In Apache Beam , while using below P transformation -*fileio.MatchAll() and fileio.ReadMatches()*  dataflow job on load performance .( processing 48 million resources)

For 2-3 minute  Throughput(element/sec) goes to zero and no element was processed during that time , it comes back again back to average normal (0.25/sec) of my job

In between these three minutes. There is no log from apache beam , if some IO error came or any warning.

Please check for any fileIO  known issue on  latest version of *apache-beam to 2.23.0*

 

Imported from Jira [BEAM-11015](https://issues.apache.org/jira/browse/BEAM-11015). Original Jira may contain additional context.
Reported by: apoorva.e.sharma@accenture.com.

**Comment by Abacn** [comment]
Intended behavior. Listing resources is not parallelized.

**Comment by Abacn** [comment]
.close-issue not_planned
