### ISSUE TITLE
Fix the wrong usage of urllib.parse in dataflow_runner.py

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20561]
Because without importing urllib.parse before using it, it cause the following error in pyflink
https://issues.apache.org/jira/browse/FLINK-20218

Currently, we choose to import `urllib.parse` to bypass this problem in PyFlink. But I think we need to correct the wrong usage in beam.

Imported from Jira [BEAM-11307](https://issues.apache.org/jira/browse/BEAM-11307). Original Jira may contain additional context.
Reported by: hxbks2ks.

**Comment by tvalentyn** [comment]
Please reopen if still affected and add more context.
