### ISSUE TITLE
NullPointerException in Flink manager when submitting job

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20567]
Apologies if this is user error, as I am still learning Beam. I am attempting to run a python-based pipeline on the Flink runner, with Flink and an external beam image running inside docker-compose (see "Environment"). Whenever I submit a job, I get the following error. Am I doing something wrong? Thanks in advance.

* Edit: Jira mangled the traceback, you can see it here: https://gist.github.com/sbrother/b9f62580fbab84e2cfc925e0ea8ffc07 

Imported from Jira [BEAM-11000](https://issues.apache.org/jira/browse/BEAM-11000). Original Jira may contain additional context.
Reported by: sbrother.

**Comment by je-ik** [comment]
@sbrother can you please attach the stacktrace? it is no longer available from the original location.

**Comment by kennknowles** [comment]
I think that is the jira username. The latest report of this was in 2021 but at this point I don't think we have enough information to go further. I'm sure a user would file a new issue if they hit a NPE at submission time.
