### ISSUE TITLE
publish guide or scripts to build Beam SDK harness container from an existing container image

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20680]
The current image building doc in [https://beam.apache.org/documentation/runtime/environments/#customizing-container-images](https://beam.apache.org/documentation/runtime/environments/#customizing-container-images) only provides paths of modifying existing Dockerfile or extending the image path.

 

It might be the case that certain large enterprise users have their own "blessed" base images which are widely extended within their company, and teams might want to adapt these images to fit into Dataflow workers. Publishing guidelines on this path might be helpful.

 

Even better, if a python equipped container images installs `apache-beam` (or an extra dependency) python package, it should be possible to be used as a container image.

Imported from Jira [BEAM-11152](https://issues.apache.org/jira/browse/BEAM-11152). Original Jira may contain additional context.
Reported by: zhitao.

**Comment by tvalentyn** [comment]
https://beam.apache.org/documentation/runtime/environments/#modify-existing-base-image
