### ISSUE TITLE
PortableRunnerTestWithSubprocesses.test_register_finalizations flaky on macOS

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20690]
This has failed on Github actions on different Python versions with different assertion errors.

self.assertEqual(results, sorted(elements_list))

AssertionError: Lists differ: ['2'] != ['1', '2']

or

AssertionError: Lists differ: [] != ['1', '2']

Imported from Jira [BEAM-10866](https://issues.apache.org/jira/browse/BEAM-10866). Original Jira may contain additional context.
Reported by: ibzib.

**Comment by TheNeuralBit** [comment]
The last report of this flake occurring in BEAM-10866 was in September/October 2020 (1.5 years ago). Let's close this. Please re-open if it's seen again.
