### ISSUE TITLE
Timer with dataflow runner can be set multiple times (dataflow runner)

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20692]
After the update from version 2.21.0 a timer (processing-time) was not overwritten but additionally set.
I set a timer several times e.g.:
processingTimerFamily.get("timer1").offset(Duration.standardSeconds(60)).setRelative();
for each incoming data in an unbound streaming pipeline.

According to the documentation the timer should be set back in each case. Since the update it seems that the existing timer is not overwritten but an additional timer (with the same timer-id) is added.
With directrunner it still works as before.

Imported from Jira [BEAM-11017](https://issues.apache.org/jira/browse/BEAM-11017). Original Jira may contain additional context.
Reported by: jaribo.

**Comment by kennknowles** [comment]
I believe this has been fixed. Can you confirm @reuvenlax? I believe you were in the loop on the fix.

**Comment by reuvenlax** [comment]
I believe this was caused by the output-timestamp bug, and should now be fixed.
