### ISSUE TITLE
TFX and Cloud Dataflow

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20749]
Add TFX and Cloud Dataflow to the Powered By list:  [https://beam.apache.org/community/powered-by/](https://beam.apache.org/community/powered-by/).

Imported from Jira [BEAM-11782](https://issues.apache.org/jira/browse/BEAM-11782). Original Jira may contain additional context.
Reported by: bhermann.

**Comment by rszper** [comment]
It looks like the https://beam.apache.org/community/powered-by/ page doesn't exist anymore.

The closest thing I could find was the Case Studies page: https://beam.apache.org/case-studies/

Is that where this information should be added?

**Comment by rszper** [comment]
Also, it looks like when there was a Powered by page, these were already added. See https://github.com/apache/beam/commit/3f9ae543d55ea486e5d05d9a5c51e45735931f20

**Comment by rszper** [comment]
.take-issue

**Comment by rszper** [comment]
.close-issue
