### ISSUE TITLE
Race condition reporting Python metrics

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20775]
A race condition has appeared on metrics for Beam 2.24.0 and 2.25.0 (likely on 2.26.0 as well)

Somewhere in this range, a change may have been included that causes this race condition

!https://screenshot.googleplex.com/4Eb7PYMLGDxQYbv.png!

Imported from Jira [BEAM-11459](https://issues.apache.org/jira/browse/BEAM-11459). Original Jira may contain additional context.
Reported by: pabloem.

**Comment by AnandInguva** [comment]
Solved in https://github.com/apache/beam/pull/13526/

**Comment by AnandInguva** [comment]
.close-issue
