### ISSUE TITLE
JmsIO is not acknowledging messages correctly

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20814]
Hello,

We noticed that messages consumption via JmsIO does not acknowledge messages properly.
Some messages are never acknowledged which results in data loss.

So when do messages get acknowledged by JmsIO?

How do We make sure all messages are being acknowledged?

 

Best regards,

Seif

Imported from Jira [BEAM-11828](https://issues.apache.org/jira/browse/BEAM-11828). Original Jira may contain additional context.
Reported by: seifeddine.gamoudi-extern@renault.com.

**Comment by rvballada** [comment]
.take-issue

**Comment by Abacn** [comment]
@rvballada Is this done and can be marked be closed?

**Comment by kennknowles** [comment]
@rvballada have you had a chance to look at this?

**Comment by rvballada** [comment]
Hello, yes this issue can be closed!
