### ISSUE TITLE
KafkaUnboundedReader doesn't support updating pipeline with re-partition case.

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20836]
When updating pipelines with re-partition topic, KafkaUnboundedReader will throw exceptions from https://github.com/apache/beam/blob/master/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaUnboundedReader.java#L470-L474

Imported from Jira [BEAM-11947](https://issues.apache.org/jira/browse/BEAM-11947). Original Jira may contain additional context.
Reported by: boyuanz.

**Comment by johnjcasey** [comment]
Closing as "will not do". This is supported using the SDF reader implementation of KafkaIO

**Comment by Abacn** [comment]
For future reference, the SDF implementation support this via "withDynamicRead(Duration)" transform configuration (done in #21752)
