### ISSUE TITLE
README example for Beam Python InteractiveRunner is broken

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20877]
Running the example from the interactive Beam README doc [1] produces an error:

```

import apache_beam as beam
from apache_beam.runners.interactive.interactive_runner import InteractiveRunner

p
= beam.Pipeline(InteractiveRunner())
pcoll = p | beam.Create([1, 2, 3])
result = p.run().wait_until_finish()
pcoll_list
= result.get(pcoll)  # This returns a list!

```

Results in:
```

---------------------------------------------------------------------------
AttributeError       
                    Traceback (most recent call last)
<ipython-input-11-b3606ce83458> in <module>()

     2 pcoll = p | beam.Create([1, 2, 3])
      3 result = p.run().wait_until_finish()
----> 4 pcoll_list
= result.get(pcoll)  # This returns a list!

AttributeError: 'NoneType' object has no attribute 'get'

```

Side note: I had to look-up the import statements here. As long as you're updating the example, it would be nice for it to be runnable with copy & paste.

[1] https://github.com/apache/beam/blob/master/sdks/python/apache_beam/runners/interactive/README.md 

 

Imported from Jira [BEAM-12234](https://issues.apache.org/jira/browse/BEAM-12234). Original Jira may contain additional context.
Reported by: shoyer.

**Comment by tvalentyn** [comment]
@KevinGG is this still an issue?

**Comment by KevinGG** [comment]
I'll update the README.md. 

This is pseudo code, the error lies within the `p.run().wait_until_finish()` but `wait_until_finish()` doesn't return the result. It should be
```python
result = p.run()
result.wait_until_finish()
```
Still the usage is discouraged, let's honor `ib.collect` in this scenario.
