### ISSUE TITLE
CalciteUtils .CharType should be generic like logicaltypes.FixedBytes

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20886]
We have a special "CalciteUtils.CharType" for fixed size char, that should be replaced with a core type like logicaltypes.FixedBytes and support added to AvroUtils and others.

Imported from Jira [BEAM-12323](https://issues.apache.org/jira/browse/BEAM-12323). Original Jira may contain additional context.
Reported by: apilloud.

**Comment by Abacn** [comment]
.remove-labels 'awaiting triage'

**Comment by Abacn** [comment]
.take-issue
