### ISSUE TITLE
google-cloud-bigquerystorage versions < 1.20.0 throw PERMISSION_DENIED in some cases

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20890]
*****description:*****
 There is an issue with the google-cloud-bigquerystorage package that has been tested using the sample google code at:  [https://cloud.google.com/bigquery/docs/write-api#using_the_with_the_java_client](https://cloud.google.com/bigquery/docs/write-api#using_the_with_the_java_client) (and confirmed by google support) to affect version(s) < 1.20.4 where writing to some BigQuery Storage Write API supported locations can incorrectly throw:

java.util.concurrent.ExecutionException: com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'TABLES_UPDATE_DATA' denied on resource 'projects/<some-project\>/datasets/<some-dataset\>/tables/<some-table\>' (or it may not exist).

This affects writing to certain locations using the BigQueryIO.Write.Method.STORAGE_WRITE_API write method

*****version(s) affected:***** 
 2.29.0

Can we update the google-cloud-bigquerystorage version to 1.20.4 or higher to resolve this issue?

Imported from Jira [BEAM-12344](https://issues.apache.org/jira/browse/BEAM-12344). Original Jira may contain additional context.
Reported by: championjared.

**Comment by kennknowles** [comment]
This is old enough I am going to close it assuming it is obsolete. Feel free to reopen if it is still happening with recent versions of Beam.
