### ISSUE TITLE
Document: _namespace is a reserved field for DoFns (used for display data)

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20907]
User reported issue when _namespace is not used for display data:

\>     self._populate_items(display_data_dict)
\>   File third_party/py/apache_beam/transforms/display.py", line 117, in _populate_items
\>     element._namespace(), element.display_data())
\> TypeError: 'str' object is not callable

Imported from Jira [BEAM-12340](https://issues.apache.org/jira/browse/BEAM-12340). Original Jira may contain additional context.
Reported by: altay.

**Comment by svetakvsundhar** [comment]
@tvalentyn ; could you provide more context on this issue? Looks like we should document this here [1] if IIUC?

[1]
https://github.com/apache/beam/blob/master/website/www/site/content/en/documentation/transforms/python/elementwise/pardo.md

**Comment by tvalentyn** [comment]
I think we can  rename HasDisplayData._namespace() to HasDisplayData._get_display_data_namespace() to prevent such collisions. As far as I can tell, the changes will be contained to `display.py`.
