### ISSUE TITLE
Squashed code snippets

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20917]
The code snippets at https://beam.apache.org/get-started/from-spark/#setup are quite wrapped, despite plenty of whitespace around them.

Imported from Jira [BEAM-12239](https://issues.apache.org/jira/browse/BEAM-12239). Original Jira may contain additional context.
Reported by: robertwb.

**Comment by pcoet** [comment]
.take-issue

**Comment by pcoet** [comment]
Fixed with https://github.com/apache/beam/pull/22770
