### ISSUE TITLE
Deprecate ParquetIO.withSplit

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20923]
We should not offer anymore the withSplit method for ParquetIO since it is the default behavior due to BEAM-12070

Imported from Jira [BEAM-12224](https://issues.apache.org/jira/browse/BEAM-12224). Original Jira may contain additional context.
Reported by: iemejia.

**Comment by aromanenko-dev** [comment]
Already fixed in #15811 (https://issues.apache.org/jira/browse/BEAM-12070)
