### ISSUE TITLE
SdkContainerImageBuilder should take machineType configs

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20947]
When prebuilding the python SDK container harness image with SdkContainerImageBuilder on google cloud build, it can run out of memory and fail the build with docker exit code 137. The default machineType is only n1-standard-1 and it is unlikely sufficient to build large images.

 

The SdkContainerImageBuilder should take additional machineType configs to circumvent the docker OOM issue.

Imported from Jira [BEAM-12447](https://issues.apache.org/jira/browse/BEAM-12447). Original Jira may contain additional context.
Reported by: yichi.

**Comment by y1chi** [comment]
Issue is fixed.
