### ISSUE TITLE
Dataflow GCS streaming file sink uses runner determined sharding

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20949]
Integrate file sink with shardable `GroupIntoBatches` (BEAM-10475) to allow runner determined dynamic sharding for streaming use cases.

Imported from Jira [BEAM-11934](https://issues.apache.org/jira/browse/BEAM-11934). Original Jira may contain additional context.
Reported by: sychen.

**Comment by Naireen** [comment]
Runner based sharding for GCS exists (done during the runner translation layer), though additional support for the runner backend to support it would require updates to the Beam model (proto API) to differentiate between the two cases.
