### ISSUE TITLE
Batch optimized translation for Spark Runner

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20943]
Spark Runner and maybe all other runners that deal with batch only data might benefit of a batch optimized translation where details about the full Beam model matter less because we are in Global window, no panes info is needed and all records use the sane (min) timestamp. With this premise the records can be encoded as 'value only' WindowValues and transforms like GroupByKey may ignore windowing (GABW) to improve performance.

Imported from Jira [BEAM-12135](https://issues.apache.org/jira/browse/BEAM-12135). Original Jira may contain additional context.
Reported by: iemejia.

**Comment by twosom** [comment]
.take-issue
