### ISSUE TITLE
Remove command prompts from quickstart commands

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20948]
We should remove the command prompts (`$`, `PS\>`) from the example commands in the quickstarts. It sucks to use the copy button to copy an e.g. Maven command, paste it into your prompt, and then have it fail because you actually copied the prompt, too. Either that or we can remove the copy button, so that users have to manually copy/paste (which is less good).

 

The Java quickstart needs this for sure, and we should check the rest.

Imported from Jira [BEAM-12407](https://issues.apache.org/jira/browse/BEAM-12407). Original Jira may contain additional context.
Reported by: pcoet.

**Comment by pcoet** [comment]
Looks like Java and Python are fixed. We just need to do the Go quickstart: https://beam.apache.org/get-started/quickstart-go/

**Comment by rszper** [comment]
.take-issue
