### ISSUE TITLE
Flink Runner 1.11 uses old Scala-Version

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20963]
I updated my project to beam 2.28.0 and also updated spring-boot to 2.2.0.RELEASE

this seems to be a problem because Spring isn't using the scala dependency any more. 

But as my dependencies says spring-kafka-test is using scala 2.12.13. 

This seems to be a problem in the testing envrionment. Because flink runner gets compiled with scala 2.11.12. As I understand scala 2.11 isn't compatible with scala 2.12.

Which leads to errors in the test environment. 

 

Adding 
```

<!-- https://mvnrepository.com/artifact/com.google.guava/guava -->
<dependency>
 <groupId>com.google.guava</groupId>

<artifactId>guava</artifactId>
 <version>26.0-jre</version>
</dependency>
```

to my pom.xml seems to solve the problem so far. 

 

But it would be nice if runner-flink could use scala 2.12 too.

 

I'm sorry if this issue isn't understandable. I'm not professional at working with maven and I only can describe as far as I understand the problem.

Imported from Jira [BEAM-12195](https://issues.apache.org/jira/browse/BEAM-12195). Original Jira may contain additional context.
Reported by: dominic.warzok.

**Comment by Abacn** [comment]
Obsolete. Flink 1.11 is no longer supported.

**Comment by Abacn** [comment]
.close-issue not_planned
