### ISSUE TITLE
org.apache.beam.runners.flink.ReadSourcePortableTest.testExecution[streaming: false] is flaky

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20975]
Example: https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/17600/

Imported from Jira [BEAM-12291](https://issues.apache.org/jira/browse/BEAM-12291). Original Jira may contain additional context.
Reported by: kenn.

**Comment by kennknowles** [comment]
Couldn't repro after running on repeat for a while. If it occurs in Jenkins we can reopen or file a new one.
