### ISSUE TITLE
Replace _unified_repr with repr

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20982]
function: https://github.com/apache/beam/blob/8926c43f20ab19b8e445d519cf424e881365fc6c/sdks/python/apache_beam/typehints/typehints.py#L354

\_unified_repr was written for Python 2.x, but repr() should now be a suitable replacement (see https://www.python.org/dev/peps/pep-3155/).

repr() is typically more verbose than \_\_name\_\_ unfortunately (<class 'int'\> vs int), breaking lots of unit tests that depend on exact strings. These test could also be updated to use the less brittle self.assertRaisesRegex.

Imported from Jira [BEAM-12469](https://issues.apache.org/jira/browse/BEAM-12469). Original Jira may contain additional context.
Reported by: udim.

**Comment by hurutoriya** [comment]
.take-issue
