### ISSUE TITLE
Easy way to run a single validates runner test

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20995]
To run a single validates runner test, usually I change the testFilter block in the source to add an includeTestsMatching for the test I want to run. There should be an easy way to do this on the command line without having to modify the source.

Imported from Jira [BEAM-12728](https://issues.apache.org/jira/browse/BEAM-12728). Original Jira may contain additional context.
Reported by: ibzib.

**Comment by mosche** [comment]
@ibzib This is absolutely possible using the usual `--tests` param, e.g.
```
gradle :runners:flink:1.15:validatesRunnerBatch --tests "org.apache.beam.sdk.schemas.AvroSchemaTest"
gradle :runners:flink:1.15:validatesRunnerStreaming --tests "org.apache.beam.sdk.schemas.AvroSchemaTest"
gradle :runners:spark:3:validatesRunnerStreaming --tests "org.apache.beam.sdk.schemas.AvroSchemaTest"
```
