### ISSUE TITLE
Support major version bump of google-cloud-vision and google-cloud-pubsub

### ISSUE THREAD

**Issue by damccorm** [apache/beam#20991]
In our project, we want to use apache-beam, but cannot due to having these dependencies:

 

google-cloud-pubsub\==2.5.0

google-cloud-vision\==2.0.0

Seems like the breaking change was due to "microgenerator"

[https://github.com/googleapis/python-pubsub/releases](https://github.com/googleapis/python-pubsub/releases)

[https://github.com/googleapis/python-vision/releases](https://github.com/googleapis/python-vision/releases)

(also dropping support for older versions of python)

 

What do we need to do to increase the version support defined here: https://github.com/apache/beam/blob/cd2117b8abd83603bf00976b28239c82a4c9918d/sdks/python/setup.py#L199

Imported from Jira [BEAM-12498](https://issues.apache.org/jira/browse/BEAM-12498). Original Jira may contain additional context.
Reported by: sangm.

**Comment by tvalentyn** [comment]
google-cloud-videointellingence also has breaking changes (https://github.com/apache/beam/pull/17615 ).

Things to do:
1) increase upper bound (<3), increase (lower bound>=2)
2) regenerate container dependencies
3) run postcommit integration tests that exercise these deps
4) fix any api incompatibilities.
5) run tests again
6) commit changes.

Assuming #4 doesn't require drastic changes, this shouldn't be too difficult, happy to provide further pointers if someone is interested to pick it up.

**Comment by AnandInguva** [comment]
FYi, goolge-cloud-vision was updated and other GCP libraries will be updated as part of https://github.com/apache/beam/pull/24599
