### ISSUE TITLE
Improve parallelism of closing files in FileIO

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21095]
Currently close happens in processElement which is per-window.
If there are many windows firing this can throttle throughput waiting for IO instead of closing in parallel in finishBundle.

Imported from Jira [BEAM-12776](https://issues.apache.org/jira/browse/BEAM-12776). Original Jira may contain additional context.
Reported by: scwhittle.

**Comment by lukecwik** [comment]
@scwhittle A fix in https://github.com/apache/beam/pull/15354 seems to be causing OOMs for certain customer workflows. The customer specifically bounded the number of parallel closes to 2 by patching the code to work around the issue.

**Comment by lukecwik** [comment]
Potential reduction in OOM potential in https://github.com/apache/beam/pull/22645
