### ISSUE TITLE
Powered-by page requires so many clicks

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21090]
Go-to https://beam.apache.org/powered-by/ page
Click 1:  Choose commercial or open source
(Let's say we clicked the first one)
There are 3 items
Click 2: Load more to see 3 more items
Click 3: Load more to see 2 more items.

There is a total of 8 items, no need for these load more links.

Could we merge all powered by items in a single page (remove commercial/oss, and remove load more)?

Imported from Jira [BEAM-12839](https://issues.apache.org/jira/browse/BEAM-12839). Original Jira may contain additional context.
Reported by: altay.

**Comment by pcoet** [comment]
This page no longer exists.
