### ISSUE TITLE
java.io.InvalidClassException With Flink Kafka

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21108]
Beam: 2.30.0

Flink: 1.12.0

Kafka: 2.6.0

- kafka-topics.sh \--version

2.6.0 (Commit:62abe01bee039651)

 

- python3 kafka_taxi.py \--bootstrap_servers localhost:9092 \--topic testTopic

INFO:apache_beam.utils.subprocess_server:Using cached job server jar from https://repo.maven.apache.org/maven2/org/apache/beam/beam-sdks-java-io-expansion-service/2.30.0/beam-sdks-java-io-expansion-service-2.30.0.jar

INFO:apache_beam.utils.subprocess_server:Starting service with ['java' '-jar' '/home/root/.apache_beam/cache/jars/beam-sdks-java-io-expansion-service-2.30.0.jar' '48391']

INFO:apache_beam.utils.subprocess_server:b'Starting expansion service at localhost:48391'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:15 PM org.apache.beam.sdk.expansion.service.ExpansionService loadRegisteredTransforms'

INFO:apache_beam.utils.subprocess_server:b'INFO: Registering external transforms: [beam:external:java:kafka:read:v1, beam:external:java:kafka:write:v1, beam:external:java:generate_sequence:v1]'

INFO:apache_beam.utils.subprocess_server:b'\tbeam:external:java:kafka:read:v1: org.apache.beam.sdk.expansion.service.ExpansionService$ExternalTransformRegistrarLoader$$Lambda$3/405662939@2aae9190'

INFO:apache_beam.utils.subprocess_server:b'\tbeam:external:java:kafka:write:v1: org.apache.beam.sdk.expansion.service.ExpansionService$ExternalTransformRegistrarLoader$$Lambda$3/405662939@2f333739'

INFO:apache_beam.utils.subprocess_server:b'\tbeam:external:java:generate_sequence:v1: org.apache.beam.sdk.expansion.service.ExpansionService$ExternalTransformRegistrarLoader$$Lambda$3/405662939@77468bd9'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:16 PM org.apache.beam.sdk.expansion.service.ExpansionService expand'

INFO:apache_beam.utils.subprocess_server:b"INFO: Expanding 'ReadFromKafka(beam:external:java:kafka:read:v1)' with URN 'beam:external:java:kafka:read:v1'"

 

 

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:17 PM org.apache.beam.sdk.expansion.service.ExpansionService$ExternalTransformRegistrarLoader payloadToConfig'

INFO:apache_beam.utils.subprocess_server:b"WARNING: Configuration class 'org.apache.beam.sdk.io.kafka.KafkaIO$Read$External$Configuration' has no schema registered. Attempting to construct with setter approach."

INFO:apache_beam.runners.worker.worker_pool_main:Listening for workers at localhost:37275

WARNING:root:Make sure that locally built Python SDK docker image has Python 3.8 interpreter.

INFO:root:Default Python SDK image for environment is apache/beam_python3.8_sdk:2.30.0

INFO:apache_beam.runners.portability.flink_runner:Adding HTTP protocol scheme to flink_master parameter: http://localhost:8081

INFO:apache_beam.utils.subprocess_server:Using cached job server jar from https://repo.maven.apache.org/maven2/org/apache/beam/beam-runners-flink-1.12-job-server/2.30.0/beam-runners-flink-1.12-job-server-2.30.0.jar

INFO:apache_beam.utils.subprocess_server:Starting service with ['java' '-jar' '/home/root/.apache_beam/cache/jars/beam-runners-flink-1.12-job-server-2.30.0.jar' '--flink-master' 'http://localhost:8081' '--artifacts-dir' '/tmp/beam-tempq392rofp/artifacts0l1avyn1' '--job-port' '36291' '--artifact-port' '0' '--expansion-port' '0']('java' '-jar' '/home/root/.apache_beam/cache/jars/beam-runners-flink-1.12-job-server-2.30.0.jar' '--flink-master' 'http://localhost:8081' '--artifacts-dir' '/tmp/beam-tempq392rofp/artifacts0l1avyn1' '--job-port' '36291' '--artifact-port' '0' '--expansion-port' '0')

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:21 PM org.apache.beam.runners.jobsubmission.JobServerDriver createArtifactStagingService'

INFO:apache_beam.utils.subprocess_server:b'INFO: ArtifactStagingService started on localhost:40891'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:21 PM org.apache.beam.runners.jobsubmission.JobServerDriver createExpansionService'

INFO:apache_beam.utils.subprocess_server:b'INFO: Java ExpansionService started on localhost:40389'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:21 PM org.apache.beam.runners.jobsubmission.JobServerDriver createJobServer'

INFO:apache_beam.utils.subprocess_server:b'INFO: JobService started on localhost:36291'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:21 PM org.apache.beam.runners.jobsubmission.JobServerDriver run'

INFO:apache_beam.utils.subprocess_server:b'INFO: Job server now running, terminate with Ctrl****C'

WARNING:apache_beam.options.pipeline_options:Discarding unparseable args: [[]]

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:22 PM org.apache.beam.runners.fnexecution.artifact.ArtifactStagingService$2 onNext'

INFO:apache_beam.utils.subprocess_server:b'INFO: Staging artifacts for job_d7203ede-84d9-4c7e-b061-22178dfd5458.'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:22 PM org.apache.beam.runners.fnexecution.artifact.ArtifactStagingService$2 resolveNextEnvironment'

INFO:apache_beam.utils.subprocess_server:b'INFO: Resolving artifacts for job_d7203ede-84d9-4c7e-b061-22178dfd5458.ref_Environment_default_environment_2.'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:22 PM org.apache.beam.runners.fnexecution.artifact.ArtifactStagingService$2 onNext'

INFO:apache_beam.utils.subprocess_server:b'INFO: Getting 1 artifacts for job_d7203ede-84d9-4c7e-b061-22178dfd5458.external_1beam:env:docker:v1.'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:22 PM org.apache.beam.runners.fnexecution.artifact.ArtifactStagingService$2 resolveNextEnvironment'

INFO:apache_beam.utils.subprocess_server:b'INFO: Resolving artifacts for job_d7203ede-84d9-4c7e-b061-22178dfd5458.external_1beam:env:docker:v1.'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:22 PM org.apache.beam.runners.fnexecution.artifact.ArtifactStagingService$2 onNext'

INFO:apache_beam.utils.subprocess_server:b'INFO: Getting 8 artifacts for job_d7203ede-84d9-4c7e-b061-22178dfd5458.null.'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:22 PM org.apache.beam.runners.fnexecution.artifact.ArtifactStagingService$2 finishStaging'

INFO:apache_beam.utils.subprocess_server:b'INFO: Artifacts fully staged for job_d7203ede-84d9-4c7e-b061-22178dfd5458.'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:22 PM org.apache.beam.runners.flink.FlinkJobInvoker invokeWithExecutor'

INFO:apache_beam.utils.subprocess_server:b'INFO: Invoking job BeamApp-root-0609171722-21833e7a_2d7211fd-2148-4475-9455-78247144f3f1 with pipeline runner org.apache.beam.runners.flink.FlinkPipelineRunner@1e523748'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:22 PM org.apache.beam.runners.jobsubmission.JobInvocation start'

INFO:apache_beam.utils.subprocess_server:b'INFO: Starting job invocation BeamApp-root-0609171722-21833e7a_2d7211fd-2148-4475-9455-78247144f3f1'

INFO:apache_beam.runners.portability.portable_runner:Environment "LOOPBACK" has started a component necessary for the execution. Be sure to run the pipeline using

  with Pipeline() as p:

    p.apply(..)

This ensures that the pipeline finishes before this program exits.

INFO:apache_beam.runners.portability.portable_runner:Job state changed to STOPPED

INFO:apache_beam.runners.portability.portable_runner:Job state changed to STARTING

INFO:apache_beam.runners.portability.portable_runner:Job state changed to RUNNING

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:23 PM org.apache.beam.runners.flink.FlinkPipelineRunner runPipelineWithTranslator'

INFO:apache_beam.utils.subprocess_server:b'INFO: Translating pipeline to Flink program.'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:23 PM org.apache.beam.runners.flink.FlinkExecutionEnvironments createStreamExecutionEnvironment'

INFO:apache_beam.utils.subprocess_server:b'INFO: Creating a Streaming Environment.'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:23 PM org.apache.beam.runners.flink.FlinkExecutionEnvironments createStreamExecutionEnvironment'

INFO:apache_beam.utils.subprocess_server:b'INFO: Using Flink Master URL localhost:8081.'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:23 PM org.apache.flink.api.java.typeutils.TypeExtractor analyzePojo'

INFO:apache_beam.utils.subprocess_server:b'INFO: No fields were detected for class org.apache.beam.sdk.util.WindowedValue so it cannot be used as a POJO type and must be processed as GenericType. Please read the Flink documentation on "Data Types & Serialization" for details of the effect on performance.'

INFO:apache_beam.utils.subprocess_server:b'Jun 09, 2021 5:17:33 PM org.apache.beam.runners.jobsubmission.JobInvocation$1 onFailure'

INFO:apache_beam.utils.subprocess_server:b'SEVERE: Error during job invocation BeamApp-root-0609171722-21833e7a_2d7211fd-2148-4475-9455-78247144f3f1.'

INFO:apache_beam.utils.subprocess_server:b'org.apache.flink.client.program.ProgramInvocationException: Job failed (JobID: 28cd91b3a65462089cf519e0f9078fe3)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.client.deployment.ClusterClientJobClientAdapter.lambda$null$6(ClusterClientJobClientAdapter.java:125)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.client.program.rest.RestClusterClient.lambda$pollResourceAsync$22(RestClusterClient.java:665)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$9(FutureUtils.java:394)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:943)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.lang.Thread.run(Thread.java:748)'

INFO:apache_beam.utils.subprocess_server:b'Caused by: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:144)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.client.deployment.ClusterClientJobClientAdapter.lambda$null$6(ClusterClientJobClientAdapter.java:123)'

INFO:apache_beam.utils.subprocess_server:b'\t... 19 more'

INFO:apache_beam.utils.subprocess_server:b'Caused by: org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:116)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:78)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:224)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:217)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:208)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:610)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:89)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:419)'

INFO:apache_beam.utils.subprocess_server:b'\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)'

INFO:apache_beam.utils.subprocess_server:b'\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)'

INFO:apache_beam.utils.subprocess_server:b'\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.lang.reflect.Method.invoke(Method.java:498)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:286)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:201)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:74)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:154)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)'

INFO:apache_beam.utils.subprocess_server:b'\tat scala.PartialFunction.applyOrElse(PartialFunction.scala:123)'

INFO:apache_beam.utils.subprocess_server:b'\tat scala.PartialFunction.applyOrElse$(PartialFunction.scala:122)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)'

INFO:apache_beam.utils.subprocess_server:b'\tat scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)'

INFO:apache_beam.utils.subprocess_server:b'\tat scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)'

INFO:apache_beam.utils.subprocess_server:b'\tat scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.actor.Actor.aroundReceive(Actor.scala:517)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.actor.Actor.aroundReceive$(Actor.scala:515)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.actor.ActorCell.invoke(ActorCell.scala:561)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.dispatch.Mailbox.run(Mailbox.scala:225)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.dispatch.Mailbox.exec(Mailbox.scala:235)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)'

INFO:apache_beam.utils.subprocess_server:b'\tat akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)'

INFO:apache_beam.utils.subprocess_server:b'Caused by: org.apache.flink.streaming.runtime.tasks.StreamTaskException: Could not deserialize inputs'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.streaming.api.graph.StreamConfig.getInputs(StreamConfig.java:265)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.streaming.api.graph.StreamConfig.getTypeSerializerIn(StreamConfig.java:280)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.streaming.api.graph.StreamConfig.getTypeSerializerIn1(StreamConfig.java:271)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.streaming.runtime.tasks.OperatorChain.wrapOperatorIntoOutput(OperatorChain.java:639)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.streaming.runtime.tasks.OperatorChain.createOperatorChain(OperatorChain.java:591)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:526)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.streaming.runtime.tasks.OperatorChain.<init\>(OperatorChain.java:164)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:485)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:531)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:722)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.runtime.taskmanager.Task.run(Task.java:547)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.lang.Thread.run(Thread.java:748)'

INFO:apache_beam.utils.subprocess_server:b'Caused by: java.io.InvalidClassException: org.apache.flink.streaming.api.graph.StreamConfig$NetworkInputConfig; local class incompatible: stream classdesc serialVersionUID = 3698633776553163849, local class serialVersionUID = -3137689219135046939'

INFO:apache_beam.utils.subprocess_server:b'\tat java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2002)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1849)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2159)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1666)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.io.ObjectInputStream.readArray(ObjectInputStream.java:2092)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1654)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.io.ObjectInputStream.readObject(ObjectInputStream.java:502)'

INFO:apache_beam.utils.subprocess_server:b'\tat java.io.ObjectInputStream.readObject(ObjectInputStream.java:460)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:576)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:562)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:550)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:511)'

INFO:apache_beam.utils.subprocess_server:b'\tat org.apache.flink.streaming.api.graph.StreamConfig.getInputs(StreamConfig.java:259)'

INFO:apache_beam.utils.subprocess_server:b'\t... 11 more'

INFO:apache_beam.utils.subprocess_server:b''

ERROR:root:java.io.InvalidClassException: org.apache.flink.streaming.api.graph.StreamConfig$NetworkInputConfig; local class incompatible: stream classdesc serialVersionUID = 3698633776553163849, local class serialVersionUID = -3137689219135046939

INFO:apache_beam.runners.portability.portable_runner:Job state changed to FAILED

Traceback (most recent call last):

  File "kafka_taxi.py", line 105, in <module\>

    run(known_args.bootstrap_servers, known_args.topic, pipeline_args)

  File "kafka_taxi.py", line 79, in run

    _ = (

  File "/usr/local/lib/python3.8/dist-packages/apache_beam/pipeline.py", line 586, in __exit__

    self.result.wait_until_finish()

  File "/usr/local/lib/python3.8/dist-packages/apache_beam/runners/portability/portable_runner.py", line 599, in wait_until_finish

    raise self._runtime_exception

RuntimeError: Pipeline BeamApp-root-0609171722-21833e7a_2d7211fd-2148-4475-9455-78247144f3f1 failed in state FAILED: java.io.InvalidClassException: org.apache.flink.streaming.api.graph.StreamConfig$NetworkInputConfig; local class incompatible: stream classdesc serialVersionUID = 3698633776553163849, local class serialVersionUID = -3137689219135046939

Imported from Jira [BEAM-12467](https://issues.apache.org/jira/browse/BEAM-12467). Original Jira may contain additional context.
Reported by: ravidborse.

**Comment by kennknowles** [comment]
This indicates a mismatch in your flink versions.
