### ISSUE TITLE
SDF BoundedSource seems to execute significantly slower than 'normal' BoundedSource

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21109]
This was discovered when using ReadFromBigQuery with Dataflow V2.

Imported from Jira [BEAM-12525](https://issues.apache.org/jira/browse/BEAM-12525). Original Jira may contain additional context.
Reported by: pabloem.

**Comment by kennknowles** [comment]
@robertwb is this obsolete or is it still blocking some migrations to v2?

**Comment by johnjcasey** [comment]
@pabloem did you have any data or specific examples for this?
