### ISSUE TITLE
Migrate to the next version of Python `requests` when released

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21119]
Hello Maintainers, 

I am a PMC member of Apache Airflow, and I wanted to give you a bit of heads-up with rather important migration to the upcoming version of `requests` library in your Python release. 

Since you are using `requests` library in your project, you are affected.

As discussed at length in https://issues.apache.org/jira/browse/LEGAL-572 we found out that the 'chardet` library used by `requests` library was a mandatory dependency to requests and since it has LGPL licence, we should not release any Apache Software with it. 

Since then (and since in Airflow we rely on requests heavily) we have been working with the requests maintainers and "charset-normalizer" maintainer to make it possible to replace `chardet` with MIT-licensed `charset-normalizer` instead so that requests library can be used in Python releases by Apache projects.

This was a bumpy road but finally the PR by [~ash] has been merged: [https://github.com/psf/requests/pull/5797](https://github.com/psf/requests/pull/5797) and we hope soon a new version of requests library will be released. 

This is just a heads-up. I will let you know when it is released, but I have a kind requests as well - I might ask the maintainers to release a release candidate of requests and maybe you could help to test it before it is released, that would be some re-assurance for the maintainers of requests who are very concerned about stability of their releases.

Let me know if you need any more information and whether you would like to help in testing the candidate when it is out.

Imported from Jira [BEAM-12598](https://issues.apache.org/jira/browse/BEAM-12598). Original Jira may contain additional context.
Reported by: potiuk.

**Comment by tvalentyn** [comment]
Thanks, Brian
