### ISSUE TITLE
[Playground] ctrl/command + z unstable behavioural

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21125]
Scenario: Put a new line

When: User put a new line in the code editor

And: Press ctrl****z or command****z 

Then: new line not rollback 

 

Scenario: Fast ctrl****v 

When: User put a new text to code editor using ctrl****v or command****v

And: Repeat ctrl/command **** v many times quickly

And: Press ctrl/command****z

Then: inserted lines not rollback

 

When: user click ctrl****z many times 

Then: inserted lines rollback correctly

Imported from Jira [BEAM-13122](https://issues.apache.org/jira/browse/BEAM-13122). Original Jira may contain additional context.
Reported by: IKozyrev.

**Comment by alexeyinkin** [comment]
Quick repeating hotkeys were fixed here: https://github.com/flutter/flutter/issues/92653

Left is inability to undo breaking a line.

## Steps to Reproduce: ##
1. In an empty Playground, type a few letters.
2. Break the line.
3. Type a few more letters.
4. Press Ctrl-Z multiple times.

**Expected:** Every typed character is undone.

**Actual:** Same line edits are undone, but breaking the line is not undone, Ctrl-Z has no effect from that point.

![vokoscreen-2022-07-15_14-15-45](https://user-images.githubusercontent.com/44893228/179204562-041bba50-f8f6-4cd8-87f0-589920c14446.gif)

If there are any more reproducible scenarios, please describe.
