### ISSUE TITLE
JDBC IO: expose max pool connections as a setting

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21200]
This is related to [BEAM-9629](https://issues.apache.org/jira/browse/BEAM-9629) and [this]([https://github.com/spotify/scio/issues/4047).](https://github.com/spotify/scio/issues/4047).) In some cases users need to have an option to bump number of max connections in the pool, but as of today the process of overriding the number isn't user friendly. Would be helpful to have this as a separate first class JDBC setting a user can configure.

Imported from Jira [BEAM-13261](https://issues.apache.org/jira/browse/BEAM-13261). Original Jira may contain additional context.
Reported by: kirillp.

**Comment by pas725** [comment]
.take-issue

**Comment by pas725** [comment]
Hello @damccorm ,

How to assign reviewers for the PR #24851 ? 
Auto reviewer assignment by bot failed.

**Comment by damccorm** [comment]
Requesting assignment like you did is fine, the bot should eventually assign reviewers even if it initially fails though (it may take some time)
