### ISSUE TITLE
BigQueryUtils doesn't process List or Map with nullables

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21208]
When using PubsubAvroToBigQuery Dataflow template, [I noticed this issue. ](https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/287)
 This seems to be related to the way [toBeamRow](https://github.com/apache/beam/blob/v2.32.0/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryUtils.java#L593) is handling TableRow with List containing null values.

The error trace has this path (I only added the relevant ones):

a. com.google.cloud.teleport.v2.transforms.BigQueryConverters$TableRowToGenericRecordFn.apply(BigQueryConverters.java:548) 
 b. [org.apache.beam.sdk.io](https://org.apache.beam.sdk.io/).gcp.bigquery.BigQueryUtils.toBeamRow(BigQueryUtils.java:580) 
 c. [org.apache.beam.sdk.io](https://org.apache.beam.sdk.io/).gcp.bigquery.BigQueryUtils.toBeamRowFieldValue(BigQueryUtils.java:593)
 d. [org.apache.beam.sdk.io](https://org.apache.beam.sdk.io/).gcp.bigquery.BigQueryUtils.toBeamValue(BigQueryUtils.java:641)

On c., a validation of null "bqValue" objects is performed; however, it appears that some of the elements are of List type (for BigQuery Record type); therefore, the List object is validated to be non-null, but not the elements of the List.

On d., the method is executed recursively to process all the elements of the List object; however, it seems that some objects are Null so this method is throwing the NullPointerExceptions.

*toBeamValue method should probably not used toBeamValue recursively but toBeamRowFieldValue instead.*

Imported from Jira [BEAM-12863](https://issues.apache.org/jira/browse/BEAM-12863). Original Jira may contain additional context.
Reported by: pocman.

**Comment by iamdebojyoti** [comment]
Hi @damccorm 
Is this issue still open? If yes, I would like to contribute to it.

**Comment by damccorm** [comment]
Hey @iamdebojyoti as far as I know this is still an issue, and we'd be happy to have you contribute. With that said, I just moved the issue [from Jira](https://issues.apache.org/jira/browse/BEAM-12863) to Issues I haven't actually run into it myself, I believe the original issue was created by @ecapoccia 

Since its somewhat old, I'd start y seeing if you can repro.

**Comment by jon-esperanza** [comment]
.take-issue

**Comment by jon-esperanza** [comment]
@Abacn can this issue be closed as well
