### ISSUE TITLE
Cassandra IO Does not work with ssl enabled Cassandra/Cosmos DB on Azure

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21223]
Not Able to use cassandra Io with ssl enabled cosmos db or cassandra as cassandra IO does not expose cluster builder options. This looks like a basic feature set. It would be great to resolve this as early as possible to avoid organizations rejecting it due to missing ssl feature.

Imported from Jira [BEAM-12844](https://issues.apache.org/jira/browse/BEAM-12844). Original Jira may contain additional context.
Reported by: bumblebee.

**Comment by damccorm** [comment]
Unable to assign user @vmarquez. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by niv-lac** [comment]
@damccorm I'd be interested on working on this improvement. My team currently leverages Cassandra using SSL and it would be nice to surface the SSL functionality so we can migrate some of our pipelines over to Dataflow.

**Comment by damccorm** [comment]
Great, I assigned you the issue! If you have any questions, @johnjcasey would be a good person to loop in (or he can probably recommend someone else)

**Comment by niv-lac** [comment]
Thank you! Thanks for the contact info, will definitely reach out to John if/when 😄  I have question.

**Comment by calvin-orange** [comment]
Just wanted to mention, I got a little swamped but able to free up some time and will start working on this soon.

**Comment by vmarquez** [comment]
Feel free to ping me if you want a review, I'm @vmarquez on github.

*~Vincent*
