### ISSUE TITLE
add external references to the Beam Community page

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21245]
There's lots of good third party content out there about Beam; we should highlight it as well:

[https://stackoverflow.com/questions/tagged/apache-beam](https://stackoverflow.com/questions/tagged/apache-beam) 

[https://towardsdatascience.com/tagged/apache-beam](https://towardsdatascience.com/tagged/apache-beam)

 

Imported from Jira [BEAM-12972](https://issues.apache.org/jira/browse/BEAM-12972). Original Jira may contain additional context.
Reported by: sachinag.

**Comment by rszper** [comment]
The StackOverflow page is already in the Join the Conversation section of the Community page: https://beam.apache.org/community/join-beam/
