### ISSUE TITLE
Deprecate amazon-web-services & kinesis module (SDK v1)

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21249]
As discussed with [~aromanenko] and previously in the community, goal is to keep only IOs for AWS SDK v2. The module for AWS SDK v1 will be deprecated and eventually be removed to avoid maintaining two code basis.

As part of this ticket we need to evaluate if there's potentially missing features in aws2 that would prevent deprecation / removal.

Particularly lack of writes for KinesisIO in aws2 are a known gap and have to be addressed.

Imported from Jira [BEAM-13174](https://issues.apache.org/jira/browse/BEAM-13174). Original Jira may contain additional context.
Reported by: mosche.

**Comment by mosche** [comment]
Just for reference, here's pointers to related discussions on the mailing list 
- https://lists.apache.org/thread/0s0cnq92cvtylnpfrd34gh9llo5k8g4f
- https://lists.apache.org/thread/b4opwr3x1rr63732b5j7f47r2bobq6h0
