### ISSUE TITLE
Dataflow runner specialization of PubsubIO should validate messages

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21252]
Currently invalid messages, such as those with attributes exceeding the maximum size are processed by the bundle successfully but fail to commit.

Throwing an exception when trying to write such a message directly would increase visibility as well as allowing users to catch and handle such exceptions.

Imported from Jira [BEAM-12942](https://issues.apache.org/jira/browse/BEAM-12942). Original Jira may contain additional context.
Reported by: scwhittle.

**Comment by damccorm** [comment]
Unable to assign user @scwhittle. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by scwhittle** [comment]
.take-issue

**Comment by scwhittle** [comment]
.close-issue
