### ISSUE TITLE
[Website] Bug in side navigation when changing tabs in code snippets

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21251]
Steps to reproduce the bug:
 - Go to the [Beam Programming Guide](https://beam.apache.org/documentation/programming-guide/) page
 - Go to any code snippet and click on its tabs
 - Notice at the right side in the side nav that the current pointer will be jumping around sections

Other pages of Beam's documentation might have the same issue.

Imported from Jira [BEAM-13229](https://issues.apache.org/jira/browse/BEAM-13229). Original Jira may contain additional context.
Reported by: Mike Hernandez.

**Comment by damccorm** [comment]
Unable to assign user @bullet03. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by bullet03** [comment]
@damccorm, didn't manage to self-assign, could you kindly do it?

**Comment by damccorm** [comment]
@bullet03 you should now be able to self-assign by commenting `.take-issue` (and you can similarly close an issue with `.close-issue`)
