### ISSUE TITLE
Race between member variable being accessed due to leaking uninitialized state via OutboundObserverFactory

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21268]
The OutboundObserverFactory leaks the InboundObserver and makes it ready to start getting requests before the method returns leading to a dangerous state where the passed in InboundObserver could be used before the constructor of the enclosing class is finished.

This was found when running the Spark PVR PostCommit:

Looks like this went from being a flake to a hard failure: 
https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/
https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/5009/

18:41:18 Build timed out (after 100 minutes). Marking the build as aborted.

Imported from Jira [BEAM-13164](https://issues.apache.org/jira/browse/BEAM-13164). Original Jira may contain additional context.
Reported by: apilloud.

**Comment by kennknowles** [comment]
This is green now. It looks like the work in #15888 got it healthy enough. (before the Jira to GitHub Issues migration)
