### ISSUE TITLE
[Playground] Perma-link generation for a sample created by a user

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21274]
As a Beam Playground __user__, I want to create a permanent link to the code sample I created in Beam Playground, so I can share this Beam Playground sample outside of the web app.

Imported from Jira [BEAM-13516](https://issues.apache.org/jira/browse/BEAM-13516). Original Jira may contain additional context.
Reported by: Artur.Khanin.

**Comment by damccorm** [comment]
The following subtask(s) are associated with this issue: #21275

**Comment by alexeyinkin** [comment]
.take-issue

**Comment by alexeyinkin** [comment]
This was done in https://github.com/apache/beam/issues/21978
Waiting for deployment to close this issue.

**Comment by rshamunov** [comment]
All related tasks were completed.
