### ISSUE TITLE
Add getOrderingKey in org.apache.beam.sdk.io.gcp.pubsub.PubsubMessage

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21304]
Currently ordering key is added in python sdk in PR: [https://github.com/apache/beam/pull/14767](https://github.com/apache/beam/pull/14767)

Need to implement similarly for java (org.apache.beam.sdk.io.gcp.pubsub.PubsubMessage).

Is this in the roadmap? If yes, could you ping the Jira here? 

Thanks!

 

Imported from Jira [BEAM-13592](https://issues.apache.org/jira/browse/BEAM-13592). Original Jira may contain additional context.
Reported by: kedia56.

**Comment by egalpin** [comment]
relates to #21162

**Comment by egalpin** [comment]
Fixed by https://github.com/apache/beam/pull/22216
