### ISSUE TITLE
Document our stance on local runners

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21349]
We often get questions like "is the direct runner suitable for production"? and the answer is usually no. We should document our recommendations for small (one machine) pipelines somewhere on the website.

Imported from Jira [BEAM-13989](https://issues.apache.org/jira/browse/BEAM-13989). Original Jira may contain additional context.
Reported by: ibzib.

**Comment by rszper** [comment]
.take-issue

**Comment by rszper** [comment]
.close-issue
