### ISSUE TITLE
Spark tests failing PerKeyOrderingTest

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21340]
Looks like new tests were added missing annotations.

java.lang.IllegalStateException: Not expected to directly translate splittable DoFn, should have been overridden: org.apache.beam.sdk.transforms.PeriodicSequence$PeriodicSequenceFn@3fddc80d

https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark

Imported from Jira [BEAM-13522](https://issues.apache.org/jira/browse/BEAM-13522). Original Jira may contain additional context.
Reported by: ibzib.

**Comment by mosche** [comment]
Fixed as part of https://github.com/apache/beam/pull/16438
