### ISSUE TITLE
[Playground] Merge Log and Output tabs into one and add there filtering

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21352]
As a Beam Playground __User__, I want to have one tab with Logs and Outputs so I can filter them to see just Logs, Outputs, or both.

*Acceptance criteria:*
 * Logs and Outputs are at the same tab
 * Logs and Outputs appear as they come
 * Logs and Outputs can be filtered
 * Logs and Outputs are showed both as default

Imported from Jira [BEAM-13756](https://issues.apache.org/jira/browse/BEAM-13756). Original Jira may contain additional context.
Reported by: Artur.Khanin.

**Comment by damccorm** [comment]
Unable to assign user @miamihotline. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by miamihotline** [comment]
.close-issue
