### ISSUE TITLE
Reduce number of Gax related threads, likely by providing common executor to GAX clients

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21368]
When looking at thread stacks for a pipeline reading pubsub and writing to BQ using the WriteApi  there were 3600 Gax- prefixed threads.

The # of threads an possibly performance could be improved by finding where these came from and using a shared executor.

Imported from Jira [BEAM-13826](https://issues.apache.org/jira/browse/BEAM-13826). Original Jira may contain additional context.
Reported by: scwhittle.

**Comment by chamikaramj** [comment]
John, assigning to you to prioritize since this could be hit by users when using various I/O connectors (for example, BigQueryIO sink with the STORAGE_WRITE_API mode).

**Comment by TheNeuralBit** [comment]
IIUC the appropriate fix is to adjust client libraries used in various IOs to use a shared channel (@lukecwik can advise).

**Comment by reuvenlax** [comment]
I thought that the main bug had already been fixed.

**Comment by johnjcasey** [comment]
Is there any documentation on where we use GAX, or a pointer to a design pattern for this?

**Comment by chamikaramj** [comment]
@reuvenlax do you have a link to the fix ?

also ccing @scwhittle who filed the original issue.

**Comment by TheNeuralBit** [comment]
@reuvenlax maybe you're thinking of https://github.com/apache/beam/pull/16619 which fixed a different thread explosion in `RetryManager`?

**Comment by TheNeuralBit** [comment]
> Is there any documentation on where we use GAX, or a pointer to a design pattern for this?

I'm not sure about documentation. My understanding from offline discussion with @lukecwik, is that gax-java is used by grpc-java which is used by Google client libraries used by various GCP IOs. The client libraries generally have ways to specify an executor that would allow us to specify a shared one. See [here](https://github.com/googleapis/gax-java/issues/1286#issuecomment-829555309) for an example in the Spanner client.

**Comment by johnjcasey** [comment]
Got it. I suppose I will need to do some research on executor options to know which one is the best for this use case

**Comment by johnjcasey** [comment]
@lukecwik do you have a recommendation on executors to try?

**Comment by johnjcasey** [comment]
A somewhat simple change would be to update the various get methods in BigQueryServicesImpl to be cached. If you pass in the same options, you get the existing client instance. 

https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java#L183

**Comment by reuvenlax** [comment]
We do cache the client instances. The problem is that today, each
destination table requires a separate client.

**Comment by johnjcasey** [comment]
got it
so we shouldn't add additional caching, but instead cache the transport s.t. all the various clients use the same one?

**Comment by johnjcasey** [comment]
Speaking of, where does that caching occur?

**Comment by reuvenlax** [comment]
Yes, but at least today there is no way of doing that AFAICT. We might have
to wait for the BigQuery support to land.

**Comment by lukecwik** [comment]
The client libraries allow injecting our own transport/threadpool via `BigQueryWriteClient#setTransportChannelProvider`  and `BigQueryWriteClient#setBackgroundExecutorProvider`.

I still think we should be re-using the client across bundles by having a global object pool of `BQ Options -> Client`

**Comment by reuvenlax** [comment]
We are reusing clients across bundles for streaming write API. The DoFns
that use this keep a global static cache of table name -> client

**Comment by scwhittle** [comment]
Did you see Luke's suggestion about that?
```
The client libraries allow injecting our own transport/threadpool via BigQueryWriteClient#setTransportChannelProvider and BigQueryWriteClient#setBackgroundExecutorProvider.
```
So you could have a static shared transport and threadpool across all the cached clients

**Comment by johnjcasey** [comment]
@lukecwik or @scwhittle do either of you have a suggestion on what transport to use? I'm fairly unfamiliar with the details of these

**Comment by lukecwik** [comment]
There is only one gRPC channel provider, the InstantiatingGrpcChannelProvider which is also the default. You could experiment with creating a fixed one but I would suggest using `setBackgroundExecutorProvider` on all the clients using a FixedExecutorService and updating https://github.com/apache/beam/blob/9be9a43c1b85be9b2f78e2943f6092ccb88e13b4/sdks/java/extensions/google-cloud-platform-core/src/main/java/org/apache/beam/sdk/extensions/gcp/options/GcsOptions.java#L136 to return a ScheduledExecutorService which is supplied to the FixedExecutorService.

**Comment by johnjcasey** [comment]
It looks like a variety of our tests assume the ThreadPoolExecutor instead of a scheduled one, and time out when a scheduled executor is default. I believe the solution will be to instead provide a second thread pool for places that need scheduled execution

**Comment by lukecwik** [comment]
How do they assume this?

If its easy to clean-up I would prefer that we use only one.

**Comment by johnjcasey** [comment]
It isn't explicit, but we have 14 tests that fail with varieties of timeouts when we use the scheduled executor.

**Comment by johnjcasey** [comment]
https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/23996/

org.apache.beam.runners.fnexecution.control.RemoteExecutionTest mostly.

when I separated to just the scheduled executor, that was causing issues in BQ itself as well

**Comment by lukecwik** [comment]
The ThreadPoolExecutor implementation uses a synchronous queue meaning that scheduling a task will block till a thread takes it. Could this be the difference?

**Comment by johnjcasey** [comment]
That seems likely. I'm not sure how to configure a scheduled executor to replicate this pattern, or to change our system to handle the async scheduling

**Comment by lukecwik** [comment]
You can wrap the ScheduledExecutorService with one that wraps callables/runnables with one that sets countdown latch and outside of it waits for the latch to be set. This will ensure that the thread has started before the method returns.

**Comment by reuvenlax** [comment]
Note that BigQuery now has a version of their library that allows sharing
multiple table writes over the same connection.

**Comment by johnjcasey** [comment]
Oh, that would be a good direction to investigate. Do you have a link to that?

**Comment by lukecwik** [comment]
Swapping libraries seems like it will be a much larger effort. Consider fixing up the much smaller scheduled executor service change.

**Comment by johnjcasey** [comment]
So, once we solve for the schedule executor service issue, I don't think we can update to just providing an SES, because it would break the existing API that allows users to specify any executorservice

**Comment by reuvenlax** [comment]
This is not a library swap - it is part of the next version of the library
we already use. (already released, but not yet part of a BOM release).

**Comment by reuvenlax** [comment]
Right now if they are writing to many tables using dynamic destinations, we
must have a separate grpc channel for each table stream. The BigQuery team
is working on multiplexing support which would allow using a single grpc
for all tables, however that is not quite ready yet.

**Comment by johnjcasey** [comment]
This has been reverted, so the fix isn't in master at the moment, but also the overall Gax issue isn't resolved

**Comment by chamikaramj** [comment]
Was it reverted in the release branch as well ? (couldn't find a reference to a revert PR here).

**Comment by johnjcasey** [comment]
here is reuven's revert pr https://github.com/apache/beam/pull/23793

**Comment by johnjcasey** [comment]
looks like it probably didn't make the release cut

**Comment by chamikaramj** [comment]
Ack. Please send a cherry-pick. (or I can start one).

**Comment by johnjcasey** [comment]
attempting it now

**Comment by johnjcasey** [comment]
@reuvenlax it looks like you then went and rolled forward the fix? https://github.com/apache/beam/pull/23795

**Comment by johnjcasey** [comment]
@reuvenlax can you clarify if master is good, or what the current state is?

**Comment by chamikaramj** [comment]
Thanks. Merged the cherry-pick.

Removing this from the 2.43.0 milestone.

**Comment by reuvenlax** [comment]
Correct - the PR only broke BigQueryIO.

**Comment by kennknowles** [comment]
Any update on this? Given that it appears to be not data loss or total loss of functionality I am downgrading to P2.

**Comment by johnjcasey** [comment]
agreed. The underlying gax library has been updated, so when that is released we can re-implement the fix

**Comment by amiyalenka** [comment]
Is this GAX Thread issue been resolved? If yes, which version having this fix?

**Comment by lukecwik** [comment]
2.45.0
