### ISSUE TITLE
Missing IterableAssert.inOnlyPane and SingletonAssert.inWindow methods

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21374]
It seems InterableAssert and SingletonAssert should provide identical pane assertions. But

there is no inOnlyPane for InterableAssert and inWindow for SingletonAssert.

Imported from Jira [BEAM-13765](https://issues.apache.org/jira/browse/BEAM-13765). Original Jira may contain additional context.
Reported by: marcin.kuthan.

**Comment by mkuthan** [comment]
It has been already resolved #16668
