### ISSUE TITLE
Slowly updating global window side inputs example reads singleton side input with multiple elements per window

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21376]
The example "The Slowly updating global window side inputs" [1] produces an unexpected error. Our implementation follows the example but uses a 30-second duration. The error first occurred after 4000 triggers. The pipeline ran on Dataflow using Java 1.8 and Beam SDK 2.33.0.

 
```

Caused by: org.apache.beam.vendor.guava.v26_0_jre.com.google.common.util.concurrent.UncheckedExecutionException:
java.lang.IllegalArgumentException: PCollection with more than one element accessed as a singleton view.

```

 

 

Applying a combine function before applying the view singleton has no positive effect. Changing the refresh duration to 5 minutes alleviates or delays the error. 

****Relevant post:****
 * [https://lists.apache.org/thread/v005b7osqxv774wjpjhg103bqto4v7yh](https://lists.apache.org/thread/v005b7osqxv774wjpjhg103bqto4v7yh)
 * [https://lists.apache.org/thread/wfm77wkqrkwlrhgbnq9f3x8nyzsn51xm](https://lists.apache.org/thread/wfm77wkqrkwlrhgbnq9f3x8nyzsn51xm)
 * [https://github.com/spotify/scio/issues/1190](https://github.com/spotify/scio/issues/1190)
 * [https://github.com/spotify/scio/issues/3521](https://github.com/spotify/scio/issues/3521)

Please let me know if you have any questions.

{****}References{****}:

 [1] [https://beam.apache.org/documentation/patterns/side-inputs/](https://beam.apache.org/documentation/patterns/side-inputs/)

Imported from Jira [BEAM-14023](https://issues.apache.org/jira/browse/BEAM-14023). Original Jira may contain additional context.
Reported by: yianni.

**Comment by nickcaballero** [comment]
The sample was updated - see https://github.com/apache/beam/issues/21605.
