### ISSUE TITLE
More friendly Filestore API

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21372]
Having to manually create Documents and Write objects can be cumbersome compared to the [https://cloud.google.com/firestore/docs/samples/firestore-data-set-id-specified](http://example.com) of filestore (see e.g. https://stackoverflow.com/questions/71163275/add-document-to-firestore-from-beam-with-auto-generated-id) We could provide a more user-friendly API.

Imported from Jira [BEAM-13994](https://issues.apache.org/jira/browse/BEAM-13994). Original Jira may contain additional context.
Reported by: robertwb.

**Comment by nbali** [comment]
I might have duplicated this in https://github.com/apache/beam/issues/24167. Althought I might add the issue is called "filestore" not "firestore".

**Comment by damccorm** [comment]
I'll close this one, we can use #24167 for tracking
