### ISSUE TITLE
Canceling a timer by ID is not yet supported in InMemoryTimerInternals

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21378]
Got the following exception with spark runner and GroupIntoBatches transform:

Caused by: java.lang.UnsupportedOperationException: Canceling a timer by ID is not yet supported.
    at org.apache.beam.runners.core.InMemoryTimerInternals.deleteTimer(InMemoryTimerInternals.java:158)
    at org.apache.beam.runners.core.SimpleDoFnRunner$TimerInternalsTimer.clear(SimpleDoFnRunner.java:1198)
    at org.apache.beam.sdk.transforms.GroupIntoBatches$GroupIntoBatchesDoFn.processElement(GroupIntoBatches.java:474)

 

The InMemoryTimerInternals.deleteTimer with a timeDomain is not supported:

public void deleteTimer(
StateNamespace namespace, String timerId, String timerFamilyId, TimeDomain timeDomain) {
throw new UnsupportedOperationException("Canceling a timer by ID is not yet supported.");
}

However, this function is called by SimpleDoFnRunner$TimerInternalsTimer.clear:

public void clear() {
this.timerInternals.deleteTimer(this.namespace, this.timerId, this.timerFamilyId, this.spec.getTimeDomain());
}

Which is called by GroupIntoBatches$GroupIntoBatchesDoFn.processElement.

 

Imported from Jira [BEAM-14018](https://issues.apache.org/jira/browse/BEAM-14018). Original Jira may contain additional context.
Reported by: wenqing.yang.

**Comment by mosche** [comment]
Same issue apparently exists for the Flink runner. 

From user@beam
> When running on Flink, eventually it hits an unsupported exception "Canceling a timer by ID is not yet supported." on this line [1]. The source inputs are AVRO files for testing (batch) but will use kafka topics (streaming) when deployed.
> 
> This happens when the batch is filled (10 items) and the max buffering time timer needs to be cancelled.
> 
> Anyone else observed this issue?
> 
> On a related note. Looks like the FlinkStatefulDoFnFunction [2] uses InMemoryTimerInternals. Curious why is FlinkTimerInternals not used? I would guess there's a difference between batch and streaming requirements?
>
> [1] [https://github.com/apache/beam/blob/b87f1f01197a78d60fb08a0ee7a4ef96bc4e08eb/runners/core-java/src/main/java/org/apache/beam/runners/core/InMemoryTimerInternals.java#L157](https://urldefense.com/v3/__https://github.com/apache/beam/blob/b87f1f01197a78d60fb08a0ee7a4ef96bc4e08eb/runners/core-java/src/main/java/org/apache/beam/runners/core/InMemoryTimerInternals.java*L157__;Iw!!CiXD_PY!Unl7jPgD471rWqXoU1CFDTX5qSwKpFHAGeryXtengpgyI2UDIfpkehBS3_SRwZFccFP97Hp__p4$)
> [2] [https://github.com/apache/beam/blob/b87f1f01197a78d60fb08a0ee7a4ef96bc4e08eb/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/functions/FlinkStatefulDoFnFunction.java#L136](https://urldefense.com/v3/__https://github.com/apache/beam/blob/b87f1f01197a78d60fb08a0ee7a4ef96bc4e08eb/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/functions/FlinkStatefulDoFnFunction.java*L136__;Iw!!CiXD_PY!Unl7jPgD471rWqXoU1CFDTX5qSwKpFHAGeryXtengpgyI2UDIfpkehBS3_SRwZFccFP97zQLGAI$)
> [3] [https://github.com/apache/beam/blob/b87f1f01197a78d60fb08a0ee7a4ef96bc4e08eb/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java#L1314](https://urldefense.com/v3/__https://github.com/apache/beam/blob/b87f1f01197a78d60fb08a0ee7a4ef96bc4e08eb/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java*L1314__;Iw!!CiXD_PY!Unl7jPgD471rWqXoU1CFDTX5qSwKpFHAGeryXtengpgyI2UDIfpkehBS3_SRwZFccFP9bD4M2yo$)

**Comment by TheNeuralBit** [comment]
Is this not exercised in any VR tests?

**Comment by mosche** [comment]
Unfortunately not, I'll address that as well
