### ISSUE TITLE
SqsIO.write input / construction of Sqs request

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21398]
SqsIO.write should support arbitrary types T and be implemented in terms of a mapper function that converts T into an AWS request.

The current implementation of write as `PTransform<PCollection<SendMessageRequest>, PDone>` is a rather poor choice. It may requires an additional unnecessary serialization & deserialisation round. But even worse, the current `SendMessageRequestCoder` does not support any advanced configuration beyond queueUrl and messageBody and will silently drop it without even warning the user.

Imported from Jira [BEAM-13416](https://issues.apache.org/jira/browse/BEAM-13416). Original Jira may contain additional context.
Reported by: mosche.

**Comment by mosche** [comment]
Obsolete, schemas support for AWS Pojos makes sure all fields are de/-serialized correctly
