### ISSUE TITLE
Improve documentation for the Dataflow Service options 

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21393]
Class DataflowPipelineOptions has the ability to set "Dataflow service options".

The description in the code is: 
```

Service options are set by the user and configure the service. This decouples service side feature
availability from the Apache Beam release cycle.
```

It would be great to have a link here to the Google cloud documentation where we can find a list of options or perhaps an example on how such an option looks like.

See also:  https://github.com/apache/beam/pull/14159#discussion_r589727367

Imported from Jira [BEAM-13630](https://issues.apache.org/jira/browse/BEAM-13630). Original Jira may contain additional context.
Reported by: mcasters.

**Comment by pcoet** [comment]
.take-issue

**Comment by rszper** [comment]
Page to link to: https://cloud.google.com/dataflow/docs/reference/service-options

**Comment by sereanaseim** [comment]
.take-issue

**Comment by rszper** [comment]
.take-issue
