### ISSUE TITLE
Dataflow runner - be more lenient with agent java version

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21402]
DataflowRunner currently uses `Environments.getJavaVersion` to detect java version and build the Dataflow user agent string.

`Environments.getJavaVersion` only accept a small subset of java version (8, 11 and 17)

It would be nice the user agent string to accept more exotic java versions to allow running the agent on more exotic jvm (still keeping the beam model itself in java 11).

Imported from Jira [BEAM-13468](https://issues.apache.org/jira/browse/BEAM-13468). Original Jira may contain additional context.
Reported by: cguillaume.

**Comment by damccorm** [comment]
Unable to assign user @guillaumecle. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by guillaumecle** [comment]
Looks like I'm not able to self-assign. @damccorm Can you assign it to me?

BTW a PR for this issue is open: #17274
