### ISSUE TITLE
Convert JDBC SchemaIO to SchemaTransform

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21408]
Here's the SchemaIO version:

[sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcSchemaIOProvider.java](https://github.com/apache/beam/blob/2a2107af70dea8c34743cb009be7904b6497858b/sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcSchemaIOProvider.java)

Imported from Jira [BEAM-14033](https://issues.apache.org/jira/browse/BEAM-14033). Original Jira may contain additional context.
Reported by: laraschmidt.
Subtask of issue #21406

**Comment by byronellis** [comment]
.take-issue
