### ISSUE TITLE
Convert Pub/Sub Schema IO to SchemaTransform

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21412]
The output of this task is to refactor [sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubSchemaIOProvider.java](https://github.com/apache/beam/blob/3c62cc906f487d7cd93430bf35d6ac2cd4cc6d3c/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubSchemaIOProvider.java) to extend [TypedSchemaTransformProvider](https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/TypedSchemaTransformProvider.java).

This task will be separated into *****four***** PRs to focus on Read and Write SchemaTransforms and their respective Configurations.  See [BigQuerySchemaTransformReadProvider](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySchemaTransformReadProvider.java) and [BigQuerySchemaTransformWriteConfiguration](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySchemaTransformWriteConfiguration.java) as an example design pattern.

Imported from Jira [BEAM-14036](https://issues.apache.org/jira/browse/BEAM-14036). Original Jira may contain additional context.
Reported by: laraschmidt.
Subtask of issue #21406

**Comment by damccorm** [comment]
Unable to assign user @damondouglas. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by damondouglas** [comment]
@damccorm Would you mind to assign me to this task?  Thank you for migrating these issues!

**Comment by damondouglas** [comment]
Associating PR: https://github.com/apache/beam/pull/17730 to this task.

**Comment by damondouglas** [comment]
This issue has a new dependency: #22768
