### ISSUE TITLE
Implement E2E tests for RunInference classes

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21439]
RunInference E2E tests are used to catch the regressions in the RunInference APIs. These tests would be a part of PostCommit suite.

Imported from Jira [BEAM-13985](https://issues.apache.org/jira/browse/BEAM-13985). Original Jira may contain additional context.
Reported by: yeandy.
Subtask of issue #21435

**Comment by AnandInguva** [comment]
.close-issue
