### ISSUE TITLE
Improve Java multi-language pipelines quickstart

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21434]
We need to rewrite [Java multi-language pipelines quickstart](https://beam.apache.org/documentation/sdks/java-multi-language-pipelines/) so that it matches the [Python quickstart](https://beam.apache.org/documentation/sdks/python-multi-language-pipelines/) in structure and quality.

Imported from Jira [BEAM-13654](https://issues.apache.org/jira/browse/BEAM-13654). Original Jira may contain additional context.
Reported by: pcoet.

**Comment by pcoet** [comment]
Done: https://github.com/apache/beam/pull/22263
