### ISSUE TITLE
Provide GPU support

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21438]
Pytorch and Tensorflow have GPU trained models. Need to support this in the RunInference classes, and also make sure they get configured in Dataflow.

Imported from Jira [BEAM-13986](https://issues.apache.org/jira/browse/BEAM-13986). Original Jira may contain additional context.
Reported by: yeandy.
Subtask of issue #21435

**Comment by yeandy** [comment]
Subtask of https://github.com/apache/beam/issues/22117

**Comment by damccorm** [comment]
@yeandy what pieces are missing to support this?

**Comment by yeandy** [comment]
The main one should be https://github.com/apache/beam/pull/22795

**Comment by damccorm** [comment]
@yeandy now that #22795 is done is there any additional work to be done here?

**Comment by yeandy** [comment]
.close-issue

**Comment by tvalentyn** [comment]
@yeandy please clarify the scope of this issue. Thanks!

**Comment by yeandy** [comment]
Clarification on this issue:

PyTorch RunInference converts data and model to GPU by using the [tensor.to(device)](https://pytorch.org/docs/stable/generated/torch.Tensor.to.html) command to move a tensor to a device. We also do implicit GPU -> CPU conversion if GPU doesn't exist in the worker.

**Comment by tvalentyn** [comment]
FYI, you can edit the description or title of the issues.

**Comment by damccorm** [comment]
> FYI, you can edit the description or title of the issues.

Probably not as a non-committer unfortunately
