### ISSUE TITLE
Remove base_run_inference in TFX-BSL and use inference.base in Beam

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21442]
TFX-BSL has shared code for a base run_inference implementation.

This is duplicate code and TFX-BSL should be able to use Beams run_inference.

 

Imported from Jira [BEAM-14268](https://issues.apache.org/jira/browse/BEAM-14268). Original Jira may contain additional context.
Reported by: Ryan.Thompson.
Subtask of issue #21435

**Comment by damccorm** [comment]
@ryanthompson591 can this one be closed out now?

**Comment by ryanthompson591** [comment]
Yes, this should be closed. TFX-BSL recently released this change.

**Comment by ryanthompson591** [comment]
.close-issue
