### ISSUE TITLE
Elastic search IO doesnot work when both username/password and keystore are used

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21455]
When using both username/password and ssl keystore, ElasticSearchIO doesnot Create correct restclient.

 

Firstly, it sets HttpClientConfigCallback using httpAsyncClientBuilder if username and passowrd is used. Afterwards, it will replace HttpClientConfigCallback to httpClientBuilder is ssl store is used, hence losing the credentials provider

Imported from Jira [BEAM-14000](https://issues.apache.org/jira/browse/BEAM-14000). Original Jira may contain additional context.
Reported by: nishantjain91.

**Comment by egalpin** [comment]
Fixed by #17297.  Thanks @nishantjain91 !
