### ISSUE TITLE
Add support for Pandas Dataframes to sklearn RunInference Implementation

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21452]
Sklearn pipelines are often set up to take pandas dataframes.

 

Our current implementation only supports numpy arrays.

 

This FR allows the sklearn implementation to autodetect pandas dataframes or numpy arrays and then combine them (via concat).

 

In the case of a pandas dataframe that value will be passed through to the pipeline.

Imported from Jira [BEAM-14535](https://issues.apache.org/jira/browse/BEAM-14535). Original Jira may contain additional context.
Reported by: Ryan.Thompson.
Subtask of issue #21435

**Comment by damccorm** [comment]
Unable to assign user @ryanthompson591. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by ryanthompson591** [comment]
This is done with PR https://github.com/apache/beam/pull/17800

**Comment by ryanthompson591** [comment]
.close-issue
