### ISSUE TITLE
Drop the clock abstraction and just use time.time for time measurements

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21451]
Right now the TFX-BSL Runinference library uses an abstract clock class to get microsecond precision, but time.time should give an adequate precision.

 

Investigate removing the clock abstraction and just using time.time.

 

Alternatively, comment why the abstraction is useful.

Imported from Jira [BEAM-14255](https://issues.apache.org/jira/browse/BEAM-14255). Original Jira may contain additional context.
Reported by: Ryan.Thompson.
Subtask of issue #21435

**Comment by damccorm** [comment]
Unable to assign user @ryanthompson591. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by damccorm** [comment]
@ryanthompson591 now that #21442 is done, can we close this one too? Was this referring to this clock usage https://github.com/tensorflow/tfx-bsl/blob/396812f4ac8361db9396ec9780abe098d88869f0/tfx_bsl/beam/run_inference_base.py#L166

**Comment by ryanthompson591** [comment]
.close-issue
