### ISSUE TITLE
Support **kwargs for PyTorch models.

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21453]
Some models in Pytorch instantiating from torch.nn.Module, has extra parameters in the forward function call. These extra parameters can be passed as Dict or as positional arguments. 

Example of PyTorch models supported by Hugging Face -\> [https://huggingface.co/bert-base-uncased](https://huggingface.co/bert-base-uncased)

[Some torch models on Hugging face](https://github.com/huggingface/transformers/blob/main/src/transformers/models/bert/modeling_bert.py)

Eg: [https://huggingface.co/docs/transformers/model_doc/bert#transformers.BertModel](https://huggingface.co/docs/transformers/model_doc/bert#transformers.BertModel)
```

inputs = {
     input_ids: Tensor1,
     attention_mask: Tensor2,
     token_type_ids: Tensor3,
}

model = BertModel.from_pretrained("bert-base-uncased") # which is a  
# subclass of torch.nn.Module

outputs
= model(**inputs) # model forward method should be expecting the keys in the inputs as the positional
arguments.
```

 

[Transformers](https://pytorch.org/hub/huggingface_pytorch-transformers/) integrated in Pytorch is supported by Hugging Face as well. 

 

Imported from Jira [BEAM-14337](https://issues.apache.org/jira/browse/BEAM-14337). Original Jira may contain additional context.
Reported by: Anand Inguva.
Subtask of issue #21435

**Comment by damccorm** [comment]
Unable to assign user @yeandy. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by damccorm** [comment]
One of the unfortunate downsides of moving to issues is that non-committers can't self-assign/triage issues that they didn't create by default. I think that's a workflow we'll need to support going forward though, I'll look into it. For the moment, I'd recommend commenting/declaring intent to work on any issues.

I have access through https://github.com/apache/beam/blob/4dce7b8857f37608321253073745fe7611a48af9/.asf.yaml#L39 which gives triage permissions, unfortunately that's limited to 20 people though

**Comment by damccorm** [comment]
Once https://github.com/apache/beam/pull/21719 is in, you should be able to do this with chat-op commands

**Comment by yeandy** [comment]
Got it, thanks!

**Comment by tvalentyn** [comment]
we decided to move forward with a separate param:  https://github.com/apache/beam/pull/21806
