### ISSUE TITLE
Changes for Python 3.10

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21458]
Changes to support Python 3.10

Imported from Jira [BEAM-13590](https://issues.apache.org/jira/browse/BEAM-13590). Original Jira may contain additional context.
Reported by: blais.

**Comment by damccorm** [comment]
Unable to assign user @AnandInguva. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by AnandInguva** [comment]
.take-issue

**Comment by AnandInguva** [comment]
Issues related to Python 3.10

Legacy Dataflow Python 3.10 tests: https://github.com/apache/beam/issues/21971
Type inference: https://github.com/apache/beam/issues/21671
Future Deprecation of  disutils: https://github.com/apache/beam/issues/19419
