### ISSUE TITLE
Kafka commit offset drop data on failure for runners that have non-checkpointing shuffle

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21465]
A user noticed that we commit Kafka offsets without any obvious checkpointing. We use a `Reshuffle.byRandomKey()` to cause Dataflow and the SparkRunner to checkpoint. But on runners with non-checkpointing shuffle, this risks data loss.

 

The modern solution is to use `{}@RequiresStableInput{`}. This is not perfectly/fully implemented across many runners, so we still need the explicit shuffle for now.

 

https://stackoverflow.com/questions/70785672/apache-beam-kafkaio-commit-offset-behaviour

Imported from Jira [BEAM-13715](https://issues.apache.org/jira/browse/BEAM-13715). Original Jira may contain additional context.
Reported by: kenn.

**Comment by kennknowles** [comment]
@johnjcasey as an FYI. I believe this may still be an issue. Reshuffle is a non-checkpointing operation but it is commonly used for checkpointing due to Dataflow's history.
