### ISSUE TITLE
Update BQ connector to support new JSON type

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21460]
BQ has a new JSON type that is defined here: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#json_type

We should update Beam BQ Java and Python connectors to support that for various read methods (export jobs, storage API) and write methods (load jobs, streaming inserts, storage API).

We should also add integration tests that exercise reading from /writing to BQ tables with columns that has JSON type.

Imported from Jira [BEAM-13945](https://issues.apache.org/jira/browse/BEAM-13945). Original Jira may contain additional context.
Reported by: chamikara.

**Comment by damccorm** [comment]
Unable to assign user @ahmedabu98. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by ahmedabu98** [comment]
Closed with #17209 and #18374

**Comment by ahmedabu98** [comment]
.close-issue
