### ISSUE TITLE
GroupIntoBatchesTest is failing

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21464]
Currently failing a test on core sdk on the following assertion. From the test description, it seems like (totalNumBatches <= numElements && totalNumBatches \>= numElements / batchSize) is what is wanted instead, but currently it is testing for numFullBatches instead and is failing the test. Is this intended?

 

Current code:

assertTrue( String.format( "total number of batches should be in the range [%d, %d] but got %d", numElements, numElements / batchSize, numFullBatches), numFullBatches <= numElements && numFullBatches \>= numElements / batchSize)

Source:

[https://github.com/apache/beam/blob/v2.34.0/sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/GroupIntoBatchesTest.java#L295](https://github.com/apache/beam/blob/v2.34.0/sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/GroupIntoBatchesTest.java#L295)

Imported from Jira [BEAM-13393](https://issues.apache.org/jira/browse/BEAM-13393). Original Jira may contain additional context.
Reported by: fructokinase.

**Comment by jrmccluskey** [comment]
Test is passing on CI, cannot reproduce.
