### ISSUE TITLE
beam_PostCommit_Python_Examples_Dataflow failing

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21468]
This test failed twice consecutively. The first time these tests failed with error "Recursion detected".

apache_beam.examples.complete.top_wikipedia_sessions_test.ComputeTopSessionsTest.test_top_wikipedia_sessions_output_files_on_small_input
apache_beam.examples.complete.autocomplete_test.AutocompleteTest.test_autocomplete_output_files_on_small_input
apache_beam.examples.complete.estimate_pi_test.EstimatePiTest.test_estimate_pi_output_file
apache_beam.examples.complete.game.user_score_it_test.UserScoreIT.test_userscore_output_checksum_on_small_input
apache_beam.examples.complete.game.hourly_team_score_it_test.HourlyTeamScoreIT.test_hourly_team_score_output_checksum_on_small_input
apache_beam.examples.cookbook.bigquery_side_input_it_test.BigQuerySideInputIT.test_bigquery_side_input_it
apache_beam.examples.cookbook.coders_test.CodersTest.test_coders_output_files_on_small_input

The second time those tests failed again, as well as one more, apache_beam.examples.dataframe.flight_delays_it_test.FlightDelaysTest.test_flight_delays with error:

E         apache_beam.runners.dataflow.dataflow_runner.DataflowRuntimeException: Dataflow pipeline failed. State: FAILED, Error:
E         Traceback (most recent call last):
E           File "/usr/local/lib/python3.8/site-packages/apache_beam/internal/dill_pickler.py", line 285, in loads
E             return dill.loads(s)
E           File "/usr/local/lib/python3.8/site-packages/dill/_dill.py", line 275, in loads
E             return load(file, ignore, **kwds)
E           File "/usr/local/lib/python3.8/site-packages/dill/_dill.py", line 270, in load
E             return Unpickler(file, ignore=ignore, **kwds).load()
E           File "/usr/local/lib/python3.8/site-packages/dill/_dill.py", line 472, in load
E             obj = StockUnpickler.load(self)
E           File "/usr/local/lib/python3.8/site-packages/dill/_dill.py", line 462, in find_class
E             return StockUnpickler.find_class(self, module, name)
E         AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/usr/local/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'\>

Imported from Jira [BEAM-13850](https://issues.apache.org/jira/browse/BEAM-13850). Original Jira may contain additional context.
Reported by: ibzib.

**Comment by Abacn** [comment]
.close-issue not_planned

obsolate
