### ISSUE TITLE
KafkaIO.read.withDynamicRead() doesn't pick up new TopicPartitions

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21478]
KafkaIO.Read().withDynamicRead() is correctly pulling messages from existing topics, but isn't picking up new topics or partitions when they are created.

Currently, this appears to be an interaction between the timer configuration, and the duration of the operating window, that is causing the problem

Imported from Jira [BEAM-13852](https://issues.apache.org/jira/browse/BEAM-13852). Original Jira may contain additional context.
Reported by: johnjcasey.

**Comment by damccorm** [comment]
Unable to assign user @johnjcasey. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by jossonpaul** [comment]
@johnjcasey We are trying to use this feature. Please let me know the previous beam version this feature was working properly if at all it was working?.

**Comment by johnjcasey** [comment]
Unfortunately, I don't believe this ever worked. I'm working on it now.
