### ISSUE TITLE
PVR_Spark2_Streaming perma-red

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21473]
https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark2_Streaming has been failing a variable number of tests for a while. 

Last successful run was Dec 28, 2021 (https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark2_Streaming/1021/), which was approximately coincident with gradle 7 changes.

Imported from Jira [BEAM-13950](https://issues.apache.org/jira/browse/BEAM-13950). Original Jira may contain additional context.
Reported by: bhulette.

**Comment by mosche** [comment]
Note: there was a recent [discussion](https://lists.apache.org/thread/opfhg3xjb9nptv878sygwj9gjx38rmco) to drop support for spark 2

**Comment by byronellis** [comment]
I tried running the Spark 2 tests locally and interestingly they seemed to pass (after I ran them under Java 8 rather than Java 11). I'm wondering if there's maybe just a misconfiguration of the Jenkins environment? (120 passed and 6 ignored)

**Comment by byronellis** [comment]
Actually, I take that back... that was just for :runners:spark:2:test

**Comment by byronellis** [comment]
Okay, validatesPortabkeRunnerStreaming is also failing some fraction of tests as well...

**Comment by byronellis** [comment]
Okay, after basically just running the tests over and over again... I think what must be happening is that Spark is getting torn down before the test actually completes which of course leads to a test failure.

**Comment by byronellis** [comment]
TIL that Spark runner tests will fail (locally at least) if you start running low (80% full or so) on storage.

**Comment by byronellis** [comment]
In local testing increasing the timeout of the streaming service addresses the issue. Not necessarily a fix, more of a bandaid but it's not clear that we can prevent the case where the service gets torn down before results of the test can be collected in another way. May also fix Spark 3 issues, but I haven't tested that yet.

**Comment by byronellis** [comment]
Okay, after changing the timeout to be *even longer* it looks like it actually managed to run on Jenkins. I think it can just take awhile for some tests to spin up Spark, do their thing and then spin down.

**Comment by damccorm** [comment]
Closing since this is now perma-green :)
