### ISSUE TITLE
Beam x-lang Dataflow tests failing due to _InactiveRpcError

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21475]
For example,

https://ci-beam.apache.org/job/beam_PostCommit_XVR_PythonUsingJava_Dataflow/63/testReport/junit/apache_beam.transforms.validate_runner_xlang_test/ValidateRunnerXlangTest/test_group_by_key/

Seems like we couldn't startup the expansion service or couldn't connect to it. [~heejong] can you check ?

state = <grpc._channel._RPCState object at 0x7fb730177ba8\>
call = <grpc._cython.cygrpc.SegregatedCall object at 0x7fb730216c08\>
with_call = False, deadline = None

    def _end_unary_response_blocking(state, call, with_call, deadline):
        if state.code is grpc.StatusCode.OK:
            if with_call:
                rendezvous = _MultiThreadedRendezvous(state, call, None, deadline)
                return state.response, rendezvous
            else:
                return state.response
        else:
\>           raise _InactiveRpcError(state)
E           grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
E           	status = StatusCode.UNAVAILABLE
E           	details = "failed to connect to all addresses"
E           	debug_error_string = "{"created":"@1644495578.531912291","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1644495578.531910958","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
E           \>

Imported from Jira [BEAM-13920](https://issues.apache.org/jira/browse/BEAM-13920). Original Jira may contain additional context.
Reported by: chamikara.

**Comment by TheNeuralBit** [comment]
@ihji is this still happening?

**Comment by damccorm** [comment]
This hasn't happened in the current Jenkins history
