### ISSUE TITLE
Flaky tests: Gradle build daemon disappeared unexpectedly

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21474]
This happens to many of our tests. It looks like this is a common issue with Gradle and we will have to do more digging to determine the true cause. https://stackoverflow.com/questions/37171043/gradle-build-daemon-disappeared-unexpectedly-it-may-have-been-killed-or-may-hav/37171110

10:04:08 \> Task :sdks:go:test:sparkValidatesRunner
10:04:08 Feb 02, 2022 6:04:08 PM org.apache.beam.sdk.expansion.service.ExpansionService loadRegisteredTransforms
10:04:08 INFO: Registering external transforms: [beam:transforms:xlang:test:cgbk, beam:transforms:xlang:test:flatten, beam:transforms:xlang:test:prefix, beam:transforms:xlang:test:multi, beam:transforms:xlang:test:gbk, beam:transforms:xlang:test:comgl, beam:transforms:xlang:test:compk, beam:transforms:xlang:count, beam:transforms:xlang:filter_less_than_eq, beam:transforms:xlang:test:partition, beam:transforms:xlang:test:parquet_write, beam:transforms:xlang:parquet_read, beam:transforms:xlang:textio_read, beam:external:java:generate_sequence:v1]
10:04:09 The message received from the daemon indicates that the daemon has disappeared.
10:04:09 Build request sent: Build{id=37ea63c1-ec5f-492a-ad6a-f26c92fd7f7e, currentDir=/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Go_VR_Spark/src}
10:04:09 Attempting to read last messages from the daemon log...
10:04:09 Daemon pid: 3299301
10:04:09   log file: /home/jenkins/.gradle/daemon/7.3.2/daemon-3299301.out.log
10:04:09 \--\--- Last  20 lines from daemon log file - daemon-3299301.out.log \--\---
10:04:09 2022-02-02T18:04:08.251****0000 [DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Marking busy by address: [2bd8c084-af4c-4924-90f5-8b8a89f85fc5 port:32889, addresses:[localhost/127.0.0.1]]
10:04:09 2022-02-02T18:04:08.251****0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
10:04:09 2022-02-02T18:04:08.251****0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
10:04:09 2022-02-02T18:04:08.252****0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
10:04:09 2022-02-02T18:04:08.252****0000 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] resetting idle timer
10:04:09 2022-02-02T18:04:08.252****0000 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] daemon is running. Sleeping until state changes.
10:04:09 2022-02-02T18:04:08.253****0000 [INFO] [org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy] Daemon is about to start building Build{id=37ea63c1-ec5f-492a-ad6a-f26c92fd7f7e, currentDir=/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Go_VR_Spark/src}. Dispatching build started information...
10:04:09 2022-02-02T18:04:08.253****0000 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 266: dispatching org.gradle.launcher.daemon.protocol.BuildStarted@42569c28
10:04:09 2022-02-02T18:04:08.255****0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment] Configuring env variables: [PATH, RUN_DISPLAY_URL, HUDSON_HOME, RUN_CHANGES_DISPLAY_URL, JOB_URL, HUDSON_COOKIE, MOTD_SHOWN, DBUS_SESSION_BUS_ADDRESS, JENKINS_SERVER_COOKIE, LOGNAME, PWD, RUN_TESTS_DISPLAY_URL, JENKINS_URL, SHELL, BUILD_TAG, ROOT_BUILD_CAUSE, BUILD_CAUSE_TIMERTRIGGER, OLDPWD, GIT_CHECKOUT_DIR, JENKINS_HOME, sha1, CODECOV_TOKEN, NODE_NAME, BUILD_DISPLAY_NAME, JOB_DISPLAY_URL, GIT_BRANCH, SETUPTOOLS_USE_DISTUTILS, SHLVL, WORKSPACE_TMP, GIT_PREVIOUS_COMMIT, JAVA_HOME, BUILD_ID, LANG, XDG_SESSION_ID, XDG_SESSION_TYPE, JOB_NAME, SPARK_LOCAL_IP, BUILD_CAUSE, GIT_PREVIOUS_SUCCESSFUL_COMMIT, NODE_LABELS, HUDSON_URL, WORKSPACE, ROOT_BUILD_CAUSE_TIMERTRIGGER, XDG_SESSION_CLASS, _, GIT_COMMIT, COVERALLS_REPO_TOKEN, CI, EXECUTOR_NUMBER, HUDSON_SERVER_COOKIE, SSH_CLIENT, JOB_BASE_NAME, USER, SSH_CONNECTION, BUILD_NUMBER, BUILD_URL, RUN_ARTIFACTS_DISPLAY_URL, GIT_URL, XDG_RUNTIME_DIR, HOME]
10:04:09 2022-02-02T18:04:08.256****0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.LogToClient] About to start relaying all logs to the client via the connection.
10:04:09 2022-02-02T18:04:08.256****0000 [INFO] [org.gradle.launcher.daemon.server.exec.LogToClient] The client will now receive all logging from the daemon (pid: 3299301). The daemon log file: /home/jenkins/.gradle/daemon/7.3.2/daemon-3299301.out.log
10:04:09 2022-02-02T18:04:08.257****0000 [INFO] [org.gradle.launcher.daemon.server.exec.LogAndCheckHealth] Starting 2nd build in daemon [uptime: 3 mins 43.954 secs, performance: 98%]
10:04:09 2022-02-02T18:04:08.264****0000 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 264: received class org.gradle.launcher.daemon.protocol.CloseInput
10:04:09 2022-02-02T18:04:08.264****0000 [DEBUG] [org.gradle.launcher.daemon.server.DefaultDaemonConnection] thread 264: Received IO message from client: org.gradle.launcher.daemon.protocol.CloseInput@3e111340
10:04:09 2022-02-02T18:04:08.271****0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has started executing the build.
10:04:09 2022-02-02T18:04:08.271****0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing build with daemon context: DefaultDaemonContext[uid=ca7e60a9-87d1-4beb-a056-dcf9ca91d510,javaHome=/usr/lib/jvm/java-8-openjdk-amd64,daemonRegistryDir=/home/jenkins/.gradle/daemon,pid=3299301,idleTimeout=10800000,priority=NORMAL,daemonOpts=-Xss10240k,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
10:04:09 2022-02-02T18:04:08.271****0000 [INFO] [org.gradle.launcher.daemon.server.exec.ForwardClientInput] Closing daemon's stdin at end of input.
10:04:09 2022-02-02T18:04:08.271****0000 [INFO] [org.gradle.launcher.daemon.server.exec.ForwardClientInput] The daemon will no longer process any standard input.
10:04:09 Configuration on demand is an incubating feature.
10:04:09 Daemon vm is shutting down... The daemon has exited normally or was terminated in response to a user interrupt.
10:04:09 \--\--- End of the daemon log \--\---

Imported from Jira [BEAM-13810](https://issues.apache.org/jira/browse/BEAM-13810). Original Jira may contain additional context.
Reported by: ibzib.

**Comment by TheNeuralBit** [comment]
Assigning to @kennknowles since you had the most recent comment in BEAM-13810:

> The claim by the scan at https://ci-beam.apache.org/view/PostCommit/job/beam_PreCommit_Java_Cron/5164/ / https://scans.gradle.com/s/kcy27wmdenr6i/timeline?anchor=nuv4fm6q4n3ks is "2749 tasks executed in 128 projects in 12m 50.990s, with 480 avoided tasks saving 8h 2m 40.377s"
> 
> The documentation claims "The reasoning is simple: improve build speed by reusing computations from previous builds. However, the benefits are dramatic: we typically measure build times reduced by 15-75% on subsequent builds. We recommend profiling your build by using --profile to get a sense of how much impact the Gradle Daemon can have for you." but the build I link above was a fresh daemon (https://scans.gradle.com/s/kcy27wmdenr6i/performance/daemon says "0 previous builds") and still had many cache hits.
> 
> So it would appear that our local cache may make the daemon's in-memory incremental building less important.

I think the takeaway here is that we should be able to turn on `--no-daemon` without a performance penalty?

**Comment by apilloud** [comment]
Still happening:

https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Commit/12108/console

**Comment by kennknowles** [comment]
Interesting thought to eliminate the daemon and only use the cache. I'm not opposed to it. I've also been seeing a number of locking issues with the cache, so may be two bad options...

**Comment by TheNeuralBit** [comment]
That was your thought :)

**Comment by kennknowles** [comment]
oh hah

**Comment by kileys** [comment]
Closing since we disabled https://github.com/apache/beam/pull/24641
