### ISSUE TITLE
Typo in method description doc

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21483]
Typo in [https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/gcp/bigquery_tools.py#L1246](https://github.com/Firlej/beam/blob/36df96e681978b199c0060b88f4a5f993ce0f340/sdks/python/apache_beam/io/gcp/bigquery_tools.py#L1246) docs. referring to a class defined here [https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/gcp/internal/clients/bigquery/bigquery_v2_messages.py#L4543](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/gcp/internal/clients/bigquery/bigquery_v2_messages.py#L4543)

Imported from Jira [BEAM-14376](https://issues.apache.org/jira/browse/BEAM-14376). Original Jira may contain additional context.
Reported by: Firlej.

**Comment by Firlej** [comment]
Fix already merged. Forgot to close issue on JIRA
