### ISSUE TITLE
spammy AWS S3 log messages

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21488]
When I ran Python wordcount on Flink, this was logged 659 times.
 
org.apache.beam.sdk.io.aws2.s3.DefaultS3ClientBuilderFactory createBuilder
INFO: The AWS S3 Beam extension was included in this build, but the awsRegion flag was not specified. If you don't plan to use S3, then ignore this message.

Imported from Jira [BEAM-14355](https://issues.apache.org/jira/browse/BEAM-14355). Original Jira may contain additional context.
Reported by: ibzib.

**Comment by Abacn** [comment]
Is duplicated by BEAM-14465 and resolved in #17645

**Comment by Abacn** [comment]
.close-issue
