### ISSUE TITLE
Very poor code wrapping on Spark comparison page.

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21496]
There is copious whitespace to the left, while the sample code to the right is wrapped to about a dozen characters.

https://beam.apache.org/get-started/from-spark/

Imported from Jira [BEAM-14131](https://issues.apache.org/jira/browse/BEAM-14131). Original Jira may contain additional context.
Reported by: robertwb.

**Comment by pcoet** [comment]
.take-issue
