### ISSUE TITLE
Update Go protobuf package to new version

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21515]
The original Go protobuf package (github.com/golang/protobuf/proto) is deprecated and should be replaced with the new version (google.golang.org/protobuf/proto)

Imported from Jira [BEAM-14242](https://issues.apache.org/jira/browse/BEAM-14242). Original Jira may contain additional context.
Reported by: jrmccluskey.
Subtask of issue #21513

**Comment by imvtsl** [comment]
.take-issue

**Comment by imvtsl** [comment]
I am now working on this. Thanks.

**Comment by imvtsl** [comment]
Hi @damccorm,

I raised [this](https://github.com/apache/beam/pull/32045) draft PR. This is my first contribution to this repository.
I am able to update all but one file. I would require help with upgrading `sdks/go/pkg/beam/create_test.go`. Can I get some help with it?

Thanks.

**Comment by damccorm** [comment]
@lostluck or @damondouglas could one of you please take a look and see if you can help here?

**Comment by lostluck** [comment]
I'll take a look! Thank you very much!

**Comment by imvtsl** [comment]
@lostluck @damccorm 
Thanks for the response.
I have a couple of approaches to try out. I will try to do them this weekend and I will share my conclusions. Thank you once again!

**Comment by lostluck** [comment]
The PR is pretty great as is TBH!

So the clarify the goal of this issue:

The intent is that most of *beam* isn't relying on the deprecated package to function. So the changes you've made a great thus far.  

However, we do want to ensure that if users are somehow still relying on v1 protocol buffer types that they're using, that they continue to function.

This means we need to keep the code in beam/create_test.go and the protov1 handling code in beam/coder.go with some very small changes.

I'll add comments to the PR directly.

**Comment by imvtsl** [comment]
Thank you for the comments. I was going in a different direction. Your clarifications saved me a lot of time!
