### ISSUE TITLE
Unvendor bytebuddy dependency

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21519]
Vendoring the bytebuddy dep was introduced in https://issues.apache.org/jira/browse/BEAM-1019:
> We encountered backward incompatible changes in bytebuddy during upgrading to Mockito 2.0.
> Shading bytebuddy helps to address them and future issues.
> This makes it harder to upgrade the bytebuddy version (e.g. https://issues.apache.org/jira/browse/BEAM-14065, https://issues.apache.org/jira/browse/BEAM-12241).

Vendoring or shading bytebuddy is discouraged by the upstream owners of the library, see e.g. [https://github.com/assertj/assertj-core/issues/2470](https://github.com/assertj/assertj-core/issues/2470) where assertj was migrated off a shaded version:
> As Byte Buddy retains compatibility, not shading the library would allow running recent JVMs without an update of assertj but only BB. Other libraries like Mockito or Hibernate do not shade BB and there are no known issues with this approach. In case of an error, stack traces would also be easier to process as break points remain intact.
> Does anyone remember additional context about the issues encountered during the mockito 2.0 upgrade? Would there be any interest in trying to unvendor bytebuddy? I'm happy to help route issues to the upstream bytebuddy and mockito projects, in general I think they want to support making it possible to use bytebuddy without shading it.

Imported from Jira [BEAM-14117](https://issues.apache.org/jira/browse/BEAM-14117). Original Jira may contain additional context.
Reported by: cushon.

**Comment by lukecwik** [comment]
Fixed by https://github.com/apache/beam/pull/17317
