### ISSUE TITLE
add "Getting Started from Apache Spark" to sidebar for Get Started page

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21536]
[https://beam.apache.org/get-started/from-spark/](https://beam.apache.org/get-started/from-spark/) should be linked from the left-hand navigation menu on [https://beam.apache.org/get-started](https://beam.apache.org/get-started) and all associated pages.  

I would recommend adding this link to the list between Tour of Beam and Quickstarts

Imported from Jira [BEAM-14155](https://issues.apache.org/jira/browse/BEAM-14155). Original Jira may contain additional context.
Reported by: sachinag.

**Comment by pcoet** [comment]
.take-issue

**Comment by pcoet** [comment]
Looks like this has been fixed.
