### ISSUE TITLE
Python JDBC API don't recognize "statement" parameter

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21542]
JDBC [write API](https://beam.apache.org/releases/pydoc/2.35.0/apache_beam.io.jdbc.html?highlight=jdbc#apache_beam.io.jdbc.WriteToJdbc) allow a "statement" parameter to pass custom INSERT statements (e.g. UPSERTs).

However, when I pass a "statement" parameter in apache_beam.io.jdbc.WriteToJdbc(), I still see the usual INSERT coming in my Postgres logs.

Additional context in this mailing list thread.

https://lists.apache.org/thread/doy941o8f6lg5jq47vvftbcfg3849ztc

Imported from Jira [BEAM-14230](https://issues.apache.org/jira/browse/BEAM-14230). Original Jira may contain additional context.
Reported by: deepix.

**Comment by pabloem** [comment]
this is fixed!
