### ISSUE TITLE
Fix Iterable todo In CoGroupByKey

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21556]
Change iterable_input_value_types to be either type.Iterable or rename the variable to specify it is supposed to be a list.

https://github.com/apache/beam/blob/6e339718c63f14fa3cc6249bec43a1b0e3a32af0/sdks/python/apache_beam/transforms/util.py#L198

Imported from Jira [BEAM-14084](https://issues.apache.org/jira/browse/BEAM-14084). Original Jira may contain additional context.
Reported by: Ryan.Thompson.

**Comment by ryanthompson591** [comment]
Fixed in PR 

This will be a breaking change to any pipelines that expect the output of CoGroupByKey to be a list instead of an iterable.

I've  [documentation](https://docs.google.com/document/d/1RIzm8-g-0CyVsPb6yasjwokJQFoKHG4NjRUcKHKINu0) on how to fix pipelines for this breaking change.

**Comment by ryanthompson591** [comment]
.add-label done-and-done
