### ISSUE TITLE
SpannerIO.Write needs exception handling tests

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21564]
There are a few tests that verify the handling of errors within SpannerIO, and there isn't a general test that various errors are handled properly. It's important to make sure that no exceptions are swallowed by the IO.

Imported from Jira [BEAM-14435](https://issues.apache.org/jira/browse/BEAM-14435). Original Jira may contain additional context.
Reported by: pabloem.

**Comment by nielm** [comment]
Fixed by #17577
