### ISSUE TITLE
JdbcIO.Write needs exception handling tests

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21562]
There are a few tests that verify the handling of errors within JdbcIO, but there isn't an effort to verify that various errors are handled properly by it.

Imported from Jira [BEAM-14417](https://issues.apache.org/jira/browse/BEAM-14417). Original Jira may contain additional context.
Reported by: pabloem.

**Comment by Amar3tto** [comment]
Seems like #17555 fixed this issue ?

**Comment by damccorm** [comment]
Yeah, looks like it
