### ISSUE TITLE
Update multi-language Java quickstart

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21583]
Multi-language Java quickstart [1] has to be updated to provide step by step instructions based on a working example.

Also it requires some cleaning up (for example, there's an unused Python tab)

[1] https://beam.apache.org/documentation/sdks/java-multi-language-pipelines/

Imported from Jira [BEAM-14105](https://issues.apache.org/jira/browse/BEAM-14105). Original Jira may contain additional context.
Reported by: chamikara.

**Comment by pcoet** [comment]
@damccorm Is there a way I can assign this to myself?

**Comment by damccorm** [comment]
Yeah, if you comment `.take-issue` (without the backtick formatting) a bot will assign you

**Comment by pcoet** [comment]
.take-issue

**Comment by pcoet** [comment]
Yay, magic! Thanks, @damccorm!

**Comment by pcoet** [comment]
Done: https://github.com/apache/beam/pull/22263
