### ISSUE TITLE
[Website] I/O, Community, and Contribute Pages Improvements

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21588]
1) Community page: Fix typos and inconsistencies - change the highlighted menu items to the following: 
 * Join Beam community 
 * Contact us
 * Twitter
 * In person
 * Case study

!image-2022-05-05-16-16-22-648.png|width=182,height=473!

2) Contribute menu: 
Change Get started contributing -\> Code contribution guide 

Fix inconsistencies: 
 * Get help
 * Pre-commit slowness triage 

!image-2022-05-05-16-25-44-112.png|width=247,height=552!

 

3. [Contribute page Ways You Can Contribute](https://beam.apache.org/contribute/#ways-you-can-contribute[/)

3.1) Replace numbered lists with orange arrows and change the color of the words "OR" to orange: 

!image-2022-05-05-16-31-13-720.png|width=790,height=471!

3.2) Change formatting of the table to make it similar to [Contact Us table ]([https://beam.apache.org/community/contact-us/)|https://beam.apache.org/community/contact-us/]:]
 * Change links color to orange
 * change header of the table to:  CONTRIBUTION                          HOW TO DO IT 
 * change background of the column CONTRIBUTION to light-orange (same color as in Contact Us table background) 
 * Make borders look the same as borders in Contact us

 

For reference, this is how the Contact Us table looks like: 

 

!image-2022-05-05-16-33-42-932.png|width=688,height=411!

 

4) I/O Connectors Page: 

[https://beam.apache.org/documentation/io/connectors/](https://beam.apache.org/documentation/io/connectors/)

Horizontal alignment: Align all columns except the first one for both tables (Built-in I/O Connectors and Other I/O Connectors): 

!image-2022-05-05-16-43-30-835.png|width=402,height=240!

 

 

 

Imported from Jira [BEAM-14428](https://issues.apache.org/jira/browse/BEAM-14428). Original Jira may contain additional context.
Reported by: daria.bezkorovaina.

**Comment by damccorm** [comment]
Unable to assign user @bullet03. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by dariabezkorovaina** [comment]
Hi @damccorm, you may mark this issue as resolved, the changes have been implemented by @bullet03 in PR#17572 https://github.com/apache/beam/pull/17572.
