### ISSUE TITLE
Please upgrade jackson-bom version to higher then 2.13.0 in the Java SDK

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21584]
jackson-databind 2.13.0 - 2.13.2 include a volunerability [https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.13.0](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.13.0)

 

Please upgrade the version

Imported from Jira [BEAM-14480](https://issues.apache.org/jira/browse/BEAM-14480). Original Jira may contain additional context.
Reported by: sshahar1.

**Comment by Abacn** [comment]
dup by #22805

**Comment by Abacn** [comment]
.close-issue
