### ISSUE TITLE
Support type hinting generics in Apache Beam type inference 

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21593]
See: [https://peps.python.org/pep-0585/](https://peps.python.org/pep-0585/) that introduces this construct.

Imported from Jira [BEAM-14397](https://issues.apache.org/jira/browse/BEAM-14397). Original Jira may contain additional context.
Reported by: tvalentyn.

**Comment by yilei** [comment]
Adding a comment from Jira:

> Also: if Iterator is imported from collections.abc instead of typing (to annotate process() of DoFn classes), then Beam does not consider it to be iterable.

Note typing.Iterator (and other generic collections types) has been deprecated since Python 3.9 in favor of collections.abc.

**Comment by TheNeuralBit** [comment]
This was just again in #23366, I'm going to close this as a duplicate since that one has additional information about the errors raised.
