### ISSUE TITLE
Python sdk's PeriodicImpulse generates a bounded PCollection

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21606]
See the dev mail list thread for details: https://lists.apache.org/thread/ps3m0jc0ngqp1y2s0mv2n6hxhvgkr3vw

PeriodicImpluse transform in Java sdk generates unbounded
PCollection; while in Python sdk it generates bounded PCollection. The
latter case may cause issues in streaming.

Per Cham: Note that the primary use-case of PeriodicImpulse (according to the design doc) was to
generate a fixed/bounded input that can slowly change over time but
changing over time dimension would make it unbounded. 

Seems like we need to make python PeriodicImpulse generates an unbounded pcoll, in  alignment with Java implementation, and also make sure that the change does not break the current implementation of its original use case (stream enrichment problem).

Imported from Jira [BEAM-14498](https://issues.apache.org/jira/browse/BEAM-14498). Original Jira may contain additional context.
Reported by: yihu.

**Comment by Abacn** [comment]
For more context, see https://lists.apache.org/thread/ps3m0jc0ngqp1y2s0mv2n6hxhvgkr3vw

**Comment by kennknowles** [comment]
It is a clear bug, but I don't think we need to block the release on this do we?
