### ISSUE TITLE
Slow Side input pattern bug in sample

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21605]
The current code sample for the slow side input pattern at:

[https://beam.apache.org/documentation/patterns/side-inputs/#slowly-updating-global-window-side-inputs](https://beam.apache.org/documentation/patterns/side-inputs/#slowly-updating-global-window-side-inputs)

Will fail under certain conditions, where more than one element is sent via the Generate code pane to the View. This should have an aggregation to correct the issue. 

 

Imported from Jira [BEAM-14307](https://issues.apache.org/jira/browse/BEAM-14307). Original Jira may contain additional context.
Reported by: rarokni@gmail.com.

**Comment by nickcaballero** [comment]
I think this was fixed by https://github.com/apache/beam/pull/17371? One thing that is missing from the sample code is the use of a default value.
