### ISSUE TITLE
BQ file loads require some exception handling tests

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21603]
Is similar to https://issues.apache.org/jira/browse/BEAM-14422 and is being worked on in this PR: [https://github.com/apache/beam/pull/17589](https://github.com/apache/beam/pull/17589) 

Imported from Jira [BEAM-14454](https://issues.apache.org/jira/browse/BEAM-14454). Original Jira may contain additional context.
Reported by: ahmedabu.

**Comment by damccorm** [comment]
Unable to assign user @ahmedabu98. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by ahmedabu98** [comment]
Closed with #17589
