### ISSUE TITLE
Remove invalid mod type from DataChangeRecord

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21618]
Remove the invalid (and unused) mod type INSERT_OR_UPDATE from the Spanner Change Streams modtype

Imported from Jira [BEAM-14419](https://issues.apache.org/jira/browse/BEAM-14419). Original Jira may contain additional context.
Reported by: thiagotnunes.

**Comment by damccorm** [comment]
Unable to assign user @thiagotnunes. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by kennknowles** [comment]
This appears to have been fixed by #17556. @thiagotnunes can you confirm?

**Comment by thiagotnunes** [comment]
Yes, that was fixed already, sorry about the late reply

**Comment by kennknowles** [comment]
@thiagotnunes since you fixed this, could you self-assign and close it for our records?

**Comment by kennknowles** [comment]
Ah, now that you commented I can assign you.
