### ISSUE TITLE
Incorrect Spanner IO Request Count metrics

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21635]
IO request count metrics calculated incorrectly for GCP Spanner

 

Resource ID is formulated incorrectly

*Spanner Table:*

`//spanner.googleapis.com/projects/\{projectId}/{*}topics{*}/\{databaseId}/tables/\{tableId`}

should be

`//spanner.googleapis.com/projects/\{projectId}/instances/\{instanceId}/databases/\{databaseId}/tables/\{tableId`}

and is populated incorrectly – instance ID is used in place of tableID

Spanner SQL Query:

`//spanner.googleapis.com/projects/\{projectId}/queries/\{queryName} `
`should be`
`{}//spanner.googleapis.com/projects/\{projectId}/{`}`{}instances/\{instanceId}/queries{`}`{}/\{queryName} {`}

and queryName is nullable which cause issued downstream
this is not actually populated at all - queries are logged as reads on an instance. 

Imported from Jira [BEAM-14121](https://issues.apache.org/jira/browse/BEAM-14121). Original Jira may contain additional context.
Reported by: nielm.

**Comment by damccorm** [comment]
Unable to assign user @nielm. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by kennknowles** [comment]
PR claims to have fixed this one.
