### ISSUE TITLE
Implement "Beam Summit 2022" banner

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21648]
Imported from Jira [BEAM-14527](https://issues.apache.org/jira/browse/BEAM-14527). Original Jira may contain additional context.
Reported by: Alexander Zhuravlev.

**Comment by damccorm** [comment]
Unable to assign user @miamihotline. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by miamihotline** [comment]
.take-issue

**Comment by miamihotline** [comment]
.close-issue
