### ISSUE TITLE
Bump clouldpilckle to 2.1.0

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21641]
When I bump Beam to 2.38.0 in Python Flink, I find a serialization error in clouldpilckle 2.0.0 version.

We should bump clouldpilckle to 2.1.0

[https://github.com/cloudpipe/cloudpickle/issues/473](https://github.com/cloudpipe/cloudpickle/issues/473)

 

[https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=36160&view=logs&j=9cada3cb-c1d3-5621-16da-0f718fb86602&t=c67e71ed-6451-5d26-8920-5a8cf9651901&l=25375](https://dev.azure.com/apache-flink/apache-flink/_build/results?buildId=36160&view=logs&j=9cada3cb-c1d3-5621-16da-0f718fb86602&t=c67e71ed-6451-5d26-8920-5a8cf9651901&l=25375)

[https://github.com/apache/flink/pull/19802](https://github.com/apache/flink/pull/19802)

Imported from Jira [BEAM-14533](https://issues.apache.org/jira/browse/BEAM-14533). Original Jira may contain additional context.
Reported by: ana4.

**Comment by deadwind4** [comment]
I have opened a PR https://github.com/apache/beam/pull/17780
