### ISSUE TITLE
Add exception test cases to GcsFileSystem

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21642]
Imported from Jira [BEAM-14475](https://issues.apache.org/jira/browse/BEAM-14475). Original Jira may contain additional context.
Reported by: johnjcasey.

**Comment by damccorm** [comment]
Unable to assign user @johnjcasey. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by johnjcasey** [comment]
this can be closed @damccorm
