### ISSUE TITLE
Add Export to BQ to FhirIO.Export

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21649]
Documentation for Export to BQ: [https://cloud.google.com/healthcare-api/docs/how-tos/fhir-export-bigquery,](https://cloud.google.com/healthcare-api/docs/how-tos/fhir-export-bigquery,) currently only GCS (
[https://cloud.google.com/healthcare-api/docs/how-tos/fhir-import-export#exporting_fhir_resources](https://cloud.google.com/healthcare-api/docs/how-tos/fhir-import-export#exporting_fhir_resources)) is implemented.

Imported from Jira [BEAM-14451](https://issues.apache.org/jira/browse/BEAM-14451). Original Jira may contain additional context.
Reported by: msbukal.

**Comment by damccorm** [comment]
Unable to assign user @lnogueir. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by lnogueir** [comment]
> Unable to assign user @lnogueir. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

Hi, I am unable to self-assign this to me. However, this issue has been resolved already by #17598.
