### ISSUE TITLE
Add a TimestampedBatch analogue for TimestampedValue

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21651]
TimestampedBatch allows a DoFn author to produce timestamps and leave it up to the SDK to assign windows/panes

Imported from Jira [BEAM-14352](https://issues.apache.org/jira/browse/BEAM-14352). Original Jira may contain additional context.
Reported by: bhulette.
Subtask of issue #21650

**Comment by TheNeuralBit** [comment]
We shouldn't do this, instead in the future we should deprecate and remove TimestampedValue.
