### ISSUE TITLE
Enable null key and value for metadata kafka xlang

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21665]
Enable nullable keys and values for byte array kafka records when using kafka xlang with metadata.

Imported from Jira [BEAM-14297](https://issues.apache.org/jira/browse/BEAM-14297). Original Jira may contain additional context.
Reported by: johnjcasey.

**Comment by damccorm** [comment]
Unable to assign user @johnjcasey. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by johnjcasey** [comment]
this can be closed @damccorm
