### ISSUE TITLE
ReadFromBigQuery with query requires exception handling tests. So does File Loads

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21668]
Tests need to be created to test the behavior of our code when expected exceptions come up when querying from BigQuery.

 

Includes writing tests for File Loads as well.

Imported from Jira [BEAM-14422](https://issues.apache.org/jira/browse/BEAM-14422). Original Jira may contain additional context.
Reported by: ahmedabu.

**Comment by damccorm** [comment]
Unable to assign user @ahmedabu98. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by ahmedabu98** [comment]
Closed with #17589

**Comment by ahmedabu98** [comment]
.close-issue
