### ISSUE TITLE
Add Read transform and initial HealthcareClient in Go SDK

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21662]
This is the first of many tickets to bring [FhirIO](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIO.java) from Java into the Go SDK.
It consists of:
 * Adding the [Read](https://github.com/apache/beam/blob/3e683606d9a03e7da3d37a83eb16c3a6b96068cd/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/FhirIO.java#L455) transform in Go SDK
 * Adding a basic implementation of the [HttpHealthcareClient](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare/HttpHealthcareApiClient.java) in Go, to be able to authenticate and make the requests needed for the transform above.

Buganizer links:
 - [b/233887489](https://b.corp.google.com/issues/233887489).

 - [b/204355275](https://buganizer.corp.google.com/issues/204355275).

Imported from Jira [BEAM-14513](https://issues.apache.org/jira/browse/BEAM-14513). Original Jira may contain additional context.
Reported by: lnogueir.

**Comment by damccorm** [comment]
Unable to assign user @lnogueir. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by lnogueir** [comment]
Unable to self-assign, but this issue has been resolved by #17748
