### ISSUE TITLE
Update fileio.MatchContinuously to allow reading already read files with a new timestamp

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21672]
This will be the Python counterpart of BEAM-14267.

For fileio.MatchContinuously, we want to add an option to choose to consider a file new if it has a different timestamp from an existing file, even if the file itself has the same name.

See the following design doc for more detail:

https://docs.google.com/document/d/1xnacyLGNh6rbPGgTAh5D1gZVR8rHUBsMMRV3YkvlL08/edit?usp=sharing&resourcekey=0-be0uF-DdmwAz6Vg4Li9FNw

Imported from Jira [BEAM-14315](https://issues.apache.org/jira/browse/BEAM-14315). Original Jira may contain additional context.
Reported by: yihu.

**Comment by damccorm** [comment]
Unable to assign user @Abacn. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by Abacn** [comment]
.close-issue

completed in #17604
