### ISSUE TITLE
Extraneous warning message: "Make sure that locally built Python SDK docker image has Python X.Y interpreter"

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21676]
This warning comes up whenever a Python pipeline is constructed. It never seems to actually indicate an issue, my pipelines is always able to run.

Looking through the commit history it looks like the warning may have been added by mistake.

Imported from Jira [BEAM-14552](https://issues.apache.org/jira/browse/BEAM-14552). Original Jira may contain additional context.
Reported by: bhulette.

**Comment by Abacn** [comment]
.close-issue
