### ISSUE TITLE
[CdapIO] Design and implement Spark Receiver Builder

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21673]
### Context:

CDAP plugins that support streaming sources include Receiver classes (ex. [HubSpotReceiver](https://github.com/data-integrations/hubspot/blob/develop/src/main/java/io/cdap/plugin/hubspot/source/streaming/HubspotReceiver.java)) that extend `org.apache.spark.streaming.receiver.Receiver` abstract class. Receiver classes are used by plugin Streaming Utils classes (ex. [HubSpotStreamingUtils](https://github.com/data-integrations/hubspot/blob/develop/src/main/java/io/cdap/plugin/hubspot/source/streaming/HubspotStreamingUtil.java)) to provide `getStream()` method to Streaming Source classes (ex. [HubSpotStreamingSource](https://github.com/data-integrations/hubspot/blob/develop/src/main/java/io/cdap/plugin/hubspot/source/streaming/HubspotStreamingSource.java)) and usually placed in `cdap/plugin/\{<plugin name>}/plugin/source/streaming` folder (ex.[ HubSpot plugin repo](https://github.com/data-integrations/hubspot/tree/develop/src/main/java/io/cdap/plugin/hubspot/source/streaming)).

Reference information:
 * [Streaming plug-ins integration](https://docs.google.com/document/d/1T-bhd0Qk7DBePIfgHEPagYiA1oLP4z5kYEd0S1SOGxQ/edit#heading=h.o88i6p9b13o9) (Apache CDAP Connection Design Doc)

 * [Plugin integration process description](https://docs.google.com/document/d/1T-bhd0Qk7DBePIfgHEPagYiA1oLP4z5kYEd0S1SOGxQ/edit#heading=h.1h6udb1b52xc) (Apache CDAP Connection Design Doc)

 * [Streaming wrapper design](https://docs.google.com/document/d/1T-bhd0Qk7DBePIfgHEPagYiA1oLP4z5kYEd0S1SOGxQ/edit#heading=h.fcafz0ydsso1) (Apache CDAP Connection Design Doc)

### Task Description:

Required to design custom Spark receivers builder class so that the custom receivers can be used in Apache Beam connector via SparkReceiverIO interface (used in CDAP IO as a dependency).
### Acceptance criteria:

Design of builder class(es) that will create custom Spark receivers in Apache Beam connectors (`{}SparkReceiverIO{`}).
#### Note:

It is necessary that this builder class be independent of CDAP receivers and can be used by any other custom Spark receiver like a part of SparkReceiverIO.

Imported from Jira [BEAM-14101](https://issues.apache.org/jira/browse/BEAM-14101). Original Jira may contain additional context.
Reported by: elizaveta.lomteva.

**Comment by damccorm** [comment]
Unable to assign user @Lizzfox. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by Lizzfox** [comment]
@damccorm please assign this task to me and @Amar3tto. I can't edit it
Thanks

**Comment by damccorm** [comment]
I assigned you, @Amar3tto will need to interact with an issue before I can assign them (commenting here is fine)

**Comment by Amar3tto** [comment]
@damccorm Please assign to me.
Thank you!
