### ISSUE TITLE
Add support for including addittional parameters to executebundle method in fhirio.

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21689]
Add FhirBundleWithMetadata in executebundles method so that we can pass additional information like message id.
FhirBundleWithMetadata represents a FHIR bundle, with it's metadata (eg. Hl7 messageId) to be executed on the intermediate FHIR store.

Imported from Jira [BEAM-14504](https://issues.apache.org/jira/browse/BEAM-14504). Original Jira may contain additional context.
Reported by: fbeevikm.

**Comment by damccorm** [comment]
Unable to assign user @fbeevikm. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by fbeevikm** [comment]
@damccorm I don't have permission to self assign. FYI the PR for this issue has been merged #17741

**Comment by damccorm** [comment]
Cool, I'll just close this issue then. FWIW once https://github.com/apache/beam/pull/21719 is merged, you'll be able to self-assign by commenting `.take-issue` and close issues by commenting `.close-issue`
