### ISSUE TITLE
Integration testing of Pipeline drain in Go SDK

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21681]
Add an integration test for pipeline drain feature [BEAM-11106](https://issues.apache.org/jira/browse/BEAM-11106) added in https://github.com/apache/beam/pull/17432. 

Imported from Jira [BEAM-14406](https://issues.apache.org/jira/browse/BEAM-14406). Original Jira may contain additional context.
Reported by: riteshghorse.

**Comment by damccorm** [comment]
Unable to assign user @riteshghorse. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by damccorm** [comment]
FWIW, this limitation should be addressed by https://github.com/apache/beam/pull/21719

**Comment by riteshghorse** [comment]
Great, thanks!
