### ISSUE TITLE
[CdapIO] Implement CDAP IO interface for batch plugins: Read

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21688]
Imported from Jira [BEAM-14198](https://issues.apache.org/jira/browse/BEAM-14198). Original Jira may contain additional context.
Reported by: elizaveta.lomteva.

**Comment by Lizzfox** [comment]
This task was completed by [[BEAM-14073] [CdapIO] CDAP IO for batch plugins: Read, Write. Unit tests included #21765](https://github.com/apache/beam/pull/21765) (Merged)

**Comment by Lizzfox** [comment]
.take-issue

**Comment by Lizzfox** [comment]
.close-issue
