### ISSUE TITLE
beam_LoadTests_Python_GBK_reiterate_Dataflow_Streaming failure

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21697]
[https://ci-beam.apache.org/job/beam_LoadTests_Python_GBK_reiterate_Dataflow_Streaming/](https://ci-beam.apache.org/job/beam_LoadTests_Python_GBK_reiterate_Dataflow_Streaming/) starts failing since 04/27.

 

This is likely caused by dataflow runner v2 update which enforces SDF semantics on restrictions more strongly than previously. The error message is 
JOB_MESSAGE_ERROR: generic::invalid_argument: Last primary index cannot decrease from previous split, was 0 and is now -1

Imported from Jira [BEAM-14434](https://issues.apache.org/jira/browse/BEAM-14434). Original Jira may contain additional context.
Reported by: yichi.

**Comment by y1chi** [comment]
This issue should have been resolved.
