### ISSUE TITLE
Beam BQIO not accepting integer values for BQ table fields of type Float64

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21693]
Customer (F5) is working on migrating to the new Storage API support in Beam SDK and are facing issues in the latest Snapshot build. Today, in production, they are using the legacy streaming API and their pipeline works fine when they are mapping an incoming integer field to a BQ table field of type Float64. However, with the storage API, their pipeline is failing with the following error "Unexpected value :0, type: class java.lang.Integer. Table field name: a, type: FLOAT64" Customer considers this as a regression and is preventing them from going live with Storage API. Customer is planning on going live with Storage API end of July and would like to have this fixed in the 2.39.0 GA release.

Imported from Jira [BEAM-14529](https://issues.apache.org/jira/browse/BEAM-14529). Original Jira may contain additional context.
Reported by: yirutang.

**Comment by damccorm** [comment]
Unable to assign user @yirutang. If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by kennknowles** [comment]
This looks like it was fixed by #17779

**Comment by kennknowles** [comment]
@yirutang FYI that I am closing this based on your PR
