### ISSUE TITLE
Dataflow portable job submission translate FileResultCoder only with window coder

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21691]
The destination coder is neglected, if there are multiple FileResultCoders with different destination coder, only first registration is successful.

Imported from Jira [BEAM-14553](https://issues.apache.org/jira/browse/BEAM-14553). Original Jira may contain additional context.
Reported by: yichi.

**Comment by kennknowles** [comment]
This is a certain bug and the fix is pretty much done waiting for re-run of flakes. But is it actually a release blocker that we need to track?

**Comment by kennknowles** [comment]
It seems this has been in the codebase for a very long time
