### ISSUE TITLE
beam_PostCommit_Java_DataflowV2, testBigQueryStorageWrite30MProto failing consistently

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21708]
testBigQueryStorageWrite30MProto seems to have been failing since being originally introduced. First failure I found: https://ci-beam.apache.org/job/beam_PostCommit_Java_DataflowV2/1391/, which includes when this PR was merged: https://github.com/apache/beam/pull/17038

I don't see any explicit reason this might be failing either in the console logs or Dataflow logs. Here's the console logs:

```

java.lang.RuntimeException: Workflow failed. Causes: S06:WriteToBQ/StorageApiLoads/GroupIntoBatches/ParDo(GroupIntoBatches)/ParMultiDo(GroupIntoBatches)/Reshard/Read+WriteToBQ/StorageApiLoads/GroupIntoBatches/ParDo(GroupIntoBatches)/ParMultiDo(GroupIntoBatches)/Reshard/UnreifyWindow+WriteToBQ/StorageApiLoads/GroupIntoBatches/ParDo(GroupIntoBatches)/ParMultiDo(GroupIntoBatches)+WriteToBQ/StorageApiLoads/StorageApiWriteSharded/Write
Records/ParMultiDo(WriteRecords)/Reshard/Reify+WriteToBQ/StorageApiLoads/StorageApiWriteSharded/Write
Records/ParMultiDo(WriteRecords)/Reshard/Write failed., The job failed because a work item has failed
4 times. Look in previous log entries for the cause of each one of the 4 failures. For more information,
see https://cloud.google.com/dataflow/docs/guides/common-errors. The work item was attempted on these
workers: 

  testpipeline-jenkins-0319-03190548-sfjp-harness-263n
      Root cause: The worker lost
contact with the service.,

```

Imported from Jira [BEAM-14263](https://issues.apache.org/jira/browse/BEAM-14263). Original Jira may contain additional context.
Reported by: danoliveira.

**Comment by kennknowles** [comment]
@reuvenlax is this fixed? not intended to work? what's the read on this?

**Comment by kennknowles** [comment]
The suite has been perma-red for a very long time. This is probably representing tests that are not supposed to pass (yet) and/or have a limitation. I know the firestore tests were being disabled in some contexts, but this is yet another context to adjust. Since this job is so vague, probably we should split it and eliminate it, or perhaps it is already redundant.

**Comment by kennknowles** [comment]
I'm going to unassign this for now, then. Feel free to comment or grab it again.

**Comment by Abacn** [comment]
obsolete - now it runs 3M proto and test is healthy
