### ISSUE TITLE
SpannerChangeStreamIT test failing

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21705]
FAILURES: https://ci-beam.apache.org/job/beam_PostCommit_Java_DataflowV2/1468/ 

org.apache.beam.sdk.io.gcp.spanner.changestreams.it.SpannerChangeStreamIT.testReadSpannerChangeStream
 org.apache.beam.sdk.io.gcp.spanner.changestreams.it.SpannerChangeStreamTransactionBoundariesIT.testTransactionBoundaries    

 

Looks like errors are related to [https://github.com/apache/beam/pull/17202](https://github.com/apache/beam/pull/17202) - we should probably change autoscaling for these tests?

 

Imported from Jira [BEAM-14277](https://issues.apache.org/jira/browse/BEAM-14277). Original Jira may contain additional context.
Reported by: emilymye.
Subtask of issue #21704

**Comment by TheNeuralBit** [comment]
No failures in Jenkins history, marking this fixed.

I suspect this was addressed by https://github.com/apache/beam/pull/17200, but I'm not sure
