### ISSUE TITLE
pubsublite.ReadWriteIT failing in beam_PostCommit_Java_DataflowV1 and V2

### ISSUE THREAD

**Issue by damccorm** [apache/beam#21703]
Example: https://ci-beam.apache.org/job/beam_PostCommit_Java_DataflowV1/1455/testReport/junit/org.apache.beam.sdk.io.gcp.pubsublite/ReadWriteIT/testReadWrite/

```

java.lang.AssertionError: Did not receive signal on projects/apache-beam-testing/subscriptions/result-subscription--586739339276181574
in 300s

```

Dataflow logs show this, might be related:

```

Error message from worker: java.lang.IllegalArgumentException
        org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)

       org.apache.beam.sdk.io.gcp.pubsublite.internal.SubscriptionPartitionLoader$GeneratorFn.getInitialWatermarkEstimatorState(SubscriptionPartitionLoader.java:76)

```

Imported from Jira [BEAM-14253](https://issues.apache.org/jira/browse/BEAM-14253). Original Jira may contain additional context.
Reported by: danoliveira.
Subtask of issue #21701

**Comment by damccorm** [comment]
Unable to assign user @dpcollins-google . If able, self-assign, otherwise tag @damccorm so that he can assign you. Because of GitHub's spam prevention system, your activity is required to enable assignment in this repo.

**Comment by kennknowles** [comment]
This test suite is healthy now.
