### ISSUE TITLE
[Bug]: Flaky test  org.apache.beam.sdk.io.gcp.spanner.SpannerIOWriteExceptionHandlingTest.testExceptionHandlingForWriteGrouped

### ISSUE THREAD

**Issue by nielm** [apache/beam#21729]
### What happened?

The test `org.apache.beam.sdk.io.gcp.spanner.SpannerIOWriteExceptionHandlingTest.testExceptionHandlingForWriteGrouped`
([SpannerIOWriteExceptionHandlingTest.java:222](https://github.com/apache/beam/blob/3c623abd631b493c8a71d05fe591065754c75d0c/sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteExceptionHandlingTest.java#L222)) seems to be flaky as a sleeper can be fired more or less times than what is required (I have seen errors with both 8 and 10 times instead of the required 9)

```
> is a org.mockito.exceptions.verification.TooManyActualInvocations
Stacktrace was: org.mockito.exceptions.verification.TooManyActualInvocations: 
sleeper.sleep(<any long>);
Wanted 9 times:
-> at org.apache.beam.sdk.io.gcp.spanner.SpannerIOWriteExceptionHandlingTest.testExceptionHandlingForWriteGrouped(SpannerIOWriteExceptionHandlingTest.java:222)
But was 10 times:
```

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-gcp

**Comment by Abacn** [comment]
.take-issue

**Comment by Abacn** [comment]
duplicates #22008 and there is another solution there
