### ISSUE TITLE
Create fake model with GB sizes

### ISSUE THREAD

**Issue by yeandy** [apache/beam#21722]
### What needs to happen?

We need to create models of various sizes (1 GB, 5GB, 10 GB) to help with benchmarking RunInference on models of various sizes. These models don't have to be trained on anything, but be randomly initialized, fully-connected networks.

Subtask of issue https://github.com/apache/beam/issues/21435

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

**Comment by tvalentyn** [comment]
Planning to use off-the-shelf models.
