### ISSUE TITLE
[Bug]: KafkaIO SplittableDoFn not resuming from last committed offset

### ISSUE THREAD

**Issue by jeanwisser** [apache/beam#21730]
### What happened?

Using `KafkaIO` with [ReadFromKafkaDoFn.java](https://github.com/apache/beam/blob/v2.39.0/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java) and `commitOffsetsFinalize` should commit offsets of processed messages and if the pipeline is restarted, should resume from the last committed offset.

While committing the offset works correctly, resuming from the latest committed offset does not work because the groupId used are not the same (using 2.39.0).

- Committing the offsets happens in [KafkaCommitOffset.java](https://github.com/apache/beam/blob/v2.39.0/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaCommitOffset.java) with a consumer defined as:
 `consumerFactoryFn.apply(updatedConsumerConfig)`

- Reading the startOffset is done in `initialRestriction()` in [ReadFromKafkaDoFn.java](https://github.com/apache/beam/blob/v2.39.0/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java) with a consumer defined as:
`consumerFactoryFn.apply(
            KafkaIOUtils.getOffsetConsumerConfig(
                "initialOffset", offsetConsumerConfig, updatedConsumerConfig)))`

Since the group name of the consumer is not the same as the group name of the consumer fetching the latest offset, the pipeline will always start from the beginning of the (topic,partition) again.

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-kafka

**Comment by chamikaramj** [comment]
@johnjcasey I believe you are looking into a similar issue ?

**Comment by johnjcasey** [comment]
I am, you can assign this to me

**Comment by chamikaramj** [comment]
Done. Feel free mark as a duplicate if needed.

**Comment by kennknowles** [comment]
Doesn't this mean that some stated functionality just isn't working? Is there a chance of data corruption if the user doesn't notice? That would make this P1 and release blocking, really.

**Comment by chamikaramj** [comment]
I think this was fixed by https://github.com/apache/beam/pull/22450

**Comment by johnjcasey** [comment]
It was

**Comment by Abacn** [comment]
There is still a reference to this issue in our code: Update: the reason is here: https://github.com/apache/beam/blob/eb23b0a123ea94429f34385194e8eca7299d66cd/sdks/python/apache_beam/io/kafka.py#L191

Since it is fixed by #22450 is it safe to remove `append_args=['--experiments=use_unbounded_sdf_wrapper']` below that line?
