### ISSUE TITLE
[Playground Task]: Migrate from Google Analytics to Matomo Cloud

### ISSUE THREAD

**Issue by VladMatyunin** [apache/beam#21763]
### What needs to happen?

Beam Playground currently uses Google Analytics.
Migrate from Google Analytics to Matomo Cloud solution for Flutter application.

### Issue Priority

Priority: 1

### Issue Component

Component: beam-playground

**Comment by kennknowles** [comment]
@VladMatyunin will you be taking this?

**Comment by VladMatyunin** [comment]
@kennknowles yes, I'll be working on that, please assign to me, thank you!

**Comment by rshamunov** [comment]
Migration to Matomo Cloud is no longer planned
