### ISSUE TITLE
Dataflow runner creates a new timer whenever the output timestamp is change

### ISSUE THREAD

**Issue by reuvenlax** [apache/beam#21794]
### What happened?

Since the output timestamp was included in the timer tag sent to Dataflow, every change of the timestamp created a brand new timer. The expected behavior is that the old timer would be overwritten.

### Issue Priority

Priority: 1

### Issue Component

Component: runner-dataflow

**Comment by kennknowles** [comment]
Was this fixed?

**Comment by kennknowles** [comment]
I believe this was fixed, but @reuvenlax can you connect with the PR please?

**Comment by damccorm** [comment]
Looks like this was fixed with https://github.com/apache/beam/pull/21793
