### ISSUE TITLE
[Bug]: beam_PostCommit_Java_Sickbay fails

### ISSUE THREAD

**Issue by kileys** [apache/beam#21826]
### What happened?

beam_PostCommit_Java_Sickbay fails to run successfully

https://ci-beam.apache.org/job/beam_PostCommit_Java_Sickbay/

### Issue Priority

Priority: 2

### Issue Component

Component: build-system

**Comment by kileys** [comment]
@kennknowles

**Comment by fernando-wizeline** [comment]
Taking a look! Thanks for the heads up.

**Comment by Abacn** [comment]
I'm working on python sickbay fixes and happened to notice this mirror issue in java, opened #21922
