### ISSUE TITLE
Unskip RunInference IT tests once the licensing on the datasets and models is complete.

### ISSUE THREAD

**Issue by AnandInguva** [apache/beam#21859]
### What needs to happen?

Torch IT test uses Imagenet dataset and torch hub pre-trained models.  Sklearn IT test uses dataset from Kaggle.

Until the licenses for these are figured out, sickbay all the IT tests that uses publicly available data and models.  

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

**Comment by tvalentyn** [comment]
PLease reopen if this is not done.

**Comment by tvalentyn** [comment]
Looks like it's not done: https://github.com/apache/beam/blob/c7f64264451af12ff6c7c0ef4bc95fd7ce0f5418/sdks/python/apache_beam/ml/inference/sklearn_inference_it_test.py#L56

**Comment by TheNeuralBit** [comment]
Helpful link: https://ci-beam.apache.org/job/beam_PostCommit_Python39/lastCompletedBuild/testReport/apache_beam.ml.inference.pytorch_inference_it_test/PyTorchInference/

shows that these tests are still skipped

**Comment by AnandInguva** [comment]
> Looks like it's not done:
> 
> https://github.com/apache/beam/blob/c7f64264451af12ff6c7c0ef4bc95fd7ce0f5418/sdks/python/apache_beam/ml/inference/sklearn_inference_it_test.py#L56

This used to be run before https://github.com/apache/beam/pull/22088. I think @ryanthompson591 accidentally added skip to that test.

**Comment by AnandInguva** [comment]
> Helpful link: https://ci-beam.apache.org/job/beam_PostCommit_Python39/lastCompletedBuild/testReport/apache_beam.ml.inference.pytorch_inference_it_test/PyTorchInference/
> 
> shows that these tests are still skipped

Jenkins UI only shows the IT tests that are part of Dataflow suite( these are written to xml files and the UI is created from that). We have 5~6 IT post commit suite. Inference tests runs here https://github.com/apache/beam/blob/94941667e6b472f279501bd81514f204e9f75038/build.gradle.kts#L335 and is not displayed on the UI. 

The tests we see in the UI are part of https://github.com/apache/beam/blob/94941667e6b472f279501bd81514f204e9f75038/build.gradle.kts#L331. Here, inference tests are collected because they have the decorator `it_postcommit` and then gets skipped because the dependencies are not installed on the Jenkins node.

The tests actually pass in the https://ci-beam.apache.org/job/beam_PostCommit_Python39/lastCompletedBuild/testReport/apache_beam.ml.inference.pytorch_inference_it_test/PyTorchInference/. It can be found in the console 
<img width="1112" alt="Screen Shot 2022-08-24 at 12 11 19 AM" src="https://user-images.githubusercontent.com/34158215/186238468-fa97ce82-83df-4e3c-90d3-6f3e2ffca292.png">

**Comment by AnandInguva** [comment]
https://github.com/apache/beam/pull/22825. Added a PR to unskip the change. Once thats merged, we can close this.

**Comment by TheNeuralBit** [comment]
Thank you for the detailed explanation!

I think it's possible for the Jenkins UI to display the output of multiple test suites. e.g. in the Python PreCommit we see duplicate runs of each test, one for each environment: 
![image](https://user-images.githubusercontent.com/675055/186284108-f5026f60-a9d8-40af-bb3d-60f053bb9321.png)

I'm not sure what is actually enabling this, but we should do it in these PostCommits too.

**Comment by tvalentyn** [comment]
@AnandInguva could you please file an issue to see if/how we can export test signal from the RunInference tests and combine it with the PostCommit signal?

**Comment by tvalentyn** [comment]
Actually, we can just reuse https://github.com/apache/beam/issues/22858
