### ISSUE TITLE
[Bug]: BigQuery table name validation doesn't allow spaces

### ISSUE THREAD

**Issue by zchenyu** [apache/beam#21878]
### What happened?

BigQuery IO currently rejects table names that contain spaces.

From https://cloud.google.com/bigquery/docs/tables#table_naming : a table name can contain spaces.

Looks like it will require an update to this regex: https://github.com/apache/beam/blob/ac20321008e51c401731895ea934642b4648efd3/sdks/python/apache_beam/io/gcp/bigquery_tools.py#L258

Similar to this PR which allowed `-` in table names: https://github.com/apache/beam/pull/14125

### Issue Priority

Priority: 2

### Issue Component

Component: io-py-gcp

**Comment by yeandy** [comment]
@BjornPrime This has intersections with I/O, but this could be a good starter bug to get you used to the workflow of testing, making a PR, etc.

**Comment by dgdheeraj** [comment]
.take-issue

**Comment by shhivam** [comment]
@dgdheeraj has kindly made a PR for this and that PR is merged.

Think we can close this issue? @damccorm @kennknowles @yeandy
