### ISSUE TITLE
[Bug]: KinesisIO javadoc is no longer up-to-date

### ISSUE THREAD

**Issue by mattcasters** [apache/beam#21948]
### What happened?

The javadoc for class KinesisIO is not up-to-date with respect to the writing of messages.

https://beam.apache.org/releases/javadoc/current/org/apache/beam/sdk/io/aws2/kinesis/KinesisIO.html

Specifically this part is causing (me) some confusion:

```
data.apply(KinesisIO.write()
     .withStreamName("streamName")
     .withPartitionKey(KV::getKey)
     .withSerializer(KV::getValue); 
```
That is to say that the `withSerializer` method simply doesn't exist.

From the KinesisIO source it appears that Write expects a `PCollection<byte[]>`, not a KV of sorts.

### Issue Priority

Priority: 0

### Issue Component

Component: io-java-kinesis

**Comment by pabloem** [comment]
the issue here may be that there's two different implementations for AWS sources. In this case, this is the one under `amazon-web-services2`. Have you tried using that one? Or perhaps you're using the one under `amazon-web-services` instead?

**Comment by mosche** [comment]
I think @pabloem is right, @mattcasters. It looks like your dependency is the old `amazon-web-services` / `kinesis` module rather than `amazon-web-services2`

**Comment by mattcasters** [comment]
Yeah I got confused there for a while.  I overlooked that Idea picked an old version of the Beam library.
