### ISSUE TITLE
[Task]: Update spanner tests to enable updating spanner version

### ISSUE THREAD

**Issue by johnjcasey** [apache/beam#21960]
### What needs to happen?

https://github.com/apache/beam/pull/21850

Dependabot wants to update our dependencies, but our tests fail because of the major version change.
The task is to update our tests, and our dependency version, to enable us to upgrade

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-gcp

**Comment by aaltay** [comment]
Who could work on this?

**Comment by johnjcasey** [comment]
@Abacn  may have bandwidth to do this. It looks like a straightforward change

**Comment by Abacn** [comment]
.take-issue

**Comment by johnjcasey** [comment]
Thanks Yi

**Comment by Abacn** [comment]
Should be labelled a python sdk task.

Per #20529 tests are actually not working all the times; and there is a cross-language spanner io (apache_beam.io.gcp.spanner). Should we deprecate this native version anyway?

**Comment by Abacn** [comment]
will close as won't do.

**Comment by Abacn** [comment]
.close-issue not_planned
