### ISSUE TITLE
[Playground] Implement Share Any Code feature on the frontend

### ISSUE THREAD

**Issue by miamihotline** [apache/beam#21978]
### What needs to happen?

Create Share Code button & dropdown on the frontend part of the app.

<img width="720" alt="Снимок экрана 2022-06-22 в 11 18 53" src="https://user-images.githubusercontent.com/48954966/174968056-bbf35416-f378-45ab-877b-76a51cd1143e.png">

Subtask of issue https://github.com/apache/beam/issues/21274

### Issue Priority

Priority: 1

### Issue Component

Component: beam-playground

**Comment by TheNeuralBit** [comment]
this is a subtask of a P4, I dropped priority.

**Comment by miamihotline** [comment]
.take-issue

**Comment by alexeyinkin** [comment]
.take-issue
