### ISSUE TITLE
[Bug]: org.apache.beam.sdk.io.gcp.spanner.SpannerIOReadTest.runBatchQueryTestWithFailures flaky

### ISSUE THREAD

**Issue by aaltay** [apache/beam#21999]
### What happened?

Example: https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/5314/

### Issue Priority

Priority: 1

### Issue Component

Component: io-java-gcp

**Comment by aaltay** [comment]
@johnjcasey - Who could own this issue?

**Comment by Abacn** [comment]
.take-issue

**Comment by Abacn** [comment]
This is a timing issue. A batch of two processElement is executed at the same time and one has error injection. Exception may be elevated in one thread before metrics is incremented in the other.

**Comment by Abacn** [comment]
R: @nielm
