### ISSUE TITLE
[Bug]: org.apache.beam.runners.flink.FlinkRunnerTest.testEnsureStdoutStdErrIsRestored flaky

### ISSUE THREAD

**Issue by aaltay** [apache/beam#22010]
### What happened?

Example: https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/5317/

@johnjcasey - Who could own this issue?

### Issue Priority

Priority: 1

### Issue Component

Component: io-java-gcp

**Comment by ahmedabu98** [comment]
I can add it to my queue, how can I assign it to myself?

**Comment by aaltay** [comment]
@ahmedabu98 - you can assign issues to yourself by commenting `.take-issue` (without the quotes)

**Comment by ahmedabu98** [comment]
.close-issue

**Comment by ahmedabu98** [comment]
Closing issue because this test has been passing for the past couple of months
