### ISSUE TITLE
[Bug]: org.apache.beam.sdk.io.aws2.kinesis.KinesisIOWriteTest.testWriteFailure flaky

### ISSUE THREAD

**Issue by aaltay** [apache/beam#22011]
### What happened?

Example: https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/5317/

@johnjcasey - Who could own this issue?

### Issue Priority

Priority: 1

### Issue Component

Component: io-java-gcp

**Comment by aaltay** [comment]
Should we remove or fix the test?

**Comment by johnjcasey** [comment]
I am fixing the tests. the flake is on verifying a side effect, not the core validation of the test. see https://github.com/apache/beam/pull/22029

**Comment by aaltay** [comment]
@kennknowles @damccorm - Is the stale bot closing open bugs automatically? Should it do that?

**Comment by damccorm** [comment]
It looks like it is, that isn't intentional and it only started doing it recently (<20 issues affected). I put up https://github.com/apache/beam/pull/23067 to fix and will reopen all issues that have been impacted

**Comment by johnjcasey** [comment]
this should be closed
