### ISSUE TITLE
[Feature Request]: [Go SDK] Add option to create table if needed in bigqueryio.Write()

### ISSUE THREAD

**Issue by kennycontreras** [apache/beam#22058]
### What would you like to happen?

`bigqueryio.Write()` allows you to write into BigQuery while providing a table string in the format of `project:dataset.table`. At the moment, if the table doesn't exist, it will fail. And there's no option like `.withCreateDisposition(CreateDisposition.CREATE_IF_NEEDED)` in the Java SDK to create the table if it doesn't exist. 

It will be a great feature to add this. The pipeline already checks if the PCollection<T> has a valid schema with the existing table, so we can use this information (T of schema type) to create the table if needed. 

### Issue Priority

Priority: 0

### Issue Component

Component: io-go-gcp

**Comment by pabloem** [comment]
fyi @youngoli

**Comment by youngoli** [comment]
This is a good feature, and something I originally intended. When I first tried, I ran into issues getting the create disposition working with the Storage Write API. But it's absolutely something we should aim for since this is a feature in both the Java and Python native versions of BQ IO.
