### ISSUE TITLE
[Feature Request]: Set option for acknowledge the messages in PulsarIO reader

### ISSUE THREAD

**Issue by MarcoRob** [apache/beam#22054]
### What would you like to happen?

Currently, the reader for PulsarIO used the Reader interface to manually handle the cursors in the ReadPulsarDoFn and it does not have the option to acknowledge the messages. So I am raising this issue to have this TODO and allow the user to set the acknowledgment of messages and implement and analyze the acknowledgment of the messages may be in batch or each time a bundle inside DoFn is done (this should be to be taken for analysis)

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-pulsar

**Comment by MarcoRob** [comment]
.take-issue

**Comment by rthneha** [comment]
@MarcoRob I am facing an another issue regarding PulsarIO. https://github.com/apache/beam/issues/30688 Can you help me in letting me know if PulsarIO can support beam streaming, if yes then I am facing some issue elaborated here ?

**Comment by Abacn** [comment]
This is essentially a feature request of implementing consumer based read (instead of the reader based read currently PulsarIO.read uses) - keep it open to track this effort
