### ISSUE TITLE
[Playground] Implement tag based filtering feature on the frontend

### ISSUE THREAD

**Issue by miamihotline** [apache/beam#22074]
### What needs to happen?

Improve type filter (all, example, kata, unit test) to the tag based filter, that can use any custom tags.
<img width="464" alt="Снимок экрана 2022-06-28 в 16 45 20" src="https://user-images.githubusercontent.com/48954966/176181837-95aedbbf-232d-461e-9c29-a1a6177fc70f.png">

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by miamihotline** [comment]
.take-issue

**Comment by alexeyinkin** [comment]
@miamihotline's work in progress: pg_22074_tag_based_filtering

**Comment by nausharipov** [comment]
.take-issue

**Comment by nausharipov** [comment]
.take-issue
