### ISSUE TITLE
instanceId.get() being called when using Dataflow Templates after upgrading to 2.40.0

### ISSUE THREAD

**Issue by jeffreyung** [apache/beam#22146]
https://github.com/apache/beam/blob/b53b16f1fb41913b0e8bbe9d64d71b8e3ebfbbf6/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerConfig.java#L165

https://github.com/apache/beam/blob/b53b16f1fb41913b0e8bbe9d64d71b8e3ebfbbf6/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerConfig.java#L177

I've built a Dataflow pipeline template which uses the SpannerConfig class and, after upgrading to BEAM 2.40.0, it fails to build because `instanceId.get()` is being called and it seems that this line is causing the issue.

I suspect this may break the existing Google-provided Dataflow Templates which uses Spanner.

**Comment by bvolpato** [comment]
Also reported here https://stackoverflow.com/questions/73765145/apache-beam-illegalstateexception-value-only-available-at-runtime-after-upgra

Will give it a shot .take-issue

**Comment by bvolpato** [comment]
.remove-labels stale
.add-labels gcp, io, java

**Comment by bvolpato** [comment]
.add-labels bug,gcp,io,java,P1
