### ISSUE TITLE
[Bug]: Significant scalability bottlenecks at high throughput due to coarse-grained locking

### ISSUE THREAD

**Issue by steveniemitz** [apache/beam#22161]
### What happened?

There are several spots in the critical (streaming) bundle execution path that serialize execution of all threads.  Importantly are:
- `ExecutionStateSampler.add/removeTracker`
- `ProxyInvocationHandler.as`
- `DoFnSignatures.getSignature`
- `ByteBuddyDoFnInvokerFactory.getByteBuddyInvokerConstructor`

A JFR recording of a typical streaming load shows this:
![image](https://user-images.githubusercontent.com/1882981/177342493-008e0c79-bbe1-4b6f-80d0-8b8969d228b8.png)

These functions should be optimized to not require a coarse-grained lock when executing.

### Issue Priority

Priority: 2

### Issue Component

Component: runner-core

**Comment by steveniemitz** [comment]
.take-issue
.remove-labels 'awaiting-triage'

**Comment by steveniemitz** [comment]
.take-issue

**Comment by lukecwik** [comment]
I think the above two PRs handled this, should we close this now?

**Comment by steveniemitz** [comment]
.close-issue
