### ISSUE TITLE
[Bug]: Seed Job failing with AttributeError for 'ldap' module

### ISSUE THREAD

**Issue by ahmedabu98** [apache/beam#22184]
### What happened?

e.g. https://ci-beam.apache.org/job/beam_SeedJob/9949/console

```
INFO:root:Generating Committers.groovy
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    generate_groovy(args.output_dir, args.ldap_uris, args.cert_path)
  File "main.py", line 53, in generate_groovy
    github_usernames=get_committers_github_usernames(
  File "main.py", line 66, in get_committers_github_usernames
    ldap.set_option(ldap.OPT_X_TLS, ldap.OPT_X_TLS_DEMAND)
AttributeError: module 'ldap' has no attribute 'OPT_X_TLS'
+ echo 'ERROR: Failed to fetch committers'
ERROR: Failed to fetch committers
```

Also affects standalone seed job (https://ci-beam.apache.org/job/beam_SeedJob_Standalone/8489/console)

### Issue Priority

Priority: 2

### Issue Component

Component: testing

**Comment by ahmedabu98** [comment]
.add-labels tests

**Comment by ahmedabu98** [comment]
.add-labels test-failures

**Comment by Abacn** [comment]
Sounds related to the recent change on pyhton-ldap package: https://pypi.org/project/python-ldap/#history

Release time coincidence with the time the job begins to fail.

**Comment by ahmedabu98** [comment]
Sounds right, release notes mentions that OPT_X_TLS is deprecated: https://github.com/python-ldap/python-ldap/releases
