### ISSUE TITLE
[Bug]: DoFn.process with @yields_batches produces PCollection with incorrect element_type

### ISSUE THREAD

**Issue by TheNeuralBit** [apache/beam#22197]
### What happened?

When determining the element_type for the PCollection output from a DoFn.process with `@yields_batchhes`, we incorrectly use the _batch_ typehint. This affects Beam 2.40.0.

Relates to #21656
Part of #21650

For example: when applying a DoFn like:

```py
class ElementToBatchDoFn(beam.DoFn):                                            
   @beam.DoFn.yields_batches                                                     
   def process(self, element: int) -> Iterator[List[int]]:      
     yield [element] * element                                                   
                                                                                 
   def infer_output_type(self, input_element_type):                              
     return input_element_type 
```

We indicated that the output PCollection has `element_type` `List[int]` (the batch type), instead of `int` (the element type).

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

**Comment by kileys** [comment]
@TheNeuralBit Will you be able to finish this by release cut (7/27) with oncall and Beam Summit?

**Comment by TheNeuralBit** [comment]
Yeah, the fix is ready. I just need to address review comments. Thanks for checking!
