### ISSUE TITLE
[Task]: Document pytorch version support 

### ISSUE THREAD

**Issue by TheNeuralBit** [apache/beam#22206]
### What needs to happen?

We currently test with multiple minor versions of pytorch, we should document the supported versions per Beam version somewhere. Maybe on the pytorch model handler's docstrings, that way it will be released with Python API docs, which are already indexed by Beam version.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

**Comment by TheNeuralBit** [comment]
Part of #21435

**Comment by TheNeuralBit** [comment]
We should also document the p[rocess for adding support for new pytorch versions, which should include updating the documentation.

**Comment by BjornPrime** [comment]
.take-issue

**Comment by BjornPrime** [comment]
.close-issue
