### ISSUE TITLE
[Playground] Result filter bug

### ISSUE THREAD

**Issue by miamihotline** [apache/beam#22214]
### What happened?

Steps to reproduce: 
1. Select an example 
2. Press the 'Run' button
3. Wait for results
4. In result filter select 'Output' option
5. Press the 'Run' button again

Expected behaviour:
Filter uses previously selected option 'Output' and user sees only the outputs.

Now:
The filter resets its state and user sees both logs and outputs.

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by miamihotline** [comment]
.take-issue

**Comment by alexeyinkin** [comment]
.take-issue
