### ISSUE TITLE
[Feature Request]: Override external SDK container URLs for Dataflow by default in Java SDK

### ISSUE THREAD

**Issue by ihji** [apache/beam#22229]
### What would you like to happen?

Override external SDK container URLs for Dataflow by default in Java SDK so users don't need to manually specify `--sdkHarnessContainerImageOverrides` for Java cross-language pipelines using Python transforms.

### Issue Priority

Priority: 2

### Issue Component

Component: cross-language

**Comment by robertwb** [comment]
Why would the user have to manually (or automatically) specify this?

**Comment by kennknowles** [comment]
@chamikaramj what do you think of this?

**Comment by chamikaramj** [comment]
I think this is done. Users do not have to specify "sdkHarnessContainerImageOverrides" when using Java multi-language on Dataflow with released Beam.
