### ISSUE TITLE
[Task]: Support newer version of google-cloud-recommendations-ai 

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#22287]
### What needs to happen?

We currently pin google-cloud-recommendations-ai to 0.2.0, see:  https://github.com/apache/beam/blob/64bcc7df2b86b9a531591a5f907e245f1af7998d/sdks/python/setup.py#L284

1) This version was released more than a year ago and it is the only package in our dependency chain that requires google-api-core 1.x. This causes dependency resolution issues when using newer versions of other client libraries. Let's try to up this bound to 

  `google-cloud-recommendations-ai<0.8.0` and adjust the lower bound if necessary

2) Upper bound should have not be inclusig

Let's try to fix this before next beam release (to be cut on July 27).

### Issue Priority

Priority: 1

### Issue Component

Component: io-py-gcp

**Comment by tvalentyn** [comment]
cc: @bjornprime

**Comment by BjornPrime** [comment]
.take-issue
