### ISSUE TITLE
[Task]: Develop complexity indicator for examples on Playground frontend application

### ISSUE THREAD

**Issue by VladMatyunin** [apache/beam#22339]
### What needs to happen?

In catalog of examples users can see complexity of each example varying from simple, medium and advanced

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by miamihotline** [comment]
.take-issue

**Comment by alexeyinkin** [comment]
.take-issue

**Comment by Malarg** [comment]
.take-issue
