### ISSUE TITLE
[Task]: Move Playground catalog info loading to read examples from Datastore instead of GCS

### ISSUE THREAD

**Issue by VladMatyunin** [apache/beam#22335]
### What needs to happen?

Currently Playground loads data about examples from GCS buckets. Since the catalog will be moved from GCS storage to Datastore, we need to update endpoints and caching mechanism to load the data from Datastore.

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by vchunikhin** [comment]
.take-issue
