### ISSUE TITLE
[Task]: Modify examples for Playground, add Tags to examples

### ISSUE THREAD

**Issue by VladMatyunin** [apache/beam#22338]
### What needs to happen?

For all current Playground examples add new field to meta information: tag

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by olehborysevych** [comment]
Tags are committed to feature branch see
https://github.com/akvelon/beam/commit/5fb6b219272e5a0f07049d29d1c91a665d4dd951 for details
