### ISSUE TITLE
[Task]: Modify Playground examples parser to collect complexity of examples, modify endpoints to provide complexity info

### ISSUE THREAD

**Issue by VladMatyunin** [apache/beam#22340]
### What needs to happen?

Depends on:
- #22341 
- #22339

Requirements:
- [ ] Modify 'Deploy Examples' scripts to parse new field 'complexity' from meta-info place
- [ ] Modify endpoints GetPrecompiledObjects, GetPrecompiledObject to include new field 'complexity'
- [ ] Add new property 'complexity' to proto files
- [ ] Add new migration to describe adding new field 'complexity'
- [ ] Unit tests for 'complexity' field

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by miamihotline** [comment]
.take-issue

**Comment by vchunikhin** [comment]
.take-issue

**Comment by vchunikhin** [comment]
.take-issue
