### ISSUE TITLE
[Task]: Implement filtering of Playground catalog to not include web-site examples in the catalog

### ISSUE THREAD

**Issue by VladMatyunin** [apache/beam#22352]
### What needs to happen?

Implement filtering of Playground catalog to not include web-site examples in the catalog
TBD: clarifying requirements

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by rshamunov** [comment]
Static Apache Beam code snippets to be replaced with Playground embeddings. (e.g. https://beam.apache.org/get-started/try-apache-beam/). Such snippets should be stored in examples catalog, but they shouldn't be visible for Playground users (https://play.beam.apache.org/)
