### ISSUE TITLE
[Task]: Add support for loading multiple snippets via query string for Playground

### ISSUE THREAD

**Issue by VladMatyunin** [apache/beam#22353]
### What needs to happen?

Current state:
- Currently Embedded Playground can load only 1 code snippet for 1 SDK. 

Requirements:
- After embedding Playground to Apache Beam web-site, we need to load an example for each SDK. When user switches between SDKs, Playground reads the examples from its state and presents the code (instead of reloading the example for switched SDK).

This task depends on state preservation feature:
- #22430 

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by alexeyinkin** [comment]
.take-issue

**Comment by alexeyinkin** [comment]
Made in #22735
