### ISSUE TITLE
[Task]: Develop Hugo shortcodes to embed playground with specific snippets

### ISSUE THREAD

**Issue by VladMatyunin** [apache/beam#22354]
### What needs to happen?
Develop Hugo shortcode to embed Playground to web-site. Example of the shortcode is presented in the comments below.
Requirements:
- Maintainer of the web-site can insert the shortcode of the Playground to one of the pages. Web-site displays the snippet in Playground frame.
- Assumption: The snippet is a Playground example, that is inserted to Playground Datastore and can be loaded to the editor.
- Shortcode may have a snippet for each of the SDKs: in this task we need to implement only saving of the snippet to Playground state. The switching of the SDK is described in issue #22362 

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by alexeyinkin** [comment]
.take-issue
