### ISSUE TITLE
[Task]: Support switching SDK on JS iframe messages for Playground

### ISSUE THREAD

**Issue by VladMatyunin** [apache/beam#22362]
### What needs to happen?
This task is targeted to improve embedded Playground, so that maintainers of Apache Beam web-site can integrate it to the web-site by replacing static snippets with Playground. The following requirements are observed:

1. Language switching is still managed in the outer page with current jQuery tabs. This maintains the existing language switching mechanics and the language preservation.
2. When the user switches the language, the website sends a JS message (with postMessage function) to Playground instances to trigger them to change the language. The embedded Playground does not contain its own SDK switch.

Main requirement:
- Playground needs to be able to receive and handle JS messages. 
- Playground can handle change SDK message

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by alexeyinkin** [comment]
.take-issue
