### ISSUE TITLE
[Feature Request]: Allow sideinput for batch DoFn

### ISSUE THREAD

**Issue by alex4adeo** [apache/beam#22411]
### What would you like to happen?

When using `.side_inputs(...)` in a ParDo with a DoFn using process_batch, we get : 

`DoFn <__main__....> has unsupported process_batch method parameter SideInputParam`

Why can't we get access to the sideinput from inside the process_batch function ?

in sdks/python/apache_beam/runners/common.py
in _validate_process_batch

```
  # Fallback to catch anything not explicitly supported
      if not d in (core.DoFn.WindowParam,
                   core.DoFn.TimestampParam,
                   core.DoFn.PaneInfoParam):
        raise ValueError(
            f"DoFn {self.do_fn!r} has unsupported process_batch "
            f"method parameter {d}")
```

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

**Comment by tvalentyn** [comment]
over to @TheNeuralBit to triage.

**Comment by TheNeuralBit** [comment]
Thanks for feedback @alex4adeo, it's good to know what users are trying to do. Let's track this under #21653 (SideInputs are a per-key param).
