### ISSUE TITLE
[Bug]: Python streaming LoadTests failing since July 8

### ISSUE THREAD

**Issue by TheNeuralBit** [apache/beam#22422]
### What happened?

https://ci-beam.apache.org/job/beam_LoadTests_Python_ParDo_Dataflow_Streaming/

```
06:01:37                      [--input_options INPUT_OPTIONS] [--timeout_ms TIMEOUT_MS]
06:01:37                      [--iterations ITERATIONS]
06:01:37                      [--number_of_counter_operations NUMBER_OF_COUNTER_OPERATIONS]
06:01:37                      [--number_of_counters=0 NUMBER_OF_COUNTERS=0]
06:01:37 pardo_test.py: error: argument --number_of_counters=0: expected one argument
```

### Issue Priority

Priority: 1

### Issue Component

Component: build-system

**Comment by TheNeuralBit** [comment]
Looks like this started with https://github.com/apache/beam/commit/20949a9d0842e1bd397a17cc0e49de100fa1b29b,

**Comment by TheNeuralBit** [comment]
This is a gross one.

The problem is the space in the argument `--experiments=use_runner_v2, shuffle_mode=appliance`

shuffle_mode=appliance is being interpreted as a separate argument because there's a space and it's not quoted. Then after we [parse the known arguments](https://github.com/apache/beam/blob/79db4d25cc83d5d4890556b28072d801badd430d/sdks/python/apache_beam/options/pipeline_options.py#L317) we're left with the unknown_args:

```
['--iterations=10', '--number_of_counter_operations=0', '--number_of_counters=0', 'shuffle_mode=appliance']
```

The [logic](https://github.com/apache/beam/blob/79db4d25cc83d5d4890556b28072d801badd430d/sdks/python/apache_beam/options/pipeline_options.py#L326) interprets shuffle_mode=appliance as the argument for an option with name `number_of_counters=0`.

We can fix by changing `use_runner_v2, shuffle_mode=appliance`, `use_runner_v2,shuffle_mode=appliance`, or nmore generally by adding quoting logic in LoadTestsBuilder.groovy. We should also adjust the retain_unknown_options logic. It's bad that it assumes the arguments are consecutive.

**Comment by tvalentyn** [comment]
cc: @robertwb
