### ISSUE TITLE
[Task]: Remove BeamSummit Banner from Website

### ISSUE THREAD

**Issue by brucearctor** [apache/beam#22424]
### What needs to happen?

There is a "BeamSummit" Banner on beam.apache.org which announced the Beam Summit which has passed.  

Please remove this banner.

Looks like was created in this PR:  https://github.com/apache/beam/commit/4fa5c43fa89c6c6be4cbaca94f851c56f77335c0 ...  Looks like that *might* be just the Playground.  So, more to look at for the 'regular' website.  

I aim to 'fix' this on the workshop on contributing to OSS on 24 July 2022.  If this is not fixed/closed by then, then anyone please address.  

### Issue Priority

Priority: 2

### Issue Component

Component: website

**Comment by pabloem** [comment]
thanks for filing this. I don't know, but I don't see the banner anymore...

**Comment by brucearctor** [comment]
agreed that banner is gone ... but how?  Since we'll want a banner in the future, I'd like to know where/how that was changed, to make it easy for whoever might address in the future.  Let's track that down.

**Comment by alexeyinkin** [comment]
The website banner was removed in 33dc35fd553a02c0be8b9ad183889ee0cf9e620f

**Comment by brucearctor** [comment]
Addressed by https://github.com/apache/beam/commit/33dc35fd553a02c0be8b9ad183889ee0cf9e620f

**Comment by brucearctor** [comment]
thanks, @alexeyinkin !
