### ISSUE TITLE
[Bug]: Python Streaming Combine load tests on Dataflow are timing out

### ISSUE THREAD

**Issue by TheNeuralBit** [apache/beam#22436]
### What happened?

https://ci-beam.apache.org/job/beam_LoadTests_Python_Combine_Dataflow_Streaming/700/

These tests are being aborted after 2 hours.

### Issue Priority

Priority: 1

### Issue Component

Component: build-system

**Comment by TheNeuralBit** [comment]
These were failing for a while due to #22422, now that that's been resolved they've gone back to their previous state: timing out.

**Comment by TheNeuralBit** [comment]
@tvalentyn is it possible there's a bug that's causing these jobs to hang? Or is it more likely that we actually just need to bump the timeout?

**Comment by tvalentyn** [comment]
it is possible, i'd look at earlier runtime and consider bisection

**Comment by TheNeuralBit** [comment]
Ack, I'll look into bisecting. Unfortunately the last passing run still in Jenkins history is in September 2020. That one took 54 minutes: https://ci-beam.apache.org/job/beam_LoadTests_Python_Combine_Dataflow_Streaming/30/

**Comment by tvalentyn** [comment]
ok, that's way too long ago to block the release.

**Comment by TheNeuralBit** [comment]
Yeah, I suppose it's possible that there was a passing run since then that was deleted, but IIUC Jenkins tries to keep the log for the last successful run indefinitely.

**Comment by TheNeuralBit** [comment]
Sending #22436 to bump the timeout and get these running again. The possible regression can be investigated separately.
