### ISSUE TITLE
[Task]: Update Pytest to support Python 3.10

### ISSUE THREAD

**Issue by AnandInguva** [apache/beam#22471]
### What needs to happen?

Update Pytest >= 6.2.5 to support Python 3.10 for Apache Beam Python SDK.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

**Comment by AnandInguva** [comment]
.take-issue

**Comment by AnandInguva** [comment]
`Run XVR_JavaUsingPython_Dataflow PostCommit` was failing with the Pytest update.  This gradle task runs on two times sequentially, with Python 3.7 and with Python 3.9 respectively. 

When Pytest gets updated, the gradle task `:sdks:python:setupVirtualenv` runs only for Python 3.7 and when python 3.9 runs, `:sdks:python:setupVirtualenv` didn't run and it uses the cache from the previous Python run(I suspect this because, next to gradle task it says `UP-TO-DATE` but it shouldn't).

**Comment by AnandInguva** [comment]
.close-issue

**Comment by svetakvsundhar** [comment]
```When Pytest gets updated, the gradle task :sdks:python:setupVirtualenv runs only for Python 3.7 and when Python 3.9 runs, :sdks:python:setupVirtualenv didn't run and it uses the cache from the previous Python run(I suspect this because, next to gradle task it says UP-TO-DATE but it shouldn't). This behavior is only observed when Pytest is updated from 4.6 to a version>=6.2.5.```

>> @AnandInguva I'm currently observing this issue with Python 3.9 and PyTest 7.1.2. Is the current workaround to upgrade to Python 3.10?
