### ISSUE TITLE
[Task]: Prepare Kubernetes templates for backend services of Playground

### ISSUE THREAD

**Issue by VladMatyunin** [apache/beam#22488]
### What needs to happen?

Requirements

1. define the Kubernetes nodes
2. create the YAML file with description of deployments for Go
3. create the YAML file with description of deployments for Java
4. create the YAML file with description of deployments for Python
5. create the YAML file with description of deployments for SCIO
6. create the YAML file with description of deployments for Router

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by MakarkinSAkvelon** [comment]
.take-issue
