### ISSUE TITLE
[Feature Request]: As a Playground user, I want to have a code editor with advanced features (collapse, read-only blocks etc)

### ISSUE THREAD

**Issue by VladMatyunin** [apache/beam#22496]
### What would you like to happen?

- [ ] Autocompletion for Beam symbols, dictionary based
- [ ] Read-only blocks
- [ ] Hotkeys
- [ ] Per-language highlighting
- [ ] Collapse / uncollapse code blocks

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by alexeyinkin** [comment]
.take-issue

**Comment by rshamunov** [comment]
Autocompletion for Beam symbols, dictionary based:

- [ ] 23917
- [ ] 23918
- [ ] 23919

**Comment by rshamunov** [comment]
Implemented
