### ISSUE TITLE
[Task]: Redeploy infrastructure of Playground to fix terraform state

### ISSUE THREAD

**Issue by VladMatyunin** [apache/beam#22490]
### What needs to happen?

Terraform state of Playground stored in GCS bucket has some missing variables. This blocks automatic deployment via terraform apply. We need to redeploy the infrastructure to fix the state.

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by MakarkinSAkvelon** [comment]
.take-issue

**Comment by rshamunov** [comment]
Not requires anymore since we moved to GKE clusters
