### ISSUE TITLE
[Tour of Beam] [Task] Learning content for "Common Transforms" module

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#22499]
### What needs to happen?
Create learning content and challenge for "Tour of Beam"::"Basic Transforms" module consisting of following unit:

- Common Transforms / Filter
- Common Transforms / Aggregation / Count
- Common Transforms / Aggregation / Sum
- Common Transforms / Aggregation / Mean
- Common Transforms / Aggregation / Min
- Common Transforms / Aggregation / Max
- Common Transforms / WithKeys
- Challenge/New motivating example (Numbers-based)

### Issue Priority
Priority: 3

**Comment by sirenbyte** [comment]
.take-issue
