### ISSUE TITLE
[Tour of Beam] [Task] Learning content for "Core Transforms" module

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#22500]
### What needs to happen?

Create learning content and challenge for Tour of Beam::Core Transforms module consisting of following units:

- Core Transforms/Map/Map Elements
- Core Transforms/Map/FlatMapElements
- Core Transforms/Map/ParDo one-to-one
- Core Transforms/Map/ParDo one-to-many
- Core Transforms/Map/GroupByKey
- Core Transforms/Combine/Combine PerKey
- Core Transforms / Branching
- WordCount Motivating Example
- Core Tranforms Challenge 1: Map - Lowercase Aggregation
- Core Tranforms Challenge 2: ParDo - Breaking Lines into Words
- Core Tranforms Challenge 3: Flat - Prefix Aggregation
- Partition
- Composite
- Flatten
- Side Input
- Multiple outputs

### Issue Priority
Priority: 3

**Comment by olehborysevych** [comment]
.take-issue

**Comment by sirenbyte** [comment]
.take-issue

**Comment by sirenbyte** [comment]
.take-issue
