### ISSUE TITLE
[Tour of Beam] [Task] Learning content for "IO Connectors" module

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#22511]
### What needs to happen?
Create learning content and challenge for Tour of Beam::IO Connectors module consisting of following unit:

- IO / TextIO (Local File)
- IO / TextIO (Google Cloud Storage)
- IO / KafkaIO
- IO / BigQueryIO / Read / Table
- IO / BigQueryIO / Read / Query
- IO / BigQueryIO / Write / Using a TableSchema
- IO / BigQueryIO / Write / Using Beam Schema
- IO / REST APIs
- IO / Motivating Example/Challenge

### Issue Priority
Priority: 3

**Comment by mengzhongtian** [comment]
a
