### ISSUE TITLE
[Bug]: Home page. Icons and information in the section Apache Beam Features cut off at page size 337.60px x 693.6px

### ISSUE THREAD

**Issue by alevtinaboiko** [apache/beam#22522]
### What happened?

Steps:

1. Open the website https://beam.apache.org/
2. Change the screen size to  337.60px x 693.6px
3. Look at the icons and information in the section Apache Beam Features

Actual result: Icons and information in the section Apache Beam Features cut off at page size 337.60px x 693.6px
![image](https://user-images.githubusercontent.com/85677902/181702395-24d59414-f087-4d95-b199-ffb3c57f9243.png)

Expected result: Icons and information in the section Apache Beam Features aren't cut off 

### Issue Priority

Priority: 1

### Issue Component

Component: beam-model

**Comment by bullet03** [comment]
.take-issue
