### ISSUE TITLE
[Bug]: Contact us page. The link commits@beam.apach.org moves to https://s.apache.org/beam-slack-channel

### ISSUE THREAD

**Issue by alevtinaboiko** [apache/beam#22520]
### What happened?

Steps:
1. Open the website https://beam.apache.org/
2. Click on the button "Contact Us" in the Footer
3. Find the section "Available contact channels"
4. Find the line with purpose "Firehose of build notifications from Jenkins"
5. Click on the link "commits@beam.apache.org" in CHANNEL column

Actual result: The page with address "https://the-asf.slack.com/?redir=%2Fmessages%2FC9H0YNP3P%2F" opens 
Expected result: The page with address "https://lists.apache.org/list.html?commits@beam.apache.org" opens 

### Issue Priority

Priority: 1

### Issue Component

Component: beam-model

**Comment by bullet03** [comment]
.take-issue
