### ISSUE TITLE
[Bug]: Incorrect address after clicking on the "Get Started"

### ISSUE THREAD

**Issue by alevtinaboiko** [apache/beam#22523]
### What happened?

Steps:

1. Open the website 
2. Click on the button "Get Started" in the navbar

Actual result: After clicking on the button "Get started" the page "https://beam.apache.org/get-started/beam-overview/" opens
Expected result: After clicking on the button "Get started" the page https://beam.apache.org/get-started  opens

### Issue Priority

Priority: 1

### Issue Component

Component: beam-model

**Comment by bullet03** [comment]
.take-issue

**Comment by rszper** [comment]
This is a duplicate of https://github.com/apache/beam/issues/21537

There already a PR with a fix: https://github.com/apache/beam/pull/23490

**Comment by rszper** [comment]
.close-issue
