### ISSUE TITLE
[Feature Request][python]: Better typing support for TimestampedValue

### ISSUE THREAD

**Issue by jonathanasdf** [apache/beam#22547]
### What would you like to happen?

Currently transforms that return a TimestampedValue need to be typed as plain "TimestampedValue" rather than generic "TimestampedValue[T]" so all underlying information about what type is being wrapped is lost.

### Issue Priority

Priority: 3

### Issue Component

Component: sdk-py-core

**Comment by jonathanasdf** [comment]
Sorry - yes that is a good rephrasing.

**Comment by liferoad** [comment]
.take-issue
