### ISSUE TITLE
[Bug]: PubsubMessage should be renamed to PubSubMessage to reduce confusion

### ISSUE THREAD

**Issue by aaltay** [apache/beam#22578]
### What happened?

Beam has PubsubMessage PubSubMessage PubsubMessages. The use is inconsistent and confusing. It would be good to use a standard naming scheme. (PubSubMessage seems to be the correct version based on the product name.)

This might require a breaking change, and if that it is the case we might need to hold on until the next major version.

### Issue Priority

Priority: 3

### Issue Component

Component: io-java-gcp

**Comment by Amar3tto** [comment]
FYI @aaltay

**Comment by aaltay** [comment]
Thank you for the analysis @Amar3tto. I think this is still an inconsistency and an issue. But I understand your point, it may not be feasible to address this. In that case we can close this as won't fix / infeasible.
