### ISSUE TITLE
[Bug]: Java Unit Tests fail to find gradle

### ISSUE THREAD

**Issue by kileys** [apache/beam#22590]
### What happened?

* Where:
Settings file 'D:\a\beam\beam\settings.gradle.kts' line: 20

* What went wrong:
Plugin [id: 'com.gradle.enterprise', version: '3.4.1', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.gradle.enterprise:com.gradle.enterprise.gradle.plugin:3.4.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository

https://github.com/apache/beam/runs/7677755961?check_suite_focus=true

### Issue Priority

Priority: 2

### Issue Component

Component: testing

**Comment by kileys** [comment]
@yeandy FYI

**Comment by damccorm** [comment]
Looks like this is still happening - https://github.com/apache/beam/actions/runs/3147702124/jobs/5117449016

**Comment by kennknowles** [comment]
Browsing https://github.com/apache/beam/actions/workflows/java_tests.yml?page=2&query=event%3Aschedule I don't see this happening any more.
