### ISSUE TITLE
[Bug]: Java PostCommit failure for testWithShardedKeyInGlobalWindow

### ISSUE THREAD

**Issue by yeandy** [apache/beam#22592]
### What happened?

See a failure for this [run](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/2544/) for the `beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming` test
```
06:27:54 org.apache.beam.sdk.transforms.GroupIntoBatchesTest > testWithShardedKeyInGlobalWindow FAILED
06:27:54     java.lang.IllegalArgumentException at GroupIntoBatchesTest.java:332
```

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-java-core

**Comment by TheNeuralBit** [comment]
It doesn't look like there's an appropriate "Uses" annotation we can add here. I think we just need to add the exclusion here: https://github.com/apache/beam/blob/c8d92b03b6b2029978dbc2bf824240232c5e61ac/runners/google-cloud-dataflow-java/build.gradle#L394
