### ISSUE TITLE
[Feature Request]: Update cibuildwheel to latest version for building wheels

### ISSUE THREAD

**Issue by AnandInguva** [apache/beam#22637]
### What would you like to happen?

RIght now, the beam python sdk uses `cibuildwheel==1.11.0` that use get-pip.py to install the PyPI dependencies. There has been some issues related to `get-pip.py`, setuptools>=60.0 and distutils, which causes the RC wheels build to fail. 

As of now, the workaround has been added at  https://github.com/apache/beam/pull/22636  and https://github.com/apache/beam/pull/22635 by introducing the environment variable `SETUPTOOLS_USE_DISTUTILS=stdlib`. This can be removed once the `cibuildwheel` gets updated to a latest version. 

`cibuildwheel` is not updated as part of the solution because it was taking so much time to build the aarch wheels and it causes time outs while building the RC wheels. 

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

**Comment by AnandInguva** [comment]
related PRs: https://github.com/apache/beam/pull/22635, https://github.com/apache/beam/pull/22635

**Comment by tvalentyn** [comment]
Is this completed?

**Comment by AnandInguva** [comment]
.close-issue
