### ISSUE TITLE
[Bug]: Home page. Stay Up To Date with Beam. Upcoming events out of frame at page size 366.40px x 693.6px

### ISSUE THREAD

**Issue by alevtinaboiko** [apache/beam#22694]
### What happened?

Steps to reproduce:
1. Open the website https://beam.apache.org/
2. Change the screen size to 366.40px x 693.6px
3. Look at Upcoming events in the section Stay Up To Date with Beam

Actual result: Upcoming events out of frame at page size 366.40px x 693.6px
https://dl.dropboxusercontent.com/s/2vgxn28343b59hj/sBNxyQl192.mp4
Expected result: Upcoming events doesn't out of frame

### Issue Priority

Priority: 3

### Issue Component

Component: beam-model

**Comment by bullet03** [comment]
.take-issue
