### ISSUE TITLE
[Bug]: Contact us. The Action of the purpose "Contact users and contributors in real time through the ASF slack workspace" contains  the word "#general" without the link

### ISSUE THREAD

**Issue by alevtinaboiko** [apache/beam#22696]
### What happened?

Steps to reproduce: 

1. Open the website page [Community](https://beam.apache.org/community/)
2. Click on the button "Contact US" in the navbar or footer
3. Find the section "Available contact channels"
4. Look at the Action of the purpose "Contact users and contributors in real time through the ASF slack workspace"

Actual result: The action contains the word "#general" without the link
Expected result: The action contains the word "#general" with the link

ASF Slack - #general was renamed to #announcements. 

### Issue Priority

Priority: 0

### Issue Component

Component: beam-model

**Comment by AKosolapov** [comment]
@bullet03 Since ASF #general was renamed to #announcements "Don’t ask Beam questions in #general. We don’t monitor it." looks like not applicable anymore. Propose that we remove this sentence.
![image](https://user-images.githubusercontent.com/11856181/184241169-10429a8a-8eb1-4bb7-b8c6-60705be25e7a.png)

**Comment by TheNeuralBit** [comment]
Per https://beam.apache.org/contribute/issue-priorities/ definition of P0:
> An outage means that some piece of infrastructure that the community relies on is down

I don't think this meets that bar.

Any interest in sending a PR to address this? The relevant code is here:
- https://github.com/apache/beam/blob/master/website/www/site/content/en/community/contact-us.md
- https://github.com/apache/beam/blob/master/website/www/site/data/en/contact_us.yaml

**Comment by bullet03** [comment]
.take-issue
