### ISSUE TITLE
[Bug]: The item "Contact Us" displayed  is in the Resources block of the footer

### ISSUE THREAD

**Issue by alevtinaboiko** [apache/beam#22695]
### What happened?

Steps to reproduce:

1. Open the website https://beam.apache.org/ 
2. Looka at the footer 
3. Find the Resources block
4. Click on the button "Contact US" in the Resources

Actual result: The address is community/contact-us/ when the "Contact Us" is in the Resources block of the footer
Expected result: The item "Contact Us" should be in the Community block of the footer

### Issue Priority

Priority: 3

### Issue Component

Component: beam-model

**Comment by chethanagopinath** [comment]
.take-issue

**Comment by chethanagopinath** [comment]
I'm not totally sure how to request reviews for my PR for this, could anybody help me out? Thanks.

**Comment by Saifuddin53** [comment]
.take-issue

**Comment by chethanagopinath** [comment]
@riteshghorse I know this is probably late to ask, but was wondering if there's a different way to tag reviewers for a PR. I had mine up for the same issue for a very long time, it got stale and closed. And then picked up by the next person and merged. Just wondering for the future.

**Comment by Saifuddin53** [comment]
You just had to mail to the apache beam developers email for requesting to review your PR @chethanagopinath chethanagopinath

**Comment by riteshghorse** [comment]
We now have a PR bot that tags reviewer automatically after all checks turn green so you may need not to mail the dev list.
@chethanagopinath So sorry that your PR went stale.
