### ISSUE TITLE
[Bug]: Navigation bar overlaps footer when there is little information on the page

### ISSUE THREAD

**Issue by alevtinaboiko** [apache/beam#22698]
### What happened?

Steps to reproduce:
1. Open the website [page](https://beam.apache.org/documentation/sdks/python-dependencies/)
2. Scroll to the bottom of the page
3. Look at the navigation bar

Actual result: Navigation bar overlaps footer when there is little information on the page
Expected result: Navigation bar doesn't overlap footer when there is little information on the page

### Issue Priority

Priority: 3

### Issue Component

Component: beam-model

**Comment by tvalentyn** [comment]
cc: @rszper who might be able to help.

**Comment by pcoet** [comment]
@bullet03 Is this something you can help with?

**Comment by bullet03** [comment]
.take-issue

**Comment by bullet03** [comment]
> @bullet03 Is this something you can help with?

Yes, sure. I'm working on it.
