### ISSUE TITLE
[Bug]: Page "I/O Connectors". In the browser Firefox Multi-language-pipelines link moves to relative path but  not in the place on the page with title "13. Multi-language pipelines" 

### ISSUE THREAD

**Issue by alevtinaboiko** [apache/beam#22699]
### What happened?

Steps to reproduce:

1. [Open the website](https://beam.apache.org/) in the browser Firefox
2. Click on the button "Documentation" in the navbar
3. Cick on the item I/O Connectors in the list
4. Find the title "I/O Connectors"
5. Click on the link "multi-language pipelines framework"

Actual result: The page opens with the address /documentation/programming-guide/#multi-language-pipelines and in the place with footer https://dl.dropboxusercontent.com/s/vzvhckysfd7gsof/kr0CPs301X.mp4
Expected result: The page opens with the address /documentation/programming-guide/#multi-language-pipelines and in the place on the page with title "13. Multi-language pipelines"

### Issue Priority

Priority: 0

### Issue Component

Component: beam-model

**Comment by bullet03** [comment]
.take-issue
