### ISSUE TITLE
[Bug]: KafkaIO.withCheckStopReadingFn does not work

### ISSUE THREAD

**Issue by johnjcasey** [apache/beam#22715]
### What happened?

If a check stop reading function is provided to the SDF Kafka IO implementation, and that function ever returns true, it will result in a failed check in the Offset based restriction tracker.

`Caused by: java.lang.IllegalStateException: Last attempted offset should not be null. No work was claimed in non-empty range [5, 9223372036854775807).`

It appears that this feature has never worked, and will need to be redesigned and reimplemented

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-kafka

**Comment by Abacn** [comment]
.take-issue

**Comment by Abacn** [comment]
Sorry, commented to wrong issue

**Comment by johnjcasey** [comment]
this has been fixed, see #22962
