### ISSUE TITLE
[Bug]: Unable to set flex template use_public_ips=False for workers

### ISSUE THREAD

**Issue by bahmandar** [apache/beam#22727]
### What happened?

Running a command like this
```
gcloud dataflow flex-template run <job-name> \
--template-file-gcs-location <template-location> \
--parameters ^~^uris=gs://test-file-location ~use_public_ips=false
```
```
ERROR: (gcloud.dataflow.flex-template.run) INVALID_ARGUMENT: The template parameters are invalid. Details:
use_public_ips: Unrecognized parameter
- '@type': type.googleapis.com/google.dataflow.v1beta3.InvalidTemplateParameters
  parameterViolations:
  - description: Unrecognized parameter
    parameter: use_public_ips
- '@type': type.googleapis.com/google.rpc.DebugInfo
  detail: |-
    [ORIGINAL ERROR] generic::invalid_argument: The template parameters are invalid. Details:
    use_public_ips: Unrecognized parameter [google.rpc.error_details_ext] { message: "The template parameters are invalid. Details: \nuse_public_ips: Unrecognized parameter" details { type_url: "type.googleapis.com/google.dataflow.v1beta3.InvalidTemplateParameters" value: "\n(\n\016use_public_ips\022\026Unrecognized parameter" } } 54820903 { 1 { 1 { 1: "cloud/dataflow/router/services/templates/flex_template_handler.cc" 2: 130 } } }
```

Adding --disable-public-ips outside of parameters will cause both the flex container and the sdk container to not have public ips. This causes install issues because we only want the workers to not have public ips.

I suspect it is related to not being able to explicitly set `use_public_ips=true`

### Issue Priority

Priority: 2

### Issue Component

Component: infrastructure

**Comment by damccorm** [comment]
Hey, sorry for the slow response here. This looks like an issue with the dataflow templates service, not Beam itself. Could you please open an issue in https://github.com/GoogleCloudPlatform/DataflowTemplates/issues

**Comment by bahmandar** [comment]
No problem. Here is the new issue for posterity:

https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/512
