### ISSUE TITLE
[Bug]: beam_PostCommit_Java_ValidatesRunner_Spark

### ISSUE THREAD

**Issue by johnjcasey** [apache/beam#22758]
### What happened?

beam_PostCommit_Java_ValidatesRunner_Spark's teardown tests are flaky.

We see irregular time outs with several tests, 
org.apache.beam.sdk.transforms.ParDoLifecycleTest.testTeardownCalledAfterExceptionInFinishBundle
org.apache.beam.sdk.transforms.ParDoLifecycleTest.testTeardownCalledAfterExceptionInProcessElement

The irregularity suggests that either the timeout should be a bit longer, or there is an issue causing teardown to take more time than expected

### Issue Priority

Priority: 2

### Issue Component

Component: runner-spark

**Comment by mosche** [comment]
Duplicate of https://github.com/apache/beam/issues/23709
