### ISSUE TITLE
[Bug][GoSDK] exec/translate.go:531 panics when first type assertion fails

### ISSUE THREAD

**Issue by jeffreyoldham** [apache/beam#22766]
blob/master/sdks/go/pkg/beam/core/runtime/exec/translate.go:531 contains a double type assertion but only the latter is checked for correctness.  If the former fails, the pipeline incorrectly panics.  The revised code should be:

```go
if pc, ok := ma.Out.(*PCollection); ok {
						if eo, ok := pc.Out.(*ExtractOutput); ok {
							// Strip PCollections from between MergeAccumulators and ExtractOutputs
							// as it's a synthetic PCollection.
							b.units = b.units[:len(b.units)-1]
							ma.Out = eo
						}
					}
```

**Comment by lostluck** [comment]
Further context: The user ran a pipeline with a lifted combiner with all fusion optimizations disabled, causing transforms that are usually merged together to not be.
