### ISSUE TITLE
[Task]: Update bigquery dependency for python SDK

### ISSUE THREAD

**Issue by davidvanrooij** [apache/beam#22857]
### What needs to happen?

The package `google-cloud-bigquery` was released on Mar 29 earlier this year and the beam package has yet to upgrade this dependency to the latest version and is explicitly pinned to a lower version:

https://github.com/apache/beam/blob/ddfb6907288369bfc71c3a310cb9ceb717a4d3a0/sdks/python/setup.py#L283

This dependency was last updated in https://github.com/apache/beam/commit/efaea052733ba41c1023fac2d29eab473c8488b8

### Issue Priority

Priority: 2

### Issue Component

Component: dependencies

**Comment by amardeep** [comment]
Looks like this got updated in https://github.com/apache/beam/commit/bb7468ff13683dd82cfe97dff31d82c5a34024c6

**Comment by kennknowles** [comment]
OK then seems like this is OK?
