### ISSUE TITLE
[Feature Request]: Better support for using Python dependencies not available in the Beam Python SDK by default

### ISSUE THREAD

**Issue by chamikaramj** [apache/beam#22859]
### What would you like to happen?

Many Python transforms used by Beam pipelines need to use new dependencies. Such dependencies usually need to be available both at job submission as well as job execution (Python SDK harness containers). For cross-language Python transforms (for example, when used by a Java pipeline), we have following workarounds for doing this.

For job submission:
* Setup a custom virtual environment with correct dependencies and startup a manual expansion service.

For job execution:
* Use a custom Beam Python container that contains correct dependencies and specify that via the `sdkHarnessContainerImageOverrides` option.
* Setting dependencies via an environment variable (TODO: add details and document).

We should simplify this by allowing users of PythonExternalTransform class to specify new dependencies. 

### Issue Priority

Priority: 2

### Issue Component

Component: cross-language

**Comment by ihji** [comment]
Another workaround: https://github.com/apache/beam/blob/master/sdks/python/apache_beam/runners/portability/expansion_service_test.py#L379
It will create and stage a custom requirement file.
