### ISSUE TITLE
[Feature Request]: Beam version compatibility (Python and Java versions should match)

### ISSUE THREAD

**Issue by chamikaramj** [apache/beam#22856]
### What would you like to happen?

Currently, when launching the Python expansion from Java we always install the latest Python SDK irrespective of the Java version. This is error prone. We should be installing a Python version that match the current Java version instead.

### Issue Priority

Priority: 2

### Issue Component

Component: cross-language

**Comment by robertwb** [comment]
Note that however we solve this, it would be nice to not break development environments (e.g. perhaps the previous version is good enough unless otherwise specified).

**Comment by chamikaramj** [comment]
Part of the issue is that the development environment will keep changing whenever a new version of Beam Python SDK is released (even for the same pipeline Java SDK version).

**Comment by chamikaramj** [comment]
Added this to 2.42.0 milestone since this could result in significant future breakages for some users.

**Comment by lostluck** [comment]
This looks like it's resolved. Marking as closed.
