### ISSUE TITLE
[Bug]: Jenkins UI doesn't display all test results for Python PostCommits

### ISSUE THREAD

**Issue by TheNeuralBit** [apache/beam#22858]
### What happened?

See https://github.com/apache/beam/issues/21859#issuecomment-1224992633 and https://github.com/apache/beam/issues/21859#issuecomment-1224592363

We run multiple test suites in different environments in Python PostCommits, but only one of them has its test results propagated to the UI. A failure in the others will still cause the job to fail, but we have to open the console log to get information about it. We should adjust the PostCommit so that all test results are elevated in the UI.

It does seem to be possible to get multiple sets of test results in the Jenkins UI, we do it in the Python PreCommit for different python versions, but I'm not sure how that works.

### Issue Priority

Priority: 2

### Issue Component

Component: infrastructure

**Comment by tvalentyn** [comment]
@AnandInguva could you please help take a look what it would take to integrate runinference test results into the rest of the postcommit?

**Comment by AnandInguva** [comment]
.take-issue

**Comment by AnandInguva** [comment]
Closing this as we are moving from Jenkins to GH actions soon.

**Comment by AnandInguva** [comment]
.close-issue
