### ISSUE TITLE
[Playground][Task]: Adding the tags field to the example response

### ISSUE THREAD

**Issue by vchunikhin** [apache/beam#22881]
### What needs to happen?

Adding the tags field to the example response

### Issue Priority

Priority: 1

### Issue Component

Component: beam-playground

**Comment by vchunikhin** [comment]
.take-issue

**Comment by TheNeuralBit** [comment]
Is P1 appropriate here? This and other playground tasks look like normal feature work, which should be categorized as P2.

**Comment by olehborysevych** [comment]
@TheNeuralBit Thank you. changed to P3. P1 was assigned by mistake. We always assign P3 for playground tasks
