### ISSUE TITLE
[Bug]: beam_PostCommit_XVR_PythonUsingJavaDataflow is flaky

### ISSUE THREAD

**Issue by jrmccluskey** [apache/beam#22891]
### What happened?

The last two failures for the [beam_PostCommit_XVR_PythonUsingJava_Dataflow test](https://ci-beam.apache.org/job/beam_PostCommit_XVR_PythonUsingJava_Dataflow/) have occurred during the `:runners:google-cloud-dataflow-java:buildAndPushDockerPythonContainer` task with the error `name unknown: Failed to get blob sizes.` This reduces the signal and reliability of the test, and should be investigated. 

### Issue Priority

Priority: 2

### Issue Component

Component: test-failures

**Comment by tvalentyn** [comment]
Over to @chamikaramj to triage,

**Comment by chamikaramj** [comment]
There seems to be a new regression. Looking.

**Comment by chamikaramj** [comment]
Seems like some of the x-lang tests are trying to run with Runner v2 now: https://ci-beam.apache.org/job/beam_PostCommit_XVR_PythonUsingJavaSQL_Dataflow/1217/testReport/junit/apache_beam.transforms.sql_test/SqlTransformTest/test_map/

Potentially something got broken by https://github.com/apache/beam/commit/8ec0568d12d495e83719848fe23c2474177b009d

@robertwb

**Comment by chamikaramj** [comment]
https://github.com/apache/beam/pull/24579 should fix the current breakage.

**Comment by lukecwik** [comment]
Thanks for figuring this out
