### ISSUE TITLE
[Bug]: beam_PostCommit_Go's TestOomParDo test is failing

### ISSUE THREAD

**Issue by jrmccluskey** [apache/beam#22892]
### What happened?

The [Go PostCommit](https://ci-beam.apache.org/job/beam_PostCommit_Go/) has had consecutive runs where the [TestOomParDo](https://github.com/apache/beam/blob/42b1640a25d5dbdea08ae2feaa0d3e81f6278575/sdks/go/test/integration/primitives/heap_dump_test.go#L31) test fails. This should be investigated as a potential flake or failure. 

### Issue Priority

Priority: 2

### Issue Component

Component: test-failures

**Comment by jrmccluskey** [comment]
CC: @damccorm

**Comment by damccorm** [comment]
Agreed!

**Comment by damccorm** [comment]
There have been failures since, but none related to this test (mostly due to Jenkins workers disconnecting). I'm going to close
