### ISSUE TITLE
[Feature Request]: Support TIMESTAMP type in BigQueryIO with BEAM_ROW output type, and in read_gbq

### ISSUE THREAD

**Issue by TheNeuralBit** [apache/beam#22909]
### What would you like to happen?

We should read BQ's Timestamp type in the read_gbq wrapper

Part of #20810

### Issue Priority

Priority: 2

### Issue Component

Component: dsl-dataframe

**Comment by svetakvsundhar** [comment]
can close this issue 🥳 (sry i dont have perms i dont think)

**Comment by TheNeuralBit** [comment]
woohoo! Thanks @svetakvsundhar
