### ISSUE TITLE
[Feature Request]: pandas.read_gbq

### ISSUE THREAD

**Issue by TheNeuralBit** [apache/beam#22907]
### What would you like to happen?

Add MVP read_gbq wrapper

### Issue Priority

Priority: 2

### Issue Component

Component: dsl-dataframe

**Comment by TheNeuralBit** [comment]
Part of #20810

**Comment by svetakvsundhar** [comment]
Hm I believe https://github.com/apache/beam/pull/22616 should fix this issue iiuc?

**Comment by TheNeuralBit** [comment]
> Hm I believe #22616 should fix this issue iiuc?

Yep!
