### ISSUE TITLE
[Bug]: Incorrect output shape in the RunInference PredictionResult object

### ISSUE THREAD

**Issue by yeandy** [apache/beam#22979]
### What happened?

Originally documented [here](https://beam.apache.org/documentation/sdks/python-machine-learning/#incorrect-inferences-in-the-predictionresult-object) in our RunInference Troubleshooting section:

For some models, the PredictionResults output might not include the correct predictions in the inferences field. This issue occurs when you use a model whose inferences return a dictionary that maps keys to predictions and other metadata. An example return type is `Dict[str, Tensor]`.

The RunInference API currently expects outputs to be an `Iterable[Any]`. Example return types are `Iterable[Tensor]` or `Iterable[Dict[str, Tensor]]`. When RunInference zips the inputs with the predictions, the predictions iterate over the dictionary keys instead of the batch elements. The result is that the key name is preserved but the prediction tensors are discarded.

To work with the current RunInference implementation, you can create a wrapper class that overrides the model(input) call. In PyTorch, for example, your wrapper would override the forward() function and return an output with the appropriate format of `List[Dict[str, torch.Tensor]]`. 

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

**Comment by yeandy** [comment]
.add-labels run-inference

**Comment by damccorm** [comment]
@yeandy is this different from #22240?

**Comment by damccorm** [comment]
Closing in favor of #22240 since its longer lived. I copied over your description from here though since I think its a little more context rich in places.

**Comment by yeandy** [comment]
Ack, thanks!
