### ISSUE TITLE
[Bug]: Double GO button in documentation/programming-guide

### ISSUE THREAD

**Issue by alevtinaboiko** [apache/beam#23004]
### What happened?

Steps to reproduce:
1. Open the website on the page 
2. Click on the item "Beam programming guide" -> "Overview" in the navbar
4. Scroll to the 3.1.1, 4.2.4.2 points
5. Look at the button Go

Actual result: Double GO button in documentation/programming-guide

![Screenshot_35](https://user-images.githubusercontent.com/85677902/188084930-617e22a6-24d8-4719-ab47-3001d8254d46.png)
Expected result: There is only one button Go

### Issue Priority

Priority: 3

### Issue Component

Component: beam-model

**Comment by alexeyinkin** [comment]
@robertwb FYI
Introduced in https://github.com/apache/beam/pull/22137
