### ISSUE TITLE
[Feature Request]: Make the Python SDK state cache a loading cache and record loading statistics

### ISSUE THREAD

**Issue by lukecwik** [apache/beam#23000]
### What would you like to happen?

The Python SDK harness state cache currently assumes that loading happens outside of the cache. This prevents a lookup strategy which blocks when multiple parties lookup the same key.

Also, the Python SDK harness state cache does not record the cost of loading a value into the cache.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-harness

**Comment by tvalentyn** [comment]
@lukecwik are you planning to work on this issue or it will need an owner?

**Comment by lukecwik** [comment]
There is an open PR already for this. I have not been able to address the PR comments for it yet.
