### ISSUE TITLE
[Bug]: setJdkAddOpenModules not work with DataflowRunner v1

### ISSUE THREAD

**Issue by takaaki7** [apache/beam#23010]
### What happened?

DataflowPipelineOptions.setJdkAddOpenModules() not work with DataflowRunner v1, but work with v2.
Is this intended behavior? If so, it should be documented.

### Issue Priority

Priority: 3

### Issue Component

Component: runner-dataflow

**Comment by kennknowles** [comment]
@kileys

**Comment by kileys** [comment]
This was fixed in 2.43.0
