### ISSUE TITLE
[Bug]: BigQueryIO.Write.Method.STORAGE_WRITE_API fails if you don’t specify the project in the destination.

### ISSUE THREAD

**Issue by gabihodoroaga** [apache/beam#23028]
### What happened?

I encountered this error when I updated my BigQuery batch pipeline write method from `FILE_LOADS` to `STORAGE_WRITE_API` 
```text
Exception in thread "main" org.apache.beam.sdk.Pipeline$PipelineExecutionException: 
java.lang.RuntimeException:  
java.lang.RuntimeException: java.lang.RuntimeException: 
com.google.api.gax.rpc.PermissionDeniedException:  
io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission denied: Consumer 'project:null' has been suspended.
```
After a while I realized that the error is generated by the fact that I’m not setting the project name when I set the destination. For example  `dataset.table` instead of `project-id:dataset.table`.

This breaks the compatibility with the current pipelines and it will make it harder for people to make the transition to the new BigQuery Storage Write API.

By digging into the source code I found the this situation is handled by the FILE_LOADS by using the project property from the pipeline options
sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/WriteTables.java:239
```java
     if (Strings.isNullOrEmpty(tableReference.getProjectId())) {
       BigQueryOptions options = c.getPipelineOptions().as(BigQueryOptions.class);
       tableReference.setProjectId(
           options.getBigQueryProject() == null
               ? options.getProject()
               : options.getBigQueryProject());
       tableDestination = tableDestination.withTableReference(tableReference);
     }
```

For the Storage API implementation this can be handled by updating this function and pass the pipeline options as parameter
```java
​​public String getTableUrn() {
 TableReference table = getTableReference();
 return String.format(
     "projects/%s/datasets/%s/tables/%s",
     table.getProjectId(), table.getDatasetId(), table.getTableId());
}
```
I can try to make a PR if this approach is acceptable.

### Issue Priority

Priority: 3

### Issue Component

Component: io-java-gcp

**Comment by kennknowles** [comment]
@johnjcasey

**Comment by johnjcasey** [comment]
@ahmedabu98 do you have some context on this?

**Comment by ahmedabu98** [comment]
This seems like a simple enough fix. @gabihodoroaga you're welcome to open a PR and tag me as a reviewer.

**Comment by ahmedabu98** [comment]
P.S. It might make more sense to add a `TableDestination::resolveProjectId` method that takes a PipelineOptions parameter.
