### ISSUE TITLE
[Playground] [Task] Fix dependency for Index creation step of "build_playground_backend" GA

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#23031]
### What needs to happen?
We need to fix dependency for DB index creation step of "build_playground_backend" Github action.
This step fails if Setup GCP Account action was not executed.
See https://github.com/apache/beam/runs/8183475997?check_suite_focus=true for details

### Issue Priority
Priority: 2

### Issue Component
Component: beam-playground

**Comment by MakarkinSAkvelon** [comment]
.take-issue
