### ISSUE TITLE
[Feature Request]: Name all Java threads to aid in debugging

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#23049]
### What would you like to happen?

Java threads can be giving names in various ways, such as [this one](https://github.com/apache/beam/blob/b2a6f46fb21709cc1927ce1950a38a922dce0a35/sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/data/BeamFnDataOutboundAggregator.java#L109). It would be useful to scan through the codebase and make sure to do this each place where we create threads or thread pools, etc. This way stuck threads or leaked threads are very obvious to debug.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-java-core

**Comment by Geddy05** [comment]
.take-issue

**Comment by Geddy05** [comment]
.close-issue
