### ISSUE TITLE
[Feature Request]: Add compile time check to target JDK8 when compiling with JDK11/17

### ISSUE THREAD

**Issue by fernando-wizeline** [apache/beam#23068]
### What would you like to happen?

Several tests fail when compiling with JDK11 due to changes made to the ByteBuffer class in JDK9.
Those changes block visibility of some ByteBuffer methods used by Beam, resulting NoSuchMethodError exceptions.
There is a --release flag added to javac to counter this, but not sure if that could help.

### Issue Priority

Priority: 3

### Issue Component

Component: examples-java

**Comment by apilloud** [comment]
Looks like this is being fixed by #23771
