### ISSUE TITLE
[Task]: Move pre-processing of example code away from grpc_code_client.dart

### ISSUE THREAD

**Issue by alexeyinkin** [apache/beam#23079]
### What needs to happen?

The code editor currently does not display tabs correctly. Tabs are the default indentation in the Go language.

The workaround made in https://issues.apache.org/jira/browse/BEAM-13446
is replacing tabs with 2 spaces in https://github.com/apache/beam/blob/master/playground/frontend/lib/utils/replace_incorrect_symbols.dart
called in https://github.com/apache/beam/blob/master/playground/frontend/lib/modules/examples/repositories/example_client/grpc_example_client.dart

... which is not an appropriate location to be aware of this. For many reasons the only appropriate location for the fix is the editor itself.

This fix should be removed from the Playground when the editor supports tab symbols or replaces them on its own:
https://github.com/akvelon/flutter-code-editor/issues/62

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by alexeyinkin** [comment]
.remove-labels 'awaiting triage'

**Comment by alexeyinkin** [comment]
.take-issue

**Comment by Malarg** [comment]
.take-issue
