### ISSUE TITLE
[Feature Request]: Auto-cancel old Actions Runs

### ISSUE THREAD

**Issue by damccorm** [apache/beam#23089]
### What would you like to happen?

Right now, our actions runs deal with long queues on a pretty much daily basis. Part of the reason for this is that if you make 5 commits in quick succession, 5 sets of workflow runs are queued and it takes a _long_ time to work through all of them.

We can work around this by auto-canceling outdated runs. We're already [doing this in Tour of Beam](https://github.com/apache/beam/pull/23032#discussion_r965927104) and it should be generalizable to the rest of the repo (or at least the workflows that are queued based on pull request pushes).

For reference, auto cancel docs: https://docs.github.com/en/enterprise-cloud@latest/actions/using-jobs/using-concurrency#example-using-concurrency-to-cancel-any-in-progress-job-or-run

### Issue Priority

Priority: 2

### Issue Component

Component: build-system

**Comment by damccorm** [comment]
@Abacn do you have the bandwidth to take this on? I think it could be a really impactful small change if it can alleviate the build queue times. If not, I'll either take it on or find someone else.

**Comment by Abacn** [comment]
.take-issue

**Comment by damccorm** [comment]
Since doing this, our average queue has gone way down - previously it was consistently hovering around 2+ hours at this point in the day; currently it is around half an hour. Thanks for doing it @Abacn
