### ISSUE TITLE
[Bug]: objsize uses GPL v3, need to swap to use ASF compatible license

### ISSUE THREAD

**Issue by lukecwik** [apache/beam#23096]
### What happened?

https://github.com/apache/beam/pull/22924 included the objsize library which is GPL v3

The suggested fix is to use pympler asizeof instead.

### Issue Priority

Priority: 0

### Issue Component

Component: sdk-py-core

**Comment by lukecwik** [comment]
I asked the maintainer whether they would swap or dual license with an ASF compatible license in https://github.com/liran-funaro/objsize/issues/5

I prefer the objsize library over pympler asizeof due to the simplicity of the implementation.

**Comment by lukecwik** [comment]
Reverting the [usage of objsize on the release branch](https://github.com/apache/beam/pull/23107) while we get an answer to https://github.com/liran-funaro/objsize/issues/5

**Comment by kennknowles** [comment]
Thanks for catching this. Is there tooling we can include in the future to catch license problems automatically?

If not, a second-best approach might be to require licenses to be declared somewhere, thus forcing a human to look it up and note what it is.
