### ISSUE TITLE
[Bug]: Reduce commit logspam in pubsublite: #22762

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#23176]
### What happened?

Filing as tracking issue to make sure #22762 is cp'ed into 2.42.0 per request from @dpcollins-google who can fill in the details if necessary.

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-gcp

**Comment by lostluck** [comment]
Send me a CP to the release branch, and I can merge it.

**Comment by tvalentyn** [comment]
for y'all convenience: https://github.com/apache/beam/pull/23188

**Comment by lostluck** [comment]
Thanks!
