### ISSUE TITLE
[Task]: RAT check is uncelar and unactionable for new contributors

### ISSUE THREAD

**Issue by TheNeuralBit** [apache/beam#23259]
### What needs to happen?

The RAT check verifies that every file has an Apache license at the top, but when it fails the Jenkins log just contains the message: 

```
08:22:05 FAILURE: Build failed with an exception.
08:22:05 
08:22:05 * What went wrong:
08:22:05 Execution failed for task ':rat'.
08:22:05 > A failure occurred while executing org.nosphere.apache.rat.RatWork
08:22:05    > Apache Rat audit failure - 19 unapproved licenses
08:22:05      	See file:///home/jenkins/jenkins-slave/workspace/beam_PreCommit_RAT_Commit/src/build/reports/rat/index.html
```

This is problematic for two reasons:
- It's unclear to new contributors that this is complaining about license headers in newly added files.
- The file outlining the issue is on a remote worker and inaccessible. Authors need to run the check locally so they can view the file with details.

At the very least we should update the message to reference "license headers in files" or similar. It would also be nice if we could dump the contents of the file to the log, or somewhere else in the UI.

### Issue Priority

Priority: 2

### Issue Component

Component: infrastructure

**Comment by TheNeuralBit** [comment]
This came up in https://github.com/apache/beam/pull/23094

CC: @damccorm

**Comment by damccorm** [comment]
So I dug in and found out that this is coming from a plugin (surprise surprise, its the RAT plugin - https://github.com/eskatos/creadur-rat-gradle). We can't customize the plugin enough to say something like "license headers in files", but we can make it at least print out the files with violations.

We could rename the jenkins run to be clearer, but that might be more jarring to our existing contributors. I settled on printing out files with violations and updating the phrase triggers readme to describe what this does
