### ISSUE TITLE
[Task]: Send unchanged examples by path when opening standalone Playground

### ISSUE THREAD

**Issue by alexeyinkin** [apache/beam#23252]
### What needs to happen?

When opening a standalone Playground from the embedded one, currently the code is sent via a window message, and so the standalone Playground URL is generic and the example cannot be shared by copying it.

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by alexeyinkin** [comment]
.remove-labels 'awaiting triage'

**Comment by alexeyinkin** [comment]
.take-issue

**Comment by Malarg** [comment]
.take-issue
