### ISSUE TITLE
[Bug]: Py37 PostCommit Failure test apache_beam.io.gcp.bigquery_file_loads_test.BigQueryFileLoadsIT.test_bqfl_streaming

### ISSUE THREAD

**Issue by Abacn** [apache/beam#23264]
### What happened?

Has been failing since Sep 14, from https://ci-beam.apache.org/job/beam_PostCommit_Python37/5719/. The test was skipped in Py38 PostCommit and only run on Py37 PostCommit.

Error message:

```
Error Message
google.api_core.exceptions.NotFound: 404 Not found: Table apache-beam-testing:python_bq_file_loads_1663183712232.output_table_ints was not found in location US

Location: US
Job ID: baf2a9a6-ecd8-49b7-a6ef-9965c7fd0cd9
```

Caused by #23012

### Issue Priority

Priority: 1

### Issue Component

Component: test-failures

**Comment by Abacn** [comment]
CC: @ahmedabu98

**Comment by ahmedabu98** [comment]
.take-issue
