### ISSUE TITLE
[Feature Request]: Add Google Drive scope to GCP Auth

### ISSUE THREAD

**Issue by ricardograca-scratch** [apache/beam#23290]
### What would you like to happen?

The current Python SDK doesn't include the `https://www.googleapis.com/auth/drive` scope when sending the authentication request to Google Cloud. This means that it's not possible to access Google Drive backed tables in BigQuery.

Adding the scope does indeed provide the required access. I'm only interested in the Python SDK, but this change should be easy to apply on all other SDKs as well if there's interest in that.

I can work on this change and submit a pull request.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

**Comment by tvalentyn** [comment]
What happens if Drive API is not enabled for a project but we include it with a scope?

**Comment by ricardograca-scratch** [comment]
I imagine the same thing that happens with any other scope, but I'll check and report back.

**Comment by ricardograca-scratch** [comment]
@tvalentyn The Drive API being enabled or not has not effect on the result if the extra scope is included. However, without the scope, even if the file is shared with the service account accessing the data this error is displayed and it's not possible to access the table:
```
Access Denied: BigQuery BigQuery: Permission denied while getting Drive credentials.
```
Adding the scope resolves the issue.

**Comment by tvalentyn** [comment]
Thanks for checking.

Would adding `https://www.googleapis.com/auth/cloud-platform` also fix the problem or this specific drive scope is necessary?

**Comment by tvalentyn** [comment]
If not, I would suggest adding a new pipeline option that allows such customizations.

Looks like in Java it's possible to specify a custom credential via a factory or credential instance : https://beam.apache.org/releases/javadoc/current/index.html?org/apache/beam/sdk/extensions/gcp/options/GcpOptions.html . In Python we don't have this. But perhaps passing a string of custom scopes  to use when authenticating would be sufficient?

**Comment by ricardograca-scratch** [comment]
> Would adding `https://www.googleapis.com/auth/cloud-platform` also fix the problem or this specific drive scope is necessary?

It's [already there](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/internal/gcp/auth.py#L49) and it doesn't allow access to Google Drive backed tables, so the drive scope is necessary.

> If not, I would suggest adding a new pipeline option that allows such customizations.

No other scope is treated this way, and it seems like I would need to do a lot of modifications to beam to enable that. I'm no beam expert, not to mention I have no experience developing Java or Go, so the likelihood of me actually pulling off what you propose is very slim, since it would require a substantial amount of time.

Can't I just add the necessary scope since it doesn't seem to cause any issues?

**Comment by ricardograca-scratch** [comment]
I agree with that. The ideal solution for me would be to provide a minimal set that is required to access BigQuery and allow users to specify any extra scopes needed.

I'll work on this change as it's currently proposed for now.

**Comment by lukecwik** [comment]
I disagree that adding scopes is a good idea, we should instead allow users to configure the scopes themselves. Adding a credential factory to python or adding a pipeline option that enables configuring these scopes with the default being the currently enabled list makes a lot more sense to me.

**Comment by lukecwik** [comment]
I would disagree, having existing users who upgrade to this version pick up additional scopes that they may not have been aware of is not a good experience.

**Comment by kennknowles** [comment]
If it is easy to do The Right Thing then go ahead and do it. But forcing arbitrary discipline on new contributors that _we ourselves never complied with_ is not how we should run things.

**Comment by lukecwik** [comment]
Continuing to do something that was done incorrectly in the past and digging a bigger hole for future maintenance is a problem.

**Comment by tvalentyn** [comment]
>  That is exactly what happened when SpannerIO was added.

I might have been covered by the google-cloud-platform scope. Java doesn't have spanner scopes, not sure if python had to reference them explicitly.

**Comment by kennknowles** [comment]
https://github.com/apache/beam/commit/5b6a0ea3ba59760515ecfc76684d8202fd54c647#diff-21a78a52eca0c898070d58302127a9bb5cdb5de512ec16b9b3d945e0b84b694c

**Comment by lukecwik** [comment]
https://github.com/apache/beam/commit/5b6a0ea3ba59760515ecfc76684d8202fd54c647#diff-21a78a52eca0c898070d58302127a9bb5cdb5de512ec16b9b3d945e0b84b694c only modifies Python's scopes and not Java's.

**Comment by lukecwik** [comment]
> If it is easy to do The Right Thing then go ahead and do it. But forcing arbitrary discipline on new contributors that _we ourselves never complied with_ is not how we should run things.

We should be guiding contributors to produce the right solution, this isn't arbitrary.

**Comment by lukecwik** [comment]
https://github.com/apache/beam/pull/23644 is a proposed solution.

**Comment by ricardograca-scratch** [comment]
Thanks everyone! The final solution looks great, and I wouldn't have minded doing the right thing to help the project, but it would have taken me a long time since I'm not familiar with the project internals.

**Comment by lukecwik** [comment]
I'm happy that you're happy with the solution.

Hopefully we can spend more time with you on your next change.
