### ISSUE TITLE
[Feature Request]: AvroUtils.toAvroSchema supports a logicaltypes.Date type

### ISSUE THREAD

**Issue by gabrywu** [apache/beam#23299]
### What would you like to happen?

Hi, folks,
I'm using a SQLTransform to read & write a Date field to parquet files. However, AvroUtils.toAvroSchema can't convert org.apache.beam.sdk.schemas.logicaltypes.Date to a avro date type. Because its identifier is `beam:logical_type:date:v1`, which can't be handled in method org.apache.beam.sdk.schemas.utils.AvroUtils.genericFromBeamField

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-java-core

**Comment by gabrywu** [comment]
`Schema beamSchema = new Schema.Builder()
                .addLogicalTypeField("date1", SqlTypes.DATE)
                .build();
        Assert.assertThrows(RuntimeException.class, () -> AvroUtils.toAvroSchema(beamSchema));`

AvroUtils.toAvroSchema can't process SqlTypes.DATE.

**Comment by gabrywu** [comment]
@reuvenlax @kanterov @piter75

**Comment by Abacn** [comment]
`beam:logical_type:date:v1` is a portable logical type (with URN). The support of portable logical types is currently underway. For now as a workaround, could create a PTransform that convert Row with `beam:logical_type:date:v1` type to `Date` type in its schema.

**Comment by gabrywu** [comment]
> `beam:logical_type:date:v1` is a portable logical type (with URN). The support of portable logical types is currently underway. For now as a workaround, could create a PTransform that convert Row with `beam:logical_type:date:v1` type to `Date` type in its schema.

I'm creating a table using a Beam SQL, can't apply a PTransform before it's created.

**Comment by Abacn** [comment]
Reopen because it is rolled back #24489
