### ISSUE TITLE
[Bug]: Java SDK: PeriodicSequence must update watermark using WatermarkEstimator

### ISSUE THREAD

**Issue by je-ik** [apache/beam#23301]
### What happened?

https://lists.apache.org/thread/m2x78d0kmzb7y4frt052qctt4y5s2pzx

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-java-core

**Comment by Abacn** [comment]
Thanks for pointing out this. Also observed similar issue (See test case in https://github.com/apache/beam/issues/21591) and ended up without an answer there

**Comment by je-ik** [comment]
> Thanks for pointing out this. Also observed similar issue (See test case in #21591) and ended up without an answer there

That is likely due to some other effect. From the top of my head, may it be different trigger?
