### ISSUE TITLE
[Playground][Task] Improve Playground infrastructure and deployment scripts

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#23319]
### What needs to happen?

Investigate and address following issues related to infrastructure and backend deployment scripts: 
Please follow following prioritised order of issues:

P2 issues:
- [x] #23339 
- [x] #23340
- [x] #23341 
- [x] #23342 
- [x] #23343 
- [x] #23344 
- [x] #23345

P2 issues after PR 23208 is merged:
- [x] #23346

P3 issues:
- [x] #23347
- [x] #23348

### Issue Priority
Priority: 2

### Issue Component
Component: beam-playground

**Comment by MakarkinSAkvelon** [comment]
.take-issue

**Comment by eantyshev** [comment]
### Legacy code
1. There's some legacy infrastructure code in playground/terraform/backend, it needs to be analyzed and removed
2. Backend images have TLS-related components (mitmproxy, allow_proxy.py) which are no longer needed
3. Gradle tasks to deploy backend are obsolete
4. playground/terraform/README.md has to be updated

### Building images
It's neccessary that we optimize building and pushing of Docker images, it takes 90% of time of deployment
No way to skip when done manually now (adressed in #23255)

### CI for Playground
Currently there's no automated CI runs for
1. Pytest in playground infrastructure
2. Playground Backend unittests
3. Playground Examples compilation

**Comment by rshamunov** [comment]
Completed
