### ISSUE TITLE
[Playground][Task]: Remove deprecated terraform templates for old backend in playground\terraform

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#23348]
### What needs to happen?
Investigate and address following issues related to infrastructure and backend deployment scripts:

Need to remove old terraform templates to clean up Playground deployment scripts

### Issue Priority
Priority: 3

### Issue Component
Component: beam-playground

**Comment by MakarkinSAkvelon** [comment]
.take-issue

**Comment by rshamunov** [comment]
Completed
