### ISSUE TITLE
[Task]: Remove upper bound on google-cloud-profiler once TensorFlow supports Protobuf 4.x

### ISSUE THREAD

**Issue by AnandInguva** [apache/beam#23355]
### What needs to happen?

Tensorflow 2.11.0 won't have upper bound on Protobuf and  then Protbuf can be updated in the Apache Beam. Once we update Protobuf, we can remove upper bound restriction on google-cloud-profiler

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

**Comment by chamikaramj** [comment]
Moving this to next milestone since Tensorflow 2.11 has not been released yet.

**Comment by kennknowles** [comment]
@tvalentyn @damccorm @AnandInguva Tensorflow 2.11.0 is released. Has this follow-up been completed? Is it critical for 2.44.0? Can you get it in ASAP if so?

**Comment by AnandInguva** [comment]
Tensorflow 2.11 pushed back on protobuf upper bound. They are still using 3.x.x protobuf. 

https://github.com/tensorflow/tensorflow/blob/d5b57ca93e506df258271ea00fc29cf98383a374/tensorflow/tools/pip_package/setup.py#L102

**Comment by AnandInguva** [comment]
We can still keep this as a tracking issue and circle back to this in the coming releases.
