### ISSUE TITLE
[Bug]: TextSource fails to handle parsing channels that return very short reads (< # delimiter characters)

### ISSUE THREAD

**Issue by lukecwik** [apache/beam#23375]
### What happened?

The `readDefaultLine` and `readCustomLine` methods do not handle cases where `0` or `1` length buffers are returned causing `IndexOutOfBoundsExceptions` due to incorrect calculation of the `appendLength`.

This was caused by https://github.com/apache/beam/commit/30a48f05cf2ee0eea0a304fea01eb40f323f9f3c and is unreleased at the moment.

### Issue Priority

Priority: 0

### Issue Component

Component: io-java-text

**Comment by lukecwik** [comment]
R: @TheNeuralBit

**Comment by TheNeuralBit** [comment]
How did we detect this?

**Comment by lukecwik** [comment]
Internal integration tests within Google caught this. Its why I added additional unit testing to cover these cases as well.
