### ISSUE TITLE
[Task][Go SDK]: Dataflow Go PostCommits timing out

### ISSUE THREAD

**Issue by lostluck** [apache/beam#23422]
### What needs to happen?

Currently the postcommits are failing. We need to investigate where the time is being spent and if possible, either parallelized it better (WRT beam project Dataflow quotas), or consolidate some test pipelines into single jobs (better handling quota), or reduce the number of specific tests we're running against dataflow post commits (eg. remove low signal tests).

 As a stop gap, double the 2.5h timeout to 5h.

### Issue Priority

Priority: 1

### Issue Component

Component: sdk-go

**Comment by lostluck** [comment]
Specifically, we could reduce the number of pipelines by consolidating them into a single pipeline for the specific area. The we have Dataflow filtering out the individual pipelines where the consolidated ones are used instead. This may require some test prefix renaming to simplify.

https://github.com/apache/beam/blob/a393efa61d4a1933717a4fe24a7559ec00e8912a/sdks/go/test/integration/integration.go#L222

eg. All the State Pipelines could be consolidated into a single pipeline:
TestConsolidatedStateAPIPipeline

And the State tests renamed and prefixed, eg. TestStateAPI_MapState

And similarly across common areas in the integration tests.

**Comment by Abacn** [comment]
Seen this before and was transient #23311

**Comment by lostluck** [comment]
Yeah, transient or not, it's a flake, which means it interrupts velocity.

 Since our apache-beam-testing project for Dataflow is a shared resource and we have  only so many simultaneous job slots, I'd rather get the post commit back down under an hour.

**Comment by lostluck** [comment]
Looks like this has is stabilized.
