### ISSUE TITLE
[Bug]: Apache Beam v2.42.0 RC00 malformed Python Wheel filename

### ISSUE THREAD

**Issue by aamontree** [apache/beam#23433]
### What happened?

The latest version (`v2.42.0rc00`) of the Python Apache Beam distribution is missing a hyphen between the distribution and version names.

https://pypi.org/simple/apache-beam/

This is breaking installations with `easy_install` (using `setuptools==51.3.3`):

```
ValueError: invalid wheel name: 'apache_beam2.42.0rc00-cp37-cp37m-macosx_10_9_x86_64.whl'
```

Following [PEP 491](https://peps.python.org/pep-0491/#file-name-convention), the wheel filename should include a hyphen `-` between the distribution and version names:

```
{distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl
```

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

**Comment by aamontree** [comment]
Looks like `v2.42.0` was "yanked": https://pypi.org/project/apache-beam/2.42.0/#history

**Comment by RobMcKiernan** [comment]
I'm still experiencing this. Is this likely to be fixed?:
```
InvalidWheelName
  apache_beam2.42.0rc00-cp37-cp37m-macosx_10_9_x86_64.whl is not a valid wheel filename.
  at /usr/local/lib/python3.8/site-packages/poetry/installation/chooser.py:36 in __init__
       32│ class Wheel:
       33│     def __init__(self, filename: str) -> None:
       34│         wheel_info = wheel_file_re.match(filename)
       35│         if not wheel_info:
    →  36│             raise InvalidWheelName(f"{filename} is not a valid wheel filename.")
       37│ 
       38│         self.filename = filename
       39│         self.name = wheel_info.group("name").replace("_", "-")
       40│         self.version = wheel_info.group("ver").replace("_", "-")
```

**Comment by RobMcKiernan** [comment]
@aamontree are you able to reopen this issue?
