### ISSUE TITLE
[Tour of Beam] [Task] Extract CI to a separate workflow with per-sdk example verification

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#23463]
### What needs to happen?
Need to refactor Playground\ToB CI\CD so that CI is separated from CD  and we are able to run CI from PR's originating from forks without access to github secrets.

- [x] #23464
- [x] #23465
- [x] #23470

### Issue Priority
Priority: 3

### Issue Component
Component: tour-of-beam, playground

**Comment by eantyshev** [comment]
.take-issue
