### ISSUE TITLE
[Tour of Beam] [Subtask] Extract reusable CI workflow for examples per-SDK

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#23464]
### What needs to happen?
Extract reusable CI per-SDK workflow without need of GCP credentials
This should be achieved by performing example verification not in GKE cluster but on the runner itself in docker container

### Issue Priority
Priority: 3

### Issue Component
Component: tour-of-beam, playground

**Comment by eantyshev** [comment]
.take-issue
