### ISSUE TITLE
[Bug]: tables content overflow

### ISSUE THREAD

**Issue by bullet03** [apache/beam#23460]
### What happened?

Steps to reproduce:

1. [Open Beam ZetaSQL lexical structure page](https://beam.apache.org/documentation/dsls/sql/zetasql/data-types/) in the browser
2. Reduce the width of the page to 1080px
3. Scroll to the section Data type properties
4. Scroll down that the right menu overlaps the table

Same issue on pages:
- https://beam.apache.org/community/presentation-materials/index.html
- https://beam.apache.org/documentation/dsls/sql/zetasql/operators/index.html
- https://beam.apache.org/documentation/dsls/sql/zetasql/lexical/index.html

Actual result: Right nav menu overlaps the table
Expected result: Right nav menu doesn't overlap the table

![before_table_1](https://user-images.githubusercontent.com/61748758/193564871-292a726e-f56d-4c04-bb16-079d681f2e33.gif)
![before_table_2](https://user-images.githubusercontent.com/61748758/193564887-be523e63-f9d1-4c38-a635-41f67929f1dc.gif)
![before_table_3](https://user-images.githubusercontent.com/61748758/193564900-d886c5fd-bdf0-40a1-b30b-df41a1775f51.gif)

### Issue Priority

Priority: 3

### Issue Component

Component: website

**Comment by bullet03** [comment]
.take-issue

**Comment by bullet03** [comment]
.take-issue

**Comment by damccorm** [comment]
The take issue command was broken until just now, should be fixed

**Comment by bullet03** [comment]
> The take issue command was broken until just now, should be fixed

Thank you! Works perfectly now!
