### ISSUE TITLE
[Tour of Beam] [Task] Create Terraform scripts for Tour of Beam backend

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#23475]
### What needs to happen?

Need to create terraform scripts for Tour of Beam backend deployment to GCP project:
- scripts for deployment ToB cloud functions to GCP
- scripts for service accounts if needed

### Issue Priority
Priority: 3

### Issue Component
Component: tour-of-beam

**Comment by ruslan-ikhsan** [comment]
.take-issue

**Comment by ruslan-ikhsan** [comment]
.take-issue
