### ISSUE TITLE
[Task]: Write better experience on TF python notebook

### ISSUE THREAD

**Issue by ryanthompson591** [apache/beam#23483]
### What needs to happen?

The current tensorflow notebook will fail on its first run, and needs the notebook to be restarted due to an import error.

Change the notebook with an explicit restart, or perhaps a try-catch block that does a restart.

See code:
https://github.com/apache/beam/blob/master/examples/notebooks/beam-ml/run_inference_tensorflow.ipynb

.take-issue
.set-labels task run-inference python ml core P3

### Issue Priority

Priority: 3

### Issue Component

Component: sdk-py-core

**Comment by ryanthompson591** [comment]
.take-issue
.set-labels task run-inference python ml core P3

**Comment by ryanthompson591** [comment]
.take-issue

**Comment by ryanthompson591** [comment]
.set-labels task run-inference python ml core P3

**Comment by damccorm** [comment]
This has been fixed
