### ISSUE TITLE
[Bug]: add DebeziumIO to the connectors page

### ISSUE THREAD

**Issue by sachinag** [apache/beam#23489]
### What happened?

https://github.com/apache/beam/tree/master/sdks/java/io/debezium/src exists but is not listed on https://beam.apache.org/documentation/io/connectors/

### Issue Priority

Priority: 1

### Issue Component

Component: website

**Comment by xinbinhuang** [comment]
.take-issue

**Comment by xinbinhuang** [comment]
.take-issue

**Comment by xinbinhuang** [comment]
@damccorm  .. seems like I can't take the issue. Is there an alternative way to assign the issue to me?

**Comment by damccorm** [comment]
I think Github actions were just backed up, looks like it succeeded eventually.

**Comment by kennknowles** [comment]
@xinbinhuang are you working on this? do you need any help?

**Comment by xinbinhuang** [comment]
@kennknowles thx for checking, was a bit busy at work the last a few weeks. I plan to do this PR before the holiday, but feel free to get to it first if you have time.
