### ISSUE TITLE
[Task]: Eliminate google-python-cloud-debugger dependency in base_image_requirements

### ISSUE THREAD

**Issue by Abacn** [apache/beam#23487]
### What needs to happen?

google-python-cloud-debugger has been deprecated and will be shutdown by May 31,2023. https://cloud.google.com/debugger/docs/release-notes

We need to eliminate this dependency in our container image by that time.
The tasks involves the investigation how this dependency works currently (beam does not use it directly) and either remove it or find alternatives.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-harness

**Comment by tvalentyn** [comment]
It sounds like we don't actually support integration with cloud debugger and this dep is a dead weight.
