### ISSUE TITLE
[Bug]: SpannerIO.readChangeStream backlog bytes reported incorrectly

### ISSUE THREAD

**Issue by thiagotnunes** [apache/beam#23494]
### What happened?

The `SpannerIO.readChangeStreams` reported `backlog bytes` using all record types from a change stream (`data change records`, `heartbeat records` and `child partition records`). However, only `data change records` are sent downstream.

This has the unintended effect of preventing downscaling when using autoscaling. The scenario where this occurs is when the throughput is `0`, but the backlog bytes is `> 0` due to the `heartbeat records`. In this case, the `backlog estimate` would not match the thresholds for downscaling, in fact preventing it.

In order to fix this, we should only use `data change records` to estimate the `backlog bytes` and disregard the other types.

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-gcp

**Comment by efalkenberg** [comment]
@lostluck this is heavily impacting customers and we would like to get this into a `v2.42.0-RC2`. Can you help me make that happen? Happy to provide more context via efalkenberg at google 
thanks!

**Comment by efalkenberg** [comment]
The corresponding PR is here: https://github.com/apache/beam/pull/23493
