### ISSUE TITLE
[Bug]: BigQueryIO schema update should be opt in

### ISSUE THREAD

**Issue by reuvenlax** [apache/beam#23504]
### What happened?

Since schema update is on by default, it often results in major slowdowns for pipelines due to querying BigQuery for new messages.

### Issue Priority

Priority: 1

### Issue Component

Component: io-java-gcp

**Comment by TheNeuralBit** [comment]
Closing this and adding to 2.43.0 milestone, please update it if that's incorrect @reuvenlax
