### ISSUE TITLE
[Feature Request]: Make CombineFns used in Python Combiners part of the public API

### ISSUE THREAD

**Issue by TheNeuralBit** [apache/beam#23511]
### What would you like to happen?

Currently the CombineFn implementations in combiners.py are [not included in `__all__`](https://github.com/apache/beam/blob/7980cb9a35cdb37ffd57a43ec9a1bfa5e204f5d7/sdks/python/apache_beam/transforms/combiners.py#L49) which makes them look like implementation details. I think we should expose these in a way that makes it clear they can be used directly (e.g. in GroupBy with aggregate_fields). Two possibilities:
- Just add the CombineFn implementations to `__all__`
- Add a `combineFn` method on the corresponding combiners - this would be analogous to the Java SDK. see [`Count.combineFn`](https://beam.apache.org/releases/javadoc/current/org/apache/beam/sdk/transforms/Count.html#combineFn--).

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

**Comment by tvalentyn** [comment]
I think there is no concern adding public CombineFn implementations to `__all__`. Re second approach - there may be some ambiguity here for composite combiners. For example: would there be an expectation for defining "Top.SmallestPerKey.combineFn" or just Top.combineFn ?
