### ISSUE TITLE
BigQuerySamplesIT.testTableIO is breaking in Java PostCommits 

### ISSUE THREAD

**Issue by ahmedabu98** [apache/beam#23541]
### What happened?

beam_PostCommit_Java_DataflowVX and beam_PostCommit_Java_Dataflow_Examples_Dataflow_V2_X are failing due to the following exception:
`
java.lang.RuntimeException: org.apache.beam.sdk.util.UserCodeException: org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.VerifyException: Expected Decimal logical type
`

### Issue Priority

Priority: 1

### Issue Component

Component: io-java-gcp

**Comment by ahmedabu98** [comment]
An error is thrown when reading in a Numeric BigQuery field with batch loads. Reproduced this by reading from a BQ table that has a single column of type Numeric.

**Comment by ahmedabu98** [comment]
The `BigQueryAvroUtils.toGenericAvroSchema()` method used [here](https://github.com/apache/beam/blob/51bcda973cf5452ae6a11bbbc3224e328f458254/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQuerySourceBase.java#L240-L241) returns a null "type" value for the Numeric type: 
```
{"type":"record","name":"root","namespace":"org.apache.beam.sdk.io.gcp.bigquery","doc":"Translated Avro Schema for root","fields":[{"name":"numeric_field","type":["null","bytes"]}]}
```

**Comment by ahmedabu98** [comment]
The schema was previously generated with `BigQueryIO.JSON_FACTORY` but was changed [here](https://github.com/apache/beam/pull/22718/files#diff-cb714b42eb4552b678a8193d34ecb892776deff2728b6589a6fda52e179cff5cL254). I added the method back and logged the schema results:
```
{"fields":[{"mode":"NULLABLE","name":"numeric_field","type":"NUMERIC"}]}
```

**Comment by steveniemitz** [comment]
@kkdoon

**Comment by kkdoon** [comment]
Thanks @ahmedabu98 for opening this issue. The root cause is the reader schema generated by `BigQueryAvroUtils.toGenericAvroSchema()` for numeric BigQuery type, where the expected schema should be like:`{"type":"bytes","logicalType":"decimal","precision":38,"scale":9}`, however this function generates `{"type":"bytes"}` instead. Using only the writer schema fixes this issue since it reads the correct AVRO schema.

I have created a PR #23594 for the same.

**Comment by ahmedabu98** [comment]
Thanks for taking a look @kkdoon 

Changing the name to note that this test failure is not limited to Dataflow runner, eg: https://ci-beam.apache.org/job/beam_PostCommit_Java_Examples_Flink_PR/10/testReport/
