### ISSUE TITLE
[Task]: Run some BigQuery integration tests only on one Dataflow Python3.X PostCommit

### ISSUE THREAD

**Issue by Abacn** [apache/beam#23573]
### What needs to happen?

There is a Dataflow Python PostCommit flake due to too many BigQuery tests running same time. 
Encountered in recent release process: https://github.com/apache/beam/pull/23200#issuecomment-1266419850

    I've found that trying to run all the dataflow based tests simultaneously simply causes spurious failures in
    various levels of API quota. apache-beam-testing simply can't do them all at the same time. 

and also observed in https://github.com/apache/beam/pull/23014#issuecomment-1264028243

Python3.x PostCommit has been timed out (4 h limit) with high probability. The most time consuming testing module is BigQuery which costs 2 h run time. As we are going to support python3.10, quota issue is going to be worse.

We should audit the current BigQuery integration tests on Dataflow to see if running on single py verision suffices (as we did for spannerIOIT), and redistribute these tests.

### Issue Priority

Priority: 1

### Issue Component

Component: test-failures

**Comment by Abacn** [comment]
.take-issue

**Comment by Abacn** [comment]
add-labels python, io, gcp

**Comment by Abacn** [comment]
Considered as a subtask of #20930

**Comment by AnandInguva** [comment]
.add-labels python, io, gcp

**Comment by Abacn** [comment]
Currently on hold as GitHub migration involves splitting postcommit tests. Downgrade to P2 for tracking if it still occurs when GitHub migration completed.

**Comment by Abacn** [comment]
.remove-labels P1

.add-labels P2

**Comment by Abacn** [comment]
let me close this. Superseded by #25970 which will reduce the run time of Python Postcommit by an hour
