### ISSUE TITLE
[Playground] [Task]: Restore workflow trigger for Playground deploy examples GA

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#23600]
### What needs to happen?
Playground example deploy workflow was switched to manual trigger due to existing bug in workflow code.
Some broken examples might get into Playground storage bucket. New Playground CI/CD will address and fix this bug but it might catch broken examples before playground backend is redeployed. Since we plan to switch to new backend deployment model soon, we don't want to be blocked until backend is fixed. 
As soon as we switch to a new backend in GKE we need to return to automated triggers for this workflow

### Issue Priority
Priority: 3

### Issue Component
Component: beam-playground

**Comment by ruslan-ikhsan** [comment]
.takeissue

**Comment by ruslan-ikhsan** [comment]
.take-issue
