### ISSUE TITLE
[Bug]: Website precommit flaky

### ISSUE THREAD

**Issue by damccorm** [apache/beam#23627]
### What happened?

Occasionally the website precommit has taken 2 hours to run and has timed out. Normally it takes <30 minutes.

Example from cron job - https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/5938/
Many examples from precommit - https://ci-beam.apache.org/job/beam_PreCommit_Website_Commit/

### Issue Priority

Priority: 1

### Issue Component

Component: website

**Comment by pabloem** [comment]
keeping open to verify improvement in a few days

**Comment by kileys** [comment]
Runtime is back down
