### ISSUE TITLE
[Feature Request]: Try to write PCollection<Row> through JdbcIO but JdbcUtil.BeamRowPreparedStatementSetter is not visible

### ISSUE THREAD

**Issue by haoyuche** [apache/beam#23646]
### What would you like to happen?

PCollection<Row> rows
rows.apply(JdbcIO.<Row>write()
                .withDataSourceConfiguration(JdbcIO.DataSourceConfiguration.create(
                        output.driverClassName, output.url)
                        .withUsername(output.username)
                        .withPassword(output.password))
                .withStatement(generateWriteStatement(rows.getSchema(), output.tableName))
                .withPreparedStatementSetter(new JdbcUtil.BeamRowPreparedStatementSetter()));

However JdbcUtil is not visible, so is there any recommended way to PreparedStatementSetter for Beam rows?

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-jdbc

**Comment by aromanenko-dev** [comment]
There is no need to use prepared statement for that, take a look on [this example](https://github.com/apache/beam/blob/85b6b643bff1157fa68787ab9bd6b0afcd6c8bc6/sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcIOTest.java#L720) from JdbcIO tests.

**Comment by haoyuche** [comment]
Thanks, I've figured out that if the output row has same schema as the output table then I don't need all of these.
