### ISSUE TITLE
[Bug]: TPC-DS Jenkins job doesn't read all data from partitioned files

### ISSUE THREAD

**Issue by aromanenko-dev** [apache/beam#23671]
### What happened?

TPC-DS Jenkins job doesn't read all data from partitioned files from `gs://beam-tpcds/datasets/parquet/partitioned` path. It can be related to an internal structure of partitioned directories and files that are not properly matched with provided path pattern. 

### Issue Priority

Priority: 2

### Issue Component

Component: testing-tpcds

**Comment by manuzhang** [comment]
Fixed in #23655
