### ISSUE TITLE
[Task]: Adjustable font size in Tour of Beam 

### ISSUE THREAD

**Issue by alexeyinkin** [apache/beam#23690]
### What needs to happen?

This is how font sizes currently compare on my 1920x1080 screen with the default Chrome settings:
![image](https://user-images.githubusercontent.com/44893228/196346942-90be23d8-7493-492a-9cf2-68be3c9ce454.png)

We should:
1. Make the sizes match the Beam website.
2. Ensure font size scales following browser settings.

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by nausharipov** [comment]
.take-issue

**Comment by olehborysevych** [comment]
Moved to next phase ideas
