### ISSUE TITLE
[Bug]: beam_Publish_Beam_SDK_Snapshots fails

### ISSUE THREAD

**Issue by Abacn** [apache/beam#23697]
### What happened?

No Snapshot container produced since Oct 14th. 

Fail since https://ci-beam.apache.org/job/beam_Publish_Beam_SDK_Snapshots/4066/

Related to #23165

### Issue Priority

Priority: 1

### Issue Component

Component: test-failures

**Comment by damccorm** [comment]
@kileys the first failure is at https://github.com/apache/beam/commit/117aa34bcef1a7854bbd894f7ffae036357aefe8 which looks suspiciously related to the error: `java17Home or java11Home property required. Re-run with -Pjava17Home or -Pjava11Home`
