### ISSUE TITLE
[Task]: Prepare removal of Spark2 runner

### ISSUE THREAD

**Issue by mosche** [apache/beam#23728]
### What needs to happen?

The Spark 2 has been deprecated for a while. Even more significant, it's actually in a badly broken state since long due to classpath issues when running on a Spark cluster (#23568).

Before Spark 2 support can be removed, all documentation and dependent components should be migrated to use Spark 3.

Notes:
- [x] Test examples against Spark 3
- [x] Java Quickstart on Spark 3
- [x] Remove obsolete `sparkRunner` from Hadoop-format
- [x] Use Spark 3 as default for portable Spark job-server.
- [x] Validate Go & Python against Spark 3
- [x] Bump metrics-core to match version used by Spark 3 (4.1.1)
- [x] Nexmark, Tpcds, Load tests
- [x] Jpms tests (cleanup build)

### Issue Priority

Priority: 2

### Issue Component

Component: runner-spark

**Comment by aromanenko-dev** [comment]
Should all sub-tasks be finished within one Beam release or it's not required?

**Comment by mosche** [comment]
> Should all sub-tasks be finished within one Beam release or it's not required?

No need for that, these tasks are pretty independent.
