### ISSUE TITLE
[Bug]: After JDBCIO read withRowOutput(), the VARCHAR/TEXT -> LOGICAL_TYPE and not compatible with SqlTypeName

### ISSUE THREAD

**Issue by haoyuche** [apache/beam#23747]
### What happened?

        PCollection<Row> rows = pipeline.apply(JdbcIO.<Row>readWithPartitions()
                .withDataSourceConfiguration(JdbcIO.DataSourceConfiguration.create(
                        input.driverClassName, input.url)
                        .withUsername(input.username)
                        .withPassword(input.password))
                .withTable(input.tableName)
                .withPartitionColumn(input.primeKeyForPartitionRead)
                .withRowOutput());

Now there is a column named "name" which is VARCHAR, which has been read as beam type LOGICAL_TYPE NOT NULL.

Then I do 
```
        Schema schemaAfterSql = Schema.builder().addNullableField("id", Schema.FieldType.INT64).addNullableField("name", Schema.FieldType.String).build();
        String selectQuery = "SELECT id, name FROM PCOLLECTION" ;
        PCollection<Row> processedRows = rows.apply("EnforcePolicy", SqlTransform.query(selectQuery)).setRowSchema(schemaAfterSql);
```
It gets "An exception occured while executing the Java class. Unable to parse query SELECT id, policy_name FROM PCOLLECTION: java.lang.IllegalArgumentException: Cannot find a matching Calcite SqlTypeName for Beam type: LOGICAL_TYPE NOT NULL"

### Issue Priority

Priority: 0

### Issue Component

Component: io-java-jdbc

**Comment by Abacn** [comment]
Thanks for reporting this. It looks like the cause is CalciteUtil here: https://github.com/apache/beam/blob/4ffeae4d2b800f2df36d2ea2eab549f2204d5691/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/impl/utils/CalciteUtils.java#L224
does not consider the logical type FieldType.

**Comment by Abacn** [comment]
.remove-labels P0, "awaiting triage"

.set_labels P2

**Comment by haoyuche** [comment]
Yes, I think somehow we should not feed LOGICAL_TYPE to CalciteUtils but instead we should feed the  [BaseT](https://github.com/apache/beam/blob/243128a8fc52798e1b58b0cf1a271d95ee7aa241/sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/Schema.java#L547) so that it can handle the normal sql types.

**Comment by Abacn** [comment]
.take-issue

**Comment by haoyuche** [comment]
Thanks Andrew for fixing this issue!
