### ISSUE TITLE
[Bug]: beam_PostCommit_Py_VR_Dataflow is failing in `translations_test.TranslationsTest.test_run_packable_combine_{globally,limit}`

### ISSUE THREAD

**Issue by TheNeuralBit** [apache/beam#23768]
### What happened?

Failing tests:
- `apache_beam.runners.portability.fn_api_runner.translations_test.TranslationsTest.test_run_packable_combine_globally`
- `apache_beam.runners.portability.fn_api_runner.translations_test.TranslationsTest.test_run_packable_combine_limit`

First failure: https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/9972/

I don't see an obvious culprit commit in that run

### Issue Priority

Priority: 1

### Issue Component

Component: runner-dataflow

**Comment by TheNeuralBit** [comment]
@riteshghorse could you take a look at this?

**Comment by riteshghorse** [comment]
Sure

**Comment by riteshghorse** [comment]
Looks like the build is green again
