### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by potiuk** [apache/beam#23848]
### What would you like to happen?

I know it is eaarly (Python 3.11 has just been released yesterday) but we are hoping in Apache Airflow to a much faster cycle of adding new Python releases - especially that Pyhon 3.11 introduces huge performance improvements (25% is the average number claimed)  due to a very focused effort to increase single-threaded Python performance (Specialized interpreter being the core of it but also many other improvements) without actually changing any of the Python code. 

Apache Beam was traditionally one of the latest dependencies of Airflow to support newer Python version so this issue is here to make you aware that we are eaager (also to help if needed) to make it faster, possibly by talking to dependencies of Beam as well (who are oftten also direct dependencies of Airflow) and help them as well. I perfectly understand we need to bubble up support so that your dependencies support them first.

Nice summary of Py3.11 support is here: https://pyreadiness.org/3.11/  - it's not very green obviously, but I hope it gets greener soon.

I'd appreciate if someone in the Beam team attempted to migrate and have a PR running (and failing possibly until all prerequisite are met so that we can also track the progress and possibly help each other to solve any problems.

I just opened such PR in Apache Airflow yesterday and plan to keep it open until it gets green :)

https://github.com/apache/airflow/pull/27264

I think it would be fantastic if we could as the open source community migrate to the new Python much faster.

Looking forward to cooperation on that one :)

### Issue Priority

Priority: 3

### Issue Component

Component: sdk-py-core

**Comment by Abacn** [comment]
.remove-labels 'awaiting triage'

**Comment by AnandInguva** [comment]
Thanks for opening this. This is interesting. I can open a draft PR and see what happens when I get some time.

**Comment by potiuk** [comment]
Looking forward to it :)

**Comment by AnandInguva** [comment]
.take-issue

**Comment by potiuk** [comment]
FYI. Pyarrow just yesterday released 3.11 compatible binary relase (10.0.1), so if you are waiitng for that - wait no more.

**Comment by AnandInguva** [comment]
Note: I will update the blockers when I discover them

Blockers
1. Dill 0.3.6 is required for Python 3.11 - https://github.com/pywbem/pywbem/issues/2948#issuecomment-1363070893

**Comment by kennknowles** [comment]
Per our bug priorities, I think this is "normal work" aka P2

**Comment by AnandInguva** [comment]
.close-issue

**Comment by potiuk** [comment]
Cool!
