### ISSUE TITLE
[Task]: PR Bot - Only push commit if non-empty

### ISSUE THREAD

**Issue by damccorm** [apache/beam#23851]
### What needs to happen?

Right now, we push a number of non-empty commits for our PR bot - https://github.com/apache/beam/blob/ead2d2e8025874ad5c3f09ea0fda06caf027e18c/scripts/ci/pr-bot/shared/persistentState.ts#L43 - we can be a little smarter about this and only push commits if they are meaningful.

### Issue Priority

Priority: 3

### Issue Component

Component: infrastructure

**Comment by ayushthe1** [comment]
hey @damccorm ,i would like to work on this issue. Please assign it to me.
Also could you please elaborate what i need to do .

**Comment by damccorm** [comment]
Hey @ayushthe1 - right now, our PR bot (which is backed by GitHub Actions) stores its state, it checks it in as a file to the branch `pr-bot-state` (this is done here - https://github.com/apache/beam/blob/ead2d2e8025874ad5c3f09ea0fda06caf027e18c/scripts/ci/pr-bot/shared/persistentState.ts#L43). Right now, we will produce a commit any time we call save state, even if there are no changes to commit.

The goal of this issue is to check if there have been any changes before producing a commit. One way to do this would be running something like `git diff-index --quiet HEAD` before adding the files to be committed; this should produce output only if there are changes.

**Comment by damccorm** [comment]
I assigned you as well. For future reference, you can self-assign issues by commenting `.take-issue`

**Comment by ayushthe1** [comment]
> I assigned you as well. For future reference, you can self-assign issues by commenting `.take-issue`

Thanks ! I will look into all the details you provided. :smile:

**Comment by ayushthe1** [comment]
hey  @damccorm i am running into some issues . I used `git diff-index HEAD` and saw it produces some output if there are any changes made in repo .It also don't produces any output if no changes are made or if the last commit was an empty commit.
However on using the `--quiet` flag ,no output is produced in both cases . So how can i use this command with `--quiet` flag if no output is produced whether or not  any changes are made in repo.

My idea initially was to use some kind of `if-else` statement on condition if `git diff-index --quiet HEAD` produces any output or not and then putting the current `git add ,commit ,push` under it.

**Comment by damccorm** [comment]
A slightly cleaner approach than inspecting the output is probably to use the `quiet` flag and then inspect the exit code. There are usually tighter guarantees around exit codes than outputs. If there are changes, `git diff-index --quiet HEAD` will have an exit code of 1, if not it will have an exit code of 0.

So if you do, for example, `git diff-index --quiet HEAD || (git add * && git commit -m "Message" && git push)`, the `add`, `commit`, and `push` steps will only run if there are changes. Alternatively, you can use the exec client we are already using to inspect the exit code of the command and then move the if/else logic into the javascript
