### ISSUE TITLE
[Task]: Current Playground example is not highlighted

### ISSUE THREAD

**Issue by alexeyinkin** [apache/beam#23865]
### What needs to happen?

MinimalWordCount should be bold:
![image](https://user-images.githubusercontent.com/44893228/198259851-13bc0428-eaea-48ac-a2e0-76fb7bc75549.png)

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by alexeyinkin** [comment]
.take-issue

**Comment by Malarg** [comment]
.take-issue
