### ISSUE TITLE
[Bug]: beam.Row.__eq__ returns true for unequal rows

### ISSUE THREAD

**Issue by aliftadvantage** [apache/beam#23875]
### What happened?

The `beam.Row.__eq__` operator has unexpected behavior when rows have different number of columns. Specifically when one row has trailing columns and all else are equal, e.g.

`beam.Row(x=1, y=2, z=3) == beam.Row(x=1, y=2)` returns true. 

### Issue Priority

Priority: 1

### Issue Component

Component: sdk-py-core

**Comment by aliftadvantage** [comment]
.take-issue

**Comment by kennknowles** [comment]
This seems pretty important. I see there is code underway. Do you need any more help finishing the PR?

**Comment by kennknowles** [comment]
I see the PR is merged. @damccorm @tvalentyn I'm assuming this is fully fixed. Any follow up needed?
