### ISSUE TITLE
[Bug]: Number of Python examples are failing for Flink and Spark on 2.43.0 release branch

### ISSUE THREAD

**Issue by chamikaramj** [apache/beam#23907]
### What happened?

Seems like following Python examples are failing for Flink and Spark on 2.43.0 release branch.

- bigquery_tornadoes
- hourly_team_score
- filters_test

For example,
https://ci-beam.apache.org/job/beam_PostCommit_Python_Examples_Spark_PR/14/
https://ci-beam.apache.org/job/beam_PostCommit_Python_Examples_Flink_PR/12/

For bigquery_tornadoes, the error is following.

RuntimeError: Pipeline BeamApp-jenkins-1028002928-4325f8c5_d8258ff0-6727-4335-867f-56bc846d9f3e failed in state FAILED: java.lang.IllegalArgumentException: PCollectionNodes [PCollectionNode{id=ref_PCollection_PCollection_52, PCollection=unique_name: "61Write/BigQueryBatchFileLoads/TriggerLoadJobsWithoutTempTables.None"
coder_id: "ref_Coder_FastPrimitivesCoder_3"
is_bounded: BOUNDED
windowing_strategy_id: "ref_Windowing_Windowing_1"
}] were consumed but never produced

I found https://github.com/apache/beam/issues/21300 that probably explain some example failures but this doesn't explain all failures above.

Valentyn, are there any known issues that explain these failures ?

### Issue Priority

Priority: 0

### Issue Component

Component: examples-python

**Comment by chamikaramj** [comment]
P0 since this is blocking the ongoing Beam release.

**Comment by tvalentyn** [comment]
Did these pass on previous release? If so, errors should be bisectable.

**Comment by Abacn** [comment]
Looks like failed tests are all BigQuery tests. Both have been failed after Sept 14th. Possible related changes on the Day of 14th: #23122 and/or #23012

**Comment by tvalentyn** [comment]
Thanks, @Abacn . The first change affects go sdk only. https://github.com/apache/beam/pull/23012 looks suspicious. @ahmedabu98 could you please take a look?

**Comment by chamikaramj** [comment]
Confirmed that this:

Passes on 2.42.0 branch
Fails on 2.43.0 branch
Fails on master

Will also try a revert.

**Comment by chamikaramj** [comment]
Fails for commit ac37784821eaedd97c2e6e39441c22ebc6d97cd3

Passes for commit 2d4f61c93250fb41112a2535394e7328bc1fdf95 (one before above).

So the culprit seems to be https://github.com/apache/beam/commit/ac37784821eaedd97c2e6e39441c22ebc6d97cd3


@ahmedabu98 can you please take a look ? We can either do a forward fix in the release branch or revert this if we can revert cleanly.

To reproduce locally, you can run the command below.

./gradlew :sdks:python:test-suites:portable:py37:flinkExamples

**Comment by ahmedabu98** [comment]
Seeing a lot of `ValueError: Unable to parse jar URL "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python_Examples_Spark/src/runners/spark/2/job-server/build/libs/beam-runners-spark-3-job-server-2.44.0-SNAPSHOT.jar". If using a full URL, make sure the scheme is specified. If using a local file path, make sure the file exists; you may have to first build the job server using './gradlew runners:spark:3:job-server:shadowJar'.`
Is this familiar to anyone?

**Comment by mosche** [comment]
Sorry @Abacn @ahmedabu98 @chamikaramj, my bad! This slipped in https://github.com/apache/beam/pull/23751 when migrating to the Spark 3 job-server. Fixed it here: https://github.com/apache/beam/pull/23936

**Comment by ahmedabu98** [comment]
Great 👍🏽 that solves the spark issues. Still looking into why those BQ tests are not starting.

**Comment by ahmedabu98** [comment]
The affected tests have a step that writes to BQ with `FILE_LOADS`. I've been reproducing locally and found the pipelines don't even start. They pass with `STREAMING_INSERTS` method though.

The errors showing up in Spark examples in @mosche 's fix in #23936 ([here](https://ci-beam.apache.org/job/beam_PostCommit_Python_Examples_Spark_PR/17/testReport/apache_beam.examples.cookbook.bigquery_tornadoes_it_test/BigqueryTornadoesIT/test_bigquery_tornadoes_it_3/)) now show the same error:
```
RuntimeError: Pipeline BeamApp-jenkins-1102122925-c4be4910_cbaf26e4-874a-42dc-adf1-f3a63242d10c failed in state FAILED: java.lang.IllegalArgumentException: PCollectionNodes [PCollectionNode{id=ref_PCollection_PCollection_52, PCollection=unique_name: "61Write/BigQueryBatchFileLoads/TriggerLoadJobsWithoutTempTables.None"
coder_id: "ref_Coder_FastPrimitivesCoder_3"
is_bounded: BOUNDED
windowing_strategy_id: "ref_Windowing_Windowing_1"
}] were consumed but never produced
```

**Comment by ahmedabu98** [comment]
The error is caused by [this `beam.Flatten()` operation](https://github.com/apache/beam/blob/f57cb9c208d9e1ac2e353c3a2d2be2b5b3ccee4a/sdks/python/apache_beam/io/gcp/bigquery_file_loads.py#L1125-L1127) that merges the results from two transforms. In most cases, one of those transforms, label: `TriggerLoadJobsWithoutTempTables`, will not be used and so will not have any elements to output. Hence, this transform is `"consumed but never produced"` by the Flatten operation.

This is not an issue for DirectRunner and DataflowRunner, but is caught by Flink and Spark.

**Comment by ahmedabu98** [comment]
Yeah I'm beginning to doubt my assessment because this was always the setup...

One thing #23012 did change though: the main output of `TriggerLoadJobs` is now produced by a [return](https://github.com/apache/beam/blame/f57cb9c208d9e1ac2e353c3a2d2be2b5b3ccee4a/sdks/python/apache_beam/io/gcp/bigquery_file_loads.py#L729) statement, previously was by a [yield](https://github.com/apache/beam/blame/2d4f61c93250fb41112a2535394e7328bc1fdf95/sdks/python/apache_beam/io/gcp/bigquery_file_loads.py#L685) statement.

**Comment by ahmedabu98** [comment]
#23954 is a workaround. The relevant BQ tests in that PR are passing now, though there are other tests in Flink and Spark example suites that are failing relatively recently (just a day ago).
