### ISSUE TITLE
[Bug]: Dataflow jpms tests fail on the 2.43.0 release branch

### ISSUE THREAD

**Issue by chamikaramj** [apache/beam#23906]
### What happened?

For example,

https://ci-beam.apache.org/job/beam_PostCommit_Java_Jpms_Dataflow_Java17_PR/19/
https://ci-beam.apache.org/job/beam_PostCommit_Java_Jpms_Dataflow_Java11_PR/25/

I ran these few times but they continue to fail. Error in the Jenkins run doesn't say much.
02:00:31 Recording test results
02:00:32 ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
02:00:32 > Task :sdks:java:testing:jpms-tests:dataflowRunnerIntegrationTest FAILED
02:00:32 Setting status of 48624f6dac8bb2ba772692ec3394537fab0877b3 to FAILURE with url https://ci-beam.apache.org/job/beam_PostCommit_Java_Jpms_Dataflow_Java17_PR/19/ and message: 'Build finished. '
02:00:32 Using context: JPMS Java 17 Dataflow Post Commit Tests
02:00:32 

Jpms tests for other runners seems to be running fine.

KIley, is there a known issue related to running these tests on the release branch ?

### Issue Priority

Priority: 0

### Issue Component

Component: sdk-java-core

**Comment by chamikaramj** [comment]
P0 since this is blocking the ongoing release.

**Comment by Abacn** [comment]
Cron jobs always succeeded instead, as well as around release cut: https://ci-beam.apache.org/job/beam_PostCommit_Java_Jpms_Dataflow_Java17/ https://ci-beam.apache.org/job/beam_PostCommit_Java_Jpms_Dataflow_Java11/

**Comment by kileys** [comment]
Taking a look

**Comment by kileys** [comment]
Checked out the release branch and tests pass locally
https://scans.gradle.com/s/omwnhwlhsom6m

**Comment by chamikaramj** [comment]
Jenkins run also had following info.

02:00:32 Execution failed for task ':sdks:java:testing:jpms-tests:dataflowRunnerIntegrationTest'.
02:00:32 > Process 'Gradle Test Executor 1' finished with non-zero exit value 143

Based on following seems like 143 error points to a potential OOM.

https://discuss.gradle.org/t/gradle-test-executor-x-finished-with-non-zero-exit-value-143/28857

But not sure why this only happened at the release branch (also this took many hours to fail instead of few minutes for the local run).

If you think this is not an actual issue in the code, feel free to reduce priority and/or move out of the release milestone.

**Comment by kileys** [comment]
Could be that the timeout killing the process

**Comment by kileys** [comment]
Ran the test with `--info` and it's getting stuck looking for the 2.43.0 container  `Error response from daemon: manifest for gcr.io/cloud-dataflow/v1beta3/beam-java17-batch:2.43.0 not found: manifest unknown: Failed to fetch \\\"2.43.0\\\"`

**Comment by kileys** [comment]
This needs the internal containers to be built to run successfully. I'm going to remove this as a blocker from the release

**Comment by kileys** [comment]
I'll re-run when the container is built to verify

**Comment by chamikaramj** [comment]
Ah, that makes sense. This should be moved to a RC validation test instead of being a part of release branch validation tests then.

**Comment by kennknowles** [comment]
Assuming this is obsolete?

**Comment by chamikaramj** [comment]
Yeah, obsolete. Thanks.
