### ISSUE TITLE
[Task]: A button to show emulator data in frontend

### ISSUE THREAD

**Issue by alexeyinkin** [apache/beam#23924]
### What needs to happen?

The simplest solution is to add a button that would navigate to the bucket view in a new tab by a URL.

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by alexeyinkin** [comment]
.take-issue

**Comment by alexeyinkin** [comment]
Backend WIP in https://github.com/akvelon/beam/tree/emulators_merged

**Comment by Malarg** [comment]
.take-issue

**Comment by rshamunov** [comment]
Implemented
