### ISSUE TITLE
[Task]: Indicate examples with emulator on frontend

### ISSUE THREAD

**Issue by alexeyinkin** [apache/beam#23923]
### What needs to happen?

Indicate examples with emulator on frontend

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by alexeyinkin** [comment]
.take-issue

**Comment by alexeyinkin** [comment]
Backend WIP in https://github.com/akvelon/beam/tree/emulators_merged

**Comment by Malarg** [comment]
.take-issue
