### ISSUE TITLE
[Task]:  Tracking issue to add tfx RunInference tests to Python 3.10 PostCommit tests

### ISSUE THREAD

**Issue by AnandInguva** [apache/beam#23966]
### What needs to happen?

tfx-bsl wheel is not built for Python 3.10. Don't add tfx-bsl RunInference tests to Pythpn 3.10 PostCommit test suite.

### Issue Priority

Priority: 2

### Issue Component

Component: run-inference

**Comment by AnandInguva** [comment]
.close-issue

**Comment by AnandInguva** [comment]
> for my education and done-and-done review, which PR adds these tests?

https://github.com/apache/beam/pull/23456

**Comment by tvalentyn** [comment]
Thanks. There is still a TODO left referencing this issue: https://github.com/apache/beam/issues/23966
