### ISSUE TITLE
What is the Control and Provision service?

### ISSUE THREAD

**Issue by cozos** [apache/beam#23993]
In the Apache Beam Fn API, what are the responsibilities of the Control service and Provision service? How do they interact with the SDK Harness Container? Does the Control/Provision service contact the SDK Harness Container (to control, or provision it...?) - or vice versa?

For context, I am building a Dataflow custom container: https://cloud.google.com/dataflow/docs/guides/using-custom-containers#create_and_building_the_container_image and I am trying to understand the boot entrypoint, which has the control and provision service: https://github.com/apache/beam/blob/master/sdks/java/container/boot.go#L49

Also asked here: https://stackoverflow.com/questions/74337565/in-apache-beam-what-is-the-control-service-and-provision-service

**Comment by aromanenko-dev** [comment]
Please, address your question on user@beam.apache.org
Thanks!
