### ISSUE TITLE
Failure in test: "beam_PerformanceTests_Kafka_IO" - timed out waiting for the condition on jobs/kafka-config

### ISSUE THREAD

**Issue by ryanthompson591** [apache/beam#24016]
Kafka IO performance tests have been red since Nov 3. A short initial triage shows a timeout on config loading.

https://ci-beam.apache.org/job/beam_PerformanceTests_Kafka_IO/

**Comment by ryanthompson591** [comment]
.add-labels P1,bug,build

**Comment by Abacn** [comment]
This is an infrastructure issue

**Comment by Abacn** [comment]
Tests are back. Now instead of permared it is flaky.

**Comment by Abacn** [comment]
.close-issue

last a couple of runs green
