### ISSUE TITLE
[Bug]: SparkReceriverIO and KafkaIO performance tests failing due to unschedulable pods on k8s

### ISSUE THREAD

**Issue by Abacn** [apache/beam#24021]
### What happened?

The new SparkReceiverIO performance test (#23305) ~adds a persistent rabbitMQ server to the io-datastore k8s cluster in the test infrastructure.~ Then both rabbitmq and kafkaIO requests ~1 GB RAM and Kafka workload fails to initialize since Nov 3 (SparkReceiverIO performance test also fails since then).

We should either make rabbitmq server deployment transient and cleanup in integration test cleanup, as the kafka performance test is doing; or bump the machine type for the k8s cluster.

Update: Removed rabbitmq workloads and see the latest performance run https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_SparkReceiver_IO/39/ does not leave persistent rabbitmq workloads on k8s cluster. The leak is either transcient or due to execution outside the jenkins (those workloads had default namespace "rabbit-test" and "default" instead of named after task ID). Both Kafka and SparkReceiverIO tests passed again. Issue mitigated but auto cleanup and bump up machine size are still action items.

### Issue Priority

Priority: 1

### Issue Component

Component: test-failures

**Comment by Abacn** [comment]
CC: @Amar3tto would you mind having a look, thanks!

**Comment by Abacn** [comment]
Deleted rabbitmq k8s workloads and it since both kafka and sparkreceiver performance tests are back. However they are still flaky. Looks like need to bump the k8s cluster available memory.

**Comment by Abacn** [comment]
> > We need a lifecycle strategy for performance test k8s workloads.
> 
> Do you mean that we have to run only one workload, that uses k8s, in a moment of time to avoid such race conditions?

As long as the k8s cluster still have resource this is not necessary. The situation was there were some (leaked) rabbitmq workloads persistently occupies k8s cluster and ran out of resources.

**Comment by Abacn** [comment]
I am monitoring the k8s cluster for a couple of days and see how much we should bump the k8s cluster machine type. I found the current specification is the smallest machine and it only has 2.5 GB memory allocable.

**Comment by Abacn** [comment]
On the other hand @Amar3tto could you please check the rabbitmq instance leaking issue?

**Comment by aromanenko-dev** [comment]
cc: @Lizzfox

**Comment by Amar3tto** [comment]
> On the other hand @Amar3tto could you please check the rabbitmq instance leaking issue?

Yes, I will take a look.

**Comment by Abacn** [comment]
> > On the other hand @Amar3tto could you please check the rabbitmq instance leaking issue?
> 
> Yes, I will take a look.

Found the latest performance run https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_SparkReceiver_IO/39/ does not leave persistent rabbitmq workloads on k8s cluster. The leak is either probabilistic or due to execution outside the jenkins (those workloads had default namespace "rabbit-test" and "default" instead of named after task ID).

The issue is mitigated for now. Thanks for your attention.

**Comment by Amar3tto** [comment]
@Abacn Thank you for the research!
I got it, yes, we tested the rabbitmq k8s cluster on the "default" and "rabbit-test" namespaces, so there might be some unnecessary resources that we didn't delete.
Have you removed them already or should I do that?

**Comment by Abacn** [comment]
> @Abacn Thank you for the research! I got it, yes, we tested the rabbitmq k8s cluster on the "default" and "rabbit-test" namespaces, so there might be some unnecessary resources that we didn't delete. Have you removed them already or should I do that?

Yeah I already removed that. So there is no leak for cron job and no further action needed

**Comment by Abacn** [comment]
.close-issue

mitigated. Bumped machine type
