### ISSUE TITLE
[Bug]:  Improve handling of side inputs in Spark dataset runner

### ISSUE THREAD

**Issue by mosche** [apache/beam#24035]
### What would you like to happen?

In the Spark dataset runner, side inputs are currently materialized and broadcasted per consuming `ParDo`.
If a `PCollection` serves as side-input to multiple `ParDo`s, it would be evaluated, collected on the driver and finally broadcasted repeatedly for every such `ParDo`.

### Issue Priority

Priority: 2

### Issue Component

Component: runner-spark

**Comment by echauchot** [comment]
A good architecture for side inputs could be to use **spark temp views** as they are lazy evaluated. I briefly (lack of time) tried it. IIRC the problem I faced was that SparkSession (needed for sql) is not designed to be used in parallel for ParDos hence serialization issues.

**Comment by mosche** [comment]
@echauchot Thanks, here's my findings / thinking so far.  

First, let's look at the side-input problem from a different perspective. Semantically it's in fact a co-group / join by window problem. Now, how to implement that efficiently in Spark considering we're dealing with a potentially very large dataset and a comparably small side-input.

Here's a couple of possible ways:
- Naively implement it as co-group / join by window. Though, that would mean shuffling both the large dataset as well as the side-input.
- We can be smarter of course, and implement it as a broadcast join. That avoids shuffling the large dataset. Instead the smaller side-input is send to all partitions of the larger one and the join happens locally in place. Sounds pretty much like what we want, right?
- And of course, we can collect the side-input on the driver and broadcast it as variable. That way we can also do a local join / lookup. Though, this has the disadvantage that we will need to evaluate (and broadcast) the side-input ahead of time during the translation of the Beam pipeline

To also mention Spark temp views, these are in fact just named `Dataset` for usage in SQL. All the above applies to them as well. Their data is distributed the same way across the cluster with the same implications.

Now, looking more closely, a couple of findings:
- To join on windows we have to first explode the dataset, so it consists rows of single windowed values. That's potentially costly.
- Broadcast joins in Spark are implemented as follows: 1) Collect data on the driver. 2) Broadcast it. Turns out this isn't much different from the manual broadcast.
- Side-inputs are typically build involving a CombineGlobally, meaning we need a global reduce step leaving just 1 partition. If we could do this final reduce step on the driver, the data would be already available to be broadcasted. Unfortunately there's additional (primitive) processing steps in-between that make this difficult.

**Comment by echauchot** [comment]
> @echauchot Thanks, here's my findings / thinking so far.
> 
> First, let's look at the side-input problem from a different perspective. Semantically it's in fact a co-group / join by window problem. Now, how to implement that efficiently in Spark considering we're dealing with a potentially very large dataset and a comparably small side-input.
> 
> Here's a couple of possible ways:
> 
> * Naively implement it as co-group / join by window. Though, that would mean shuffling both the large dataset as well as the side-input.
> * We can be smarter of course, and implement it as a broadcast join. That avoids shuffling the large dataset. Instead the smaller side-input is send to all partitions of the larger one and the join happens locally in place. Sounds pretty much like what we want, right?

Agree

> * And of course, we can collect the side-input on the driver and broadcast it as variable. That way we can also do a local join / lookup. Though, this has the disadvantage that we will need to evaluate (and broadcast) the side-input ahead of time during the translation of the Beam pipeline
> 
> To also mention Spark temp views, these are in fact just named `Dataset` for usage in SQL. All the above applies to them as well. Their data is distributed the same way across the cluster with the same implications.
> 
> Now, looking more closely, a couple of findings:
> 
> * To join on windows we have to first explode the dataset, so it consists rows of single windowed values. That's potentially costly.

yes, better to use another approach

> * Broadcast joins in Spark are implemented as follows: 1) Collect data on the driver. 2) Broadcast it. Turns out this isn't much different from the manual broadcast.

So then doing the manual broadcast seems better as it will allow you proper control and potential optimizations on the broadcast. Hence what you chose in the related PR.

> * Side-inputs are typically build involving a CombineGlobally, meaning we need a global reduce step leaving just 1 partition. If we could do this final reduce step on the driver, the data would be already available to be broadcasted. Unfortunately there's additional (primitive) processing steps in-between that make this difficult.  

Yes, that would have been a good improvement to avoid collecting to the driver. Let's see, maybe in a next step.

**Comment by cozos** [comment]
> If a PCollection serves as side-input to multiple ParDos, it would be evaluated, collected on the driver and finally broadcasted repeatedly for every such ParDo.

@mosche does this mean the pcollections are re-computed? So if you do:

```py
pcoll_1 = pipeline | "ParDo 1" >> ParDo(...)
pcoll_2 = pipeline | "ParDo 2" >> ParDo(..., my_side_input=pcoll_1)
pcoll_3 = pipeline | "ParDo 3" >>  ParDo(..., my_side_input=pcoll_2)
```

Will `ParDo 1` be computed 3 times, and `ParDo 2` be computed 2 times?

**Comment by satybald** [comment]
@mosche could you please clarify if this issue applies to spark structural streaming or batch RDD?

**Comment by mosche** [comment]
@cozos @satybald This only applies to the new experimental `Dataset` based batch runner (`SparkStructuredStreamingRunner`, but to be renamed), not the `RDD` based runner (`SparkRunner`)

**Comment by cozos** [comment]
Thank you. Out of curiosity does the recomputation thing happen?

**Comment by mosche** [comment]
@cozos Yes, the execution graph for that new experimental Dataset based runner was all lazy until recently, so nothing was cached. By now Datasets are cached if reused and broadcast variables used for side-inputs are shared.

**Comment by cozos** [comment]
Thank you for the clarification. If you care to know the context, I was digging into the Python `Write` ptransform, which reuses side inputs heavily:

https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/iobase.py#L1151-L1174

If I understand correctly, the previous behaviour which does recomputation of side inputs would be really bad for performance, as it would repeat the writing of files many times.

**Comment by mosche** [comment]
Closed by https://github.com/apache/beam/pull/24288
