### ISSUE TITLE
[Tour of Beam] [Task] Update Playground saveSnippet endpoint to allow updates of snippets

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#24086]
### What needs to happen?
Update Playground saveSnippet endpoint to allow updating snippets for authenticated ToB users
- update snippet model
- Update unit tests
- Update integration tests

### Issue Priority
Priority: 3

### Issue Component
Component: beam-playground

**Comment by eantyshev** [comment]
.take-issue
