### ISSUE TITLE
[Bug]: Thumb up/down icons not visible

### ISSUE THREAD

**Issue by rshamunov** [apache/beam#24085]
### What happened?

Open Playground page in a browser. Thumb up and thumb down Icons not visible on the left corner of the screen after "Enjoying Playground?" text

### Issue Priority

Priority: 2

### Issue Component

Component: beam-playground

**Comment by alexeyinkin** [comment]
.take-issue

**Comment by alexeyinkin** [comment]
Which branch is that? @olehborysevych

**Comment by alexeyinkin** [comment]
Not reproducible. Must be a defect in the particular build.

| | HTML Renderer | CanvasKit Renderer |
|-|-|-|
| `master` | ![image](https://user-images.githubusercontent.com/44893228/202387855-afb5fa28-f51a-463e-99c4-f98726fd96b4.png) | ![image](https://user-images.githubusercontent.com/44893228/202388379-d54655a1-11e9-4674-8a04-19a0e2f84321.png) |
| `tob-demo-deploy` | ![image](https://user-images.githubusercontent.com/44893228/202390489-4c090c2d-cb75-4b35-8780-bdbb39d4aa4c.png) | ![image](https://user-images.githubusercontent.com/44893228/202389945-740c4f3c-4097-414a-9145-26874195663a.png) |

**Comment by alexeyinkin** [comment]
@rshamunov to confirm.

**Comment by rshamunov** [comment]
it's not reproduced in my environment neither
