### ISSUE TITLE
[Feature Request]: Add a ValidatesContainer integration test that exercises --experiments=[no]use_sibling_sdk_workers

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#24092]
### What would you like to happen?

Add two tests to the existing dataflow suite that runs a RunnerV2 pipeline with the use_sibling_sdk_worker experiment explicitly enabled and disabled.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-harness

**Comment by tvalentyn** [comment]
to have less running pipelines, we can add this experiment to one of the existing tests in the suite, and remove it on one other test.

**Comment by ryanthompson591** [comment]
.take-issue

**Comment by ryanthompson591** [comment]
Run Python Dataflow ValidatesContainer

**Comment by ryanthompson591** [comment]
Run Python Dataflow ValidatesContainer

**Comment by ryanthompson591** [comment]
R: @tvalentyn 

I was trying to figure out if we should use the prebuild_sdk_container_engine flag in this test. WDYT?

**Comment by ryanthompson591** [comment]
oops I posted my comments on the issue instead of the PR ----  will fix.

**Comment by tvalentyn** [comment]
we don't need to use prebuiliding, but we need to make sure to use a UW if it's not used. also it should run on a vm that has at least 2 cores, which i think is the case by default.

**Comment by tvalentyn** [comment]
we could merge this with one of prebuilding tests to reduce the suite runtime (alhough that makes test scenario less specific..)
