### ISSUE TITLE
[Bug]: `Filter.whereFieldName` appears in docs but not available

### ISSUE THREAD

**Issue by laysakura** [apache/beam#24100]
### Problem

A doc says:

<https://beam.apache.org/documentation/programming-guide/#filtering-events>

```java
purchases.apply(Filter
    .whereFieldName("costCents", c -> c > 100 * 20));
```

Another doc says:

<https://javadoc.io/static/org.apache.beam/beam-sdks-java-core/2.42.0/org/apache/beam/sdk/schemas/transforms/Filter.html>

```java
 locations.apply(Filter
    .whereFieldName("latitude", lat -> lat < 40.720 && lat > 40.699));
```

But they don't compile because `Filter.whereFieldName()` is undefined.

### Workaround

I confirmed this worked.

```java
    PCollection<Row> nonNegTemperature = temperature.apply(
        Filter.<Row>create().whereFieldName("temperature", temp -> (float) temp >= 0));
```

### Solution

- Fix docs?
- Or provide methods from `Filter.Inner` to `Filter`?

### Issue Priority

Priority: 3

### Issue Component

Component: website

**Comment by kennknowles** [comment]
@reuvenlax what is the intended method here?

**Comment by reuvenlax** [comment]
It looks like create() is required.

**Comment by laysakura** [comment]
@kennknowles Yes. I'll try to create a PR later.

**Comment by kennknowles** [comment]
thanks!
