### ISSUE TITLE
[Task]: Validate that beam_PostCommit_Py_ValCont tests use runner_v2

### ISSUE THREAD

**Issue by ryanthompson591** [apache/beam#24107]
### What needs to happen?

beam_PostCommit_Py_ValCont tests were recently failing with a runner v1 stack trace.

However, the default should be runner_v2.

Investigate that these tests are using the right options.

Tests to investigate:

apache_beam.examples.wordcount_it_test.WordCountIT.test_wordcount_it_with_prebuilt_sdk_container_cloud_build
apache_beam.examples.wordcount_it_test.WordCountIT.test_wordcount_it_with_prebuilt_sdk_container_local_docker
apache_beam.examples.wordcount_it_test.WordCountIT.test_wordcount_fnapi_it
apache_beam.examples.wordcount_it_test.WordCountIT.test_wordcount_it_with_prebuilt_sdk_container_cloud_build
apache_beam.examples.wordcount_it_test.WordCountIT.test_wordcount_fnapi_it
apache_beam.examples.wordcount_it_test.WordCountIT.test_wordcount_it_with_prebuilt_sdk_container_local_docker
apache_beam.examples.wordcount_it_test.WordCountIT.test_wordcount_it_with_prebuilt_sdk_container_cloud_build
apache_beam.runners.dataflow.dataflow_exercise_metrics_pipeline_test.ExerciseMetricsPipelineTest.test_metrics_fnapi_it
apache_beam.examples.wordcount_it_test.WordCountIT.test_wordcount_it_with_prebuilt_sdk_container_local_docker

Related issue:
https://github.com/apache/beam/issues/23940

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-py-core

**Comment by ryanthompson591** [comment]
.take-issue

**Comment by AnandInguva** [comment]
.close-issue
