### ISSUE TITLE
[Bug]: Update Stager and Beam containers to allow for the new format of Apache Beam wheels. 

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#24110]
### What happened?

We need to update stager.py and the entrypoints for Beam's container and Dataflow internal container to work with the new wheel format.

pointers:

https://github.com/apache/beam/blob/master/sdks/python/apache_beam/runners/portability/stager.py#L721

https://github.com/apache/beam/blob/4b96193250a63b27721a8c5e1a3bd6ecff983093/sdks/python/container/boot.go#L336

### Issue Priority

Priority: 1

### Issue Component

Component: sdk-py-core

**Comment by tvalentyn** [comment]
see: https://pypi.org/project/apache-beam/#files  versus https://pypi.org/project/apache-beam/2.43.0rc1/#files

**Comment by tvalentyn** [comment]
@AnandInguva would you have time to look into this?

**Comment by chamikaramj** [comment]
P0 since this is blocking the ongoing release.

**Comment by AnandInguva** [comment]
.take-issue
