### ISSUE TITLE
[Playground] [Task] Fix Beam SDK version in playground example CI workflow

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#24120]
### What needs to happen?
Playground example CI uses docker image  SDK from docker hub. After braking changes are introduced to SDK and examples, our CI fails because we still use SDK image without new code. Need to build SDK image from source and use it in our CI  

### Issue Priority
Priority: 3

### Issue Component
Component: beam-playground

**Comment by rshamunov** [comment]
PRs merged
