### ISSUE TITLE
[Feature Request]: BigQuery Storage API read throttle

### ISSUE THREAD

**Issue by dmateusp** [apache/beam#24169]
### What would you like to happen?

Beam version: `2.36.0`

Jobs reading from the BigQuery Storage API can hit Quota limits and eventually fail with `The worker lost contact with the service.` (Dataflow runner)

The reason for the failure can be diagnosed on the API Monitoring (GCP) for BigQuery Storage API calls, where a spike in `429`s can be seen for `ReadRows` when the throughput of the job starts going downhill.

On the GCP side we've tried to resolve it through Quota increases, but it would be helpful to de-risk jobs crashing

related to:
* https://github.com/apache/beam/pull/15445 <- Shouldn't this PR have pervented this kind of issue?

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-gcp

**Comment by kennknowles** [comment]
@johnjcasey @reuvenlax @chamikaramj any thoughts?

**Comment by dmateusp** [comment]
hey thanks for having a look, it seems like the version of Beam we were using did not include https://github.com/apache/beam/pull/15445

We use Beam through SCIO and we don't have a release that includes Beam `2.43.0` yet, so I wasn't able to test the fix

We could close this issue for now and I could re-open it if we encounter it in 2.43.0 (which I don't think we will, given the fix above)

**Comment by kennknowles** [comment]
Sounds good. Thanks for replying!

**Comment by stfines-clgx** [comment]
as the actual GCP customer with the issue - it continues to occur in 2.46.0

**Comment by liferoad** [comment]
.reopen-issue

**Comment by liferoad** [comment]
@chamikaramj Is your PR supposed to write the appropriate error messages?

**Comment by chamikaramj** [comment]
Did you mean https://github.com/apache/beam/pull/15445 (different author) ?

I don't think that changes the retry behavior. Seems like it bumps up the metric used by Dataflow autoscaler to keep track of time the worker is throttled so that job does not unnecessarily scale up in that scenario.

Also note that this is BQ read API (different from BQ Storage Write API) in case that is what you are trying to track here.
