### ISSUE TITLE
[Task]: Documentation for ParDo/DoFn Life Cycle

### ISSUE THREAD

**Issue by Abacn** [apache/beam#24184]
### What needs to happen?

This is a fairly fundamental concept. We have unit tests for them e.g. https://github.com/apache/beam/blob/master/sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/ParDoLifecycleTest.java but no javadoc are seen. The task includes a page for the ParDo/DoFn Life Cycle in Beam website and some brief description in the documentation of each SDK's DoFn class.

Noticed here: #24180

### Issue Priority

Priority: 3

### Issue Component

Component: website

**Comment by kennknowles** [comment]
We do have some at https://beam.apache.org/documentation/programming-guide/#dofn

**Comment by DhirajSardar** [comment]
How can I get started  for contribution?

**Comment by svetakvsundhar** [comment]
@Abacn ; given that this is documented here [1], should we add to this page? Or is the current documentation sufficient?


[1]
 https://beam.apache.org/documentation/programming-guide/#dofn

**Comment by Abacn** [comment]
@svetakvsundhar Thanks for pinning. The documentation page is good overall, though some small points can be better documented (like TearDown is not guaranteed, i.e. best effort; or the number of actual DoFn instance is runner dependent. This was the initiative of this issue). That said there is still some small action items

- Add the beam website link to the Javadoc, for better visibility
- update the documentation for the aforementioned points

Will do

**Comment by svetakvsundhar** [comment]
.take-issue
