### ISSUE TITLE
[Task]: Version-control the default config.g.dart

### ISSUE THREAD

**Issue by alexeyinkin** [apache/beam#24200]
### What needs to happen?

`/playground/frontend/lib/config.g.dart` is required to build both Playground and Tour of Beam Flutter apps. It is generated during the new GKE deployment but for development purposes we must have this file in the repository so the project is immediately runnable after checkout.

However due to infrastructure migration issues we temporarily cannot have this file in the repository, and this must be fixed.

Meanwhile the workaround is copy an example file after checkout:

```bash
cp playground/frontend/lib/config.example.dart playground/frontend/lib/config.g.dart
```

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by damondouglas** [comment]
@MakarkinSAkvelon / @alexeyinkin / @olehborysevych Is this fix more involved or something that can be done quickly?
