### ISSUE TITLE
[Task]: Backend support for 'notebook' field in examples

### ISSUE THREAD

**Issue by alexeyinkin** [apache/beam#24225]
### What needs to happen?

In addition to GitHub link, examples may have 'notebook' field that leads to a hosted Google Colab notebook. On the backend:

1. 'notebook' field should be parsed from `beam-playground` comment.
2. The field should be stored with the example.
3. `notebookUrl` field should be added to gRPC responses for examples.

Also the current `link` field should be renamed to `githubUrl` for clarity.

The corresponding frontend issue: #24170

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by eantyshev** [comment]
.take-issue
