### ISSUE TITLE
[Failing Test]: Timeout waiting to lock gradle

### ISSUE THREAD

**Issue by apilloud** [apache/beam#24267]
### What happened?

https://ci-beam.apache.org/job/beam_PreCommit_SQL_Commit/5818/console

12:17:38 FAILURE: Build failed with an exception.
12:17:38 
12:17:38 * What went wrong:
12:17:38 A problem occurred configuring root project 'beam'.
12:17:38 > Timeout waiting to lock kotlin-dsl (/home/jenkins/.gradle/caches/7.5.1/kotlin-dsl). It is currently in use by another Gradle instance.
12:17:38   Owner PID: 189470
12:17:38   Our PID: 189710
12:17:38   Owner Operation: 
12:17:38   Our operation: 
12:17:38   Lock file: /home/jenkins/.gradle/caches/7.5.1/kotlin-dsl/kotlin-dsl.lock

### Issue Priority

Priority: 1

### Issue Component

Component: infrastructure

**Comment by apilloud** [comment]
https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/5784/console

Another varient of this:

6:45:03 Execution failed for task ':sdks:java:io:azure:compileTestJava'.
16:45:03 > Failed to store cache entry c2b6b9e488c64d739a3dbd8e90c6553a for task ':sdks:java:io:azure:compileTestJava': Timeout waiting to lock Build cache (/home/jenkins/.gradle/caches/build-cache-1). It is currently in use by another Gradle instance.
16:45:03   Owner PID: 3271069
16:45:03   Our PID: 3274029
16:45:03   Owner Operation: 
16:45:03   Our operation: 
16:45:03   Lock file: /home/jenkins/.gradle/caches/build-cache-1/build-cache-1.lock

**Comment by kennknowles** [comment]
I'm unclear whether there is a better or more appropriate way to have a gradle cache. Right now it is per node but I wonder if we are holding it wrong.

**Comment by kennknowles** [comment]
Just noting that I do continue to see this once in a while.

**Comment by kennknowles** [comment]
Has anyone seen this recently? I haven't gone so far as to manually or automatically inspect recent Jenkins logs.

**Comment by kennknowles** [comment]
This is happily green for now.
