### ISSUE TITLE
TypedSchemaTransformProvider returns an inconsistent configuration Schema object

### ISSUE THREAD

**Issue by ahmedabu98** [apache/beam#24361]
### What happened?

TypedSchemaTransformProvider's `configurationSchema()` method returns Schema object with inconsistent field orderings. A consistent Schema is needed to reliably create configuration Row objects to instantiate and use SchemaTransforms. 

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-gcp

**Comment by ahmedabu98** [comment]
.take-issue

**Comment by chamikaramj** [comment]
This should probably be in 2.44.0 milestone since it fixes an important issue that can affect x-lang based I/O connectors.
