### ISSUE TITLE
[Failing Test]: HadoopFormatIOElasticTest.classMethod ExceptionInInitializerError ContainerFetchException

### ISSUE THREAD

**Issue by apilloud** [apache/beam#24389]
### What happened?

15:49:51 > Task :sdks:java:io:hadoop-format:test
15:49:51 
15:49:51 org.apache.beam.sdk.io.hadoop.format.HadoopFormatIOElasticTest > classMethod FAILED
15:49:51     java.lang.ExceptionInInitializerError at Unsafe.java:-2
15:49:51         Caused by: org.testcontainers.containers.ContainerFetchException at HadoopFormatIOElasticTest.java:80
15:49:51             Caused by: java.lang.IllegalStateException at HadoopFormatIOElasticTest.java:80
15:50:10 

https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/5784/consoleFull

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 1

### Issue Component

Component: io-java-hadoop-format

**Comment by kennknowles** [comment]
This is a good candidate for moving out of the general "Java PreCommit"

**Comment by damccorm** [comment]
Closing since this is for a decommissioned Jenkins job
