### ISSUE TITLE
[Bug]: Daemon will be stopped at the end of the build after the daemon was no longer found in the daemon registry

### ISSUE THREAD

**Issue by apilloud** [apache/beam#24383]
### What happened?

https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/25030/console

Daemon will be stopped at the end of the build after the daemon was no longer found in the daemon registry
13:58:55 Remove shutdown hook failed
13:58:55 java.lang.IllegalStateException: Shutdown in progress
13:58:55 	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
13:58:55 	at java.lang.Runtime.removeShutdownHook(Runtime.java:231)
13:58:55 	at org.gradle.process.internal.shutdown.ShutdownHooks.removeShutdownHook(ShutdownHooks.java:38)
13:58:55 	at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:208)
13:58:55 	at org.gradle.process.internal.DefaultExecHandle.aborted(DefaultExecHandle.java:366)
13:58:55 	at org.gradle.process.internal.ExecHandleRunner.completed(ExecHandleRunner.java:108)
13:58:55 	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:84)
13:58:55 	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
13:58:55 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
13:58:55 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
13:58:55 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13:58:55 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13:58:55 	at java.lang.Thread.run(Thread.java:750)
13:58:55 ----- End of the daemon log -----
13:58:55 
13:58:55 
13:58:55 FAILURE: Build failed with an exception.
13:58:55 
13:58:55 * What went wrong:
13:58:55 Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

### Issue Priority

Priority: 1

### Issue Component

Component: infrastructure

**Comment by kileys** [comment]
Disabled the daemon as part of https://github.com/apache/beam/issues/21474. Closing.
