### ISSUE TITLE
[Bug]: RampupThrottlingFnTest.testRampupThrottler TooManyActualInvocations

### ISSUE THREAD

**Issue by apilloud** [apache/beam#24384]
### What happened?

14:53:07 > Task :sdks:java:io:google-cloud-platform:test
14:53:07 
14:53:07 org.apache.beam.sdk.io.gcp.datastore.RampupThrottlingFnTest > testRampupThrottler FAILED
14:53:07     java.lang.AssertionError at RampupThrottlingFnTest.java:106
14:53:07         Caused by: org.mockito.exceptions.verification.TooManyActualInvocations at RampupThrottlingFnTest.java:52
14:53:13 

https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/5782/consoleFull

### Issue Priority

Priority: 1

### Issue Component

Component: io-java-gcp

**Comment by kennknowles** [comment]
Good candidate to remove from the monster precommit

**Comment by BjornPrime** [comment]
.take-issue

**Comment by kennknowles** [comment]
These were split to their own job in #24584

**Comment by kennknowles** [comment]
https://ci-beam.apache.org/job/beam_PreCommit_Java_Hadoop_IO_Direct_Cron/ does not look flaky, but it could be useful to run it 10k times or something

**Comment by BjornPrime** [comment]
Thanks, I'll put it through its paces. Just trying to get my hands on something simple and IO-related.

**Comment by kennknowles** [comment]
My mistake, wrong job.

**Comment by kennknowles** [comment]
https://ci-beam.apache.org/job/beam_PreCommit_Java_GCP_IO_Direct_Cron/

**Comment by BjornPrime** [comment]
`./gradlew :sdks:java:io:google-cloud-platform:test --tests org.apache.beam.sdk.io.gcp.datastore.RampupThrottlingFnTest.java` ran 1000 times with no problems. Closing issue.

**Comment by BjornPrime** [comment]
.close-issue
