### ISSUE TITLE
[Task]: Add support for new regions to terraform scripts

### ISSUE THREAD

**Issue by rshamunov** [apache/beam#24395]
### What needs to happen?

Terraform scripts (playground/terraform/infrastructure/appengine) fail when a region name in GKE differs from region name in AppEngine.
https://cloud.google.com/appengine/docs/standard/locations
 
Deployment must work for all regions.

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by MakarkinSAkvelon** [comment]
.take-issue
