### ISSUE TITLE
[Task] Upgrade Jackson version.

### ISSUE THREAD

**Issue by lostluck** [apache/beam#24441]
### What needs to happen?

There are known vulnerabilities with the current used version (2.13.3), resolved in newer versions (2.14.1).

https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind

This shows up in security scanners, which may indicate a risk to users. Resolution is to update them.

### Issue Priority

Priority: 1

### Issue Component

Component: sdk-java-core

**Comment by kennknowles** [comment]
Merged to release branch.
