### ISSUE TITLE
[Failing Test]: Local environment tests failing on GHA

### ISSUE THREAD

**Issue by damccorm** [apache/beam#24460]
### What happened?

These tests are consistently failing - https://github.com/apache/beam/actions/workflows/local_env_tests.yml?query=branch%3Amaster

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1

### Issue Component

Component: sdk-py-core

**Comment by damccorm** [comment]
Not sure why, but this popped up immediately after the fix for #24432

**Comment by tvalentyn** [comment]
Do we need to increase lower bounds in https://github.com/apache/beam/blob/master/sdks/python/setup.py#L355-L356 ?

**Comment by damccorm** [comment]
> Do we need to increase lower bounds in https://github.com/apache/beam/blob/master/sdks/python/setup.py#L355-L356 ?

I don't think so? Is there something that you're specifically concerned with? I'd expect lower versions of pandas to work just fine.
