### ISSUE TITLE
[Task]: Create FileWriteSchemaTransformConfiguration

### ISSUE THREAD

**Issue by damondouglas** [apache/beam#24468]
## What work does this Task describe?

This task addresses #24464 through creation of a  `FileWriteSchemaTransformConfiguration` as outlined in the [design document](https://docs.google.com/document/d/1IOZrQ4qQrUS2WwQhadN35vX4AzhG4dyXMk1J-R1qJ9c/edit?usp=sharing).  The following outlines the `@AutoValue` based class diagrams where the corresponding `@AutoValue.Builder` inner class is not shown.

```mermaid
classDiagram

class FileWriteSchemaTransformConfiguration
<<abstract>> FileWriteSchemaTransformConfiguration
FileWriteSchemaTransformConfiguration : abstract +String getFormat()
FileWriteSchemaTransformConfiguration : abstract +String getFileNamePrefix()
FileWriteSchemaTransformConfiguration : abstract +String getCompression()
FileWriteSchemaTransformConfiguration : abstract +String getDelimiter()
FileWriteSchemaTransformConfiguration : abstract +Integer getNumShards()
FileWriteSchemaTransformConfiguration : abstract +Boolean getEnableSharding()
FileWriteSchemaTransformConfiguration : abstract +String getShardNameTemplate()
FileWriteSchemaTransformConfiguration : abstract +String getFileNameSuffix()
FileWriteSchemaTransformConfiguration : abstract +Row getCsvConfiguration()
FileWriteSchemaTransformConfiguration : abstract +Row getParquetConfiguration()
FileWriteSchemaTransformConfiguration : abstract +Row getXmlConfiguration()

class CsvConfiguration
<<abstract>> CsvConfiguration
CsvConfiguration : abstract +String getPreamble()
CsvConfiguration : abstract +String getFormat()

class ParquetConfiguration
<<abstract>> ParquetConfiguration
ParquetConfiguration : abstract +String getCompressionCodecName()
ParquetConfiguration : abstract +Integer getRowGroupSize()

class XmlConfiguration
<<abstract>> XmlConfiguration
XmlConfiguration : abstract +String getRootElement()
XmlConfiguration : abstract +String getCharset()
```

## What value may result from this Task's output?

The configuration is the point of entry into a File write support within a SchemaTransform context.  See #24464 for details.

### Ready

The following are blockers for beginning this task.

- [x] Community review of [design document](https://docs.google.com/document/d/1IOZrQ4qQrUS2WwQhadN35vX4AzhG4dyXMk1J-R1qJ9c/edit?usp=sharing)

### Done

The following are measures for marking this Task complete.

`@AutoValue` and `@AutoValue.Builder` classes for:
- [x] `FileWriteSchemaTransformConfiguration`
- [x] `CsvConfiguration`
- [x] `ParquetConfiguration`
- [x] `XmlConfiguration`

### Issue Priority

Priority: 2

### Issue Component

Component:  io-java-files

**Comment by damondouglas** [comment]
.take-issue

**Comment by damondouglas** [comment]
@kennknowles May I trouble you to modify this task to `P2` and `io-java-files` unless it will be updated automatically.  Thank you!

**Comment by kennknowles** [comment]
I _believe_ there are magic github bot commands like `.remove-label` and `.add-label` which you can use. Too bad you cannot do it simply by being assigned.
