### ISSUE TITLE
[Task]: Implement FileWriteSchemaTransformProvider

### ISSUE THREAD

**Issue by damondouglas** [apache/beam#24472]
## What work does this Task describe?

This task finalizes support for a transform that encodes Row elements and writes the serialized payload to a file or object system. The provider unifies and normalizes Beam file writing related details into a single schema aware configuration and produces a file writing transform such as FileIO.Write or TextIO.Write.

## What value may result from this Task's output?

 See #24464 for details.

### Ready

The following are blockers for beginning this task.

- [x] Community review of [design document](https://docs.google.com/document/d/1IOZrQ4qQrUS2WwQhadN35vX4AzhG4dyXMk1J-R1qJ9c/edit?usp=sharing)
- [x] #24469 
- [x] #24468 

### Done

The following are measures for marking this Task complete.

**Tests detect errors in:**

- [ ] validating `FileWriteSchemaTransformConfiguration` schema
- [ ] `PCollection<Row>` input to byte content according to the chosen format (avro, json, etc)
- [ ] `FileWriteSchemaTransformConfiguration` maps to the appropriately built IO such as AvroIO, ParquetIO, etc
- [ ] `PCollection<Row>` input to file system writes
- [ ] `PCollection<Row>` input to Google Cloud Storage object writes

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-files

**Comment by kennknowles** [comment]
Per https://beam.apache.org/contribute/issue-priorities/ "normal work" is P2
