### ISSUE TITLE
[Feature Request]: `IntervalWindow`'s [`start`, `end`) for merged windows (e.g. Sessions)

### ISSUE THREAD

**Issue by laysakura** [apache/beam#24510]
## Example dataset

Per-hour weather data.

```json
{"timestamp": "2022-08-01T00:00:00.000+00:00", "temperature [°C]": 0.0, "rainfall [mm]": 0.0}
{"timestamp": "2022-08-01T01:00:00.000+00:00", "temperature [°C]": 0.0, "rainfall [mm]": 0.0}
{"timestamp": "2022-08-01T02:00:00.000+00:00", "temperature [°C]": 0.0, "rainfall [mm]": 0.0}
```

## Example code

```java
    // 1-day session window
    PCollection<Float> windowedTemperature = temperatureOver30.apply(
        Window.<Float>into(
            Sessions.withGapDuration(Duration.standardDays(1))));

    PCollection<KV<Instant, Float>> windowedTemperatureWithDate = windowedTemperature.apply(
        ParDo.of(new DoFn<Float, KV<Instant, Float>>() {
          @ProcessElement
          public void processElement(
              @Element Float temperature,
              IntervalWindow window,
              OutputReceiver<KV<Instant, Float>> out) {
            Instant winEnd = window.maxTimestamp();

            System.out.println(window);  // PRINT HERE

            out.output(KV.of(winEnd, temperature));
          }
        }));
```

See the full codes: <https://gist.github.com/laysakura/175cf1137c8cb3356236ed7ab2443b71>

## Expected outputs from `println()`

```text
[2022-08-01T00:00:00.000Z..2022-08-02T02:00:00.000Z)
```

## Actual outputs from `println()`

```text
[2022-08-01T00:00:00.000Z..2022-08-02T00:00:00.000Z)
[2022-08-01T01:00:00.000Z..2022-08-02T01:00:00.000Z)
[2022-08-01T02:00:00.000Z..2022-08-02T02:00:00.000Z)
```

## Problem hypothesis and solution

`assignWindows()` has control to `IntervalWindow`: <https://github.com/apache/beam/blob/ec91ea4f6b83e6a8e3bd2041057fa90d0c8f0dd0/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/windowing/WindowFn.java#L59-L60>

but `mergeWindows()` doesn't: <https://github.com/apache/beam/blob/ec91ea4f6b83e6a8e3bd2041057fa90d0c8f0dd0/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/windowing/WindowFn.java#L88>.

So `mergeWindoews()` might have to modify `IntervalWindow.start` and `IntervalWindow.end` after merges of windows happen.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-java-core

**Comment by kennknowles** [comment]
This is a gap in our explanations. Assigning windows is like assigning keys. The actual grouping by window and merging them only happens during an aggregation aka `Combine` or `GroupByKey`.

**Comment by kennknowles** [comment]
In your full code you have a `Count.perKey()` and this will merge the windows.

**Comment by kennknowles** [comment]
I believe this is not a bug, but a question that we can continue to discuss but I will close the ticket. Feel free to reopen if you think it is appropriate.
