### ISSUE TITLE
[Failing Test]: Python Postcommits are failing.

### ISSUE THREAD

**Issue by AnandInguva** [apache/beam#24531]
### What happened?

https://ci-beam.apache.org/job/beam_PostCommit_Python38/3457/testReport/junit/apache_beam.examples.dataframe.taxiride_it_test/TaxirideIT/test_aggregation/

Failing tests
[apache_beam.examples.dataframe.taxiride_it_test.TaxirideIT.test_aggregation](https://ci-beam.apache.org/job/beam_PostCommit_Python38/3456/testReport/junit/apache_beam.examples.dataframe.taxiride_it_test/TaxirideIT/test_aggregation/)
[apache_beam.examples.dataframe.flight_delays_it_test.FlightDelaysTest.test_flight_delays](https://ci-beam.apache.org/job/beam_PostCommit_Python38/3456/testReport/junit/apache_beam.examples.dataframe.flight_delays_it_test/FlightDelaysTest/test_flight_delays/)
[apache_beam.examples.dataframe.taxiride_it_test.TaxirideIT.test_enrich](https://ci-beam.apache.org/job/beam_PostCommit_Python38/3456/testReport/junit/apache_beam.examples.dataframe.taxiride_it_test/TaxirideIT/test_enrich/)
[apache_beam.dataframe.io_it_test.ReadUsingReadGbqTests.test_ReadGbq_with_computation](https://ci-beam.apache.org/job/beam_PostCommit_Python38/3456/testReport/junit/apache_beam.dataframe.io_it_test/ReadUsingReadGbqTests/test_ReadGbq_with_computation/)

The postcommits are failing. This happened on Dec 2, 2022. https://github.com/apache/beam/pull/23973 might be the root cause. 

Running tests on revered PR https://github.com/apache/beam/pull/24530 to see if that PR is causing errors.

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1

### Issue Component

Component: sdk-py-core

**Comment by kennknowles** [comment]
Is there a common cause?

**Comment by AnandInguva** [comment]
The container tag needs to be updated to reflect the Pandas update.

**Comment by kennknowles** [comment]
try reverting the commit and running those ITs

**Comment by kennknowles** [comment]
OK then we can probably fix forward at the same and see which one passes tests first

**Comment by AnandInguva** [comment]
https://github.com/apache/beam/pull/24530 -> reverted PR to see if that is root cause.

**Comment by tvalentyn** [comment]
Are lower bounds for pandas set correctly ?

**Comment by Abacn** [comment]
Error message:
```
RuntimeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apache_beam/internal/dill_pickler.py", line 285, in loads
    return dill.loads(s)
  File "/usr/local/lib/python3.10/site-packages/dill/_dill.py", line 275, in loads
    return load(file, ignore, **kwds)
  File "/usr/local/lib/python3.10/site-packages/dill/_dill.py", line 270, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/usr/local/lib/python3.10/site-packages/dill/_dill.py", line 472, in load
    obj = StockUnpickler.load(self)
  File "/usr/local/lib/python3.10/site-packages/dill/_dill.py", line 462, in find_class
    return StockUnpickler.find_class(self, module, name)
AttributeError: Can't get attribute '_NoDefault' on <module 'pandas._libs.lib' from '/usr/local/lib/python3.10/site-packages/pandas/_libs/lib.cpython-310-x86_64-linux-gnu.so'>
```

**Comment by damccorm** [comment]
Should be fixed now
