### ISSUE TITLE
[Task]: Support Protobuf v4 in Python SDK.

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#24569]
### What needs to happen?

Upgrade upper & lower bounds to use Protobuf v4.

### Issue Priority

Priority: 2

### Issue Component

Component: dependencies

**Comment by tvalentyn** [comment]
@AnandInguva would you have time sometime this/next week to take a look if Protobuf v4 just works? Thanks.

**Comment by AnandInguva** [comment]
.take-issue

**Comment by AnandInguva** [comment]
We are still blocked on Tensorflow for the protobuf update. Tensorflow is still on `protobuf >= 3.9.2, < 3.20`
https://github.com/tensorflow/tensorflow/blob/d5b57ca93e506df258271ea00fc29cf98383a374/tensorflow/tools/pip_package/setup.py#L102

**Comment by aucampia** [comment]
> We are still blocked on Tensorflow for the protobuf update. Tensorflow is still on `protobuf >= 3.9.2, < 3.20` https://github.com/tensorflow/tensorflow/blob/d5b57ca93e506df258271ea00fc29cf98383a374/tensorflow/tools/pip_package/setup.py#L102

I made an upstream issue to track this:

- https://github.com/tensorflow/tensorflow/issues/59221
