### ISSUE TITLE
[Task]: Gradle tasks for ToB frontend

### ISSUE THREAD

**Issue by alexeyinkin** [apache/beam#24563]
### What needs to happen?

The tasks should mirror the tasks of Playground frontend. In particular:

- `generate`
- `generateCode`
- `pubGet`
- `format`
- `run`
- `test`
- `precommit`
- `cleanFlutter`
- `cleanGenerated`

Some of the Playground's tasks calls appropriate tasks on `playground_components`, and this is easy because the latter is a sub-project of the former.

ToB also depends on `playground_components`, so ToB's tasks should call `playground_components`'s tasks in all the same cases that Playground does. This may be a bit harder because that is not a sub-project anymore.

The Gradle project file for ToB should be in `.kts` format.

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

**Comment by nausharipov** [comment]
.take-issue
