### ISSUE TITLE
[Tour of Beam] [Task] Fix broken display of tabs/spaces in markdown

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#24615]
### What needs to happen?
Need to fix broken display of tabs/spaces in ToB learning materials markdown.

### Issue Priority
Priority: 3

### Issue Component
Component: tour-of-beam

**Comment by nausharipov** [comment]
.take-issue

**Comment by ZhengLin-Li** [comment]
@olehborysevych  let's close this issue as it has been resovled by #365
