### ISSUE TITLE
[Tour of Beam] [Task] Fix broken Timer in ToB Run/Cancel button or hide it completely

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#24617]
### What needs to happen?
Timer in Tour of Beam Run/Cancel button runs forever. Need to fix it or not show it if it can't be fixed.

Issue Priority
Priority: 3

### Issue Component
Component: tour-of-beam

**Comment by alexeyinkin** [comment]
.take-issue

**Comment by alexeyinkin** [comment]
Plan:
1. In `PlaygroundController`, remove `executionTime` stream.
2. Move `PlaygroundController.runCode` method to `SnippetEditingController`.
3. Add `SnippetEditingController.executionStartDate`, set and unset it properly when running, finishing, and cancelling.
4. Add the calculation of elapsed time to the button itself.

**Comment by nausharipov** [comment]
.take-issue

**Comment by nausharipov** [comment]
@olehborysevych @alexeyinkin is the timer needed?
