### ISSUE TITLE
[Feature Request]: A more detailed logging with file deletion in filebasedsink

### ISSUE THREAD

**Issue by xzhang95** [apache/beam#24638]
### What would you like to happen?

When using Google Cloud Dataflow, sometimes it does not delete the temp files generated and will caused error in downstream tasks. 
It seems there is no logging here with temp file deletion.
https://github.com/apache/beam/blob/83679216cce2d52dbeb7e837f06ca1d57b31d509/sdks/python/apache_beam/io/filebasedsink.py#L367-L371
Would it be possible for a more detailed logging on this that can give information on whether it actually deletes the temp files?  And also it would be nice to have logging on what error happened if it didn't delete the files.

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [x] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by kennknowles** [comment]
Makes sense. Would you like to contribute a change to add this logging?

**Comment by tvalentyn** [comment]
> Would it be possible for a more detailed logging on this that can give information on whether it actually deletes the temp files?

It's possible to add a debug logging when we do delete a file, but that might be noisy logs in most cases? It's possible to add as a debug-level logging, so that you can opt-in if you find them helpful.

When we don't delete, typically some error happened, for example OOM, and likely this will be surfaced in the logging in some way, for example there may be messages like: `SDK harness sdk-0-0 disconnected` and Error log entries.

**Comment by xzhang95** [comment]
In our case, it seems when it doesn't delete, other logging message didn't appear as well so it was hard for us to determine the actual reason. Hence we think a warning or debug message here might help with giving more info.

I can get a PR to add on to this

**Comment by Abacn** [comment]
Fixed by #24653
