### ISSUE TITLE
[Bug]: POM of beam-sdks-java-core 2.45.0-SNAPSHOT is broken

### ISSUE THREAD

**Issue by mosche** [apache/beam#24675]
### What happened?

As of https://github.com/apache/beam/pull/24271 the pom of `beam-sdks-java-core` is broken. There's no version specified for `org.json:json` in `BeamModulePlugin`:

```groovy
json_org: "org.json:json", // Try to keep in sync with google_cloud_platform_libraries_bom transitive deps.
everit_json_schema: "com.github.erosb:everit-json-schema:${everit_json_version}",
```

```
[WARNING] The POM for org.apache.beam:beam-sdks-java-core:jar:2.45.0-20221214.234815-14 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for org.apache.beam:beam-sdks-java-core:2.45.0-SNAPSHOT
[ERROR] 'dependencies.dependency.version' for org.json:json:jar is missing. @
```

@pabloem @lukecwik Could you have a look?

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by aromanenko-dev** [comment]
I raised this one to P1 since it causes the compilation fails of user code.

**Comment by aromanenko-dev** [comment]
@pabloem 
Kind ping on this - this issue causes a broken `beam-sdks-java-core` artifacts.
