### ISSUE TITLE
Python: CombineGlobally() needs to be able to produce expected output when processing multiple windows simultaneously

### ISSUE THREAD

**Issue by BjornPrime** [apache/beam#24683]
### What would you like to happen?

CombineGlobally() is supposed to reduce a PCollection to a single value. When given multiple windows to process, it would previously fail due to an assert statement that limited the max length of its output to one. I replaced this assert statement with a more descriptive error statement here (#24435), but a comprehensive solution for situations when the transform handles multiple windows, and thus multiple PCollections, at once, is still needed, since this situation is expected to arise from fairly run-of-the-mill use of the transform in streaming pipelines.

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by liferoad** [comment]
.take-issue

**Comment by robertwb** [comment]
We would need to define what it means to combine globally with defaults for non-trivial windowing. (Presumably that'd be a empty value for every empty window, so we'd need some way to enumerate windows.) If one wants to see combined values only when there is data, `without_defaults` should be advised and used.

**Comment by liferoad** [comment]
fixed by #26922
