### ISSUE TITLE
[Task]: Move CodeRunner.outputType into a view

### ISSUE THREAD

**Issue by alexeyinkin** [apache/beam#24691]
### What needs to happen?

It is not a controller's job to store a filter for the output.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by alexeyinkin** [comment]
.take-issue

**Comment by nausharipov** [comment]
.take-issue
