### ISSUE TITLE
[Tour of Beam] [Task] Support saving multifile examples to datastore

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#24694]
### What needs to happen?
Need to update Playground CI\CD python scripts to support multifile examples:

- support new tag for multifile examples in python scripts
- saving multiply files to datastore
-  replace hardcoded number of files to actual number of files for multifile examples
- update tests 

### Issue Priority
Priority: 2

### Issue Component
Component: beam-playground, tour-of-beam

**Comment by eantyshev** [comment]
.take-issue
