### ISSUE TITLE
[Task]: Align terraform variables between manual and CloudBuild deployment

### ISSUE THREAD

**Issue by rshamunov** [apache/beam#24707]
### What needs to happen?
1) Rename 'location' to 'zone'
2) Ensure default values for TF variables aligned
3) Add a section to readme to deploy examples catalog

See also:
https://github.com/apache/beam/pull/24593#pullrequestreview-1221287008

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by MakarkinSAkvelon** [comment]
.take-issue
