### ISSUE TITLE
[Task]: Update frontend to support RunCode method for examples with datasets and emulators

### ISSUE THREAD

**Issue by rshamunov** [apache/beam#24703]
### What needs to happen?

RunCode GRPC method must be called with additional parameters for examples with Kafka emulators

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Malarg** [comment]
.take-issue
