### ISSUE TITLE
[Bug]: links with 404 error

### ISSUE THREAD

**Issue by bullet03** [apache/beam#24745]
### What happened?

Steps to reproduce:

1. Open [https://beam.apache.org/documentation/io/connectors/](https://beam.apache.org/documentation/io/connectors/) page
2. Scroll to the table Built-in I/O Connectors
3. Scroll to SparkReceiverIO at the bottom of the table
4. Click on the ✔ [native](https://beam.apache.org/releases/javadoc/current/org/apache/beam/sdk/io/sparkreceiver/2/SparkReceiverIO.html)

Actual result: link will lead to the page with 404 error
Expected result: link will lead to the page with no error or there is no link, just text

![404_error](https://user-images.githubusercontent.com/61748758/208890930-77720279-4802-4c63-a85b-b08d218f4d87.gif)

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [X] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by bullet03** [comment]
.take-issue

**Comment by Abacn** [comment]
Reopen and set milestone to v2.46.0 to remind us add back the removed links after v2.45.0 release
