### ISSUE TITLE
[Failing Test]: Exclude MultimapState tests from  Dataflow VR suites

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#24750]
### What happened?

Validates runner and  VR Java11/Java17/Streaming test suites are failing after https://github.com/apache/beam/pull/23491 was merged, example:

https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/4492/

```
org.apache.beam.sdk.transforms.ParDoTest$StateTests.testMultimapStateClear

Failing for the past 1 build (Since #4492 )
Took 5.2 sec.
Error Message
java.lang.UnsupportedOperationException: DataflowRunner does not currently support MultimapState
Stacktrace
java.lang.UnsupportedOperationException: DataflowRunner does not currently support MultimapState
	at org.apache.beam.runners.dataflow.DataflowRunner.verifyDoFnSupported(DataflowRunner.java:2427)
	at org.apache.beam.runners.dataflow.BatchStatefulParDoOverrides$StatefulMultiOutputParDo.expand(BatchStatefulParDoOverrides.java:192)
	at org.apache.beam.runners.dataflow.BatchStatefulParDoOverrides$StatefulMultiOutputParDo.expand(BatchStatefulParDoOverrides.java:177)
	at org.apache.beam.sdk.Pipeline.applyReplacement(Pipeline.java:576)
```

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
@zhengbuqian would you mind excluding relevant tests on Dataflow for now? Thanks!
cc: @lukecwik

**Comment by lukecwik** [comment]
This should be as simple as excluding the test category

**Comment by lukecwik** [comment]
Is this now fixed?

Note that you can add `fixes #YYY` to the body of a PR and it will auto-close the issue when the PR is merged.

**Comment by zhengbuqian** [comment]
Yes this has been fixed, the newest runs of the failed test are passing https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/
