### ISSUE TITLE
[Failing Test]: sklearnInferenceTest is failing in Python 3.9 PostCommit

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#24787]
### What happened?

Sample failure:

https://ci-beam.apache.org/job/beam_PostCommit_Python39/1266/consoleText

> Task :sdks:python:test-suites:direct:py39:sklearnInferenceTest FAILED

model = <[AttributeError("'OneHotEncoder' object has no attribute 'sparse_output'") raised in repr()] Pipeline object at 0x7f15ef958b80>

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
@AnandInguva could you please take a look? Thanks!

**Comment by tvalentyn** [comment]
@kennknowles FYI this might be failing on the release branch as well, so tentatively adding a milestone. feel free to remove if that's not the case.

**Comment by AnandInguva** [comment]
.take-issue

**Comment by AnandInguva** [comment]
Thanks. taking a look now.

**Comment by AnandInguva** [comment]
I see the error [1mSklearnInference::test_sklearn_regression[0m - AttributeError: 'ColumnTransformer' object has no attribute '_name_to_fitted_passthrough' [while running 'RunInference all_features/BeamML_RunInference']

**Comment by AnandInguva** [comment]
The tets uses models run with sklearn 1.1.0. These were working fine with later versions but started failing with sklearn 1.2.0. 

I think the models are not backward compatible.

**Comment by AnandInguva** [comment]
https://scikit-learn.org/stable/model_persistence.html#interoperable-formats.

This explains sklearn models should be used for inference on the same version it is trained on. It may work on newer versions but in not advisable and it may fail.

Our models fails on v1.2.0. So we need to retrain the model or have an automated way of doing it in the pipeline.

**Comment by kennknowles** [comment]
I'm still trying to reproduce. Currently on the release branch locally it continues to fail to set up the virtualenv ([scan](https://gradle.com/s/6ctun4oxtdvs4)).

**Comment by kennknowles** [comment]
Actually I read that wrong. Anyhow here is the failure I am seeing (also you can see it in the scan):

```
>>> RUNNING integration tests with pipeline options: --runner=TestDirectRunner --project=apache-beam-testing --region=us-central1 --staging_location=gs://temp-storage-for-end-to-end-tests/staging-it --temp_location=gs://temp-storage-for-end-to-end-tests/temp-it --output=gs://temp-storage-for-end-to-end-tests/py-it-cloud/output --sdk_location=build/apache-beam.tar.gz --requirements_file=postcommit_requirements.txt --num_workers=1 --sleep_secs=20 --kms_key_name=projects/apache-beam-testing/locations/global/keyRings/beam-it/cryptoKeys/test --dataflow_kms_key=projects/apache-beam-testing/locations/global/keyRings/beam-it/cryptoKeys/test |  
-- | --
  | >>>   pytest options: --capture=no --numprocesses=8 --timeout=4500 --color=yes --log-cli-level=INFO |  
  | >>>   collect markers: -m=uses_sklearn and it_postcommit |  
  | ImportError while loading conftest '/Users/klk/GitHub/apache/beam/sdks/python/conftest.py'. |  
  | conftest.py:22: in <module> |  
  | from apache_beam.options import pipeline_options |  
  | apache_beam/__init__.py:92: in <module> |  
  | from apache_beam import coders |  
  | apache_beam/coders/__init__.py:17: in <module> |  
  | from apache_beam.coders.coders import * |  
  | apache_beam/coders/coders.py:59: in <module> |  
  | from apache_beam.coders import coder_impl |  
  | apache_beam/coders/coder_impl.py:57: in <module> |  
  | from fastavro import parse_schema |  
  | ../../build/gradleenv/1398941893/lib/python3.9/site-packages/fastavro/__init__.py:47: in <module> |  
  | import fastavro.read |  
  | ../../build/gradleenv/1398941893/lib/python3.9/site-packages/fastavro/read.py:4: in <module> |  
  | from . import _read_py as _read  # type: ignore |  
  | ../../build/gradleenv/1398941893/lib/python3.9/site-packages/fastavro/_read_py.py:11: in <module> |  
  | import lzma |  
  | /Users/klk/.pyenv/versions/3.9.11/lib/python3.9/lzma.py:27: in <module> |  
  | from _lzma import * |  
  | E   ModuleNotFoundError: No module named '_lzma' |  
  |   |  
  | FAILURE: Build failed with an exception.
```

**Comment by AnandInguva** [comment]
Hm looks like the error is not related to the actual sklearn test but a dependency issue on fastavro?

**Comment by kennknowles** [comment]
The cherrypicks do not seem to have fixed this problem.

**Comment by kennknowles** [comment]
https://stackoverflow.com/questions/59690698/modulenotfounderror-no-module-named-lzma-when-building-python-using-pyenv-on suggests `brew install xz` and then reinstall the pyenv python versions. Trying that.

**Comment by kennknowles** [comment]
Or potentially `PYTHON_CONFIGURE_OPTS="--enable-framework"`

**Comment by AnandInguva** [comment]
> The cherrypicks do not seem to have fixed this problem.

Maybe it is due to different issue. Now the Sklearn tests pass
![image](https://user-images.githubusercontent.com/34158215/210859629-5ea0b5ed-acf5-4b3b-b0c1-1288a0c74d5f.png)

**Comment by kennknowles** [comment]
After installing xz and reinstalling python 3.9 I got `ImportError: cannot import name 'schema_pb2' from 'apache_beam.portability.api' (unknown location)`

**Comment by kennknowles** [comment]
Seems unrelated, but still preventing easy verification of release branch. I know we only _need_ it to pass in Jenkins or a different environment, but I would not like to have it fragile

**Comment by kennknowles** [comment]
I've confirmed on a linux box that this succeeds and I see `sdks/python/apache_beam/portability/api/__init__.py`. On my mac laptop it fails and I do not see that file. I'm not sure if it just failed in some other way, if it is nondeterministic or nonhermetic or what. I don't think this has to block the release, but should stay open and be fixed to be reliable.

**Comment by kennknowles** [comment]
It worked on a clean git clone.
