### ISSUE TITLE
[Failing Test]: org.apache.beam.sdk.io.gcp.pubsub.PubsubSchemaIT.classMethod in beam_PostCommit_Java_DataflowV1 and V2

### ISSUE THREAD

**Issue by Abacn** [apache/beam#24802]
### What happened?

error message:
```
org.apache.beam.sdk.io.gcp.pubsub.PubsubSchemaIT.classMethod

Error Message
java.nio.file.NoSuchFileException: file:/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_DataflowV2/src/sdks/java/io/google-cloud-platform/build/libs/beam-sdks-java-io-google-cloud-platform-2.45.0-SNAPSHOT-tests.jar!/org/apache/beam/sdk/io/gcp/pubsub/avro_all_data_types_flat_schema.json
```

caused by #24443

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by damondouglas** [comment]
.take-issue

**Comment by lukecwik** [comment]
Can we disable the test if the fix is not obvious?
