### ISSUE TITLE
[Bug]: Playground Examples CI / check (java) / pre-check (pull_request) 

### ISSUE THREAD

**Issue by damondouglas** [apache/beam#24807]
### What happened?

The Playground Examples CI / check (java) / pre-check (pull_request) fails when changing the names of files.
For example, https://github.com/apache/beam/actions/runs/3797038264/jobs/6457649054 shows the error message:

```
FileNotFoundError: [Errno 2] No such file or directory: '../../sdks/java/io/fileschematransform/src/main/java/org/apache/beam/sdk/io/fileschematransform/FileWriteSchemaTransformFormatProviders.java'
```

In the context of the PR check, the directory `fileschematransform` was changed to `file-schema-transform`.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by olehborysevych** [comment]
Thank you @damondouglas ! Working on it.
