### ISSUE TITLE
[Task]: Use exclusion list in python precommit instead of inclusion list

### ISSUE THREAD

**Issue by damccorm** [apache/beam#24813]
### What needs to happen?

With #24204 we are adopting a list of subfolders to run the python precommit on; it would be better to have a catch-all version that just excludes some directories we're sure we're testing. This is less likely to be brittle and miss tests we add in future new subdirectories.

Additional context - https://github.com/apache/beam/pull/24204#discussion_r1058408893

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
#24204 is breaking python precommit
```
ERROR: module or package not found: 'apache_beam/*.py (missing __init__.py?)

ERROR: InvocationError for command /home/jenkins/jenkins-slave/workspace/beam_PreCommit_Python_Cron/src/sdks/python/test-suites/tox/py39/build/srcs/sdks/python/scripts/run_pytest.sh py39-cython ''"'"'apache_beam/*.py apache_beam/coders apache_beam/internal apache_beam/io apache_beam/metrics apache_beam/ml apache_beam/options apache_beam/portability apache_beam/testing apache_beam/tools apache_beam/typehints apache_beam/utils'"'"'' (exited with code 4)
```
likely posargs does not support wildcard `apache_beam/*.py` so we can only use exclusion list, actually

**Comment by damccorm** [comment]
Not sure why this didn't show up in the runs I queued earlier - https://github.com/apache/beam/pull/24855 should fix
