### ISSUE TITLE
[Task]: Adapt Playground CI/CD scripts to support GCP Datastore multitenancy

### ISSUE THREAD

**Issue by rshamunov** [apache/beam#24815]
### What needs to happen?

Add an input variable for CI/CD scripts to support custom namespaces for Datastore client. 

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by TSultanov** [comment]
.take-issue
