### ISSUE TITLE
[Bug]:  The document, "Get the SDK and the examples" section of "Go SDK Quickstart", can be improved

### ISSUE THREAD

**Issue by ZhengLin-Li** [apache/beam#24845]
### What happened?

The **_Get the SDK and the examples_** section of _**Go SDK Quickstart**_ is not accurate, the document can be improved. Here is the link: [https://beam.apache.org/get-started/quickstart-go/#set-up-your-environment](https://beam.apache.org/get-started/quickstart-go/#set-up-your-environment)

After ensuring that my go version meets the requirement, I followed the instruction and tried to run the command `go get -u github.com/apache/beam/sdks/v2/go/pkg/beam` on my machine in an empty folder, I got the following error:

```bash
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

**It seems that we need to run `go mod init` first.** I believe this section of the documentation is not very friendly for beginners to get started, especially those who are new to the Go programming language. 

So, I propose that we can add additional information for those who are new to Beam and Go. This can be achieved by adding `go mod init` before `go get -u github.com/apache/beam/sdks/v2/go/pkg/beam`.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by yyy1000** [comment]
I think the original command

> go get -u github.com/apache/beam/sdks/v2/go/pkg/beam

could work if you have initiated your go module using "go mod init"

**Comment by ZhengLin-Li** [comment]
> I think the original command
> 
> > go get -u github.com/apache/beam/sdks/v2/go/pkg/beam
> 
> could work if you have initiated your go module using "go mod init"

Yes, this works. Thanks for your comment.
