### ISSUE TITLE
[Task]: Fix Example CI script failing on new examples

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#24899]
What needs to happen?
Playground Example CI fails when new examples are added.
This is due to example categories are not initialised in checker.py

Issue Priority
Priority: 3 (bug fix)

Issue Components
 

- [ ] Component: Python SDK
- [ ]  Component: Java SDK
- [ ]  Component: Go SDK
- [ ]  Component: Typescript SDK
- [ ]  Component: IO connector
- [ ]  Component: Beam examples
- [x]  Component: Beam playground
- [ ]  Component: Beam katas
- [ ]  Component: Website
- [ ]  Component: Spark Runner
- [ ]  Component: Flink Runner
- [ ]  Component: Samza Runner
- [ ]  Component: Twister2 Runner
- [ ]  Component: Hazelcast Jet Runner
- [ ]  Component: Google Cloud Dataflow Runner

**Comment by TSultanov** [comment]
.take-issue
