### ISSUE TITLE
[Task]: Separate positive and negative feedback texts

### ISSUE THREAD

**Issue by alexeyinkin** [apache/beam#24901]
### What needs to happen?

The report: https://datastudio.google.com/reporting/efefcabd-c537-4013-b4ef-1b6371fe8f6f/page/tWDGB/edit

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by alexeyinkin** [comment]
.take-issue

**Comment by nausharipov** [comment]
.take-issue
