### ISSUE TITLE
[Playground][Task] Migrate Playground to Google Analytics 4

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#24924]
### What needs to happen?
Need to add analytics events for ToB application:

Please consider following set of events and metrics:

Tour Of Beam Analytics Metrics 

- Audience
- Number of users
- New users
- Number of Sessions per User
- Sessions
- Avg. Session Duration
- New Visitor vs Returning Visitor
- Language breakdown
- Country breakdown
- Device breakdown
- Registered\Anonymous users

Tour Of Beam Usage

- Units opened
1. By Unit  
2. By SDK

- Examples run 
1. By example
2. By SDK

- Examples modified 
1. By Example
2. By SDK

- Units completed 
1. By Unit
2. By SDK 

- Modules completed ???
1. By Module 
2. By SDK

- Feedback (likes\dislikes)
1. By units
2. By SDK

- Time spent in a unit ??? 
1. By Unit 
2. By SDK

### Issue Priority
Priority: 3 

### Issue Components:
tour-of-beam

**Comment by nausharipov** [comment]
.take-issue
