### ISSUE TITLE
[Failing Test]: Python PostCommit failing: Dataflow test apache_beam.io.gcp.bigquery_json_it_test.BigQueryJsonIT.test_query_read 

### ISSUE THREAD

**Issue by Abacn** [apache/beam#24934]
### What happened?

Error message:

failing since midnight of Jan 7

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Python38/3587/
https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Python39/1309/
https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Python310/322/

Python37 also failed with this test but does not show in Test Result Tab (shown in log):
```
06:25:27 =========================== short test summary info ============================
06:25:27 FAILED apache_beam/io/gcp/bigquery_json_it_test.py::BigQueryJsonIT::test_query_read - 
```

The error message is
>```
apache_beam.testing.util.BeamAssertException: Failed assert: [{'country_code': 'usa', 'past_leader': '"George W. Bush"', 'gdp': '58559.675', 'city_name': '"Los Angeles"', 'landmark_name': '"Golden Gate Bridge"'}, {'country_code': 'aus', 'past_leader': '"Kevin Rudd"', 'gdp': '58043.581', 'city_name': '"Melbourne"', 'landmark_name': '"Great Barrier Reef"'}, {'country_code': 'special', 'past_leader': '"!@#$%^&*()_+"', 'gdp': '421.7', 'city_name': '"Bikini Bottom"', 'landmark_name': '"Willy Wonka\'s Factory"'}] == [{'country_code': 'aus', 'past_leader': None, 'gdp': '58043.581', 'city_name': '"Melbourne"', 'landmark_name': '"Great Barrier Reef"'}, {'country_code': 'special', 'past_leader': None, 'gdp': '421.7', 'city_name': '"Bikini Bottom"', 'landmark_name': '"Willy Wonka\'s Factory"'}, {'country_code': 'usa', 'past_leader': None, 'gdp': '58559.675', 'city_name': '"Los Angeles"', 'landmark_name': '"Golden Gate Bridge"'}], unexpected elements [{'country_code': 'aus', 'past_leader': None, 'gdp': '58043.581', 'city_name': '"Melbourne"', 'landmark_name': '"Great Barrier Reef"'}, {'country_code': 'special', 'past_leader': None, 'gdp': '421.7', 'city_name': '"Bikini Bottom"', 'landmark_name': '"Willy Wonka\'s Factory"'}, {'country_code': 'usa', 'past_leader': None, 'gdp': '58559.675', 'city_name': '"Los Angeles"', 'landmark_name': '"Golden Gate Bridge"'}], missing elements [{'country_code': 'usa', 'past_leader': '"George W. Bush"', 'gdp': '58559.675', 'city_name': '"Los Angeles"', 'landmark_name': '"Golden Gate Bridge"'}, {'country_code': 'aus', 'past_leader': '"Kevin Rudd"', 'gdp': '58043.581', 'city_name': '"Melbourne"', 'landmark_name': '"Great Barrier Reef"'}, {'country_code': 'special', 'past_leader': '"!@#$%^&*()_+"', 'gdp': '421.7', 'city_name': '"Bikini Bottom"', 'landmark_name': '"Willy Wonka\'s Factory"'}] [while running 'assert_that/Match-ptransform-43']
```

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
The assertion fail due to returned results has "past leader=None" where there supposed to be not Null string. Checked that apache-beam-testing.bq_jsontype_test_nodelete.json_data did not modify, however.

**Comment by Abacn** [comment]
Apparently it is a BigQuery bug?? Doing the query on bigquery UI also get null for past leader

**Comment by Abacn** [comment]
Same test in Java SDK also causes Java PostCommit fail.

**Comment by emkornfield** [comment]
What region is primarily used for testing?

**Comment by Abacn** [comment]
tests green again.
