### ISSUE TITLE
[Bug]: Py quick start has out dated python version information

### ISSUE THREAD

**Issue by aaltay** [apache/beam#25002]
### What happened?

There is a note about "The Python SDK supports Python 3.6, 3.7, and 3.8. Beam 2.24.0 was the last release with support for Python 2.7 and 3.5.". This is no longer accurate since py 3.9, 3.10 are supported as well. We need to update this and other instances, and find a way to keep this up-to-date in the future.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [X] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
Thanks. 
@AnandInguva Can you PTAL as part of your new  version support work? this can also wait until next  week.

**Comment by AnandInguva** [comment]
.take-issue
