### ISSUE TITLE
### java.lang.NoSuchMethodError: 'io.grpc.MethodDescriptor com.google.bigtable.v2.BigtableGrpc.getPingAndWarmMethod()'

### ISSUE THREAD

**Issue by hiroshitash** [apache/beam#25005]
I am seeing an error below with apache beam version 2.43.0. 

testWriteRead(com.evernote.de.iterable.RefreshUsersBtTest)  Time elapsed: 1.717 sec  <<< ERROR!
java.lang.NoSuchMethodError: 'io.grpc.MethodDescriptor com.google.bigtable.v2.BigtableGrpc.getPingAndWarmMethod()'
	at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStub.createPingAndWarmCallable(EnhancedBigtableStub.java:835)
	at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStub.<init>(EnhancedBigtableStub.java:290)
	at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStub.create(EnhancedBigtableStub.java:153)
	at com.google.cloud.bigtable.data.v2.BigtableDataClient.create(BigtableDataClient.java:162)
	at com.evernote.de.iterable.RefreshUsersBtTest.setUp(RefreshUsersBtTest.java:60)

The issue is explained below where two versions (1.27.1 and 2.14.1) of google-cloud-bigtable are included and getPingAndWarmMethod is not found in version 1.27.1.

              ### grpc-google-cloud-bigtable-v2 version

```
(com.google.api.grpc:grpc-google-cloud-bigtable-v2:1.27.1) com.google.bigtable.v2.BigtableGrpc's method getPingAndWarmMethod() is not found;
  referenced by 1 class file
    com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStub (com.google.cloud:google-cloud-bigtable:2.11.0)
  Cause:
    Dependency conflict: com.google.api.grpc:grpc-google-cloud-bigtable-v2:1.27.1 does not define com.google.bigtable.v2.BigtableGrpc's method getPingAndWarmMethod() but com.google.api.grpc:grpc-google-cloud-bigtable-v2:2.11.0 defines it.
      selected: org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.42.0-SNAPSHOT / com.google.cloud.bigtable:bigtable-client-core:1.26.3 (compile) / com.google.api.grpc:grpc-google-cloud-bigtable-v2:1.27.1 (compile)
      unselected: org.apache.beam:beam-sdks-java-io-google-cloud-platform:jar:2.42.0-SNAPSHOT / com.google.cloud:google-cloud-bigtable:2.11.0 (compile) / com.google.api.grpc:grpc-google-cloud-bigtable-v2:2.11.0 (compile)
```

https://gist.github.com/suztomo/9aef72d020f96446b70f4eab8cba948b

On bigtable-client-core, the latest 1.27.1 https://search.maven.org/artifact/com.google.cloud.bigtable/bigtable-client-core/1.27.1/jar declares dependencyManagement to import https://search.maven.org/artifact/com.google.cloud/google-cloud-bigtable-bom/1.27.1/pom (via `bigtable.version` 1.27.1 set in https://search.maven.org/artifact/com.google.cloud.bigtable/bigtable-client-parent/1.27.1/pom), which has grpc-google-cloud-bigtable-v2 version "1.27.1", not 2.11.0.

@kolea2 (Probably not in this pull request) Would you provide guidance what Bigtable-related artifact versions Apache Beam should depend on?

_Originally posted by @suztomo in https://github.com/apache/beam/issues/22996#issuecomment-1239704538_

**Comment by suztomo** [comment]
> Originally posted by suztomo

I did comment in the pull request but I didn’t file an issue nor encounter the error. It seems some mistake. I’ll close this issue.

If this is still a valid issue, please clarify who observed the issue and which part is a quotation, and then reopen this issue.

**Comment by hiroshitash** [comment]
For whoever faced this issue, I just had to manually specify the correct version 2.14.1 below. Please add it at the top of <dependencies> tag so that it supersedes other dependencies.

<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-bigtable</artifactId>
  <version>2.14.1</version>
</dependency>

Suzuki san, Kura sushi in LA doesn't usually have a line:-)

**Comment by suztomo** [comment]
Thank you for the instruction for the fix.
