### ISSUE TITLE
[Feature Request] - Inclusion of Apache Beam Java JDBC IO - Read With Partitions as External Transform in Python

### ISSUE THREAD

**Issue by Murli16** [apache/beam#25011]
Hi Team,

We are using Apache Beam Python SDK - JDBC IO for reading from SQL Server but it is taking too long to read.

The dataflow execution with Java SDK JDBC IO - ReadWithPartitions proved to be much faster as we could provide number of partitions and partition column additionally as parameters.

We want to evaluate python for now based on client requirement.

This request is to include ReadWithPartitions (Java JDBC IO) as external transform for python SDK.

**Comment by byronellis** [comment]
.take-issue

**Comment by byronellis** [comment]
A PR to modify the existing SchemaIO has been generated, just awaiting final review and merge

**Comment by Abacn** [comment]
done by #25577
