### ISSUE TITLE
[Feature Request]: Upgrade Beam Flink Runner to Flink 1.16

### ISSUE THREAD

**Issue by achang52** [apache/beam#25046]
### What would you like to happen?

We would like to have Flink 1.16 support for the beam Flink Runner + translators. The current most up to date we can find is for Flink 1.16. 

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [X] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Note that there is a plan to migrate Flink runner to run batch jobs with DataStream API: https://docs.google.com/document/d/1cjUJHOS1eEkH76hMNeBuc-kPhbIIc9w2gvjm8miIFS8/edit#

where it suggested "when new Flink version (e.g. Flink 1.16) is added", set to use DataStream API by default. May mark this issue may be blocked by DataStream API migration.

**Comment by becketqin** [comment]
@Abacn Thanks for the comment. Perhaps we don't have to block the Flink 1.16 upgrade for the `DataStream` API migration. If the Flink 1.16 upgrade patch goes in first, by default the Flink batch jobs run with `DataSet` API, but users can always change the config and run batch jobs with `DataStream` API if they want to.
