### ISSUE TITLE
[Task]: Add unit tests for JdbcSchemaIOProvider

### ISSUE THREAD

**Issue by aromanenko-dev** [apache/beam#25120]
### What needs to happen?

To test a basic functionality and avoid breaking changes, like #25061, `JdbcSchemaIOProvider` should be tested by unit tests. 

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by olalamichelle** [comment]
.take-issue

**Comment by olalamichelle** [comment]
I have opened a PR https://github.com/apache/beam/pull/28174. There was actually a bug in the SchemaIOProvider that the maxConnections was Short in the config but read back as Integer. I fixed it also added unit tests for it to prevent similar breaking changes described in this ticket.

**Comment by olalamichelle** [comment]
.close-issue
