### ISSUE TITLE
[Bug]: Cannot pip install Beam 2.44.0 on M1 Mac with Python 3.9

### ISSUE THREAD

**Issue by liferoad** [apache/beam#25172]
### What happened?

I created a fresh venv with:
```
python -m venv beam44
```
then tried to install Beam 2.44 with `beam44`
```
pip install "apache-beam[gcp,interactive]"
```
I saw a lot of errors caused by grpcio (see this: https://github.com/grpc/grpc/issues/30723). I tried couple of suggestions from that grpc PR but could not get it working yet. Any thought to solve this?

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
are you able to `pip install grpcio`  ? what about some older versions of grpcio ?

**Comment by tvalentyn** [comment]
if you see errors from https://github.com/grpc/grpc/issues/30723,  i think the key is to make sure  that grpcio is installed from a wheel. i do see arm wheel files available in  https://pypi.org/project/grpcio/#files , such as grpcio-1.51.1-cp39-cp39-linux_armv7l.whl . I wonder if your machine picks them up.

**Comment by liferoad** [comment]
No, my M1 machine (macOS 13.1 (22C65)) does not pick up any of these whl files. The older version is also broken now.

**Comment by liferoad** [comment]
I solved my issue by upgrading my python to python 3.10.6 (I use pyenv on my Mac):
```
pyenv install 3.10.6
pyenv local 3.10.6
```
I do not think this is related to Beam. (I guess reinstalling the python should work as well).
