### ISSUE TITLE
[Failing Test]: Python PostCommit failing xlang tests

### ISSUE THREAD

**Issue by Abacn** [apache/beam#25189]
### What happened?

python postcommit tests `apache_beam.io.external.xlang_debeziumio_it_test.CrossLanguageDebeziumIOTest.test_xlang_debezium_read` start failing likely related to #25104:

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Python310/393/
https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Python39/1381/
https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Python38/3658/
https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Python37/ (same test failed though not shown in jenkins, can be checked from log)

```
Error Message
RuntimeError: Service failed to start up with error 1
Stacktrace
self = <apache_beam.io.external.xlang_debeziumio_it_test.CrossLanguageDebeziumIOTest testMethod=test_xlang_debezium_read>
```

beam_PostCommit_XVR_Direct also failing due to the same xlang test of Go, but it does not appear in test result though.

looks like it fails to start the expansion service.

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by AnandInguva** [comment]
cc: @johnjcasey Can you take a look since it is an IO test?

**Comment by Abacn** [comment]
CC: @lukecwik possibly related to recent change of JRH

**Comment by damccorm** [comment]
+1, I think this is likely caused by #25104 - this is the first failure -  https://ci-beam.apache.org/job/beam_PostCommit_Python310/393/ - and the JRH change is the only particularly suspicious change there.
