### ISSUE TITLE
[Task]: Move names of environment variables into consts in infrastructure scripts

### ISSUE THREAD

**Issue by TSultanov** [apache/beam#25202]
### What needs to happen?

Scripts under `playground/infrastructure` have names of environment variables used for configuration scattered throughout the code. Consider extracting these strings into constants.

For example, from
```python
use_webgrpc = os.getenv("BEAM_USE_WEBGRPC", False)
```
into
```python
BEAM_USE_WEBGRPC_KEY = "BEAM_USE_WEBGRPC"
......
use_webgrpc = os.getenv(BEAM_USE_WEBGRPC_KEY, False)
```

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by sultanalieva-s** [comment]
I would like to fix the issue but cannot assign it to myself :)) can I still fix the issue somehow ? :33

**Comment by pabloem** [comment]
@sultanalieva-s I've assigned the issue to you!
