### ISSUE TITLE
[Bug]: Error when running an XLang quickstart

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#25305]
### What happened?

I tried running an XLang wordcount using: https://beam.apache.org/documentation/sdks/java-multi-language-pipelines/#run-with-dataflow-runner-using-a-maven-archetype-beam-2430-and-later
but getting and error (see below). Any idea what am I doing wrong? Thanks!

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project multi-language-beam: An exception occured while executing the Java class. org.apache.beam.vendor.guava.v26_0_jre.com.google.common.util.concurrent.UncheckedExecutionException: org.apache.beam.vendor.guava.v26_0_jre.com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Failed to decode Schema due to an error decoding Field proto:
[ERROR] 
[ERROR] name: "word"
[ERROR] type {
[ERROR]   nullable: true
[ERROR]   logical_type {
[ERROR]     urn: "beam:logical:pythonsdk_any:v1"
[ERROR]   }
[ERROR] }
[ERROR] : Unexpected type_info: TYPEINFO_NOT_SET
[ERROR] -> [Help 1]
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
cc: @chamikaramj

**Comment by chamikaramj** [comment]
This is most probably due to using Python 3.7 or below.

The Dataframe transform mentioned in the quick-start guide requires Beam 3.8 and above to perform the type inference correctly for some cases.

It's mentioned here: https://beam.apache.org/documentation/sdks/java-multi-language-pipelines/#prerequisites

**Comment by tvalentyn** [comment]
thanks. not reproducible on Py3.8.
