### ISSUE TITLE
[Task]:  Add runtime metrics to the TFT benchmark tests

### ISSUE THREAD

**Issue by AnandInguva** [apache/beam#25345]
### What needs to happen?

TFT benchmark tests don't emit any useful metrics as of now. Add runtime metric to the TFT pipelines and create a grafana dashboard to visualize it. 

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by damccorm** [comment]
@AnandInguva is this one actually closed or do we need a follow up PR to add a grafana dashboard first?

**Comment by AnandInguva** [comment]
A follow up PR on grafana dashboard is pending. It will be done today.

**Comment by tvalentyn** [comment]
@AnandInguva do you know why the metrics are not being populated on http://104.154.241.245/d/C9nj1oxVk/tft-criteo-benchmarks?orgId=1 ?
