### ISSUE TITLE
[Feature Request]: Making number of retries configurable in BigQuery Storage Write connector

### ISSUE THREAD

**Issue by fpoon** [apache/beam#25382]
### What would you like to happen?

Hi,
Is it possible to make this instance of retry manager configurable?
https://github.com/apache/beam/blob/f5020e7ac2bdd3363619aafbf257f2ebf8e3fe2b/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java#L658
Retrying the request to BQ Storage Write API a thousand times seems to be a bit too generous, especially with some nonrecoverable errors, but I guess, it may have its justification in some cases. However, in streaming mode, it clogs the pipeline for an unreasonable amount of time. Maybe clients should be allowed to configure this value?

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Amar3tto** [comment]
.take-issue
