### ISSUE TITLE
[Feature Request]: Google Cloud Bigtable Change Stream Connector

### ISSUE THREAD

**Issue by tonytanger** [apache/beam#25412]
### What would you like to happen?

Google Cloud Bigtable is launching Change Stream API. We're expanding BigtableIO to include a new connector that streams changes using the new API.

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tonytanger** [comment]
.take-issue

**Comment by pabloem** [comment]
fyi @damccorm that @tonytanger requested we mark this as P1 for the 2.46.0 milestone

**Comment by damccorm** [comment]
I don't think we should be blocking the release for this. In general, our guidance is to not block releases on new features unless there is strong community consensus to delay the release - https://beam.apache.org/contribute/release-blocking/#:~:text=for%20a%20release.-,Release%2Dblocking%20features,-By%20default%2C%20features

If we want to block the release, we should have a clear statement on the impact of this feature and the ETA, and we should get larger consensus

**Comment by tonytanger** [comment]
Thanks for the info @damccorm We don't have to block 2.46 release then. We will try our best to meet the 2.46 release cut date.

**Comment by kennknowles** [comment]
Based on https://beam.apache.org/contribute/issue-priorities/ the right priority for this sort of thing is P2
