### ISSUE TITLE
[Tour of Beam] [Task] Get ToB examples precompiled objects from PG backend

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#25484]
### What needs to happen?
Ensure that ToB  can get examples precompiled objects from PG backend

Dev note:  Looks like we need to get rid of example name to cloudPath mapping and also check origin filtering in PG catalog.

### Issue Priority
Priority: 3

### Components:
tour-of-beam, beam-playground

**Comment by TSultanov** [comment]
.take-issue
