### ISSUE TITLE
[Bug]: BEAM SDKs Java IO ClickHouse dependency using ru.yandex instead of com.clickhouse issue

### ISSUE THREAD

**Issue by mzitnik** [apache/beam#25511]
### What happened?

[BEAM SDKs Java IO ClickHouse](https://mvnrepository.com/artifact/org.apache.beam/beam-sdks-java-io-clickhouse) still using [ru.yandex.clickhouse](https://mvnrepository.com/artifact/ru.yandex.clickhouse) » [clickhouse-jdbc](https://mvnrepository.com/artifact/ru.yandex.clickhouse/clickhouse-jdbc), but in https://github.com/apache/beam/pull/24424 we changed to use our new library from implementation "com.clickhouse:clickhouse-jdbc:$clickhouse_jdbc_version:all" with one of our latest releases 

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
https://mvnrepository.com/artifact/org.apache.beam/beam-sdks-java-io-clickhouse/2.45.0 is available on mavencentral now and the dependency `clickhouse-jdbc` is from `com.clickhouse`

**Comment by mzitnik** [comment]
@Abacn thanks for the update can tell what have you done since next time when i will update the driver i will have control over that

**Comment by johnjcasey** [comment]
It looks like 2.45 is using the new path as expected.
https://mvnrepository.com/artifact/org.apache.beam/beam-sdks-java-io-clickhouse/2.45.0
