### ISSUE TITLE
[Tour of beam] [Task] Scrolling through learning materials is broken when hint is present

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#25575]
### What needs to happen:

Looks like scrolling through learning materials is broken when Hint button is displayed. Need to fix scrolling.

### Issue priority:
P3

### Components:
tour-of-beam

**Comment by nausharipov** [comment]
.take-issue

**Comment by nausharipov** [comment]
This was fixed in January in the https://github.com/apache/beam/pull/25298 branch.
