### ISSUE TITLE
[Bug]: Building website changes fails with proto issues

### ISSUE THREAD

**Issue by damccorm** [apache/beam#25649]
### What happened?

When running `./beam/release/src/main/scripts/build_release_candidate.sh ` per https://beam.apache.org/contribute/release-guide/#run-build_release_candidatesh-to-create-a-release-candidate, the script fails on website generation with the following error:

```
Processing ./target/.tox/.tmp/package/1/apache-beam-2.44.0.tar.gz
  Preparing metadata (setup.py) ... error

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/usr/local/google/home/klk/website_update_dir/python_doc/beam/sdks/python/target/.tox/py38-docs/tmp/pip-req-build-0ht9l7p_/setup.py", line 180, in <module>
          generate_protos_first()
        File "/usr/local/google/home/klk/website_update_dir/python_doc/beam/sdks/python/target/.tox/py38-docs/tmp/pip-req-build-0ht9l7p_/setup.py", line 150, in generate_protos_first
          gen_protos.generate_proto_files()
        File "/usr/local/google/home/klk/website_update_dir/python_doc/beam/sdks/python/target/.tox/py38-docs/tmp/pip-req-build-0ht9l7p_/gen_protos.py", line 476, in generate_proto_files
          raise RuntimeError(error_msg)
      RuntimeError: Not in apache git tree, unable to find proto definitions.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

Upthread, we also see 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.                                                                                                                                            
virtualenv 20.17.1 requires distlib<1,>=0.3.6, but you have distlib 0.3.1 which is incompatible.
```

This can be worked around by running `python gen_protos.py` as an intermediate step in the script before running `tox -e py38-docs`, which indicates this probably is a bug with gen_protos in other directories.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by AnandInguva** [comment]
What tox version were you using?

**Comment by AnandInguva** [comment]
I have encountered this issue before when I was trying to update tox to 4.x.x. Tox 4.x.x uses isolated builds by default and this could be the reason our generated pb_2 files and urn files are not getting copied to the sdist created by tox ( I might be totally wrong here) but the same code worked with tox 3.x in which our tox tasks didn't run on isolated builds.

**Comment by damccorm** [comment]
I'd have to check the exact version, but it was definitely tox 4.x.x (which is what now gets installed by default in our local dev setup https://github.com/apache/beam/blob/62e9a1239bb6f9ef2f1469d0c1af192697f8b10c/local-env-setup.sh#L126)

**Comment by AnandInguva** [comment]
Can we try to fix a tox version and investigate what is happening with tox 4.x and gen protos? 

> I have encountered this issue before when I was trying to update tox to 4.x.x. Tox 4.x.x uses isolated builds by default and this could be the reason our generated pb_2 files and urn files are not getting copied to the sdist created by tox ( I might be totally wrong here) but the same code worked with tox 3.x in which our tox tasks didn't run on isolated builds.
> 
> May be this could be a bug with gen_protos. If it is, we need to figure out what it is since it could be a blocker for #25123

I started to dig into it but this is where I stopped. I can pick it up after Python 3.11 work if its not resolved by then.
