### ISSUE TITLE
[Task]: Do an audit of Beam Python SDK dependencies and verify that bounds are set appropriately.

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#25655]
### What needs to happen?

The ask here is to take a pass over existing dependencies in Beam Python SDK and make sure the constraints make sense in light of lessons learned in https://s.apache.org/beam-python-dependencies-pm.

Subtask of #25652 

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
cc: @AnandInguva

**Comment by jrmccluskey** [comment]
@tvalentyn @AnandInguva is this considered a release blocker for 2.47? Or should it be moved to the 2.48 milestone?

**Comment by AnandInguva** [comment]
@jrmccluskey If the dependencies in https://github.com/apache/beam/blob/master/sdks/python/setup.py are up to date/or doesn't contains releases that are more than 1 year old, we can move it to the next release.

I think this task says it is done by release manager once before release.

**Comment by jrmccluskey** [comment]
Having read the context from the post-mortem, this is not a release task.

**Comment by tvalentyn** [comment]
This is mostly completed in https://github.com/apache/beam/pull/24599 and will be resolved by: https://github.com/apache/beam/pull/26242

Thanks!
