### ISSUE TITLE
[Feature]: Implement and reenable GroupIntoBatchesTest.testWithShardedKeyInGlobalWindow: causes dataflow suite to be permared

### ISSUE THREAD

**Issue by damccorm** [apache/beam#25675]
### What happened?

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/ is permared. The failing test is `testWithShardedKeyInGlobalWindow`.

I looked at an example job and it isn't even starting up correctly - https://pantheon.corp.google.com/dataflow/jobs/us-central1/2023-03-01_02_18_07-687229064971437925;bottomTab=JOB_LOGS;logsSeverity=ERROR;graphView=0?project=apache-beam-testing&pageState=%28%22dfTime%22:%28%22l%22:%22dfJobMaxTime%22%29%29&e=-13802955&jsmode=o&mods=dataflow_dev - in the Dataflow backend I see Job 2023-03-01_02_18_07-687229064971437925 failed to start with status: generic::invalid_argument: Autosharding is not supported with Unified Worker/Runner v2.

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

**Comment by damccorm** [comment]
Confirmed that this is a known issue with Dataflow runner v2, so I'm sickbaying the test and will cherry pick that to the release branch and remove the release blocker

**Comment by kennknowles** [comment]
Since this is ongoing feature work in Dataflow, it is P2

**Comment by kennknowles** [comment]
I believe @danielarn is working on this from the Dataflow side. Daniel, if you want you could self-assign this so no one else tries to do anything with it.

**Comment by danielarn** [comment]
Confirming that I'm actively working on this from the Dataflow side. Will update once autosharding functionality is restored.

**Comment by damccorm** [comment]
Note, this is slightly different than the initial problem since its on runner v1, not runner v2

**Comment by Abacn** [comment]
Run Java Dataflow V2 ValidatesRunner Streaming
