### ISSUE TITLE
[Task]: Update Cloud Build configuration to deploy Playground Infrastructure

### ISSUE THREAD

**Issue by rshamunov** [apache/beam#25735]
### What needs to happen?

Need to update #24006 according to new changes. 
Triggers should support deployment of multiple environments to the same GCP Project.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by ruslan-ikhsan** [comment]
.take-issue
