### ISSUE TITLE
[Task]: Upgrade bigdataoss version without breaking use_grpc_for_gcs experiment

### ISSUE THREAD

**Issue by johnjcasey** [apache/beam#25777]
### What needs to happen?

based on #23588, 2.2.8 broke this experiment, and as such we rolled back to 2.2.6. Newer versions are available, however.

The task here is to upgrade the bigdataoss version to the most recent version, and resolve any breaks in the use_grpc_for_gcs experiment discovered

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by damccorm** [comment]
This should've been resolved by #27679
