### ISSUE TITLE
[Feature Request]: Support pymongo v4

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#25783]
### What would you like to happen?

We currently restrict PyMongo to V3 or below, https://github.com/apache/beam/blob/1c0ea9742da4413d1ffc2018a7398ece9acc5cf1/sdks/python/setup.py#L253
PyMongo 4 was released EOY2021: https://pypi.org/project/pymongo/#history.

Having older dependencies in dependency chains is a risk and can cause issues like  https://s.apache.org/beam-python-dependencies-pm.

We should generally plan to add support for major releases of IO connectors dependencies within the first year they became available. In this sense, we are overdue with pymongo upgrade.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
This makes sense to me. Let's kick off a test PR for `<5.0.0` and run integration/load tests
