### ISSUE TITLE
[Bug]: Illegal to use destination for this producer while using the jmsIO.write with 2.46.0 version

### ISSUE THREAD

**Issue by sriram23kmm** [apache/beam#25849]
### What happened?

When we upgraded the Beam version to **2.46.0** to use the **Retryconfiguration** we faced this issue:

JmsIO.Write<String> sink = JmsIO.<String>write()
        .withConnectionFactory(ConnectionsFactoryObject)
        .withValueMapper(new TextMessageMapper())
        .withRetryConfiguration(RetryConfiguration.create(5))
        .withQueue("testQueqe");

Here we used the TIBCO for jms

### Issue Priority

Priority: 0 (outage / urgent vulnerability)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Thanks for reporting. RetryConfiguration is recently added in #24973. Could you please provide the full exception stacktrace?

we reserve P0 to outage so move the priority for now

**Comment by sriram23kmm** [comment]
java.lang.UnsupportedOperationException: Illegal to use destination for this producer
	at com.tibco.tibjms.TibjmsMessageProducer._publish(TibjmsMessageProducer.java:198)
	at com.tibco.tibjms.TibjmsMessageProducer.send(TibjmsMessageProducer.java:573)
	at org.apache.beam.sdk.io.jms.JmsIO$Writer$JmsConnection.publishMessage(JmsIO.java:1035)
	at org.apache.beam.sdk.io.jms.JmsIO$Writer$JmsIOProducerFn.publishMessage(JmsIO.java:1118)
	at org.apache.beam.sdk.io.jms.JmsIO$Writer$JmsIOProducerFn.processElement(JmsIO.java:1102)

**Comment by Abacn** [comment]
@sriram23kmm This error is handled and suppressed: https://github.com/apache/beam/blob/ddae966f3346fbe247486324cbf8a8a532895316/sdks/java/io/jms/src/main/java/org/apache/beam/sdk/io/jms/JmsIO.java#L653
