### ISSUE TITLE
[Failing Test]: TFT benchmarks broken by protobuf upgrade

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#25889]
### What happened?

https://ci-beam.apache.org/job/beam_CloudML_Benchmarks_Dataflow/70/console

Side note: we could come up with a better name for these, they might confuse people.

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [x] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
cc: @AnandInguva

**Comment by AnandInguva** [comment]
.take-issue

**Comment by AnandInguva** [comment]
I will just rename it to beam_Python_TFT_Criteo_Benchmarks or something like that

**Comment by AnandInguva** [comment]
This got solved with the newer release of TFT
