### ISSUE TITLE
[Task]: Update Java version used by the runner to a newer version

### ISSUE THREAD

**Issue by rshamunov** [apache/beam#25989]
### What needs to happen?

Java container build is based on Apache Beam Java 8 base image.
https://github.com/apache/beam/blob/3a1b64106657346f436bc9011d894ca90408a69e/playground/backend/containers/java/Dockerfile#L55

Update it to a newer Java version (e.g. beam_java11_sdk)

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by TSultanov** [comment]
.take-issue
