### ISSUE TITLE
[Task]: Add an optional tag to not run an example from cache

### ISSUE THREAD

**Issue by rshamunov** [apache/beam#25990]
### What needs to happen?

Streaming examples from unbounded data sources can run for a long period of time. They should not run during CI/CD and should always run as there is no precompiled object available.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by TSultanov** [comment]
.take-issue
