### ISSUE TITLE
[Failing Test]: Python 3.7 PostCommit failing BigQueryXlangStorageWriteIT

### ISSUE THREAD

**Issue by Abacn** [apache/beam#26016]
### What happened?

These tests were recently added in #25685

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
CC: @ahmedabu98

**Comment by ahmedabu98** [comment]
Ah looks like Postcommit tests do [all the tests](https://github.com/apache/beam/blob/469101dd378368d1a9cbb3418b81e28506d72bdf/sdks/python/test-suites/direct/common.gradle#L43) in `apache_beam/io/gcp/bigquery_write_it_test.py`. Did not mean for the new xlang tests to be included in this suite. Looks like will have to make a new file to host BQ xlang tests.

**Comment by ahmedabu98** [comment]
.take-issue

**Comment by Abacn** [comment]
These test can be moved to `sdks/python/apache_beam/io/external` which is current external transform test locates
