### ISSUE TITLE
[Task]: Update XGBoost notebook to install Beam from released version instead of GitHub head once 2.47 is released

### ISSUE THREAD

**Issue by damccorm** [apache/beam#26077]
### What needs to happen?

This notebook https://github.com/apache/beam/blob/master/examples/notebooks/beam-ml/run_inference_xgboost.ipynb installs beam from head instead of a released version, we should update once 2.47 is released

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by smeet07** [comment]
.take-issue
