### ISSUE TITLE
Cannot install apache-beam gcp and google-ads

### ISSUE THREAD

**Issue by algreeck** [apache/beam#26080]
### What happened?

I am trying to create a python beam project which used google ads api. When i try to install the package google-ads==20.0.0 which is supports the latest version of Google Ads API (v13)  it fails to resolve the dependencies with the error:
Cannot install GoogleAds and apache-beam[gcp]==2.46.0 because these package versions have conflicting dependencies The conflict is caused by: apache-beam[gcp] 2.46.0 depends on protobuf<4 and >3.12.2 google-ads 20.0.0 depends on protobuf>=4.21.5

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

**Comment by AnandInguva** [comment]
Unfortunately, Beam 2.46.0 is not compatible with protobuf 4.x. 

Beam recently updated protobuf version to 4.x.x at #24599. It will be included in the release 2.47.0.

**Comment by AnandInguva** [comment]
I am closing this issue. If you have anything else, please feel free to open and comment on this.

**Comment by AnandInguva** [comment]
.close-issue
