### ISSUE TITLE
[Feature Request]: Allow to set operator chaining for flink runner

### ISSUE THREAD

**Issue by zjffdu** [apache/beam#26095]
### What would you like to happen?

By default, flink enable operator chaining for performance purpose (https://nightlies.apache.org/flink/flink-docs-master/docs/dev/datastream/operators/overview/#task-chaining-and-resource-groups), but it would be helpful to disable operator chaining for diagnose in the development stage so that it is more convenient for users to see what is the topological structure of the pipeline. 

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [X] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by je-ik** [comment]
Closed via #26096
