### ISSUE TITLE
[Feature Request]: Support Assume-Role with web identity

### ISSUE THREAD

**Issue by mokamoka03210120** [apache/beam#26097]
### What would you like to happen?

I would like to use Assume-Role by web identity, but  AwsOptions does not support it.
To do that, AwsOptions must be able to handle `StsAssembleRoleWithWebIdentityCredentialsProvider`.

* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sts/assume-role-with-web-identity.html
* https://github.com/apache/beam/blob/master/sdks/java/io/amazon-web-services2/src/main/java/org/apache/beam/sdk/io/aws2/options/AwsOptions.java#L75-L144

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by mokamoka03210120** [comment]
.take-issue

**Comment by mosche** [comment]
@mokamoka03210120 Thanks for this issue and your PR! 
Before going to review, could you elaborate briefly on your use case to give a bit of context here. Thanks so much.

**Comment by mokamoka03210120** [comment]
@mosche 
Thank you for the comment.
I am building a batch pipeline on Cloud Dataflow which have to get files on AWS S3 bucket. It can access to the bucket with  access key and secret by current SDK, but in that case, I have to rotate the credentials for security and it is a hassle. So, I am considering using assume-role by id token of GCP service account to get temporary credentials when needed.
