### ISSUE TITLE
[Tour of Beam] [Task] Links in Tour of Beam theory should be clickable

### ISSUE THREAD

**Issue by olehborysevych** [apache/beam#26115]
### What needs to be done:
Links in Tour of Beam theory units should be clickable and opened in a new browser window.
Unit with links: https://apache-beam-testing.web.app/tour/go/introduction/beam-concepts/runner-concepts
### Priority:
P3

### Component:
tour-of-beam

**Comment by nausharipov** [comment]
.take-issue
