### ISSUE TITLE
[Feature Request]: Upgrade pandas to 2.x

### ISSUE THREAD

**Issue by AnandInguva** [apache/beam#26155]
### What would you like to happen?

Recently Pandas released a new major version https://pypi.org/project/pandas/#files.

Update the Pandas bounds in [setup.py](https://github.com/apache/beam/blob/2a9e1ab78feeadf30c92e2a5336f07399826f3b6/sdks/python/setup.py#L277)

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by liferoad** [comment]
.take-issue

**Comment by liferoad** [comment]
With pandas 2.0, `from apache_beam.runners.interactive.interactive_runner import InteractiveRunner` stops working with this error: `AttributeError: type object 'Series' has no attribute 'append'. Did you mean: '_append'?`

**Comment by AnandInguva** [comment]
.take-issue

**Comment by AnandInguva** [comment]
Pandas 2.0 removed the append method for both `Series` and `Dataframe`. I think we should do the same(remove append from deferred dataframes) but we need to provide alternatives with concat.

https://github.com/pandas-dev/pandas/issues/35407

cc: @robertwb

**Comment by tvalentyn** [comment]
Let's track in https://github.com/apache/beam/issues/27221
