### ISSUE TITLE
[Failing Test]: :sdks:java:container:pullLicenses faling since Apr 5th affecting lots of PostCommits

### ISSUE THREAD

**Issue by Abacn** [apache/beam#26173]
### What happened?

':sdks:java:container:pullLicenses' is currently failing on master and affecting lots of PostCommit. This may also affect current release process.

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
The exact error message:

```
07:47:45 Executing python /home/jenkins/jenkins-slave/workspace/beam_PostCommit_XVR_Direct/src/sdks/java/container/license_scripts/pull_licenses_java.py --license_index=/home/jenkins/jenkins-slave/workspace/beam_PostCommit_XVR_Direct/src/sdks/java/container/build/reports/dependency-license/index.json        --output_dir=/home/jenkins/jenkins-slave/workspace/beam_PostCommit_XVR_Direct/src/sdks/java/container/build/target/java_third_party_licenses        --dep_url_yaml=/home/jenkins/jenkins-slave/workspace/beam_PostCommit_XVR_Direct/src/sdks/java/container/license_scripts/dep_urls_java.yaml        --manual_license_path=/home/jenkins/jenkins-slave/workspace/beam_PostCommit_XVR_Direct/src/sdks/java/container/license_scripts/manual_licenses
07:47:45 Traceback (most recent call last):
07:47:45   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_XVR_Direct/src/sdks/java/container/license_scripts/pull_licenses_java.py", line 36, in <module>
07:47:45     from tenacity import retry
07:47:45   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_XVR_Direct/src/sdks/java/container/build/virtualenv/lib/python3.11/site-packages/tenacity/__init__.py", line 451, in <module>
07:47:45     from tenacity._asyncio import AsyncRetrying
07:47:45   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_XVR_Direct/src/sdks/java/container/build/virtualenv/lib/python3.11/site-packages/tenacity/_asyncio.py", line 33, in <module>
07:47:45     class AsyncRetrying(BaseRetrying):
07:47:45   File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_XVR_Direct/src/sdks/java/container/build/virtualenv/lib/python3.11/site-packages/tenacity/_asyncio.py", line 41, in AsyncRetrying
07:47:45     @asyncio.coroutine
07:47:45      ^^^^^^^^^^^^^^^^^
07:47:45 AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
07:47:45 
07:47:45 > Task :sdks:java:container:pullLicenses FAILED
```
Python 3.11 removed asyncio.coroutine: https://github.com/python/cpython/pull/26369

This is because we bumped to use python3.11 as the Python environment to run pullLicenses, however it appears that not all (transient) dependency yet support python3.11.

**Comment by Abacn** [comment]
reopen to cherry-pick

**Comment by jrmccluskey** [comment]
With the mitigation cherrypicked into 2.47 are we good to remove this bug from the release milestone?
