### ISSUE TITLE
[Failing Test]: :sdks:go:container:docker failing while copying a license 

### ISSUE THREAD

**Issue by jrmccluskey** [apache/beam#26180]
### What happened?

During the :sdks:go:container:docker step used in multiple pre and post-commits the following error appears:

```
15:41:55 #10 [6/8] COPY target/LICENSE target/go-licenses/* /opt/apache/beam/third_party_licenses/golang/
15:41:55 #10 ERROR: lstat /var/lib/docker/tmp/buildkit-mount2275715998/target/go-licenses: no such file or directory
15:41:55 ------
15:41:55 
15:41:55  > [6/8] COPY target/LICENSE target/go-licenses/* /opt/apache/beam/third_party_licenses/golang/:
15:41:55 > Task :sdks:go:container:docker FAILED
```

This is preventing Go test from building and executing successfully.

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 0 (outage / failing precommit test impacting development)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by jrmccluskey** [comment]
CC: @lostluck

**Comment by lostluck** [comment]
The failure is that it's not finding the "target/go-licenses" directory at all. Very strange.

COPY doc reference for myself: https://docs.docker.com/engine/reference/builder/#copy

Last path is the destination, so the error is in the set up. Something is probably getting deleted more thoroughly then anticipated...

**Comment by lostluck** [comment]
Well I found something interesting.

From a clean run, we produce the following files

```
➜  beam git:(golicenses2023) ✗ ls -R sdks/go/container/build/*
sdks/go/container/build/docker:
docker  Dockerfile  target

sdks/go/container/build/docker/docker:
target

sdks/go/container/build/docker/docker/target:
LICENSE  LICENSE.python  linux_amd64  NOTICE

sdks/go/container/build/docker/docker/target/linux_amd64:
boot

sdks/go/container/build/docker/target:
go-licenses  LICENSE  LICENSE.python  linux_amd64  NOTICE

sdks/go/container/build/docker/target/go-licenses:

sdks/go/container/build/docker/target/linux_amd64:
boot

sdks/go/container/build/target:
go-licenses  LICENSE  LICENSE.python  linux_amd64  NOTICE

sdks/go/container/build/target/go-licenses:

sdks/go/container/build/target/linux_amd64:
boot
```

In particular, we end up with several layers of target,docker/target,docker/docker/target with the last one, not having a `go-license` directory.

I've only checked the Go side for this so far. Lets see what happens with Python and Java...

**Comment by lostluck** [comment]
Java doesn't have the recursive thing but still ends up failing for the same reason.

Also going down the "skip path" at least.

If you set the pull license property, the Java one fails on pull licenses, but unreleated to the go licence step AFAICT.

`./gradlew  :sdks:java:container:java8:docker -Pdocker-pull-licenses=true`

The Go one passes, which means that it is just the existence of the folder being weird in this current docker or gradle version. There doesn't appear to be recent changes (in the container directories) that would seem to cause this behavior, so it's external. This means it's time to work around it (for all containers).
