### ISSUE TITLE
[Task]: Migrate Playground Datastore updates operations to Cloud Functions

### ISSUE THREAD

**Issue by rshamunov** [apache/beam#26191]
### What needs to happen?

We need to remove datastore update permissions from GKE service account for security considerations. All functionalities can be moved to Cloud Functions.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by TSultanov** [comment]
.take-issue
