### ISSUE TITLE
[Failing Test]: Samza XVR Test Failure on release-2.47.0 branch

### ISSUE THREAD

**Issue by jrmccluskey** [apache/beam#26241]
### What happened?

The Samza cross-language validates runner test suite is failing on the release branch with the following error in the TestDebeziumIO_BasicRead test:

```
2023/04/12 17:19:07  (): java.lang.UnsupportedOperationException: The ActiveBundle does not have a registered bundle checkpoint handler.
2023/04/12 17:19:07 Job state: FAILED
    ptest.go:108: Failed to execute job: job go0testdebeziumio0basicread0521-jenkins-0412171850-7f7d8f6d_49001b62-7368-42c6-8be8-92ce416f7f7c failed
--- FAIL: TestDebeziumIO_BasicRead (44.53s)
```

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 0 (outage / failing precommit test impacting development)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [X] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by jrmccluskey** [comment]
CC: @chamikaramj @lostluck @johnjcasey 

Covering the xlang, Go, and IO experts

**Comment by lostluck** [comment]
It looks like some change on the Java portable runner side likely caused this, and something with the Samza integration was not changed. 

The Go Xlang or the Debezium code hasn't changed in a while (other thank a refactor to testcontainer launching, which wouldn't cause this error).

On the other hand, the other Java runners all filter out this test as well IIRC likely due to runner configuration issues. The test seems to still run fine on Python Portable.

I'm not able to investigate the specifics for this until I add Xlang support to prism, so that we can be able to catagorically assign this as a Java Runner issue, rather than a Go integration issue for Xlang.

**Comment by chamikaramj** [comment]
Is the same test passing for Spark,Flink,Direct XVR tests that also use the same runner ?

**Comment by jrmccluskey** [comment]
Yes the other XVR suites are passing

**Comment by lostluck** [comment]
Go can't use the "Direct" runner (Which I assume is either the Java direct runner).

I don't know if there's a run of this against the Python Portable runner, but it's not filtered from there.

It is filtered out in Flink and Spark, and this style of test (local databases) would never work against Dataflow.  Go Direct Runner will never support xlang, and Prism doesn't yet support Xlang.

**Comment by chamikaramj** [comment]
It's passing for Dataflow: https://ci-beam.apache.org/job/beam_PostCommit_XVR_GoUsingJava_Dataflow/1516/console

(there's a separate BQ failure which looks like a easy fix)

**Comment by chamikaramj** [comment]
(on HEAD)

**Comment by lostluck** [comment]
It doesn't matter if the suite is passing on Dataflow, when that test is filtered from running on Dataflow.

**Comment by chamikaramj** [comment]
Ah, nvm then. Just saw your PR https://github.com/apache/beam/pull/26243 and filtering. This should not be a P0 or a blocker for the release.
