### ISSUE TITLE
[Task]: Improve Playground examples tags handling

### ISSUE THREAD

**Issue by rshamunov** [apache/beam#26256]
### What needs to happen?

Make fields categories and context_line optional in examples tag
Resolve bug with incorrectly calculated context line after tag is removed from an example
Resolve bug with an incorrectly reported context line for an example in catalog

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by TSultanov** [comment]
.take-issue
