### ISSUE TITLE
[Feature Request]: Upgrade setup.py to pyproject.toml

### ISSUE THREAD

**Issue by davidcavazos** [apache/beam#26266]
### What would you like to happen?

Installing `apache-beam` gives a deprecation warning because it uses a `setup.py` file to configure the installation, which will be deprecated in `pip` 23.1 in favor of a `pyproject.toml` file.

How to reproduce:

```sh
python -m venv env
source env/bin/activate

pip install apache-beam
```

Shows the following warning:

`DEPRECATION: apache-beam is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559`

`pip` version [23.1 is targeted to release by April 30](https://github.com/pypa/pip/milestone/68), by then the `setup.py` file will be deprecated.

[PEP-621](https://peps.python.org/pep-0621) describes more context on why this change and how to upgrade. The good news is that the `pyproject.toml` file is declarative instead of containing arbitrary code, which makes writing it and maintaining it much simpler than the `setup.py` file.

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by AnandInguva** [comment]
.take-issue

**Comment by AnandInguva** [comment]
Using `setup.py` along with `pyproject.toml` is fine but using `setup.py install`, `setup.py sdist` are deprecated. I am working on a PR that would add a simple `pyproject.toml` file.
