### ISSUE TITLE
[Bug]: Typescript SDK doesn't export type declarations

### ISSUE THREAD

**Issue by sinus-problems** [apache/beam#26299]
### What happened?

1. `npm i apache-beam`
2. try to import it in a typescript project.
3. You will receive an error `Could not find a declaration file for module 'apache-beam'.`

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [X] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tferullo-bunsen** [comment]
.take-issue

**Comment by BlakeHyde** [comment]
This is an unfortunate issue. It isn't clear how this is intended to be used in a generic TypeScript project at all if it's not consumable from `npm`. Is there a `@types` package that I'm overlooking?

**Comment by pequalsnp** [comment]
I am in the same state, I get errors immediately trying to import the library.  I have tried version `2.46.0` and `2.48.0` and I get this same error

```
TS7016: Could not find a declaration file for module 'apache-beam'. '/Users/kylegalloway/src/github.com/BeReal-App/backend/node_modules/apache-beam/dist/src/apache_beam/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/apache-beam` if it exists or add a new declaration (.d.ts) file containing `declare module 'apache-beam';`
    1 | import { Injectable } from '@nestjs/common';
  > 2 | import * as beam from 'apache-beam';
      |                       ^^^^^^^^^^^^^
    3 | import * as yargs from 'yargs';
```

**Comment by pequalsnp** [comment]
That PR seems to publish properly ☝️
