### ISSUE TITLE
[Task]: Bump AWS Kinesis client version

### ISSUE THREAD

**Issue by psolomin** [apache/beam#26295]
### What needs to happen?

Current Kinesis client lib version is 2.3.4 which is > 2 years old, so it needs a bump.

https://github.com/apache/beam/blob/9c00dca093f6ddfa18a879e0b9fef76871f0902a/sdks/java/io/amazon-web-services2/build.gradle#L55

It brings Lombok dependency which is not compatible with Java 17 (https://github.com/projectlombok/lombok/issues/2898)

```
$ ./gradlew -p sdks/java/io/amazon-web-services2 -q dependencies --configuration testRuntimeClasspath
...
+--- software.amazon.kinesis:amazon-kinesis-client:2.3.4
...
|    +--- software.amazon.glue:schema-registry-serde:1.0.0
...
|    |    +--- org.projectlombok:lombok:1.18.2
|    |    \--- org.projectlombok:lombok-utils:1.18.12
|    +--- software.amazon.glue:schema-registry-common:1.0.0 (*)
...
```

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by mosche** [comment]
@psolomin Are you planning to look into this? Shall I assign this to you?

**Comment by psolomin** [comment]
@mosche I'm not sure I have time next 2 weeks, I would leave it unassigned for now. Add `good first issue` maybe? If it stays unassigned by the end of Apr, I will assign myself.

**Comment by mosche** [comment]
I had a quick look, actually there's a few issues with transitive dependencies that require a bit of care. Will tackle the next days.
