### ISSUE TITLE
[Task]: Python Jdbc xlang test uses deprecated API for sqlalchemy

### ISSUE THREAD

**Issue by Abacn** [apache/beam#26333]
### What needs to happen?

This blocks updating sqlalchemy to 2.x

Context: #25872

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Dippatel98** [comment]
This issue has been fixed by #30919
