### ISSUE TITLE
[Task]: Stabilize self hosted runners

### ISSUE THREAD

**Issue by andreydevyatkin** [apache/beam#26346]
### What needs to happen?

Beam currently uses dynamically provisioned runners on top of K8s, and they have significant stability issues. Replace dynamic runners with static VMs hosting runners or a more stable solution. Ensure that all workflows are stable and correct with the static runners.

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

**Comment by volatilemolotov** [comment]
.take-issue
