### ISSUE TITLE
[Failing Test]:  Python_ParDo_Dataflow_Streaming loadtest suite has been timing out. 

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#26345]
### What happened?

See: https://ci-beam.apache.org/job/beam_LoadTests_Python_ParDo_Dataflow_Streaming/ 

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
Suite has been timing out recently as per:

https://ci-beam.apache.org/job/beam_LoadTests_Python_ParDo_Dataflow_Streaming/buildTimeTrend. We can increase the timeout and watch https://s.apache.org/beam-community-metrics to see if there is a performance regression in some tests once the suite is running again.

**Comment by tvalentyn** [comment]
@riteshghorse did you get the chance to inspect performance tests dashboards for obvious regressions?

**Comment by damccorm** [comment]
I looked at http://104.154.241.245/d/MOi-kf3Zk/pardo-load-tests?orgId=1 and didn't see any clear trends one way or another, so I think this is safe to close
