### ISSUE TITLE
[Feature Request]: Lifting protobuf version restriction for Python3.10

### ISSUE THREAD

**Issue by calvin-scio** [apache/beam#26356]
### What would you like to happen?

I noticed in [these lines](https://github.com/apache/beam/blob/release-2.46.0/sdks/python/setup.py#L183-L189) of setup.py that on Python3.10 the protobuf versions are highly restricted `['protobuf>3.12.2,<3.19.5']`. Sadly, my repository has a number of other dependencies that require a more forward version of protobuf (google-api-core, tensorflow), and was wondering if there's work in progress to lift the restriction / fix incompatibilities and allow >=3.19.5. Or, is there a workaround to allow these other libraries able to coexist?

(I am on Darwin, M1, python3.10). Thanks so much!

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
In upcoming Beam v2.47.0 it now requires protobuf 4.x for all supported python version: https://github.com/apache/beam/blob/release-2.47.0/sdks/python/setup.py#L251

**Comment by calvin-scio** [comment]
Oh that's great news, thank you! Do you know when the estimated release will be for 2.47.0? I'll be sure to update once that happens 😄

**Comment by calvin-scio** [comment]
Thanks so much 🙏
