### ISSUE TITLE
[Bug]: In Tour of Beam the code snippets are not selectable. 

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#26452]
### What happened?

In Tour of Beam, the code snippets in the left hand side orange panes are not selectable. 

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [X] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
Also consider introducing a separate component or tag for TOB issues, and pre-select issues with this tag, when forwarding users to GitHub to file an issue. This would make it easy to see if similar issues have already been reported.

**Comment by tvalentyn** [comment]
Also looks like that when selecting the text outside code snippets, there are some rendering artifacts, and text is selected only within a paragraph.

**Comment by nausharipov** [comment]
.take-issue
