### ISSUE TITLE
[Task]: Add support for passing file pattern directly into RunInference

### ISSUE THREAD

**Issue by damccorm** [apache/beam#26500]
### What needs to happen?

Instead of
```
inference_pcoll = (
    images_pcoll
    | "RunInference" >> RunInference(
    model_handler=tf_model_handler,
    model_metadata_pcoll=side_input_pcoll))
```

It would be nice to be able to do something like:

```
 RunInference(
    model_handler=tf_model_handler,
    model_metadata_file_pattern=file_pattern))
```

We could do this by doing something like:

```
self._model_metadata_pcoll = pcoll.pipeline | WatchFilePattern(file_pattern)
```

in [expand](https://github.com/apache/beam/blob/73b9b092e3679e45c5258dd96e8dd1a9519bb3a1/sdks/python/apache_beam/ml/inference/base.py#L559)

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by AnandInguva** [comment]
Is it better to support a new input arg `model_metadata_file_pattern ` for the method  and we can create the side input pcoll under the hood?
