### ISSUE TITLE
[Bug]: Tour of Beam Terraform automation appears break gradle build

### ISSUE THREAD

**Issue by johnjcasey** [apache/beam#26528]
### What happened?

When I clone a new repo, I get the following log building beam:

The connection to the server localhost:8080 was refused - did you specify the right host or port?

This appears to be caused by the getRouterHost task introduced here: https://github.com/apache/beam/pull/25793

I suspect some server isn't stood up, that existed on the development machine, but not mine.

This prevents gradle from running correctly

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by johnjcasey** [comment]
@ruslan-ikhsan please take a look

**Comment by TSultanov** [comment]
.take-issue
