### ISSUE TITLE
[Feature Request]: Add an integration test to address the scenario in #26521

### ISSUE THREAD

**Issue by johnjcasey** [apache/beam#26531]
### What would you like to happen?

Add an integration test to address the scenario in #26521

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by johnjcasey** [comment]
@ahmedabu98

**Comment by ahmedabu98** [comment]
.take-issue

**Comment by ahmedabu98** [comment]
.close-issue

**Comment by ahmedabu98** [comment]
added in #26976
