### ISSUE TITLE
[Failing Test]: beam_PreCommit_Website_Cron

### ISSUE THREAD

**Issue by BjornPrime** [apache/beam#26549]
### What happened?

:website:buildDockerImage failed. The suite has been failing more often than it succeeds since April 28th. The recent failures may have something to do with 404s being returned on initial package requests.

See full Jenkins [console output](https://ci-beam.apache.org/job/beam_PreCommit_Website_Cron/6748/console) for more info.

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [X] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Fixed by #26592
