### ISSUE TITLE
[Bug]: beam_LoadTests_Java_CoGBK_Dataflow_Batch failing to run

### ISSUE THREAD

**Issue by BjornPrime** [apache/beam#26552]
### What happened?

See console output: https://ci-beam.apache.org/job/beam_LoadTests_Java_CoGBK_Dataflow_Batch/1361/console

It seems the suite has been flaky since around April 23rd, possibly due to resource constraints. This is suspected due to log entries like `SEVERE: 2023-05-03T14:50:49.539Z: Startup of the **** pool in zone us-central1-b failed to bring up any of the desired 5 ****s. Please refer to https://cloud.google.com/dataflow/docs/guides/common-errors#****-pool-failure for help troubleshooting. ZONE_RESOURCE_POOL_EXHAUSTED_WITH_DETAILS: Instance 'load0tests0java0dataflow0-05030749-95jc-harness-mgjn' creation failed: The zone 'projects/apache-beam-testing/zones/us-central1-a' does not have enough resources available to fulfill the request.  '(resource type:compute)'.`.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
should be mitigated by #26556
