### ISSUE TITLE
[Failing Test]: beam_PostCommit_Java_PVR_Spark_Batch

### ISSUE THREAD

**Issue by BjornPrime** [apache/beam#26550]
### What happened?

:sdks:java:container:java8:docker has been failing since May 3rd. Possible culprit is `ERROR: lstat /var/lib/docker/tmp/buildkit-mount284588220/target/profiler: no such file or directory'.

See Jenkins [console output](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/1968/console).

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [X] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Fixed by #26901
