### ISSUE TITLE
[Failing Test]: Java PostCommit  failing RecommendationAIUserEventIT.createUserEvent

### ISSUE THREAD

**Issue by Abacn** [apache/beam#26614]
### What happened?

introduced in #26441

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
add a release blocker for 2.48.0 since release cut is close (tomorrow)

**Comment by Abacn** [comment]
CC: @kennknowles

**Comment by kennknowles** [comment]
Would be helpful to directly link to failure. I will look it up.
