### ISSUE TITLE
[Failing Test]: beam_PerformanceTests_SparkReceiver_IO failing

### ISSUE THREAD

**Issue by Abacn** [apache/beam#26621]
### What happened?

Since Apr 25, 2023.

Error massage:

```
23:05:17 org.apache.beam.sdk.io.sparkreceiver.SparkReceiverIOIT > testSparkReceiverIOReadsInStreamingWithOffset FAILED
23:05:17     java.lang.AssertionError: expected:<5000000> but was:<4700000>
23:05:17         at org.junit.Assert.fail(Assert.java:89)
23:05:17         at org.junit.Assert.failNotEquals(Assert.java:835)
23:05:17         at org.junit.Assert.assertEquals(Assert.java:647)
23:05:17         at org.junit.Assert.assertEquals(Assert.java:633)
23:05:17         at org.apache.beam.sdk.io.sparkreceiver.SparkReceiverIOIT.testSparkReceiverIOReadsInStreamingWithOffset(SparkReceiverIOI
```

the actual number of element is fluctuating and always smaller than the expected. May indicates a data loss bug

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Possible cause: #26051 the only SparkreceiverIO PR merged at that time （among 3 java sdk and runner change on that day)

even though the test was succeeded in trigger run: https://ci-beam.apache.org/job/beam_PerformanceTests_SparkReceiver_IO/379/

CC: @aromanenko-dev

**Comment by Abacn** [comment]
#23785 passed on test branch by reverting a14f98a

CC: @Amar3tto

**Comment by aromanenko-dev** [comment]
CC: @Amar3tto 
https://ci-beam.apache.org/job/beam_PerformanceTests_SparkReceiver_IO/ is failing. 
Do you have any ideas how it can be fixed?

**Comment by Amar3tto** [comment]
> CC: @Amar3tto https://ci-beam.apache.org/job/beam_PerformanceTests_SparkReceiver_IO/ is failing. Do you have any ideas how it can be fixed?

Working on this.

**Comment by riteshghorse** [comment]
+1 to @Abacn 's PR to disable the test for now and target this for 2.49.0 Release

Let me know if you think otherwise @Amar3tto

**Comment by Abacn** [comment]
Sorry #26738 does not disable this test. I linked wrong issue at that PR. This is a performance test not in the validation postcommits for the release so up to @riteshghorse to determine whether it's a blocker. If not made into 2.48.0 we should either revert #26051 or release with a known issue

**Comment by riteshghorse** [comment]
okay, Saw disabling the test and stopped there. Thanks for catching Yi!

@aromanenko-dev what do you think about moving this to 2.49.0?

**Comment by riteshghorse** [comment]
Looking at the issue https://github.com/apache/beam/pull/26051, it closed https://github.com/apache/beam/issues/26011 which was P3 issue. As per our release blocker policy https://beam.apache.org/contribute/release-blocking/ I believe we can move this to 2.49.0

**Comment by Abacn** [comment]
Surprisingly the test is back green yesterday: https://ci-beam.apache.org/view/PerformanceTests/job/beam_PerformanceTests_SparkReceiver_IO/ We can close it for now

Why it was recovered itself remains unclear...

**Comment by Abacn** [comment]
It's failing again after 3 successful run, same reason (not all record counted). Reopen...

**Comment by aromanenko-dev** [comment]
Is it just a flaky test?

**Comment by aromanenko-dev** [comment]
Also, since it takes quite significant amount of time to finish, I'd recommend to run this job less often - once per day, for example.
