### ISSUE TITLE
[Bug]: Dask runner limited to 100 concurrent tasks

### ISSUE THREAD

**Issue by jacobtomlinson** [apache/beam#26669]
### What happened?

If I call `beam.Create` with an iterable that has >=200 items then Dask only executes 100 tasks concurrently. If it has <199 items it executes all items concurrently.

Therefore if my Dask cluster has more than 200 workers I cannot fully saturate the cluster. And even if my cluster has 199 workers if my collection is larger than 199 I lose performance.

It seems that Beam is batching parallel do operations before constructing the Dask graph. Is that batch size configurable somehow?

```python
import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions
from apache_beam.runners.dask.dask_runner import DaskRunner

from dask.distributed import Client, performance_report

class NoopDoFn(beam.DoFn):
    def process(self, item):
        import time
        time.sleep(0.1)
        return [item]


def run_pipeline(n_items):
    client = Client()
    pipeline = beam.Pipeline(
        runner=DaskRunner(),
        options=PipelineOptions(["--dask_client_address", client.cluster.scheduler_address]),
    )

    (
        pipeline
        | "Create collection" >> beam.Create(range(n_items))
        | "Noop 1" >> beam.ParDo(NoopDoFn())
        | "Noop 2" >> beam.ParDo(NoopDoFn())
        | "Noop 3" >> beam.ParDo(NoopDoFn())
    )

    with performance_report(filename=f"dask-report-{n_items}.html"):
        result = pipeline.run()
        result.wait_until_finish()

def main() -> None:
    # If this is <=199 I get one task per item per stage (800 tasks, 199 concurrent)
    run_pipeline(199)
    # If this is >=200 I get max 100 tasks per stage (404 tasks, 100 concurrent)
    run_pipeline(200)


if __name__ == "__main__":
    main()
```

This reproducer outputs two files, [`dask-report-199.html`](https://gistcdn.githack.com/jacobtomlinson/7cd1d4b0ffb67034f64385628996e38f/raw/deeaa2cb93c7f98b3d6e32c32a5ec121bb0d328c/dask-report-199.html) and [`dask-report-200.html`](https://gistcdn.githack.com/jacobtomlinson/7cd1d4b0ffb67034f64385628996e38f/raw/deeaa2cb93c7f98b3d6e32c32a5ec121bb0d328c/dask-report-200.html). Each report contains a "Tasks Information" section where you can see the number of Dask tasks produced.

#### `dask-report-199.html`

<img width="196" alt="image" src="https://github.com/apache/beam/assets/1610850/60a3fe32-4384-45fb-bdc6-108a6b2bb96d">

#### `dask-report-200.html`

<img width="214" alt="image" src="https://github.com/apache/beam/assets/1610850/6863e060-5081-4832-a735-591d46e52069">

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner
- [X] Component: Dask Runner

**Comment by AnandInguva** [comment]
cc: @pabloem

**Comment by tvalentyn** [comment]
cc: @alxmrs

**Comment by jacobtomlinson** [comment]
After exploring this further there seem to be two separate things going on here.

First is that Dask Bag has a limit on the number of partitions it creates by default. This limit is 100, but due to some integer rounding it will overshoot until it is a multiple of 100 and then collapse again. This is why we see a ~50% performance drop between 199 items and 200 items, then a small increase before dropping again at 300, etc. I've opened https://github.com/dask/dask/pull/10294 to address this so that the number of tasks continues to grow with the number of items, just in a non-linear way.

The second is that Beam is always using a Dask Distributed cluster, and at the time of execution has an instance if `dask.distributed.Client`. Therefore we could override the default partitioning scheme altogether and explicitly set the number of partitions to match the number of workers in the cluster. This would require Beam to somehow communicate this information to the `Create` node when it walks the pipeline.

**Comment by jacobtomlinson** [comment]
Quick update. The latest Dask release (`2023.5.1`) includes the fix to Dask Bag's partitioning heuristic which means that the number of partitions will continue to increase as more items are added to the bag. This partially works around the problem we are seeing here because in theory with enough items in the PCollection you can saturate any number of Dask workers. However in reality you may not actually have enough items in your dataset so it may not solve this problem for everyone.

A complete fix for this would be for Beam to explicitly set the number of partitions in the bag equal to the number of workers in the cluster. Beam knows this information at execution time so it should be a case of passing this along. I started looking into proposing a fix for this but it seems the bag gets created lazily at a point in time where we don't yet have a Dask Distributed Client. I think I'm at the point where I need someone more familiar with Beam like @alxmrs to point me in the right direction of what to do next.

cc @rabernat who may have a passing interest in this issue

**Comment by alxmrs** [comment]
Hey Jacob,

Thanks for looking into this! Are you free this Thursday or Friday after 1pm PST?

**Comment by alxmrs** [comment]
I put time on your cal for tomorrow :)
