### ISSUE TITLE
[Failing Test][Go SDK]: Flake in lastModified test for local filesystem.

### ISSUE THREAD

**Issue by lostluck** [apache/beam#26703]
### What happened?

```
-- FAIL: TestLocal_lastModified (0.00s)
    local_test.go:177: LastModified("/tmp/TestLocal_lastModified2985575980/001/file.txt") = 2023-05-15 21:32:42.998867243 +0000 UTC, want in range [2023-05-15 21:32:43 +0000 UTC, 2023-05-15 21:32:43.004302634 +0000 UTC m=+0.001527498]
FAIL
	github.com/apache/beam/sdks/v2/go/pkg/beam/io/filesystem/local	coverage: 77.4% of statements
FAIL	github.com/apache/beam/sdks/v2/go/pkg/beam/io/filesystem/local	0.036s
```

https://github.com/apache/beam/blob/05eba4cfc86785f18ee4b7625bbb2f564afef95b/sdks/go/pkg/beam/io/filesystem/local/local_test.go#L157

Might need to update that resolution to 2 seconds. The system time modification is *after* the time range oddly enough. TIL there's system vs go runtime skew... 

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by lostluck** [comment]
cc: @johannaojeling

**Comment by johannaojeling** [comment]
Interesting, thanks for raising this. I'll open a PR. Looks like the system mod time in this case is below the range though? I can increase the range on both ends

**Comment by johannaojeling** [comment]
.take-issue
