### ISSUE TITLE
[Task]: Build comment triggers replacement

### ISSUE THREAD

**Issue by andreydevyatkin** [apache/beam#26742]
### What needs to happen?

Build comment triggers replacement (e.g. Run Python PreCommit) using Github Actions

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by kevingtz** [comment]
.take-issue

**Comment by celeste-zeng** [comment]
https://github.com/apache/beam/pull/27982 adds github-actions trigger commands for Datafow ARM test suites to github_actions_jobs.txt, which was later read in release/src/main/scripts/mass_comment.py , we should add all github-actions trigger commands to github_actions_jobs.txt once the script can handle GitHub Actions triggers.
