### ISSUE TITLE
[Bug]: Python SDK Worker failure should be CRITICAL/FATAL, not ERROR

### ISSUE THREAD

**Issue by cozos** [apache/beam#26756]
### What happened?

In Beam on Dataflow, we are getting Python SDK Harness failures that manifest in the job logs like this:

```
Error message from worker: SDK harness sdk-0-1 disconnected. This usually means that the process running the pipeline code has crashed. Inspect the Worker Logs and the Diagnostics tab to determine the cause of the crash.
```

Looking through the logs, the root cause for the failure is dropping the gRPC connection for Fn Control API:

```
Python sdk harness failed:
Traceback (most recent call last):
  File "/bag_data_cache_docker_pybinary.runfiles/cruise_ws/cruise/mlp/cfs/projects/trajectory_ranking/pipeline/bag_data_cache_docker_pybinary_exedir/apache_beam/runners/worker/sdk_worker_main.py", line 157, in main
    sdk_harness.run()
  File "/bag_data_cache_docker_pybinary.runfiles/cruise_ws/cruise/mlp/cfs/projects/trajectory_ranking/pipeline/bag_data_cache_docker_pybinary_exedir/apache_beam/runners/worker/sdk_worker.py", line 234, in run
    for work_request in self._control_stub.Control(get_responses()):
  File "/bag_data_cache_docker_pybinary.runfiles/cruise_ws/cruise/mlp/cfs/projects/trajectory_ranking/pipeline/bag_data_cache_docker_pybinary_exedir/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/bag_data_cache_docker_pybinary.runfiles/cruise_ws/cruise/mlp/cfs/projects/trajectory_ranking/pipeline/bag_data_cache_docker_pybinary_exedir/grpc/_channel.py", line 809, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "keepalive watchdog timeout"
	debug_error_string = "{"created":"@1684279532.354148410","description":"Error received from peer ipv6:[::1]:12371","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"keepalive watchdog timeout","grpc_status":14}"
```

Ignoring the root cause for now (although if some Dataflow experts can help shed some light on this, it'd be appreciated) - it was pretty hard to actually find that `Python sdk harness failed` log message.

This is because the log severity of this stack trace is just `ERROR` - but I would expect a problem that brought down a worker process to be `CRITICAL`! It's important that we understand what killed our SDK Harness.

![Screen Shot 2023-05-18 at 12 40 32 AM](https://github.com/apache/beam/assets/2646862/7eef4077-8068-4cc9-afe3-2330eca4aa3e)

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by cozos** [comment]
Added PRs:

* https://github.com/apache/beam/pull/26757 < `master`
* https://github.com/apache/beam/pull/26758 < `release-2.47.0`

I added `release-2.47.0` for selfish reasons, because I want to use this change in 2.47.0

**Comment by jrmccluskey** [comment]
Hi @cozos, 2.47.0 is already released, and the release process involves more than just applying a patch to the GitHub release branch. Unfortunately this wouldn't be sufficient to lead to a 2.47.1

**Comment by tvalentyn** [comment]
> a worker restart and retry the work, so it is not "critical" by definition

these errors trigger SDK disconnections, which are logged at critical level later by UW harness. If it helps users to find the rootcause easier surfacing relevant worker log with a higher severity, I am happy to give this a try.

**Comment by tvalentyn** [comment]
@cozos - if you'd like to patch this on top of 2.47.0 you can do so locally and supply a custom SDK zip via the `--sdk_location` pipeline option.

**Comment by cozos** [comment]
Thanks for the help team.

> The error will re-raise and causing a worker restart and retry the work, so it is not "critical" by definition.
In my case, this error will retry and reoccur 4 times - so it ended up being critical. Unlike other exceptions which are logged at the `ERROR` level and are caught further down the bundle processing stack, these exceptions *causes abrupt termination of the SDK harness* - which is definitely not normal. Because of this I think it's important to surface with `CRITICAL`.
