### ISSUE TITLE
[Failing Test]: Tests for Flink runners are failing in "Java PreCommit check"

### ISSUE THREAD

**Issue by TSultanov** [apache/beam#26785]
### What happened?

I'm noticing that "Java PreCommit check" job is failing in several of my PRs, some of which are not related to any Java code.

The failures are all seem to be related to Flink runner (`:runners:flink:...:test` jobs). I've tried running these tests locally, but they all seem to pass fine.

PRs with failing "Java PreCommit check":
| PR Link | Jenkins Link |
|-|-|
| https://github.com/apache/beam/pull/26762 | https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/6094/ |
| https://github.com/apache/beam/pull/26488 | https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/27220 |
| https://github.com/apache/beam/pull/26713 | https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/27221/ |

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [X] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
This is known flake (#21333); this flink tests each setup a flink minicluster, and when jenkins node under high load it then stucks. A recent build system change worsened the issue: #26776 should be partly mitigated after #26784 in.

**Comment by Abacn** [comment]
Also, we could separate flink runner tests of version matrices into another precommit to reduce the noise. That is, he current java precommit runs on a single flink version; while other versions in another precommit that is only triggered when runner code change.

**Comment by Abacn** [comment]
close as fixed by #26784. Recent java precommit cron jobs are pretty green now
