### ISSUE TITLE
[Feature Request]: BigQueryIO Storage Write should have metrics/counter for failed inserts

### ISSUE THREAD

**Issue by bvolpato** [apache/beam#26853]
### What would you like to happen?

In case the FailedInserts PCollection is not consumed, BigQueryIO will silently drop records.

This is probably working as intended, but I believe we should use a counter to expose this situation to users.

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by bvolpato** [comment]
cc @reuvenlax

**Comment by Abacn** [comment]
Part of the graph:

<img width="288" alt="image" src="https://github.com/apache/beam/assets/8010435/da7881ab-251f-4f39-af26-77a091ea9670">

Both Convert and StorageApiWriteUnsharded have DLQ sending to flatternErrors

Codepaths where Exceptions gets suppressed:

- in Convert

  https://github.com/apache/beam/blob/83e2e6197372283dcfeec4b6cd398368ed6c9899/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiConvertMessages.java#L146

- in Write Records
  
  handled by a failedRowsReceiver:

  https://github.com/apache/beam/blob/83e2e6197372283dcfeec4b6cd398368ed6c9899/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java#L491

Both send to a Flatten:

https://github.com/apache/beam/blob/83e2e6197372283dcfeec4b6cd398368ed6c9899/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiLoads.java#L148

**Comment by johnjcasey** [comment]
Generally speaking, we should probably at least warn for any pcollection that isn't consumed.

**Comment by Abacn** [comment]
Addressed in #26919
