### ISSUE TITLE
[Failing Test]:  PythonExternalTransformTest.java failing

### ISSUE THREAD

**Issue by riteshghorse** [apache/beam#26868]
### What happened?

This test is failing on release branch:
```
org.apache.beam.sdk.extensions.python.PythonExternalTransformTest > pythonTransformWithDependencies FAILED
    org.apache.beam.vendor.grpc.v1p54p0.io.grpc.StatusRuntimeException at PythonExternalTransformTest.java:73
```

Log link: https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct_PR/164/consoleText

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by riteshghorse** [comment]
@chamikaramj (feel free to triage)

**Comment by chamikaramj** [comment]
How did you try the test ?

Seems like it's passing on HEAD: https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/4145/testReport/org.apache.beam.sdk.extensions.python/PythonExternalTransformTest/pythonTransformWithDependencies/

**Comment by chamikaramj** [comment]
Seems like it passed after a retry: https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct_PR/165/
