### ISSUE TITLE
[Task][Clean-Up]: Create `Healthcare` Directory under Python SDK IOs

### ISSUE THREAD

**Issue by svetakvsundhar** [apache/beam#26877]
### What needs to happen?

To mirror what we have in the Java IOs [1], we should create a new directory under [2], and add the DICOM Python IO. This will make the codebase readability cleaner and give a location for folks to add more healthcare IOs in Python if the need arises.

[1]
https://github.com/apache/beam/tree/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/healthcare

[2]
https://github.com/apache/beam/tree/master/sdks/python/apache_beam/io/gcp

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by svetakvsundhar** [comment]
cc: @ahmedabu98 @Abacn @johnjcasey if you are ok with this, I will put up a PR.

**Comment by svetakvsundhar** [comment]
.take-issue

**Comment by Abacn** [comment]
Yeah In Java each gcp component has its own package (bigquery/bigtable/healthcare etc) but for Python, for now, most are all in gcp (exception is pubsublite which is an external transform) moving healthcare alone does not improve the situation much

and in general I feel like Python modules tends to have fewer layer. Not sure if this was language convention. We moved kafka connector from apache_beam.io.external to apache_beam.io before

**Comment by svetakvsundhar** [comment]
Offline discussion with @Abacn : 

The new team I just joined leverages the Healthcare Connectors and so moving these under a healthcare folder will help reduce tech debt in case we contribute Python specific connectors in the future.

We could do what was done in [1] to avoid breaking changes.

cc: @tvalentyn 

[1]
https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/external/kafka.py

**Comment by tvalentyn** [comment]
i don't have a strong opinion, but yes we should pay attention to not make breaking changes.

**Comment by johnjcasey** [comment]
Agreed on better factoring of connectors.
