### ISSUE TITLE
[Task]: Consolidate dev container image

### ISSUE THREAD

**Issue by Abacn** [apache/beam#26921]
### What needs to happen?

We publish same Python container in two places, e.g.

gcr.io/apache-beam-testing/beam_portability/beam_python3.7_sdk:latest
daily by https://ci-beam.apache.org/job/beam_Publish_Docker_Snapshots/

gcr.io/apache-beam-testing/beam-sdk/beam_python3.7_sdk
every 4 hours by https://ci-beam.apache.org/job/beam_Publish_Beam_SDK_Snapshots

The first place also has java-sdk and go-sdk containers but no longer continuously publishing (last time was in 2022). This task involves stop publish Python SDK snapshot in this dir and switch to use the ones in gcr.io/apache-beam-testing/beam-sdk.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [x] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
cc: @damccorm
