### ISSUE TITLE
[Failing Test]: Website tests and deploy failing due to 2.48.0 blog post

### ISSUE THREAD

**Issue by Abacn** [apache/beam#26983]
### What happened?

Error message:

```
20:16:24 ERROR 2023/06/01 00:16:24 Author 'riteshghorse' is not defined. Please add them to 'website/www/site/data/authors.yml'
20:16:35 Total in 12880 ms
20:16:35 Error: Error building site: logged 1 error(s)
20:16:35 error Command failed with exit code 255.
20:16:35 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

See https://ci-beam.apache.org/view/PostCommit/job/beam_PreCommit_Website_Cron/6857/console

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
CC: @riteshghorse assigned you

**Comment by riteshghorse** [comment]
Oh I need to add myself to the list.. looking at it now
