### ISSUE TITLE
[Failing Test]: test_avro_nyc_trips_output_files_on_small_input different result on Spark and Flink failing Example test suite

### ISSUE THREAD

**Issue by Abacn** [apache/beam#27046]
### What happened?

The new example is added in #26689

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Python_Examples_Flink/1917/
https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Python_Examples_Spark/1895/testReport/

However it passes on Direct and Dataflow:

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Python_Examples_Direct/lastCompletedBuild/testReport/apache_beam.examples.avro_nyc_trips_it_test/

```
AssertionError: Lists differ: [{'service': 'Lyft', 'day': 'Fri', 'total_price': 58.39[816 chars]042}] != [{'service': 'Uber', 'day': 'Fri', 'total_price': 21.22[376 chars]042}]

First differing element 0:
{'service': 'Lyft', 'day': 'Fri', 'total_price': 58.39[379 chars]3928}
{'service': 'Uber', 'day': 'Fri', 'total_price': 21.22[375 chars]5042}
```

Not sure why but it since the example is non-deterministic?

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by nyoungstudios** [comment]
Thanks for raising this, I can take a look to fix my example

**Comment by nyoungstudios** [comment]
.take-issue

**Comment by nyoungstudios** [comment]
I fixed the test case for the Spark and Flink runners in the linked pull request above. The reason those were failing was because the data output was written to separate files rather that what I assumed was just 1 file.
