### ISSUE TITLE
[Bug]: Python KafkaIO read transform is inefficient when using the commit_offsets_in_finalize option

### ISSUE THREAD

**Issue by chamikaramj** [apache/beam#27061]
### What happened?

Seems like Python Kafka IO read transform requires significant more resources when using"commit_offsets_in_finalize" option.

'commit_offsets_in_finalize' adds an extra Reshuffle and a callback to Kafka to commit messages.

For streaming jobs, seems like this results in backlog of the Kafka read work item  increasing by a large amount time to time and Dataflow jobs are unable to downscale due to this backlog. 

Transform can operate efficiently when not using the "commit_offsets_in_finalize" option.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by chamikaramj** [comment]
Java pipelines may exhibit similar behaviors but I haven't tested that.

@johnjcasey is this something we can track as a part of the ongoing effort to improve the Kafka connector ?

**Comment by Abacn** [comment]
related Java issue (commitOffsetsInFinalize): #20689

**Comment by scwhittle** [comment]
#31682 removes the reshuffle when commit offsets in finalized is enabled
