### ISSUE TITLE
[Failing Test]: SpannerWriteIT is failing on master.

### ISSUE THREAD

**Issue by Dippatel98** [apache/beam#27104]
### What happened?

https://ci-beam.apache.org/job/beam_PreCommit_Java_GCP_IO_Direct_Phrase/188/

The test seems to be failing because it is trying to insert null values in the field `Value` of the Spanner test table `user`. 

The below exception is being thrown by the test on master branch w/o any changes.
```
com.google.cloud.spanner.SpannerException: FAILED_PRECONDITION: com.google.api.gax.rpc.FailedPreconditionException: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Value must not be NULL in table users.
```

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
The test is recovered green
