### ISSUE TITLE
[Feature Request]: allow users to provide their own JdbcReadWithPartitionsHelper

### ISSUE THREAD

**Issue by hughlunnon** [apache/beam#27120]
### What would you like to happen?

at the moment, readWithPartition is limited to the data types of Long, DateTime. It would be great for users to be able to provide their own JdbcReadWithPartitionsHelper (the interface exists) to allow them to partition on other key types (eg strings). 

I'm happy to add it to the java sdk, no idea if the problem exists on other sdks?

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Thanks! This is a nice feature to have. For other SDK (Python) because it is configured by schema, so user cannot pass an object (like Python function) to config ReadFromJdbc

**Comment by Amar3tto** [comment]
.take-issue
