### ISSUE TITLE
[Bug]: Website, quickstart-go looks not up-to-date

### ISSUE THREAD

**Issue by aromanenko-dev** [apache/beam#27207]
### What happened?

I try to follow the steps on https://beam.apache.org/get-started/quickstart-go/ to run a `wordcount` with Go SDK and have some difficulties.

The command `go get` seems is not working anymore with latest versions of Go:
```
$ go version
go version go1.20.5 darwin/amd64

$ go get -u github.com/apache/beam/sdks/v2/go/pkg/beam
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

When I try to install the latest version with `install` command then it fails: 
```
$ go install github.com/apache/beam/sdks/v2/go/pkg/beam@latest
package github.com/apache/beam/sdks/v2/go/pkg/beam is not a main package
```
When I try to specify a version explicitly I have the same result:
```
$ go install github.com/apache/beam/sdks/v2/go/pkg/beam@v2.47.0
package github.com/apache/beam/sdks/v2/go/pkg/beam is not a main package
$ echo $?
1
```

I'm a Go noobie, so, please let me know if I'm doing something wrong.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by aromanenko-dev** [comment]
Ping @lostluck

**Comment by lostluck** [comment]
Per the instructions produced by vy the Go  there, the user needs to be in a module for our instructions to work as intended.

See https://go.dev/doc/tutorial/getting-started for the basics of Go.

We try not to spend time teaching language operations in the beam docs since the point of Beam is to use the language you like already, not to force you to learn a new one.

I can't check and fix the quickstart instructions at present to clarify the module expectation however. In a car for several hours.

**Comment by aromanenko-dev** [comment]
Yes, I agree about not teaching the basics of Go there, but I'd add more details on Quickstart Go page about how to run Beam Go pipeline properly and with all needed commands/steps (especially, for people like me, who just started their journey with Go).

**Comment by lostluck** [comment]
Oh, I agree!

I just can't make the change from my phone.
