### ISSUE TITLE
[Feature Request]: Dynamic Staging Bucket Argument for Apache Beam Dataflow Pipelines

### ISSUE THREAD

**Issue by rohan472000** [apache/beam#27201]
### What would you like to happen?

I'm using below function:

                  def final_pipeline():     
                      with beam.Pipeline(options=pipeline_options) as pipeline: 
                          readable_files = (                 
                                       pipeline                 
                                          | fileio.MatchFiles(file_pattern="gs://bucket_name/zipfile/*.csv")   
                                          | fileio.ReadMatches()               
                                          | beam.Reshuffle()        
                                            )         
                          files_parsing = ( 
                                      readable_files                 
                                           | beam.ParDo(DataTransformFn())    
                                           | WriteToBigQuery(user_options.TABLE_NAME)         
                                            ) 
                  
                  if _name_ == '_main_':     
                      final_pipeline()  
           
          
Is there a way to dynamically pass the staging bucket location as an argument to the `final_pipeline()` function or to `beam.Pipeline()`in Apache Beam, allowing for flexibility in specifying the source location of files for subsequent pipelines in Google Cloud Platform (GCP) Dataflow?

I don't want to use match file pattern i,e.. `fileio.MatchFiles()`, because it will lead to have different dataflows for different files, instead of that I want to pass a dynamic bucket path to the `final_pipeline()` function in `main` which I'll fetch from composer using `user_options`.

### High

Priority: 3 (nice-to-have improvement)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
Since you are a Dataflow user, see also Flex template +  parameters: https://cloud.google.com/dataflow/docs/guides/templates/using-flex-templates#run-a-flex-template-pipeline
