### ISSUE TITLE
Enable FirestoreV1IT to run against hosts other than the default Firestore host

### ISSUE THREAD

**Issue by SabaSathya** [apache/beam#27255]
### What happened?

Currently, FirestoreV1IT is executed against the hard coded default Firestore host.  During development and testing, it needs to be executed against dev/QA hosts.  This can be achieved by adding an env variable that can point to a Firestore host other than the default host.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Could this issue be closed?

**Comment by SabaSathya** [comment]
Yes.  Closing this as a host can be given as arg in 2.50.0-SNAPSHOT.
