### ISSUE TITLE
[Failing Test]: beam_Release_Gradle_Build permared

### ISSUE THREAD

**Issue by Abacn** [apache/beam#27320]
### What happened?

This test suite (https://ci-beam.apache.org/job/beam_Release_Gradle_Build/) only runs during release verification and does not have a cron job. From the history the last successful build was #25600 for beam 2.46.0. Since them several projects failing for different reasons. beam2.47.0-2.48.0 released without this suite passing

We need to decide either fix or deprecate this test suite

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by kennknowles** [comment]
What does this job do? Do we need to keep it?

**Comment by Abacn** [comment]
It basically run `./gradlew build`, which involves run `:build` tasks for every project - involve compile and run unit test. Some recently added test-only projects (e.g. `:sdks:java:io:kafka:kafka-251`) appear to be not configured correctly

```
02:30:39 Caused by: ca.cutterslade.gradle.analyze.DependencyAnalysisException: Dependency analysis found issues.
02:30:39 unusedDeclaredArtifacts
02:30:39  - beam.sdks.java.io:kafka:2.49.0@jar
02:30:39  - org.apache.kafka:kafka-clients:2.4.1@jar
```

**Comment by kennknowles** [comment]
I would say that general of a run is not a good idea, so we should just delete it.

**Comment by Abacn** [comment]
ok, will draft a PR removing it / update documentation
