### ISSUE TITLE
[Task]: Standardize GCSIO batch methods responses

### ISSUE THREAD

**Issue by BjornPrime** [apache/beam#27325]
### What needs to happen?

In the upgrade from an apitools-based client GCSIO's batch methods needed to use the new GCS client Batch objects, which reported their responses differently from what Beam tends to expect. Transform the batch._responses field that they're currently returning into a tuple of the form (path, exception) for delete_batch and (src, dest, exception) for copy_batch. Then fix their usage in gcsfilesystem.py so that paths with be passed along with their exceptions, like the other methods in that file.

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by BjornPrime** [comment]
.take-issue

**Comment by lostluck** [comment]
2.50 release manager here.
This issue is currently tagged for the 2.50.0 release, which cuts in a week on August 9th.

Please complete work and get it into the main branch in that time, or move this issue to the 2.51 Milestone: https://github.com/apache/beam/milestone/15

**Comment by Abacn** [comment]
This was obsolete. Original change reverted on master
