### ISSUE TITLE
[Bug]:  CancellableQueue keeps references to elements when cancelled and reset

### ISSUE THREAD

**Issue by scwhittle** [apache/beam#27401]
### What happened?

sdks/java/fn-execution/src/main/java/org/apache/beam/sdk/fn/CancellableQueue.java has an internal array that it puts elements in.  The take, cancel and reset methods modify the offsets of where logically elements are stored but the references to elements remain in the array which could keep them alive increasing memory usage

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
add to 2.49.0 release since this bug is reported to cause worker OOM for streaming pipelines

**Comment by Abacn** [comment]
reopen to track cherry-pick

**Comment by Abacn** [comment]
closed by #27401
