### ISSUE TITLE
[Task]: fix the javadoc which indicate that fileload doesnt support json type

### ISSUE THREAD

**Issue by byeshvantlive** [apache/beam#27448]
### What needs to happen?

On the javadoc for BigQuery fileload we mention that load with json field types is not supported 
https://javadoc.io/doc/org.apache.beam/beam-sdks-java-io-google-cloud-platform/latest/org/apache/beam/sdk/io/gcp/bigquery/BigQueryIO.Write.Method.html#FILE_LOADS

Can we fix this javadoc confusing if this is allowed but the doc doesnt align.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by brucearctor** [comment]
@byeshvantlive -- I was just reading docs and noticed this as well.  Have you tested?  Does the functionality work?  Is this a matter of fixing the docs?  Or do we also need to fix the functionality so that BQ FILE_LOADS works with JSON BQ type?

**Comment by brucearctor** [comment]
Relates to --> https://github.com/apache/beam/issues/23025
