### ISSUE TITLE
[Failing Test]: StreamingDataflowWorkerTest.testMaxThreadMetric looks flaky

### ISSUE THREAD

**Issue by mosche** [apache/beam#27555]
### What happened?

I've seen StreamingDataflowWorkerTest.testMaxThreadMetric failing a couple of time on [Jenkins](https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/lastCompletedBuild/testReport/org.apache.beam.runners.dataflow.worker/StreamingDataflowWorkerTest/testMaxThreadMetric_0___streamingEngine_false__/) and suspect it's flaky, particularly as it was just added very recently.

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

**Comment by olalamichelle** [comment]
.take-issue

**Comment by olalamichelle** [comment]
I have created a PR for this issue: https://github.com/apache/beam/pull/28173.

**Comment by olalamichelle** [comment]
.close-issue
