### ISSUE TITLE
[Bug]: beam_PostCommit_XVR_Direct is consistently failing to complete its runs

### ISSUE THREAD

**Issue by BjornPrime** [apache/beam#27641]
### What happened?

[beam_PostCommit_XVR_Direct](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/) hasn't completed a run since July 22nd and hasn't had a successful run since July 20th.

This is possibly related to #27640 , failures on a similar test that began around the same time.

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
It's related. All XVR Tests, except Dataflow, are failing multiple JavaUsingPython tests with container issues. 

There is no Beam code change between the last succeeded run and first failing run:

Jul 20, 2023, 5:42 PM https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_XVR_Samza/2902/

Jul 20, 2023, 4:18 PM https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_XVR_Flink/7124/

Is it transitive dependency issue?
