### ISSUE TITLE
[Failing Test]:  beam_PostCommit_XVR_Flink is consistently experiencing multiple failing tests

### ISSUE THREAD

**Issue by BjornPrime** [apache/beam#27640]
### What happened?

About a dozen tests from beam_PostCommit_XVR_Flink have been [failing](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/) consistently since late on July 20th.

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [X] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
All JavaUsingPython test suite on different runners are failing. Let's use #27641 for tracking

**Comment by Abacn** [comment]
close as duplicate
