### ISSUE TITLE
[Failing Test]: apache_beam.runners.portability.portable_runner_test.PortableRunnerTestWithSubprocesses.test_pardo_state_with_custom_key_coder

### ISSUE THREAD

**Issue by kennknowles** [apache/beam#27667]
### What happened?

Failure: [apache_beam.runners.portability.portable_runner_test.PortableRunnerTestWithSubprocesses.test_pardo_state_with_custom_key_coder](https://ci-beam.apache.org/job/beam_PreCommit_Python_Coverage_Commit/3144/testReport/junit/apache_beam.runners.portability.portable_runner_test/PortableRunnerTestWithSubprocesses/test_pardo_state_with_custom_key_coder/)

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
duplicates #24313 (still open)
