### ISSUE TITLE
[Bug]: beam_PreCommit_Python_Cron build failed

### ISSUE THREAD

**Issue by BjornPrime** [apache/beam#27663]
### What happened?

Most recent build failed. See [console](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/7373/console) for more details.

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
no longer failing.
