### ISSUE TITLE
[Task]: Create a GitHub Actions workflow for publishing nightly Beam snapshots

### ISSUE THREAD

**Issue by andreydevyatkin** [apache/beam#27821]
### What needs to happen?

Create a GitHub Actions workflow for publishing nightly Beam snapshots

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by volatilemolotov** [comment]
.take-issue
