### ISSUE TITLE
[Bug]: Update Grafana version

### ISSUE THREAD

**Issue by aaltay** [apache/beam#27908]
### What happened?

Currently we are using v8.1.8 at http://metrics.beam.apache.org/. There are newer versions. We should consider latest, or if that is not possible we can upgrade to latest in the 8.x.x line (8.5.27 as of now.)

@liferoad @Abacn 

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by liferoad** [comment]
.take-issue
