### ISSUE TITLE
[Task]: Update Base Image Dependencies for Python Container Images

### ISSUE THREAD

**Issue by lostluck** [apache/beam#27944]
### What needs to happen?

The release manager needs to do this.

The week before the next release cut, then update this issue's milestone to next version.

Follow the instructions per https://s.apache.org/beam-python-requirements-generate

Tag the PR with the release milestone in question.

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by kennknowles** [comment]
I followed the release guide and did not consult GitHub issues. This is not the place for things that need to happen before the cut, as burning down issues to zero is a post-cut activity. Perhaps moving the release guide to the Wiki so it is easy and lightweight to edit could make sense.

**Comment by damccorm** [comment]
Added https://github.com/apache/beam/pull/28645 for this

**Comment by kennknowles** [comment]
#28625 is a little further along in terms of waiting for GHA to complete
