### ISSUE TITLE
[Task]: Cleanup Python tests in pipeline options module

### ISSUE THREAD

**Issue by kerrydc** [apache/beam#28024]
### What needs to happen?

Current Python tests in options/pipeline_options_test.py and options/pipline_options_validator_test.py use an antipattern of for loops to approximate parameterized testing. This has the side effect of failing on the first test case that fails in the loop, masking further errors. In addition, the asserts do not contain the case the triggered the failure, making it hard to see which case failed.

Rewrite these tests to use https://pypi.org/project/parameterized/. Ensure that the test failures give clear error messages, and also ensure that the tests cases are all executed even when the first one fails.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by timgrein** [comment]
Would like to take a look at that one! :)

**Comment by timgrein** [comment]
.take-issue
