### ISSUE TITLE
[Task]: Document combinefn compact on programming guide

### ISSUE THREAD

**Issue by damccorm** [apache/beam#28129]
### What needs to happen?

Right now, https://beam.apache.org/documentation/programming-guide/#combine shows all the combinefn lifecycle methods except for compact. We should include that for completeness

(implementation in Python here - https://github.com/apache/beam/blob/5ceed8eaf0927940a75a56637ec07253ba19abe4/sdks/python/apache_beam/transforms/core.py#L1084)

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [X] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by mohamedawnallah** [comment]
.take-issue

**Comment by damccorm** [comment]
@mohamedawnallah looks like this issue has sat for a bit so I'm going to take it forward
