### ISSUE TITLE
[Feature Request]: Access PipelineOptions in BeamSqlSeekableTable

### ISSUE THREAD

**Issue by gabrywu** [apache/beam#28145]
### What would you like to happen?

I'm creating a BeamSqlSeekableTable class, and want to access PipelineOptions.
For example, a HadoopDataSeekableTable needs loading data from Hadoop, and our Hadoop cluster needs keberos auth. 
So, my question is that is it possible to access pipeline options to complete the auth?

I know that I can pass auth parameters to table properties, however, it will be convenient to get parameters from PipelineOptions.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by gabrywu** [comment]
any one need this feature? I can create a PR to this feature (already released our production environment)

**Comment by liferoad** [comment]
> any one need this feature? I can create a PR to this feature (already released our production environment)

Please do a PR. Thanks for contributing to Beam!
