### ISSUE TITLE
[Bug]: Error when pushing transform/expansion service containers for releases

### ISSUE THREAD

**Issue by chamikaramj** [apache/beam#28214]
### What happened?

Reported by Beam 2.50.0 release manager @lostluck.

When building RC containers using the following command:
```
./gradlew :sdks:python:expansion-service-container:pushAll  -PisRelease -Pdocker-pull-licenses -Pdocker-tag=${RELEASE_VERSION}rc${RC_NUM} -Pjava11Home=${JAVA11_HOME} --no-daemon --no-parallel
```

Following error gets raised:

```
#32 exporting to image
#32 pushing layers 23.1s done
#32 pushing manifest for 
docker.io/apache/beam_python_expansion_service:2.50.0rc2@sha256:1fa57e448081df4df30089c4b46006e0d7d54eb0f0ce004a28f1dde2cc12e6b3
#32 pushing manifest for docker.io/apache/beam_python_expansion_service:2.50.0rc2@sha256:1fa57e448081df4df30089c4b46006e0d7d54eb0f0ce004a28f1dde2cc12e6b3 2.0s done
#32 DONE 46.3s

> Task :sdks:python:expansion-service-container:dockerTag2.50.0 FAILED
Error response from daemon: No such image: apache/beam_python_expansion_service:2.50.0rc2

FAILURE: Build failed with an exception.
```

Same error gets raised when building following containers.

```
./gradlew :sdks:java:transform-service:controller-container:pushAll
./gradlew :sdks:java:expansion-service:container:pushAll
```

Nevertheless seems like containers got built and pushed to the repository anyways (so not a release blocker).

But the error indicates that something is broken during the build step.

This is likely related to recent ARM container changes.

@celeste-zeng can you check ?

cc: @valen

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by celeste-zeng** [comment]
I will TAL, thanks!

**Comment by chamikaramj** [comment]
Thanks Celeste!
