### ISSUE TITLE
[Task]: Give github-actions service account auth to healthcare.fhirStores.create

### ISSUE THREAD

**Issue by celeste-zeng** [apache/beam#28227]
### What needs to happen?

[beam_PostCommit_Go_Dataflow_ARM.yml](https://github.com/apache/beam/blob/master/.github/workflows/beam_PostCommit_Go_Dataflow_ARM.yml) failed due to permission healthcare.fhirStores.create denied:
![image](https://github.com/apache/beam/assets/61256376/002a96e9-1fe5-461d-a8d8-8dd676d436bd)

https://github.com/apache/beam/pull/28215 excludes TestFhirIO.* from the test lists so that [beam_PostCommit_Go_Dataflow_ARM.yml](https://github.com/apache/beam/blob/master/.github/workflows/beam_PostCommit_Go_Dataflow_ARM.yml) passed. During the Jenkins -> github-actions transition, should make sure the github-actions service account have permission to healthcare.fhirStores.create.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by liferoad** [comment]
@svetakvsundhar FYI.
