### ISSUE TITLE
[Go SDK] lint warning from Golint

### ISSUE THREAD

**Issue by shunping-google** [apache/beam#28235]
The lint warning of `exported method W.Connected should have comment or be unexported` is reported In the following code: https://github.com/apache/beam/blob/c7b13f90874940dd0e897eab472e81f70627e91f/sdks/go/pkg/beam/runners/prism/internal/worker/worker.go#L249

**Comment by jrmccluskey** [comment]
I was going to make a run at this but there's enough going on here that I'll hold off. @lostluck FYI

**Comment by lostluck** [comment]
Thanks!

Yeah, I'm fixing this in my next PR. Consolidated failures will make the flow easier to follow.

Ideally, a failure can only come after a bundle errors out, and then this can resolve retries cleanly at a later stage.

**Comment by lostluck** [comment]
The specific instance has been resolved.
