### ISSUE TITLE
[Bug]: Calls to pipeline.options. in Beam codebase cause unactionable deprecation warning for users.

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#28236]
### What happened?

Deprecation warning was added in : https://github.com/apache/beam/pull/2801.

Quick search for places where this is used: https://github.com/search?q=repo%3Aapache%2Fbeam+%22pipeline.options.%22&type=code

Given that we use the option in Beam code and removing the `Pipeline.options()` would be a breaking change that we won't do anytime soon (after all we didn't do it for 6 years)..., I think it's fine to remove this warning. 

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
Can also remove silences like: https://github.com/apache/beam/blob/c7b13f90874940dd0e897eab472e81f70627e91f/sdks/python/apache_beam/runners/interactive/recording_manager.py 

This should be a simple cleanup.

**Comment by JoeCMoore** [comment]
I second this. The warning is misleading if you aren't up to speed with what it originates from.

**Comment by AtharvaShekatkar** [comment]
.take-issue

**Comment by aku019** [comment]
.take-issue

**Comment by aku019** [comment]
https://github.com/apache/beam/pull/28774

Hi Guys, look into this PR and share your views.

This is my first PR , so guidance will be valued. Thanks!

**Comment by tvalentyn** [comment]
Merged, thanks a lot! Welcome to Apache Beam!
