### ISSUE TITLE
[Feature Request]: Pass joinSubsetType to BeamSqlSeekableTable in JoinAsLookup

### ISSUE THREAD

**Issue by gabrywu** [apache/beam#28283]
### What would you like to happen?

As of now, BeamSqlSeekableTable has 3 methods, setUp, seekRow and tearDown, 
seekRow is the most important method to BeamSqlSeekableTable in JoinAsLookup. 
However BeamSqlSeekableTable doesn't know any details of the join condition before it startup. In many cases, we'd better to know the join keys for a lookup table. 
With join keys, we can build a local cache based on them when startup. So I recommend that we push the join condition to BeamSqlSeekableTable

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by gabrywu** [comment]
@Abacn how about this feature? If you think it is reasonable, I can create a PR

**Comment by Abacn** [comment]
Hi @gabrywu thanks, this sounds good to me. 

I see recently there were other BeamSqlSeekableTable improvements (e.g. #28253). If these are part of larger effort, consider sending a design doc to devlist so more people could see and help it

**Comment by gabrywu** [comment]
> Hi @gabrywu thanks, this sounds good to me.
> 
> I see recently there were other BeamSqlSeekableTable improvements (e.g. #28253). If these are part of larger effort, consider sending a design doc to devlist so more people could see and help it

Sure. I think there is not too much effort
