### ISSUE TITLE
[Bug]: GitHub Action Phrase Issues

### ISSUE THREAD

**Issue by Abacn** [apache/beam#28320]
### What happened?

Create a persistent issue for GitHub Action phrase implementations. Update the current status in comments below

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Current status

- The comment phrase can work and run the workflow, but there are at least following problem

- Another PR comment, regardless what content it is, will cancel the ongoing phrase triggered run for another job
  this essentially let only one phrase triggered workflow can be run at one time. This would be a blocker for retire Jenkins because mass_commit won't work

- If not triggered by commit, phrase triggered job won't update its status to the PR.
  While it does not affect functionality, this introduce inconvenience when developing postcommit / need test with postcommits

**Comment by volatilemolotov** [comment]
Seems like we need to think about the PostCommit nature to solve it correctly. 

Not sure at this point what is the best option but ill take the issue and report what is going on and how to continue.

**Comment by volatilemolotov** [comment]
.take-issue

**Comment by volatilemolotov** [comment]
Ok so the first issue
> Another PR comment, regardless what content it is, will cancel the ongoing phrase triggered run for another job
> this essentially let only one phrase triggered workflow can be run at one time. This would be a blocker for retire 
> Jenkins because mass_commit won't work

Is due to concurrency groups added:
```
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.sha || github.head_ref || github.ref }}-${{ github.event.sender.login }}-${{ github.event.schedule || github.event.comment.created_at}}'
  cancel-in-progress: true

**Comment by Abacn** [comment]
Thanks, github.event.comment.body sounds good. Does "irrelevant comment will cancel the previous one" mean `${{ github.workflow }}` never worked?

**Comment by Abacn** [comment]
how about 

'${{ github.workflow }} @ ${{ github.event.issue.number || github.event.pull_request.head.label || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule || github.event.comment.body }}' ?

this is because the second part ${{ github.event.pull_request.head.label || github.sha || github.head_ref || github.ref }} is observed to be always head sha for pull request; and we do not care about sender - just same PR should have only one run on one workflow

**Comment by volatilemolotov** [comment]
${{ github.event.sender.login }} is needed for dispatch

**Comment by Abacn** [comment]
Then how about `'${{ github.workflow }} @ ${{ github.event.issue.number || github.event.pull_request.head.label || github.sha || github.head_ref || github.ref }}-${{ github.event.schedule || github.event.comment.body || github.event.sender.login}}'` ?

**Comment by volatilemolotov** [comment]
Created a draft: https://github.com/apache/beam/pull/28373
I agree with the approach and some limited testing shows it should be correct
If we agree I will move from draft and lets merge it.
