### ISSUE TITLE
[Task]: Update beam_PostCommit_Java_IO_Performance_Tests.yml to select release branch automatically

### ISSUE THREAD

**Issue by johnjcasey** [apache/beam#28330]
### What needs to happen?

beam_PostCommit_Java_IO_Performance_Tests.yml is hardcoded to the most recent release. This should be updated to query the Github releases endpoint, and automatically select the most recent release.

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
why is this suite testing a release branch as opposed to testing dev SDK? 
Also seems broken as of now:

Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/runner/_work/beam/beam/.github/actions/setup-environment-action'. Did you forget to run actions/checkout before running your local action?

**Comment by johnjcasey** [comment]
This suite is designed to run performance tests, and collect metrics against our released branches. We don't want to add master-branch metrics to our results

**Comment by lostluck** [comment]
The suite appears to be Permared at present.

https://github.com/apache/beam/actions/workflows/beam_PostCommit_Java_IO_Performance_Tests.yml?query=is%3Afailure

In particular the PublishJUnitTestResults step is failing

```
Warning: Could not find any files for **/build/test-results/**/*.xml
```

https://github.com/apache/beam/actions/runs/7802551908/job/21280300993
