### ISSUE TITLE
[Bug]: Docker container RC promotion missed multiarch layer

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#28341]
### What happened?

It appears that 2.50.0 containers are not multiarch, but 2.50.0rc2 containers were multiarch.
See: https://hub.docker.com/r/apache/beam_python3.10_sdk/tags

Work around (if anyone needs ARM images immediately): use apache-beam==2.50.0rc2 or containers associated with RC2. 

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by lostluck** [comment]
Images are re-tagged and multi arch are available. Should be resolved.
