### ISSUE TITLE
[Bug]: pip install apache_beam is very slow

### ISSUE THREAD

**Issue by robertwb** [apache/beam#28364]
### What happened?

This seems to be due to the grcpio package that doesn't often have appropriate wheels (and ends up essentially compiling the whole proto compiler). It seems this package is only needed for development/testing, perhaps it could be made optional (again)? This would cut the install time from ~5 minutes to tens of seconds (or better if packages are already cached). 

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
I don't repro this, in the past this happened in the immediate aftermath of  grpcio release. 

@gnossen - is it possible to adjust grpcio release pipeline to publish wheels and sources in the future (or wheels first)? Otherwise, this penalizes projects that have an open bound on grpcio.

**Comment by tvalentyn** [comment]
i looked at dependency chain, we have a dep on grpcio also through other packages, so would be harder to let go of it completely, i'll reach out to maintainers again.

**Comment by tvalentyn** [comment]
i got this feedback:

> The appropriate place to ask would be [github.com/grpc/grpc](http://github.com/grpc/grpc). As to the question, we do publish wheels at the same time as source distributions. Due to limitations of the PyPi release protocol, releases are not atomic, so there will be a period of around 10 minutes every six weeks where you will be able to observe some set of artifacts published besides the full artifact.

**Comment by tvalentyn** [comment]
@robertwb - to confirm,  was this issue transient?

**Comment by tvalentyn** [comment]
cc: @Polber
