### ISSUE TITLE
[Feature Request]: Decrease the number of GET requests GCSIO makes

### ISSUE THREAD

**Issue by BjornPrime** [apache/beam#28398]
### What would you like to happen?

The new implementation of GCSIO (see PR #28079, if not already merged), contains several uses of GET requests to GCS when it is possible that simply instantiating the objects of interest would provide better performance, since GCS has some capability of figuring things out once a potent request (be it copy, delete, etc.) is made, based on bucket and blob names.

See [here](https://github.com/googleapis/python-storage/issues/1112) for an example of how this can be done.

Using this pattern was attempted during the initial migration to the GCS client, but floundered on concerns that confusing errors may be thrown in some instances. In particular, attempting to access a non-existent object through an operation involving a instantiated version sometimes threw permissions errors instead of 404s. To resolve this issue investigate this design pattern more thoroughly and see if the errors issues are real and can't be overcome. If they can be, swap out any unnecessary GETs for instantiations to improve performance. If they can't, connect with the GCS client team to share these concerns and see if they have any further info or workarounds.

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by BjornPrime** [comment]
.take-issue

**Comment by lgeiger** [comment]
@BjornPrime It would be great if the the amount of GET requests in GCSIO could be reduced.

In particular the code seems to often call `client.get_bucket()` or `client.lookup_bucket()` which will do an unnecessary GET request compared to just using `client.bucket()` or `storage.Blob.from_string()` where possible. Often this doubles the amount of requests needed to e.g. read a blob which is significantly slower.

Furthermore `get_bucket` and `lookup_bucket` require `storage.buckets.get` permissions. These are not part of the "Storage Object Viewer" role but only available in the "Storage Object Admin" role which also grants write permission. This means people running in environments that only allow read access to certain buckets will not be able use the new GCSIO implementation to read blobs. This currently broke one of our pipelines when trying to upgrade from 2.52 to 2.53.

As far as I can tell switching from `get_bucket` to `bucket` is also recommended in the [docs](https://cloud.google.com/storage/docs/downloading-objects#storage-download-object-python), so not sure where the permission error that you mention is coming from.

Out of interest, are there any advantages of using the beams builtin GCSIO over a generic implementation like [fsspec](https://filesystem-spec.readthedocs.io/en/latest/) in pipeline?

**Comment by shunping** [comment]
.take-issue

**Comment by shunping** [comment]
@lgeiger, do you mind taking a look at #30205 and see if it satisfies your request?

**Comment by lgeiger** [comment]
> @lgeiger, do you mind taking a look at #30205 and see if it satisfies your request?

Looks great, thanks for the fast fix!
