### ISSUE TITLE
[Feature Request]: Enable statecache for Python SDK

### ISSUE THREAD

**Issue by AnandInguva** [apache/beam#28770]
### What would you like to happen?

For Python SDK, the statecache is off by default at 0 MB. There are plans to improve the default state cache for Python SDK. As part of the process, enable the state cache to a default of 100 MB. 

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by damccorm** [comment]
@AnandInguva I'm going to remove the milestone since I don't think this is a release blocker. If you disagree, feel free to add it back.
