### ISSUE TITLE
[Failing Test]: GHA performance tests not publishing metrics

### ISSUE THREAD

**Issue by Abacn** [apache/beam#28830]
### What happened?

Example run: https://github.com/apache/beam/actions/runs/6400435522/job/17374057091

```
org.apache.beam.sdk.io.avro.AvroIOIT > writeThenReadAll STANDARD_ERROR
    ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
    Oct 04, 2023 1:43:23 AM org.apache.beam.sdk.testutils.publishing.InfluxDBPublisher publishWithCheck
    WARNING: Unable to publish metrics due to error: Connect to 10.128.0.96:8086 [/10.128.0.96] failed: Connection refused (Connection refused)

```

Same as Python performance tests

```
WARNING:apache_beam.testing.load_tests.load_test_metrics_utils:Failed to publish metrics to InfluxDB: HTTPConnectionPool(host='10.128.0.96', port=8086): Max retries exceeded with url: /write?db=beam_test_metrics&precision=s (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1326d30a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
CC: @volatilemolotov

**Comment by volatilemolotov** [comment]
Working on that. We will put the ARC cluster in the same network as metrics to enable communication.

**Comment by volatilemolotov** [comment]
.take-issue

**Comment by Abacn** [comment]
Now we have switched the network for containers, the warning message changed:

```
org.apache.beam.sdk.bigqueryioperftests.BigQueryIOIT > testWriteThenRead STANDARD_ERROR
    Oct 17, 2023 2:05:22 PM org.apache.beam.sdk.testutils.publishing.InfluxDBPublisher publishWithCheck
    WARNING: Unable to publish metrics due to error: Response code: 401. Reason: "unable to parse authentication credentials"
```

it indicates the GHA worker now able to ping the influxdb server, but missing credential

**Comment by volatilemolotov** [comment]
Probably credentials are not in the env. Will prepare a PR tommorow

**Comment by Abacn** [comment]
https://github.com/apache/beam/pull/29006 added these env. Let's see if https://github.com/apache/beam/actions/workflows/beam_Inference_Python_Benchmarks_Dataflow.yml?query=event%3Aschedule starts to publish metrics.

**Comment by Abacn** [comment]
confirm that now performance tests and load teats are publishing metrics to influxdb. We can start teardown the Jenkins tests
