### ISSUE TITLE
[Feature Request]: Use BigQuery emulator

### ISSUE THREAD

**Issue by thomas-flynn-ingka** [apache/beam#28841]
### What would you like to happen?

I want to have a purely local development environment.
There is a BigQuery emulator (https://github.com/goccy/bigquery-emulator) with a docker image freely available (ghcr.io/goccy/bigquery-emulator:latest).
How do I change the googleapis endpoint that beam points at?
Is there an environment variable to do this?

This will be used in a continuous integration environment rather than connecting to a google environment.

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by kennknowles** [comment]
Merging with #28149 28149
