### ISSUE TITLE
[Bug]:  Python PostCommits are failing for 3.8, 3.9, 3.10, 3.11

### ISSUE THREAD

**Issue by riteshghorse** [apache/beam#28870]
### What happened?

PostCommits for Python have been failing for last 3 days:

Python3.8 - https://ci-beam.apache.org/job/beam_PostCommit_Python38/4676/
Python3.9 - https://ci-beam.apache.org/job/beam_PostCommit_Python39/2397/
Python3.10 - https://ci-beam.apache.org/job/beam_PostCommit_Python310/1409/
Python3.11 - https://ci-beam.apache.org/job/beam_PostCommit_Python311/748/

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by riteshghorse** [comment]
CC: @tvalentyn @AnandInguva

**Comment by riteshghorse** [comment]
Failing Bigquery tests:
![image](https://github.com/apache/beam/assets/25881114/c836b33e-fdd5-433e-9619-80bc262ba94b)


CC: @ahmedabu98

**Comment by tvalentyn** [comment]
we can track in https://github.com/apache/beam/issues/28811
