### ISSUE TITLE
[Bug]: Nightly snapshot release is failing due to Gradle 8 upgrade

### ISSUE THREAD

**Issue by ahmedabu98** [apache/beam#28898]
### What happened?

Around the same time that Gradle 8 got upgraded (#28756), the nightly snapshot has been failing on both Jenkins and GHA. For both, I'm seeing errors with many Gradle task configurations that go like:

```
Some problems were found with the configuration of task ':sdks:java:core:testSourcesJar' (type 'Jar').
- Gradle detected a problem with the following location: '/home/jenkins/jenkins-agent/26ff11f4/workspace/beam_Release_NightlySnapshot/src/sdks/java/core/build/generated-test-avro-java'.
 
Reason: Task ':sdks:java:core:testSourcesJar' uses this output of task ':sdks:java:core:generateTestAvroJava' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

Possible solutions:
  1. Declare task ':sdks:java:core:generateTestAvroJava' as an input of ':sdks:java:core:testSourcesJar'.
  2. Declare an explicit dependency on ':sdks:java:core:generateTestAvroJava' from ':sdks:java:core:testSourcesJar' using Task#dependsOn.
  3. Declare an explicit dependency on ':sdks:java:core:generateTestAvroJava' from ':sdks:java:core:testSourcesJar' using Task#mustRunAfter.

For more information, please refer to https://docs.gradle.org/8.3/userguide/validation_problems.html#implicit_dependency in the Gradle documentation.
```
Example: https://ci-beam.apache.org/job/beam_Release_NightlySnapshot/2041/console

Looks like Gradle 8 is more strict on declaring dependencies.

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by ahmedabu98** [comment]
Some relevant links: 
Default source configuration: https://github.com/apache/beam/blob/d17063412ea4a3417b5a4e3f2d14fa1640c8caed/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L1787-L1797
Flink module has copy and merge source overrides: https://github.com/apache/beam/blob/d17063412ea4a3417b5a4e3f2d14fa1640c8caed/runners/flink/flink_runner.gradle#L46-L78

**Comment by Abacn** [comment]
Thanks for triaging. This additional check in Gradle 8 has broken several test (e.g. #28845) - they are existing problem in our build but begins to be enforced in Gradle 8. 

From the migration guide, I ran `gradle help --scan ` to detect possible breakages for migrating to gradle 8; it detected many, but not this specific issue, causing many cases get missed in #28756

**Comment by Abacn** [comment]
Also note - flink runner errors in https://ci-beam.apache.org/job/beam_Release_NightlySnapshot/2041/console are likely the cause of the timing issue of #28419
