### ISSUE TITLE
[Bug]: Where does KafkaTableSource recover from?

### ISSUE THREAD

**Issue by gabry-lab** [apache/beam#28958]
### What happened?

One of our jobs running on flink runner. It throws OOM, and related operators recover from its checkpoint folders.
But I find that kafka reader source is recovering from latest offset, even-though printing logs 
`Restoring state in the UnboundedSourceWrapper.
Unbounded Flink Source 1/3 is reading from sources: [org.apache.beam.sdk.io.kafka.KafkaUnboundedSource@1e14b4e0]`

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by gabrywu** [comment]
close this issue, since it's duplicated by #28985
