### ISSUE TITLE
[Bug]: UnboundedSourceWrapper.splitSources is assigned too early.

### ISSUE THREAD

**Issue by gabrywu** [apache/beam#29048]
### What happened?

UnboundedSourceWrapper assign a value to splitSources when it's creating, but what will happen if our kafka consumer need kerberos auth and the submiting host doesn't have that auth info?

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by johnjcasey** [comment]
This is a known drawback in the Unbounded source implementation. If you need this dynamically, you can use the SDF implementation, and avoid splitting at submit time
