### ISSUE TITLE
[Bug]: Fix typos in HistogramData.java and HistogramDataTest.java

### ISSUE THREAD

**Issue by shunping-google** [apache/beam#29085]
### What happened?

The recent commit of HistogramData (https://github.com/apache/beam/commit/9aaf9c213e) has introduced a few typos to the code.

(1) wiht -> with https://github.com/apache/beam/blob/7632d48c3bdcf2309e8e4d43bb282e6ba38072c8/sdks/java/core/src/main/java/org/apache/beam/sdk/util/HistogramData.java#L82

(2) effecient -> efficient https://github.com/apache/beam/blob/7632d48c3bdcf2309e8e4d43bb282e6ba38072c8/sdks/java/core/src/main/java/org/apache/beam/sdk/util/HistogramData.java#L384

(3) Postive -> Positive
https://github.com/apache/beam/blob/7632d48c3bdcf2309e8e4d43bb282e6ba38072c8/sdks/java/core/src/test/java/org/apache/beam/sdk/util/HistogramDataTest.java#L208

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by viveksumanth** [comment]
“.take-issue”
