### ISSUE TITLE
[Bug]: ClickhouseIOWriter doesn't support Boolean

### ISSUE THREAD

**Issue by rthneha** [apache/beam#29087]
### What happened?

Apache Beam supports Boolean Datatype read.
https://beam.apache.org/releases/javadoc/current/org/apache/beam/sdk/schemas/Schema.FieldType.html

But ClickhouseIOWriter class doesn't support it.
https://github.com/apache/beam/blob/master/sdks/java/io/clickhouse/src/main/java/org/apache/beam/sdk/io/clickhouse/ClickHouseWriter.java

We can add Boolean support for it by doing below changes maybe:

      case BOOL:
        BinaryStreamUtils.writeUInt8(stream, (Boolean) value);
        break;  

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by mzitnik** [comment]
@rthneha Hi, I'm from ClickHouse i can handle the addition of bool type. Do we know any other types that we want to add as well.

**Comment by priteshgudge** [comment]
Hi, I'm from ClickHouse i can handle the addition of bool type. Do we know any other types that we want to add as well.

@mzitnik Can we add support for Decimal32, Decimal64 and DateTime64 as well?

**Comment by priteshgudge** [comment]
> Hi, I'm from ClickHouse i can handle the addition of bool type. Do we know any other types that we want to add as well.

@mzitnik Can we add support for Decimal32, Decimal64 and DateTime64 as well?

Should I add a new Issue to track this?
