### ISSUE TITLE
[Bug]: The Python MatchFiles ignore "empty_match_treatment" parameter 

### ISSUE THREAD

**Issue by admovdz** [apache/beam#29195]
### What happened?

The class `MatchFiles` not pass "empty_match_treatment" parameter in `MatchAll()`, so the parameter is ignore

https://github.com/apache/beam/blob/c2816c8d9770df3d30eec15a2563c48cb66a66b3/sdks/python/apache_beam/io/fileio.py#L198

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by AnandInguva** [comment]
that is right. I am happy to review a PR if you can fix the bug.
