### ISSUE TITLE
[YAML][Bug]: BigQueryStorageWriteApiSchemaTransformProvider throws a null pointer 

### ISSUE THREAD

**Issue by ffernandez92** [apache/beam#29414]
### What happened?

When I tried to write into BigQuery using Beam YAML, I ran into the following NULL pointer exception issue:

[BigQueryStorageWriteApiSchemaTransformProvider.class]
```
Integer numStreams = configuration.getNumStreams();
        // Triggering frequency is only applicable for exactly-once
        if (!configuration.getUseAtLeastOnceSemantics()) {
          write =
              write.withTriggeringFrequency(
                  (triggeringFrequency == null || triggeringFrequency <= 0)
                      ? DEFAULT_TRIGGERING_FREQUENCY
                      : Duration.standardSeconds(triggeringFrequency));
        }
        // set num streams if specified, otherwise default to autoSharding
        if (numStreams > 0) {
          write = write.withNumStorageWriteApiStreams(numStreams);
        } else if (autoSharding == null || autoSharding) {
          write = write.withAutoSharding();
        }
```

`getUseAtLeastOnceSemantics` and `numStreams` are nullable. Since they don't have a default value, it throws a null pointer exception when using Beam YAML  

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [X] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [X] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
@ffernandez92 Thanks for reporting!
cc: @Polber could you help triage this ?
