### ISSUE TITLE
[Bug]: Python sources missing in the PyPI  2.52.0 release 

### ISSUE THREAD

**Issue by ajayk** [apache/beam#29489]
### What happened?

Python sources are not available for the latest 2.52.0 release 
<img width="1328" alt="Screenshot 2023-11-18 at 8 12 18 PM" src="https://github.com/apache/beam/assets/1015125/5d98fc4c-bc53-43ef-a77a-5e2baeb708f0">

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by damccorm** [comment]
Looks like this is because we changed from a zip file to a tar.gz file extension and that got missed in our automation. I'll see if I can fix it for this release, if not I should be able to at least for releases going forward.

**Comment by damccorm** [comment]
This has been fixed - https://pypi.org/project/apache-beam/2.52.0/#files - I'll leave this issue open until the automation is fully fixed to avoid the problem in the future though. Thanks for reporting this!
