### ISSUE TITLE
[Bug]: org.apache.beam.sdk.io.gcp.bigquery.AvroGenericRecordToStorageApiProto.toProtoValue fails to handle MAP type schema

### ISSUE THREAD

**Issue by DANIELK121** [apache/beam#29516]
### What happened?

Beam Version - 2.52.0
Language - Java

This is the problematic function:
![Screenshot 2023-11-22 at 12 09 26](https://github.com/apache/beam/assets/31109964/6db094ea-589e-415e-aadc-d7563dc28869)

In line 278 is the case handling a MAP Avro schema type. In line 280 it is trying to compute the value type of the Map but accessing the `Schema::getElementType` method, which is implemented only by the `org.Apache.Avro.ArraySchema` (and not by the `org.Apache.Avro.MapSchema`). This is causing the case to throw an `AvroRuntimeException` with a message "Not an array: ...", and NEVER succeed the handling.

I believe that in line 280, instead of calling `Schema::getElementType`, it should call `Schema::getValueType` which is implemented by the `org.Apache.Avro.MapSchema` class.

P.S - It seems that same bug exists in the org.apache.beam.sdk.io.gcp.bigquery.AvroGenericRecordToStorageApiProto.fieldDescriptorFromAvroField function when handling a MAP type schema.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by codertimu** [comment]
I didn't see this and opened the similar bug issue #31652.  
PR #31653 fixes this issue.

**Comment by Amar3tto** [comment]
.take-issue
