### ISSUE TITLE
[Bug]: Dataflow not reading from PubSub once I add external API call to a transform within RunnerV2 in streaming mode

### ISSUE THREAD

**Issue by matthiasa4** [apache/beam#29527]
### What happened?

I have a very simple Beam Python pipeline, reading from PubSub, doing a transform and writing to BigQuery. The transform includes a call to the Translate API which is causing trouble:

```
class TranslateMessage(beam.DoFn):
    def __init__(self, project_id):
        self.project_id = project_id

    def setup(self):
        self.translate_client = translate.TranslationServiceClient()

    def process(self, element):
        # location = "global"
        # parent = f"projects/{self.project_id}/locations/{location}"

        # language_detected = self.translate_client.detect_language(
            content=element.text,
            parent=parent).languages[0]
        # logging.info("Translating message: " + element.text)

        yield Log(element.timestamp,
                  element.text,
                  element.user_id,
                  'en',
                  1
                  )
```
works, but
```
class TranslateMessage(beam.DoFn):
    def __init__(self, project_id):
        self.project_id = project_id

    def setup(self):
        self.translate_client = translate.TranslationServiceClient()

    def process(self, element):
        location = "global"
        parent = f"projects/{self.project_id}/locations/{location}"
        language_detected = self.translate_client.detect_language(
            content=element.text,
            parent=parent).languages[0]
        logging.info("Translating message: " + element.text)

        yield Log(element.timestamp,
                  element.text,
                  element.user_id,
                  language_detected.language_code,
                  language_detected.confidence
                  )
```
causes the whole pipeline to grind to a halt. It starts up, but PubSub messages are never consumed, none of the stages adds any elements to the input or output collections. No logs are created, no error messages are thrown.

Dependencies:
```
apache-beam[gcp]==2.52.0
google-cloud-translate==2.0.1
```

I have been able to fix the issue for now by using `apache-beam[gcp]==2.44.0` and `--experiments=disable_runner_v2_until_2023` but would be interested in what the underlying issue is and how I can upgrade to Runner V2.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

**Comment by liferoad** [comment]
1. Can you add logs when entering `setup` and `process`?
2. Do you need to close `self.translate_client`? 
3. You might need `retry.with_exponential_backoff` if the API calls are throttling. 
4. If you continue having the issue with Runner V2, please open a GCP support ticket.

**Comment by matthiasa4** [comment]
Thanks @liferoad, answers below.

> 1. Can you add logs when entering `setup` and `process`?
I will try this and report back.
> 2. Do you need to close `self.translate_client`?
Not that I am aware.
> 3. You might need `retry.with_exponential_backoff` if the API calls are throttling.
There are no API calls on the Translate API side when I check the metrics.
> 4. If you continue having the issue with Runner V2, please open a GCP support ticket.
I have done this.

**Comment by liferoad** [comment]
I got this when trying to install both:

ERROR: Cannot install apache-beam[gcp]==2.52.0 and google-cloud-translate==2.0.1 because these package versions have conflicting dependencies.

**Comment by liferoad** [comment]
I did my own test with this code:
```
import argparse
import logging

import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions
from apache_beam.options.pipeline_options import SetupOptions
from apache_beam.options.pipeline_options import GoogleCloudOptions
from apache_beam.options.pipeline_options import StandardOptions
from apache_beam.io import ReadFromPubSub
from google.cloud import translate_v3 as translate

class TranslateMessage(beam.DoFn):
    def __init__(self, project_id):
        self.project_id = project_id

    def setup(self):
        self.translate_client = translate.TranslationServiceClient()

    def process(self, element):
        text = element.decode(encoding="utf-8")
        location = "global"
        parent = f"projects/{self.project_id}/locations/{location}"
        language_detected = self.translate_client.detect_language(
            content=text, parent=parent
        ).languages[0]
        logging.info("Translating message: " + text + " lang: " + language_detected.language_code)

        yield (text, language_detected)

def main(argv=None, save_main_session=True):
  """Main entry point; defines and runs the wordcount pipeline."""

  parser = argparse.ArgumentParser()
  known_args, pipeline_args = parser.parse_known_args(argv)

  options = PipelineOptions(pipeline_args)
  options.view_as(SetupOptions).save_main_session = True
  options.view_as(StandardOptions).streaming = True
  project = options.view_as(GoogleCloudOptions).project
  topic = "projects/pubsub-public-data/topics/shakespeare-kinglear"

  p = beam.Pipeline(options=options)
  _ = (
      p
      | "Read PubSub topic" >> ReadFromPubSub(topic=topic)
      | beam.ParDo(TranslateMessage(project))
  )
  p.run()

if __name__ == '__main__':
  logging.getLogger().setLevel(logging.INFO)
  main()
```
I do not see any problem:

<img width="628" alt="image" src="https://github.com/apache/beam/assets/7833268/8c2f2763-4f80-4f1e-9df1-7a8073d16030">

The code needs to be polished to handle throttling but it seems working well with Runner V2 and google-cloud-translate-3.12.1

**Comment by matthiasa4** [comment]
> I got this when trying to install both:
> 
> ERROR: Cannot install apache-beam[gcp]==2.52.0 and google-cloud-translate==2.0.1 because these package versions have conflicting dependencies.

Fair - I think I was using `3.12.1` for both actually. 

I can confirm your code works for me as well. Thanks for the repro. I tested it on my subscription as well which works too. I am adding the other components back 1 by 1 to see if everything keeps working. 

I was using the `--setup_file` for dependencies, but now used `--requirements_file`. I am starting to think something might have gone wrong there. But still unsure why I was seeing the behaviour of a pipeline starting up successfully but not consuming any messages.

**Comment by liferoad** [comment]
When you have many package dependencies, you should switch to custom container: https://cloud.google.com/dataflow/docs/guides/using-custom-containers. I also created a sample project you could check: https://github.com/google/dataflow-ml-starter.

**Comment by liferoad** [comment]
I am going to close this for now. Feel free to reopen if it is indeed a bug in Beam.
