### ISSUE TITLE
[Bug]: CoGroupByKey Tour of Beam Python example shows Go code

### ISSUE THREAD

**Issue by lazarillo** [apache/beam#29535]
### What happened?

I am going through the "Tour of Beam", and the CoGroupByKey Python example shows Go code instead of Python.  It can be seen in the playground starting a bit below here:

https://github.com/apache/beam/blob/3e0d0d62a5b1a9063f9e07a62556ba8a7299afbe/learning/tour-of-beam/learning-content/core-transforms/map/co-group-by-key/description.md#playground-exercise

I am happy to make a PR and fix it, but being new to Beam, I wasn't sure if that would help.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [X] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [X] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
> I am happy to make a PR and fix it, but being new to Beam, I wasn't sure if that would help.

That would absolutely help and you are most welcome to send a PR. Thanks a lot!
