### ISSUE TITLE
[Failing Test]: Python PostCommits are failing due to a possible dependency update

### ISSUE THREAD

**Issue by riteshghorse** [apache/beam#29684]
### What happened?

`apache_beam/io/external/xlang_jdbcio_it_test.py::CrossLanguageJdbcIOTest::test_xlang_jdbc_write_read` is faling for last 3 runs for all Python postcommits ([3.9](https://ci-beam.apache.org/job/beam_PostCommit_Python39/2625/consoleText), [3.11](https://ci-beam.apache.org/job/beam_PostCommit_Python311/975/)).

This test hasn't been modified for a long time so likely a dependency update?

Full stack trace:
```
FAILED apache_beam/io/external/xlang_jdbcio_it_test.py::CrossLanguageJdbcIOTest::test_xlang_jdbc_write_read_0_postgres - RuntimeError: Pipeline BeamApp-jenkins-1208002334-8b3649cd_9ce5b455-0bb4-4895-a9e9-7ffe529a5ea8 failed in state FAILED: java.lang.RuntimeException: Error received from SDK harness for instruction 25: Traceback (most recent call last):
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python39/src/sdks/python/apache_beam/runners/worker/bundle_processor.py", line 231, in process_encoded
    decoded_value = self.windowed_coder_impl.decode_from_stream(
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python39/src/sdks/python/apache_beam/coders/coder_impl.py", line 1488, in decode_from_stream
    value = self._value_coder.decode_from_stream(in_stream, nested)
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python39/src/sdks/python/apache_beam/coders/coder_impl.py", line 1837, in decode_from_stream
    item = component_coder.decode_from_stream(in_stream, True)
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python39/src/sdks/python/apache_beam/coders/coder_impl.py", line 1890, in decode_from_stream
    return self.logical_type.to_language_type(
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python39/src/sdks/python/apache_beam/typehints/schemas.py", line 1000, in to_language_type
    return DecimalLogicalType().to_language_type(value)
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python39/src/sdks/python/apache_beam/typehints/schemas.py", line 962, in to_language_type
    return decimal.Decimal(value.decode())
AttributeError: 'decimal.Decimal' object has no attribute 'decode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python39/src/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 297, in _execute
    response = task()
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python39/src/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 372, in <lambda>
    lambda: self.create_worker().do_instruction(request), request)
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python39/src/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 625, in do_instruction
    return getattr(self, request_type)(
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python39/src/sdks/python/apache_beam/runners/worker/sdk_worker.py", line 663, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python39/src/sdks/python/apache_beam/runners/worker/bundle_processor.py", line 1056, in process_bundle
    input_op_by_transform_id[element.transform_id].process_encoded(
  File "/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Python39/src/sdks/python/apache_beam/runners/worker/bundle_processor.py", line 234, in process_encoded
    raise ValueError(
ValueError: Error decoding input stream with coder WindowedValueCoder[RowCoder]
```

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [x] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by riteshghorse** [comment]
SQLAlchemy upgrade is not the reason. It fails with 1.4.49 as well when tried locally

**Comment by riteshghorse** [comment]
CC: @yathu @ahmedabu98

**Comment by riteshghorse** [comment]
Last successful run was [2624](https://ci-beam.apache.org/job/beam_PostCommit_Python39/2624/)

**Comment by riteshghorse** [comment]
I think this may have caused because of #29639

I tried a sample run with https://github.com/apache/beam/pull/29718 to not decode if the value is already `decimal.Decimal` but that seems to create other issues.

**Comment by robertwb** [comment]
Is there a command to reproduce this locally? 

I'm not seeing how #29639 is related, but the implementation of `FixedPrecisionDecimalLogicalType` does look wrong as it claims the `representation_type` is `DecimalLogicalType` but `to_representation_type` and `to_language_type` convert to and from `bytes`.

**Comment by Abacn** [comment]
> Is there a command to reproduce this locally?
> 
> I'm not seeing how #29639 is related, but the implementation of `FixedPrecisionDecimalLogicalType` does look wrong as it claims the `representation_type` is `DecimalLogicalType` but `to_representation_type` and `to_language_type` convert to and from `bytes`.

`DecimalLogicalType` and `FixedPrecisionDecimalLogicalType` correspond to `DECIMAL` premitive type  and decimal logical type in Java SDK. The portability framework excluded `DATETIME` and `DECIMAL` from primitive but they remain in Java SDK caused problems as the encoded form of them cannot be decoded using portable primitive types (representation_type) and need to special treatments.

I added this as a release blocker as it breaks xlang jdbcio

**Comment by riteshghorse** [comment]
> Is there a command to reproduce this locally?
> 

> I'm not seeing how #29639 is related, but the implementation of `FixedPrecisionDecimalLogicalType` does look wrong as it claims the `representation_type` is `DecimalLogicalType` but `to_representation_type` and `to_language_type` convert to and from `bytes`.

I don't have a strong reason to point to this PR but the PostCommit run started to fail after a couple of commits which had this commit.  

I tried a revert for this commit at https://github.com/apache/beam/pull/29746, and the tests seems to be passing .

Need to resolve the conflicts but we could do a revert to unblock the release?

**Comment by Abacn** [comment]
Did some local test and confirm that reverting #29639 the test is green. It affects source, so it affects JdbcIO read. It seems not affect sink (e.g. JdbcIO write and BigQueryIO storage write which also uses `DecimalLogicalType`). It may affect other read transform involves DecimalLogicalType or MillisInstant.

**Comment by robertwb** [comment]
Presumably most of https://github.com/apache/beam/pull/29639 is irrelevant? What about just reverting the line

   `user_type._beam_schema_proto = _Ephemeral(schema)`

from external.py? (This was added so that the round trip of Beam Schema <-> Proto is not lossy, so it should be *more* correct, but seems to have uncovered something?)

**Comment by riteshghorse** [comment]
Yeah, looks like reverting the line `user_type._beam_schema_proto = _Ephemeral(schema)` will do it

test pr -  https://github.com/apache/beam/pull/29754
passing run - https://ci-beam.apache.org/job/beam_PostCommit_Python311_PR/144/consoleText

![image](https://github.com/apache/beam/assets/25881114/df5e798f-d972-4077-b089-5b4151f19d51)

**Comment by robertwb** [comment]
OK, so somehow these tests are depending on a lossy conversion back to protos :(. 

We can revert that for now (it was used for generating correct documentation) to unblock the release and file a bug to try to get this fixed the right way.

**Comment by riteshghorse** [comment]
Great, thanks! Filed https://github.com/apache/beam/issues/29756
