### ISSUE TITLE
[Feature Request]: Optimize [multi]map side inputs.

### ISSUE THREAD

**Issue by robertwb** [apache/beam#29691]
### What would you like to happen?

Currently the only way to read a map is key-by-key lookup. While this works great for too-large-to-fit-into-memory maps, for smaller maps (which are commonly used) this is very inefficient. 

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by jrmccluskey** [comment]
@robertwb is work completed on this task?

**Comment by robertwb** [comment]
The attached PRs should resolve the issue for the SDK and local runners.
