### ISSUE TITLE
[Failing Test]: beam_PostCommit_Java_ValidatesRunner_ULR is perma-red

### ISSUE THREAD

**Issue by jrmccluskey** [apache/beam#29818]
### What happened?

Full run log: https://github.com/apache/beam/actions/runs/7200942301/job/19616004260?pr=29758

Gradle scan: https://ge.apache.org/s/im2h7gr64kuji

The specific failing tests are listed below:
```
org.apache.beam.sdk.transforms.ViewTest > testEmptyMultimapSideInput FAILED
    java.lang.RuntimeException at ViewTest.java:950

org.apache.beam.sdk.transforms.ViewTest > testEmptyMultimapSideInputWithNonDeterministicKeyCoder FAILED
    java.lang.RuntimeException at ViewTest.java:984

org.apache.beam.sdk.transforms.ViewTest > testEmptyMapSideInput FAILED
    java.lang.RuntimeException at ViewTest.java:1297

org.apache.beam.sdk.transforms.ViewTest > testEmptyMapSideInputWithNonDeterministicKeyCoder FAILED
    java.lang.RuntimeException at ViewTest.java:1331
```

These may be related to the recent multi-map side input changes in #29691. 

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by jrmccluskey** [comment]
@robertwb

**Comment by kennknowles** [comment]
I'm thinking this is what you need:

```
Caused by: java.lang.IllegalStateException: Unknown state type: multimap_keys_side_input
    at org.apache.beam.fn.harness.state.BeamFnStateGrpcClientCache$GrpcStateClient$InboundObserver.onNext(BeamFnStateGrpcClientCache.java:191)
```

Agree that this should block release until/unless we are sure it isn't a bug and we decide the ULR is OK not supporting this.

**Comment by robertwb** [comment]
See comments and "fix" at https://github.com/apache/beam/pull/29836

**Comment by damccorm** [comment]
This has been fixed
