### ISSUE TITLE
[Bug]: Usage of logical types breaks Beam YAML Sql

### ISSUE THREAD

**Issue by robertwb** [apache/beam#29825]
### What happened?

Though schema transforms are generally preferred, this doesn't work for SqlTransform as its config schema uses java-only logical types. 

This is a specific case of https://github.com/apache/beam/issues/29824

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [X] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by robertwb** [comment]
Re-opening until change is cherry-picked into the release.

**Comment by lostluck** [comment]
There's one week until the 2.54.0 cut and this issue is tagged for that release, if possible/necessary please complete the necessary work before then, or move this to the [2.55.0 Release Milestone](https://github.com/apache/beam/milestone/19).

**Comment by Abacn** [comment]
This one sounds already done in 2.53.0 release. 2.54.0 milestone is an effect of close and then re-open this after 2.53.0 cut
