### ISSUE TITLE
[Bug]: Race Condition detected in SpannerTransactionWriterDoFn

### ISSUE THREAD

**Issue by VardhanThigle** [apache/beam#29832]
### What happened?

# Race Condition detected in `SpannerTransactionWriterDoFn` between the setup and teardown phases leading to missing records during spanner migration.

## Root cause :
The root cause is `spanner` object being closed immediately after create due to a race condition in [SpannerAccessor](third_party/java_src/apache_beam4g/srcs/sdks/io/google_cloud_platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerAccessor.java) class.

### Race Condition:
1. `SpannerAccessor.getOrCreate` get's called during the `@setup` of the [SpannerTransactionWriterDoFn](https://source.corp.google.com/piper///depot/google3/third_party/java_src/cloud/teleport/v2/datastream-to-spanner/src/main/java/com/google/cloud/teleport/v2/templates/SpannerTransactionWriterDoFn.java;l=176?q=spanner%20close&ss=piper%2FGoogle%2FPiper:google3%2Fthird_party%2Fjava_src%2Fcloud%2Fteleport%2Fv2%2F) and `SpannerAccessor.close` get's called during it's `@teardown`
2. These functions use a combination of synchronous access and atomic Reference counts to share the spanner connections for a given spanner config. This leads to a case where in rare timing conditions, a spannerAccessor can be returend when it's getting closed concurrently in another threead.
3. 
4. When `SpannerAccessor.getOrCreate` provisions a new connection:

    3.1. Queries the Accessor from a concurrent hashmap

    3.2. If not found, it takes the lock, provisions the connection.

    3.3. sets the refcount to 0.

    3.4. releases the lock.
 
    3.5. increments the refcount outside the lock.

5. When `SpannerAccessor.close` destroys a connection:

     4.1.  atomically decrements the refcount.

     4.2 if the refcount is 0.
 
     4.3. it, takes the lock.

     4.4 Rechecks the refcount.

     4.5. destroys a connection iff the refcount during the second check is <= 0.

6. If the Sequence of execution is 3.1, 4.1, 4.2, 4.3, 4.4, 4.5, 3.5, we lead to the race condition.

## A few options that could fix this
1. Let `spanner.close()` currently being called by the close routine be deferred to `finalize()`. This will let the obtained object remain valid till it gets picked up for GC. 

2. Guard the entire logic in `getOrCreate` and `close` under readWrite locks. 

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [x] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by nielm** [comment]
.take-issue
.add-label spanner,gcp

**Comment by nielm** [comment]
.add-labels spanner,gcp
