### ISSUE TITLE
[Task]: Document how to investigate OOMs

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#29862]
### What needs to happen?

Add a playbook that will describe how to investigate memory leaks in Beam.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
Added a page: https://cwiki.apache.org/confluence/display/BEAM/Investigating+Memory+Leaks

**Comment by reddaly** [comment]
OOMs are not always a result of memory leaks. Sometimes workers must perform memory-intensive computation. How are users expected to implement such workloads?
