### ISSUE TITLE
[Bug]: Fix lints in timers.go

### ISSUE THREAD

**Issue by shunping** [apache/beam#29895]
### What happened?

1. In `func TimersEventTime_Bounded()`, the function name should not contain "_". https://github.com/apache/beam/blob/783c72a6dcebee2e60fb065f6890be6f8de4d48d/sdks/go/test/integration/primitives/timers.go#L142. 
   Please make sure to change the comment at https://github.com/apache/beam/blob/783c72a6dcebee2e60fb065f6890be6f8de4d48d/sdks/go/test/integration/primitives/timers.go#L141
2. In `func TimersEventTime_Unbounded()`, the function name should not contain "_". https://github.com/apache/beam/blob/783c72a6dcebee2e60fb065f6890be6f8de4d48d/sdks/go/test/integration/primitives/timers.go#L147.
  Please make sure to change the comment at
https://github.com/apache/beam/blob/783c72a6dcebee2e60fb065f6890be6f8de4d48d/sdks/go/test/integration/primitives/timers.go#L146. Notice that the original comment is incorrectly referencing the "Bounded" function.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by lostluck** [comment]
Google's slightly more stringent lint policy strikes again. This is under active work, so I'll fix it in my next PR.
