### ISSUE TITLE
[Failing Test]: testReshufflePreservesMetadata not working for some runners

### ISSUE THREAD

**Issue by Abacn** [apache/beam#29973]
### What happened?

Added in #28853,  the newly added test `testReshufflePreservesMetadata` not working for all runners:

beam_PostCommit_Java_PVR_Samza:  https://github.com/apache/beam/actions/runs/7399747764/job/20131866953

beam_PostCommit_Java_PVR_Spark3_Streaming: https://github.com/apache/beam/actions/runs/7399737943/job/20131836389

beam_PostCommit_Java_PVR_Spark3_Batch: https://github.com/apache/beam/runs/20340841429

beam_PostCommit_Java_ValidatesRunner_ULR also

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by kennknowles** [comment]
I will take this. They should be disabled for now, as the runners simply don't support it. Sorry! I missed these.

**Comment by lostluck** [comment]
There's one week until the 2.54.0 cut and this issue is tagged for that release, if possible/necessary please complete the necessary work before then, or move this to the [2.55.0 Release Milestone](https://github.com/apache/beam/milestone/19).
