### ISSUE TITLE
[Bug]: Python SchemaRegistry is not properly populated when calling `add`

### ISSUE THREAD

**Issue by mlhamel** [apache/beam#29975]
### What happened?

In that https://github.com/apache/beam/pull/28169

The following change was introduced:

```
  def add(self, typing, schema):
    if not schema.id:
      self.by_id[schema.id] = (typing, schema)
```

I know the `SCHEMA_REGISTRY` is an internal service but we were using it in our tests and stopped working with the release of beam 2.51.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by damccorm** [comment]
Hey @mlhamel as mentioned in https://github.com/apache/beam/blob/0a813b996572191bc179c724d3f31d535eb45e7d/sdks/python/apache_beam/typehints/schema_registry.py#L18 that code is intended for internal use only and does not have backwards compatibility guarantees. In general, you should not explicitly depend on its behavior unless you're ok taking on the risk of it changing
