### ISSUE TITLE
[Bug]: WriteToFiles(output_fn=...) is seemingly unused

### ISSUE THREAD

**Issue by dlwh** [apache/beam#30009]
### What happened?

There's a ctor argument output_fn to WriteToFiles that isn't used other than setting a member variable that is never read:

https://github.com/apache/beam/blob/0d58d23f2d9c34ae5f068acddc622fa3ac6b0854/sdks/python/apache_beam/io/fileio.py#L542

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
agreed, appears to be never used. We could clean it up and force keyword-only arguments after it. It could be a breaking change for some users, so could also not touch it and add a note that it's unused and leftover for backward compatibiltiy.

**Comment by ima-attac-helikoptaaa** [comment]
.take-issue

**Comment by riteshghorse** [comment]
@ima-attac-helikoptaaa are you still working on it?

**Comment by tsafacjo** [comment]
> agreed, appears to be never used. We could clean it up and force keyword-only arguments after it. It could be a breaking change for some users, so could also not touch it and add a note that it's unused and leftover for backward compatibiltiy.

To sum up we shouldn't change it ?

**Comment by tvalentyn** [comment]
we can still make the clarification in the code that it is unused. Removing is fine too as long as we force keyword-only args.

**Comment by hayk2377** [comment]
> agreed, appears to be never used. We could clean it up and force keyword-only arguments after it. It could be a breaking change for some users, so could also not touch it and add a note that it's unused and leftover for backward compatibiltiy.

should we add a note on the docstring so that it is visible for the caller

**Comment by mohamedawnallah** [comment]
.take-issue
