### ISSUE TITLE
[Doc Bug]: `fileio.ReadAll()` on integration test

### ISSUE THREAD

**Issue by svetakvsundhar** [apache/beam#30004]
### What happened?

I am working to create more granular integration tests for `dicomio.py` and came across the example listed here: https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/gcp/healthcare/dicomio.py#L96

This is outdated as fileio doesnt have the ReadAll() method. What would be the recommended and updated version of this example, given the recent GCS IO migration? 

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by svetakvsundhar** [comment]
cc: @shunping , @Abacn

**Comment by Abacn** [comment]
GcsIO migration should not change any beam API and user faced transform. `fileio.ReadAll()` seems never existed. Checked that at the commit of this comment first introduced: https://github.com/apache/beam/blob/b87bb64a44c40114779b05ab742b91cbc20e2754/sdks/python/apache_beam/io/fileio.py I did not see fileio.readAll

There exists textio.ReadAllFromText though
