### ISSUE TITLE
[Bug]: FlinkRunner: KafkaIO emits MAX_WATEMARK

### ISSUE THREAD

**Issue by je-ik** [apache/beam#30050]
### What happened?

When reading data from Kafka with legacy Read, MAX_WATERMARK is emitted when the source is not completed.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [X] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by je-ik** [comment]
Probably related to https://github.com/apache/beam/pull/29563.

**Comment by je-ik** [comment]
> Probably related to #29563.

Reverting the commit seems not to resolve the issue.

**Comment by Abacn** [comment]
Does this related to #29902 or would integrating #29993 resolve the issue?

**Comment by je-ik** [comment]
I don't think it relates. This bug manifests on Beam 2.53.0, Beam 2.52.0 seems to work fine.
