### ISSUE TITLE
[Bug]: JMSIO drops messages when autoscaling down.

### ISSUE THREAD

**Issue by jlampek** [apache/beam#30054]
### What happened?

**Steps to Reproduce**
1. Create a Dataflow job that uses JMSIO to read from an MQ queue. 
2. Configure the Dataflow job to use stream engine with number of workers initially set to 5 and minimum to 1. 
3. Use the DefaultAutoscaler so the workers will auto downgrade from 5 to 1 when Dataflow cannot determine the backlog. 
4. Publish messages to the MQ topic. 

**Expected Behavior**
Workers should scale down, no messages should be dropped. 

**Current Behavior**

1. The dataflow job is consistently dropping transactions at the point in time the workers autoscale down. 
2. GCP Dataflow logs do not indicate that the runner is downscaling. 

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
May or may not be related to #25945. I was suspecting using connection pool that closes only in tearDown could cause problem https://github.com/apache/beam/pull/25945#issuecomment-1481392783. If the publish is cached and only get flushed on closing session then data loss might happen, as teardown is not guaranteed to be called.
