### ISSUE TITLE
[Bug]: MLTransform read_artifact_location does only accept local paths

### ISSUE THREAD

**Issue by LaurenzReitsam** [apache/beam#30062]
### What happened?

The `read_artifact_location` parameter of the `MLTransform` does not work with nonlocal paths like GCS.
This cannot be wanted behavior because `write_artifact_location` does accept those paths.

The reason for failure is the usage of the `os`. The module is used to check the path for validity. This doesn't make sese in combination with `metadata_io`.

See [handlers.py line 438](https://github.com/apache/beam/blob/d5a7fc92cdfcba199f817cd0bd0793b16c5e105e/sdks/python/apache_beam/ml/transforms/handlers.py#L438):
```python
      if not os.path.exists(os.path.join(
          self.artifact_location, RAW_DATA_METADATA_DIR, SCHEMA_FILE)):
        raise FileNotFoundError(
            "Artifacts not found at location: %s when using "
            "read_artifact_location. Make sure you've run the pipeline with "
            "write_artifact_location using this artifact location before "
            "running with read_artifact_location set." %
            os.path.join(self.artifact_location, RAW_DATA_METADATA_DIR))
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by AnandInguva** [comment]
Did you run your pipeline using `write_artifact_location` first?

`read_artifact_location` works only when artifacts are saved during `write_artifact_location`

**Comment by AnandInguva** [comment]
Is it possible to provide an example that can reproduce the error?

**Comment by LaurenzReitsam** [comment]
@AnandInguva, here is an example to reproduce the error:

```python
from apache_beam.ml import MLTransform
from apache_beam.ml.transforms import tft
import apache_beam as beam

GCP_PATH = "gs://GCS_BUCKET_ID/dataflow/tst"

data = [
    {'x': 1},
    {'x': 2},
]

t_fn_write = MLTransform(write_artifact_location=GCP_PATH).with_transform(
    tft.ScaleTo01(columns=['x']),
)

t_fn_read = MLTransform(read_artifact_location=GCP_PATH)

with beam.Pipeline() as p:
        p | beam.Create(data) | t_fn_write | beam.Map(print)
print("writing susccessful...\n")

with beam.Pipeline() as p:
    p | beam.Create(data) | t_fn_read | beam.Map(print)
```

This returns the following output:
```
Row(x=array([0.], dtype=float32))
Row(x=array([1.], dtype=float32))
writing susccessful...

Traceback (most recent call last):
  File "/mnt/c/Users/rlaurenz/Documents/Projects/GCP_ML_Demos/python/demo1/dataflow/foo.py", line 22, in <module>
    p | beam.Create(data) | t_fn_read | beam.Map(print)
  File "/home/laurenz/demo1_beam_env/lib/python3.9/site-packages/apache_beam/pvalue.py", line 137, in __or__
    return self.pipeline.apply(ptransform, self)
  File "/home/laurenz/demo1_beam_env/lib/python3.9/site-packages/apache_beam/pipeline.py", line 731, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish, self._options)
  File "/home/laurenz/demo1_beam_env/lib/python3.9/site-packages/apache_beam/runners/runner.py", line 203, in apply
    return self.apply_PTransform(transform, input, options)
  File "/home/laurenz/demo1_beam_env/lib/python3.9/site-packages/apache_beam/runners/runner.py", line 207, in apply_PTransform
    return transform.expand(input)
  File "/home/laurenz/demo1_beam_env/lib/python3.9/site-packages/apache_beam/ml/transforms/base.py", line 312, in expand
    pcoll = pcoll | ptransform
  File "/home/laurenz/demo1_beam_env/lib/python3.9/site-packages/apache_beam/pvalue.py", line 137, in __or__
    return self.pipeline.apply(ptransform, self)
  File "/home/laurenz/demo1_beam_env/lib/python3.9/site-packages/apache_beam/pipeline.py", line 731, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish, self._options)
  File "/home/laurenz/demo1_beam_env/lib/python3.9/site-packages/apache_beam/runners/runner.py", line 203, in apply
    return self.apply_PTransform(transform, input, options)
  File "/home/laurenz/demo1_beam_env/lib/python3.9/site-packages/apache_beam/runners/runner.py", line 207, in apply_PTransform
    return transform.expand(input)
  File "/home/laurenz/demo1_beam_env/lib/python3.9/site-packages/apache_beam/ml/transforms/handlers.py", line 440, in expand
    raise FileNotFoundError(
FileNotFoundError: Artifacts not found at location: gs://<GCS_BUCKET_ID>/dataflow/tst/a60250/raw_data_metadata when using read_artifact_location. Make sure you've run the pipeline with write_artifact_location using this artifact location before running with read_artifact_location set.
```

The code is working as expected when using local paths. As mentioned, the reason for this is the usage of the `os` module [here](https://github.com/apache/beam/blob/d5a7fc92cdfcba199f817cd0bd0793b16c5e105e/sdks/python/apache_beam/ml/transforms/handlers.py#L438) that can't deal with blob storage.

My setup:
apache-beam==2.53.0
tensorflow==2.15.0.post1
tensorflow-estimator==2.15.0
tensorflow-io-gcs-filesystem==0.35.0
tensorflow-metadata==1.14.0
tensorflow-serving-api==2.14.1
tensorflow-transform==1.14.0

**Comment by AnandInguva** [comment]
Okay. It should be using Beam's FileSystems to check the path. Let me send a fix. Thanks

**Comment by AnandInguva** [comment]
@LaurenzReitsam Can you review the fix PR https://github.com/apache/beam/pull/30082?
