### ISSUE TITLE
[Feature Request]: Upgrade numpy version bound in Python SDK

### ISSUE THREAD

**Issue by siddharthab** [apache/beam#30098]
### What would you like to happen?

The current numpy version bound is set at 1.25.0, with the rationale given as

```
# numpy can have breaking changes in minor versions.
# Use a strict upper bound.
```

I did not find an issue listing known compatibility issues, so maybe this is as simple as running the tests with an updated numpy version. Because numpy is such a pervasive dependency, other packages in my pipeline could have started depending on new features in later versions, and so it will help to stay current.

Happy to help in any way I can.

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
Thanks for the request, sent a PR.
