### ISSUE TITLE
[Task]: Implement load and stress tests for streaming cases

### ISSUE THREAD

**Issue by andreydevyatkin** [apache/beam#30107]
### What needs to happen?

Implement load/stress tests for the following streaming cases:
- BigQuery Stress Test
- BigTable Stress Test
- Kafka Stress Test
- Pub/Sub Load Test
- Pub/Sub Stress Test
- Spanner Stress Test

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Amar3tto** [comment]
.take-issue
