### ISSUE TITLE
[Task]: Develop a reporting mechanism to notify about flaky test cases

### ISSUE THREAD

**Issue by andreydevyatkin** [apache/beam#30109]
### What needs to happen?

Develop a reporting mechanism to notify about flaky test cases if constant failed runs occur. Today on GitHub Actions, there are no clear signals on what tests are consistently flaky.

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by volatilemolotov** [comment]
.take-issue
