### ISSUE TITLE
[Task]: Improve Beam code coverage analysis

### ISSUE THREAD

**Issue by andreydevyatkin** [apache/beam#30110]
### What needs to happen?

Update a GitHub workflow (PreCommit) to identify the testing gaps on specific code branches. The workflow should be part of the pull request process, and identify which code is not covered as part of the PR. If the branch is not covered by unit tests, it should be reported on the PR as a single comment.

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by volatilemolotov** [comment]
.take-issue
