### ISSUE TITLE
[Task]: Create a workflow to run Nightly Playground examples CI checks

### ISSUE THREAD

**Issue by andreydevyatkin** [apache/beam#30111]
### What needs to happen?

Nightly Playground examples CI checks: Verify examples nightly to make sure they remain functioning between SDK changes, etc. This will help to ensure that the examples are always up-to-date and that users can successfully use them.

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by volatilemolotov** [comment]
.take_issue
