### ISSUE TITLE
[Task]: Add a default watermark emit interval to FlinkUnboundedSourceReader

### ISSUE THREAD

**Issue by je-ik** [apache/beam#30125]
### What needs to happen?

Currently, when autoWatermarkInterval is not set, watermarks are not emitted in FlinkUnboundedSourceReader. This does not work wth Beam's event-time default behavior. Use a sensible default for watermark emission when not explicitly set.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [X] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by hardshah** [comment]
.take-issue

**Comment by hardshah** [comment]
Hi @je-ik I have submitted a PR for your review whenever you have time.

**Comment by je-ik** [comment]
Closed via #30141
