### ISSUE TITLE
[Task]: [flink] EncodedValueComparator can use serialzed bytes for deterministic Coders

### ISSUE THREAD

**Issue by je-ik** [apache/beam#30139]
### What needs to happen?

EncodedValueComparator enforces deserialization of serialized bytes for key comparison. This can be avoided for deterministic Coders.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [X] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by hardshah** [comment]
Hi can you assign it to me. I'd like to work on this issue

**Comment by shourya5** [comment]
.take-issue

**Comment by kirupha2000** [comment]
@je-ik I'd like to contribute to this issue if it's still open. I went over the issue description but I wasn't able to understand where exactly the de-serialization is enforced and also how to determine if the bytes were encoded by a deterministic coder. Can you please guide me?

**Comment by je-ik** [comment]
Hi @kirupha2000 , the current implementation of mentioned `EncodedValueComparator` seems correct to me now. Closing this.
