### ISSUE TITLE
[Failing Test]: PostCommit Python Xlang Gcp Direct and Dataflow failing due to #30059

### ISSUE THREAD

**Issue by Abacn** [apache/beam#30159]
### What happened?

#30059 introduces a constraint that failing pipeline on numShards=0 for xlang BigQueryIO storage write API. However, there are tests covering this and working until this constraint is set. Likely the constraint is to broad and breaking known use case.

We should either limit the scope of the constraint or just add warning

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Add as release blocker because it's breaking two post commits

**Comment by Abacn** [comment]
CC: @Polber @lostluck

**Comment by tvalentyn** [comment]
Thanks for taking care of this issue!

**Comment by lostluck** [comment]
Cherry pick is merged in. Currently running the failing suites against the branch. Will close issue if they are green.
