### ISSUE TITLE
[Bug]: Newly introduced OutputReceiver.outputWindowedValue breaking downstream user transforms

### ISSUE THREAD

**Issue by Abacn** [apache/beam#30203]
### What happened?

Introduced in #29616, OutputReceiver implementations now requires a new method `outputWindowedValue` to be implemented in subclasses.

Arguably this was already noticed as a breaking change in #29616, as multiple `@Override
              public void outputWindowedValue(..) {throw new UnsupportedOperationException} ` was added in Beam code.

We should consider declare the interface method as a default method there

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
CC: @kennknowles @lostluck

**Comment by Abacn** [comment]
Let us figure out if this a release blocker or not

**Comment by kennknowles** [comment]
Users are not intended to be implementing OutputReceiver. They should only be calling methods on OutputReceivers that we give them.

**Comment by kennknowles** [comment]
This may be a documentation or labeling `@Internal` issue.

We could add a default method that crashes but that just pushes errors from compile time to runtime. Which is OK if used in a context where it will never be called, but generally worse.

**Comment by Abacn** [comment]
> We could add a default method that crashes but that just pushes errors from compile time to runtime. Which is OK if used in a context where it will never be called, but generally worse.

this is what #29616 currently does. It added override method throwing `UnsupportedOperationException` in a couple of places. We add this method and force IOs implementing it, I see the result is the same

**Comment by lostluck** [comment]
Agreed that conventionally for prod code, one shouldn't be overriding OutputReceiver.

 But if better that it's only causing a runtime error in tests that would be calling the unimplemented default method, than breaking all tests using that pattern.

This is fundamentally a "new required method", which is a breaking pattern, when it should have been added with a default implementation, so code that doesn't need to know about it, doesn't need to care.

Let me know when a fix is in, and I'll create cherry pick for the release branch.

**Comment by Abacn** [comment]
Sure. will create a fix by the end of the day
