### ISSUE TITLE
[Feature Request]: [beam-sdks-java-core]: Create method SerializableComparator.comparing(SerialiableFunction)

### ISSUE THREAD

**Issue by je-ik** [apache/beam#30257]
### What would you like to happen?

Analogous to `Comparator.comparing()`.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by protonpluss** [comment]
Hi @je-ik, I'm currently working on Java projects & would love to contribute in this code. Can you please assign this issue to me?

**Comment by je-ik** [comment]
Hi, you can do that yourself, see [here][1], section "Fix an open issue".

 [1]: https://beam.apache.org/contribute/

**Comment by Mr-Magnificent** [comment]
.take-issue

**Comment by imvtsl** [comment]
.take-issue

**Comment by kirupha2000** [comment]
.take-issue

**Comment by kirupha2000** [comment]
Hi @je-ik , first time contributor here! I've gone through the contributing guidelines and raised a pull request for the issue here - https://github.com/apache/beam/pull/32074. Please take a look and let me know if I'm missing something. Thanks in advance!
