### ISSUE TITLE
[Bug]: The Documentation of `@SchemaFieldNumber` has the wrong type

### ISSUE THREAD

**Issue by iht** [apache/beam#30273]
### What happened?

The annotation `@SchemaFieldNumber` expects a String, but [the documentation shows an example using integers](https://beam.apache.org/releases/javadoc/2.53.0/org/apache/beam/sdk/schemas/annotations/SchemaFieldNumber.html).

This is [how that annotation is used](https://github.com/apache/beam/blob/e9202abb7ad8b2041a257fb3f50337a2f03127b1/sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/FieldValueTypeInformation.java#L150) (with `parseInt` applied to a `String`), and [here is an example in the repo actually using `String` and not integers](https://github.com/apache/beam/blob/e9202abb7ad8b2041a257fb3f50337a2f03127b1/sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/utils/TestPOJOs.java#L228-L266).

This is a documentation-only bug.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Amar3tto** [comment]
Can the issue be closed? 
[2.57 documentation](https://beam.apache.org/releases/javadoc/2.57.0/org/apache/beam/sdk/schemas/annotations/SchemaFieldNumber.html) seems correct

**Comment by iht** [comment]
Fixed elsewhere
