### ISSUE TITLE
[Task]: Pick FileDescriptor automatically from messageName

### ISSUE THREAD

**Issue by ffernandez92** [apache/beam#30313]
### What needs to happen?

The current implementation for Beam YAML to read proto events is not allowing multiple imports from FileDescriptors. Ideally we want to support picking the right file descriptor based on the message name. 

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [X] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by ffernandez92** [comment]
.take-issue

**Comment by damccorm** [comment]
Is this completed by https://github.com/apache/beam/pull/30314?

**Comment by ffernandez92** [comment]
Yes, sorry for the delayed response. I'm closing the issue.
