### ISSUE TITLE
[Feature Request]: Add examples for using metrics with Python to Beam Website

### ISSUE THREAD

**Issue by tvalentyn** [apache/beam#30419]
### What would you like to happen?

Currently the website only has examples for Java and Go: https://beam.apache.org/documentation/programming-guide/#metrics

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [X] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by selango1** [comment]
can I work on this issue?

**Comment by TrackAir** [comment]
can I work on this issue?

- Component: Java SDK

**Comment by manishkumar23829928** [comment]
can i work on this issue?

**Comment by liferoad** [comment]
Feel free to take the issue: https://github.com/apache/beam/blob/master/.github/ACTIONS.md#issue-management

**Comment by VETREA** [comment]
can i work on this issue ?
i am beginner to open source

**Comment by PrabeshPP** [comment]
.take-issue

**Comment by shreyakri026** [comment]
can i work on this issue..?

**Comment by tvalentyn** [comment]
Given how much interest this issue has been receiving, feel free to express the interest by sending a PR without asking for permission to work on it.

For anyone else who commented before - do feel free to chime in or send a link to draft PR if you had a chance to start and plan to finish this work.

**Comment by hjtran** [comment]
Is this issue outdated? I see examples of how to use metrics with the python SDK on the website already
<img width="1115" alt="image" src="https://github.com/user-attachments/assets/d4be2874-6985-4c24-81af-f06b0433f289">

**Comment by tvalentyn** [comment]
A recent addition - https://github.com/apache/beam/pull/32464, hooray!
Thanks @boomanaiden154

**Comment by boomanaiden154** [comment]
>  in the future, you can mention #fixes: in the PR description, to automatically link the affected issue. Thanks for your contribution!

I didn't even realize there was an issue open for this or I would've tagged it in the PR. Sorry about that.

**Comment by tvalentyn** [comment]
Ah, that's even better :)
