### ISSUE TITLE
[Bug]: Upgrade compatibility broken when upgrading BQ read/write transforms to 2.55.0.dev 

### ISSUE THREAD

**Issue by chamikaramj** [apache/beam#30534]
### What happened?

Seems like we added two required constructions properties in https://github.com/apache/beam/commit/6a8c27ef6fb945921b4f70766c1f1bd6c493dadc.

These properties are not available in previous BQ transform versions, hence upgrade compatibility will be broken.

Is it possible to make these properties optional in the transform ?

If above can be done, we can also avoid adding such properties during construction (see https://github.com/apache/beam/pull/30032) which would preserve upgrade compatibility.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by chamikaramj** [comment]
cc: @kennknowles @robertwb we might run into other similar upgrade compatibility issues in the future, hence we should think about how to detect/avoid them.

**Comment by Abacn** [comment]
What is the plan as for 2.55.0 release ?

**Comment by chamikaramj** [comment]
I'm working on a fix.

**Comment by chamikaramj** [comment]
Should be fixed by https://github.com/apache/beam/issues/30534.

**Comment by chamikaramj** [comment]
Need to open a cherry-pick to 2.55.0 branch.

**Comment by Abacn** [comment]
The fix #30551 breaks XVR PythonUsingJavaSql tests (for all runners). See 
- https://github.com/apache/beam/actions/workflows/beam_PostCommit_XVR_PythonUsingJavaSQL_Dataflow.yml?query=event%3Aschedule
- https://github.com/apache/beam/actions/workflows/beam_PostCommit_XVR_Samza.yml?query=event%3Aschedule
- https://github.com/apache/beam/actions/workflows/beam_PostCommit_XVR_Spark3.yml?query=event%3Aschedule

and revert can make the test run: https://github.com/apache/beam/pull/30577

It fails early at failing to start expansion service

**Comment by Abacn** [comment]
Sorry, I now pretty sure it is gradle cache issue. Initiated the test locally it passed.

**Comment by Abacn** [comment]
Opened https://issues.apache.org/jira/browse/INFRA-25595 request delete remote Gradle cache
