### ISSUE TITLE
[Feature Request]: Allow compression of Elasticsearch requests

### ISSUE THREAD

**Issue by henrikno** [apache/beam#30641]
### What would you like to happen?

I noticed requests from Dataflow were using a lot of bandwidth compared to our other similar traffic, and one of the reasons is that it's not using any compression on requests. When running in the cloud there's various charges on network traffic that add up. Enabling compression should help there. 

Compression of requests was enabled in ES client 7.10 https://github.com/elastic/elasticsearch/pull/63230, it's currently using 7.9 so need to bump the version and use `setCompressionEnabled`.
There's a CPU tradeoff so it should be possible to configure. In my opinion it should default to use compression, responses are already compressed, most other clients I see use compression by default as well. 

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Amar3tto** [comment]
.take-issue
