### ISSUE TITLE
[Bug]: Beam Playground scio examples cannot run

### ISSUE THREAD

**Issue by Abacn** [apache/beam#30757]
### What happened?

Open https://play.beam.apache.org/ then select a scio example, make a white space change (otherwise it will read from cache)

Attempt to run the example, it get:

```
The processing has been started with the pipeline options: --output output.txt

Error during preparing: Error during setup file system for the code processing: error during create necessary files for the Scio sdk: exit status 1
```

Found when upgrading playground to 2.55.0, but found it is a pre-exisiting issue on prod

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by andreydevyatkin** [comment]
Should be fixed as part of #31556
