### ISSUE TITLE
[Task]: Re-enable schedule trigger for PostCommit Java IO Performance Tests

### ISSUE THREAD

**Issue by volatilemolotov** [apache/beam#30787]
### What needs to happen?

We need to re-enable schedule trigger for PostCommit Java IO Performance Tests after the 2.56 release. 

The change is done in this PR #30751

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by damccorm** [comment]
I have #31024 to fix this once the 2.56 release is out
