### ISSUE TITLE
[Failing Test]: Python Coverage is failing because of new version of typing-extension release

### ISSUE THREAD

**Issue by riteshghorse** [apache/beam#30806]
### What happened?

It looks like two of our python tests using tensorflow are failing. The reason being that the tensorflow has dependency on typing extension <4.6

![image](https://github.com/apache/beam/assets/25881114/5aac242e-cb1d-4d8c-840a-935b4434146c)

and

![image](https://github.com/apache/beam/assets/25881114/9d94e6b1-a9c4-4efc-8d02-615bd58e3ec6)

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
Also caused #30799

**Comment by riteshghorse** [comment]
Yes, I think it was added to catch issues like these, that is, to catch breaking changes from other libraries by checking against pre-releases.

**Comment by riteshghorse** [comment]
Until `tensorflow==2.13`, it has strict dependency on `typing-extensions<4.6.0` which is creating this issue. I'll move the version to 2.14 for relevant tests

**Comment by riteshghorse** [comment]
https://github.com/apache/beam/pull/30863 fixed it
