### ISSUE TITLE
[Bug]: Install fails with Python3.12 due to old grpcio-tools version

### ISSUE THREAD

**Issue by sehoffmann** [apache/beam#30820]
### What happened?

Installing `grpcio-tools==1.53.0` (listed in https://github.com/apache/beam/blob/master/sdks/python/pyproject.toml) fails with Python3.12. See this related issue  https://github.com/grpc/grpc/issues/33063 in the grpc project. As a result, it is impossible to install `apache-beam` on Python3.12.

*Solution*: Upgrade to a more recent version of `grpcio-tools`  which has this bug fixed by now.

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by sehoffmann** [comment]
*More infomation:* 
* The project installs successfully when using `pip install --no-build-isolation apache-beam`.
* Executing `pip install grpcio-tools==1.53.0` fails, whereas `pip install grpcio-tools` works

**Comment by liferoad** [comment]
Supporting 3.12 is tracked at https://github.com/apache/beam/issues/29149

**Comment by tvalentyn** [comment]
sent https://github.com/apache/beam/pull/30912
