### ISSUE TITLE
[Bug]: ClassCastException with REPEATED RECORD and STORAGE_WRITE_API

### ISSUE THREAD

**Issue by lucasnoetzold** [apache/beam#30850]
### What happened?

We're gettig a `ClassCastException` when trying to write data to a BigQuery table with the STORAGE_WRITE_API. This only happens we are writing to a REPEATED RECORD and `withAutoSchemaUpdate` option is set to `true`.

```log
BigQueryStorageApiInsertError {
 row=GenericData{classInfo=[f], {a_repeated_record=[{a_field=a_value}]}},
 errorMessage='org.apache.beam.sdk.io.gcp.bigquery.TableRowToStorageApiProto$SchemaDoesntMatchException:
  Problem converting field root.a_repeated_record expected type: STRUCT.
   Exception: java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.util.List (java.util.LinkedHashMap and java.util.List are in module java.base of loader 'bootstrap')'
}
```

**Conditions:**
- BigQuery table that contains a "RECORD" type field
- the record field must be on mode "REPEATED"
- `.withAutoSchemaUpdate(true)`

As far as I was able to test, every time these 3 conditions are met, we get the error.

**Expected Behavior:** no error, the data should be written to BigQuery.

---

I've managed to reproduce the error with this minimal code:

```java
var theObject = Map.of("a_field", "a_value");
var theRepeated = List.of(theObject);
var theRow = new TableRow().set("a_repeated_record", theRepeated);

var pipeline = Pipeline.create();

pipeline.apply(Create.<TableRow>of(row))
  .apply(BigQueryIO.<TableRow>write()
    .ignoreUnknownValues()
    .withAutoSchemaUpdate(true)
    .withFormatFunction(identity())
    .withMethod(BigQueryIO.Write.Method.STORAGE_WRITE_API)
    .withCreateDisposition(CreateDisposition.CREATE_NEVER)
    .to(new TableReference()
      .setProjectId("the_project_id")
      .setDatasetId("the_dataset_id")
      .setTableId("test_table")));

pipeline.run();
```

The BigQuery table schema used is the following:
![image](https://github.com/apache/beam/assets/27974653/c9550854-3e92-4d81-9a36-eecb40bbda30)

Looking at the stack we can see that it happens when it's handling the unknown fields.
![image](https://github.com/apache/beam/assets/27974653/0c4173c2-e2ea-4c8a-b28e-d306fbf0c3a0)

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by ahmedabu98** [comment]
This happens because `TableRowToStorageApiProto` always marks a STRUCT field as an unknown and gives it a value of an empty TableRow (later to be populated). When there are actually no unknown nested fields, we never clean up this empty TableRow (more details in #31447). Some weird conversion happens down the line that leads to the error you're seeing
