### ISSUE TITLE
[Failing Test]: Java IO Precommit failing due to KafkaIOTranslation being out of sync

### ISSUE THREAD

**Issue by ahmedabu98** [apache/beam#30941]
### What happened?

Error:
```
java.lang.AssertionError: Method getConsumerPollingTimeout will not be tracked when upgrading the 'KafkaIO.Read' transform. Please update 'KafkaIOTranslation.KafkaIOReadWithMetadataTranslator' to track the new method and update this test.
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.apache.beam.sdk.io.kafka.upgrade.KafkaIOTranslationTest.testReadTransformRowIncludesAllFields(KafkaIOTranslationTest.java:170)
```

A new builder method was added for KafkaIO in #30877, which now needs to be added in KafkaIOTranslation.

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
This affects PreCommit so bump to P1

**Comment by chamikaramj** [comment]
Fixed by https://github.com/apache/beam/pull/30877.
