### ISSUE TITLE
[Failing Test]: setuptools 69.3.0 breaks sdist

### ISSUE THREAD

**Issue by Abacn** [apache/beam#30955]
### What happened?

Even though there is a log

```
/private/var/folders/wg/hwmcqjwd4zz75mjs0r5z_3f400y2yj/T/build-env-h7rslxzz/lib/python3.8/site-packages/setuptools/dist.py:318: InformationOnly: Normalizing '2.56.0.dev' to '2.56.0.dev0'
```

the "normalized" version is

```
creating apache_beam-2.55.dev0
```

Likely a bug in the latest setuptools.

Update: setuptools 69.4.0 released after 2 hr of 69.3.0 release, still not resolve the issue

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
They also changed the handling of dashes: apache-beam becomes apache_beam

**Comment by Abacn** [comment]
> They also changed the handling of dashes: apache-beam becomes apache_beam

Yeah, this is https://github.com/pypa/setuptools/issues/4300
