### ISSUE TITLE
[Bug]: Embedded Video (and other content) in iframes are not working

### ISSUE THREAD

**Issue by aaltay** [apache/beam#30981]
### What happened?

For example this page (https://beam.apache.org/get-started/resources/videos-and-podcasts/#tensorflow-extended-an-end-to-end-machine-learning-platform-for-tensorflow) shows a bunch of content blocked errors.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [X] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by rszper** [comment]
<img width="541" alt="iframe" src="https://github.com/apache/beam/assets/98840847/1cd22ed1-5ba8-4397-b75a-76bb41d15ba3">

**Comment by tvalentyn** [comment]
Opened https://github.com/apache/beam/issues/31018, to use a proper way to embed iframes. In the short term we could  temporary enable YT frames similar as in https://github.com/apache/beam/pull/30391 or switch to links.

**Comment by aaltay** [comment]
Another blocked content here: https://beam.apache.org/community/presentation-materials/

Could we allow access to https://drive.google.com/ as well?

**Comment by tvalentyn** [comment]
cc: @svetakvsundhar

**Comment by brucearctor** [comment]
<img width="1310" alt="Screenshot 2024-04-29 at 12 04 54 PM" src="https://github.com/apache/beam/assets/5032356/1e7be3d2-4491-458f-a56b-39fdbf03cab7">

Unclear whether this is fixed -- also, see screenshot, or message "This content is blocked. Contact the site owner to fix the issue." ...

**Comment by tvalentyn** [comment]
it takes some time to for the update to propagate.

**Comment by tvalentyn** [comment]
feel free to reopen if not fixed in 24 hrs.
You can see currently allowed urls in the headers if you open chrome debugging console and look for errors.
