### ISSUE TITLE
[Task]: Normalize Beam YAML PubSub format to uppercase

### ISSUE THREAD

**Issue by ffernandez92** [apache/beam#31067]
### What needs to happen?

The current PubSub YAML implementation has the `format` option in lowercase. However, Kafka and PubSub Lite have it in uppercase. I'd like to change the current PubSub one to accept uppercase and grandfather in the existing uses.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [X] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by ffernandez92** [comment]
.take-issue

**Comment by brucearctor** [comment]
Marking as closed.  There is likely an eventual follow up task to actually standardize, instead of allowing both.  But, can revisit that in MANY versions from now.
