### ISSUE TITLE
[Bug]: Beam programming guide missing Counters example

### ISSUE THREAD

**Issue by aaltay** [apache/beam#31098]
### What happened?

In: https://beam.apache.org/documentation/programming-guide/#using-metrics

It says: "Below, there is a simple example of how to use a Counter metric in a user pipeline."

But it is not followed by an example.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [X] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by liferoad** [comment]
<img width="1384" alt="image" src="https://github.com/apache/beam/assets/7833268/c3cf394e-cd08-4ea1-928c-8d550828c850">

Is this not the desired example?

**Comment by aaltay** [comment]
That is correct. This seems to be an issue on my end. I can see the example in incognito mode but I cannot see without. It must an extension or a browser setting on my end doing this. Closing this issue, thanks for the quick reply.
