### ISSUE TITLE
[Bug][Python]: ReadFromCsv with the dtype argument is very slow

### ISSUE THREAD

**Issue by liferoad** [apache/beam#31152]
### What happened?

# Test code

```python
import apache_beam as beam
import datetime

CSV_DATA = r"""a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r
1,"text",1,21,5945023,376974,0,0,0,1,2,0,4,,,,,,
"""

filename = '/tmp/input.csv'
with open(filename, 'w') as f:
  f.write(CSV_DATA)

# less than 1 second
start = datetime.datetime.now()
with beam.Pipeline() as pipeline:
  ( pipeline | beam.io.ReadFromCsv('/tmp/input.csv')
    | beam.io.WriteToCsv('/tmp/output.csv')
  )
print('Elapsed time ', (datetime.datetime.now() - start))

# ~25 seconds with dtype=str 
start = datetime.datetime.now()
with beam.Pipeline() as pipeline:
  ( pipeline | beam.io.ReadFromCsv('/tmp/input.csv', dtype=str)
    | beam.io.WriteToCsv('/tmp/output.csv')
  )
print('Elapsed time ', (datetime.datetime.now() - start))
```

# Problem

`WriteToCsv` does not matter here. When running this with `%prun`, [output_partitioning_in_stage](https://github.com/apache/beam/blob/670e56fb1b439ff902dac4079c901ff145c207fb/sdks/python/apache_beam/dataframe/transforms.py#L305) is dominated. We need to figure out why this happens and fix this performance issue.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by liferoad** [comment]
One workaround is to convert the value using your own function, for example,

```
with beam.Pipeline() as pipeline:
    (
        pipeline
        | beam.io.ReadFromCsv("input.csv", dtype=None)
        | beam.Map(lambda x: [str(t) for t in x])
        | beam.Map(print)
    )
```

**Comment by sorensenjs** [comment]
That workaround code example doesn't work, because ReadFromCsv and WriteToCsv both produce/require schemas.

Even if you were to use a ._asdict() like so

```  
( pipeline | beam.io.ReadFromCsv('/tmp/input.csv', dtype=str)
      | beam.Map(lambda x: x._asdict())
      | beam.Map(print)
```

Conversion to str element by element will result in 'None' values instead of empty strings. Values interpreted as floating point may loose precision.

```
{'a': 'text', 'b': 1, 'c': 21, 'd': 5945023, 'e': 376974, 'f': 0, 'g': 0, 'h': 0, 'i': 1, 'j': 2, 'k': 0, 'l': 4, 'm': None, 'n': None, 'o': None, 'p': None, 'q': None, 'r': None}
Elapsed time  0:00:00.878320
{'a': 'text', 'b': '1', 'c': '21', 'd': '5945023', 'e': '376974', 'f': '0', 'g': '0', 'h': '0', 'i': '1', 'j': '2', 'k': '0', 'l': '4', 'm': None, 'n': None, 'o': None, 'p': None, 'q': None, 'r': None}
Elapsed time  0:00:24.243182
```

**Comment by liferoad** [comment]
My example just shows that you can do the conversation without using `dtype=str`. If you need to keep the schemas, you could do something like:

```
with beam.Pipeline() as pipeline:
    (
        pipeline
        | beam.io.ReadFromCsv("input.csv", dtype=None)
        | beam.Map(lambda x: beam.Row(a=x.a, b=str(x.b)))
        | beam.io.WriteToCsv("output1.csv")
    )
```
