### ISSUE TITLE
[Bug][Prism]: panic: nothing in progress and no refreshes with non zero pending elements

### ISSUE THREAD

**Issue by damondouglas** [apache/beam#31338]
Java test `org.apache.beam.sdk.transforms.FlattenTest` fails on Prism with error `panic: nothing in progress and no refreshes with non zero pending elements`:

Steps to reproduce.

1) Run Prism server.

```
./gradlew :runners:prism:runServer
```

2) Execute `:runners:portability:java:ulrLoopbackValidatesRunnerTests` on Prism:

```
TEST=org.apache.beam.sdk.transforms.FlattenTest
./gradlew :runners:portability:java:ulrLoopbackValidatesRunnerTests -PjobEndpoint=localhost:8073 --tests="$TEST"
```

Parent tracker: #28187

**Comment by damondouglas** [comment]
@lostluck so far I found that job being stuck, reported by the panic, may be due to the upstream watermark. In the following logs, I see a reporting of "insufficient upstream watermark" i.e. `inputW == upstreamW` in the bundleReady method. One hypothesis generating idea would be to collect which Java validates runner tests are leading to the panic to detect a potential pattern.

```
{"time":"2024-06-03T23:16:17.984115241Z","level":"DEBUG","msg":"bundleReady: insufficient upstream watermark","stage":"stage-001","watermark":{"upstream":9223372036854775,"input":9223372036854775}}
{"time":"2024-06-03T23:16:17.984145011Z","level":"DEBUG","msg":"Bundles: nothing in progress after advance","advanced":{"stage-001":{}},"refreshCount":1,"pendingElementCount":2}
{"time":"2024-06-03T23:16:17.984161971Z","level":"DEBUG","msg":"bundleReady: insufficient upstream watermark","stage":"stage-006","watermark":{"upstream":-9223372036854775,"input":-9223372036854775}}
{"time":"2024-06-03T23:16:17.984172671Z","level":"DEBUG","msg":"Bundles: nothing in progress and no refreshes","pendingElementCount":2}
panic: nothing in progress and no refreshes with non zero pending elements: 2
```

**Comment by lostluck** [comment]
I'd put the test (and clarify that it's running on prism) in the title instead of the symptom. The panic is to avoid a forever hang when there is no way to make progress. It's never going to be unique to this test. You will see this much more.

**Comment by damondouglas** [comment]
> I'd put the test (and clarify that it's running on prism) in the title instead of the symptom. The panic is to avoid a forever hang when there is no way to make progress. It's never going to be unique to this test. You will see this much more.

Multiple tests result in this panic. I just chose one so it is quick to get to this state.
