### ISSUE TITLE
[Bug]: apache_beam.io.gcp.bigquery_tools.py uses logging.info instead of _LOGGER

### ISSUE THREAD

**Issue by tomaslink** [apache/beam#31414]
### What happened?

While the module uses `_LOGGER = logging.getLogger(__name__)`, there is [one line](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/io/gcp/bigquery_tools.py#L652) in which it is still using the root logger implicitly with `logging.info`, so that line gets excluded from any possible logging configuration done for this specific module at a higher level.

Related:
- https://github.com/apache/beam/issues/18626
- https://issues.apache.org/jira/browse/BEAM-3523

Beam version: 2.56.0

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by tvalentyn** [comment]
Thanks for reporting - would you like to send a PR to fix this?
