### ISSUE TITLE
[Bug][Prism]: unsupported feature "WindowStrategy.AllowedLateness"

### ISSUE THREAD

**Issue by damondouglas** [apache/beam#31463]
Several Java tests fail on Prism with the error:

```
unsupported feature "WindowingStrategy.AllowedLateness" set with value 9223372036854775
```

Steps to reproduce:

1. Run Prism server.

```
./gradlew :runners:prism:runServer
```

2.  Execute `:runners:portability:java:ulrLoopbackValidatesRunnerTests` on Prism:

Many tests fail with these errors, but to see the output of one quickly:

```
TEST=org.apache.beam.sdk.transforms.ReshuffleTest
./gradlew :runners:portability:java:ulrLoopbackValidatesRunnerTests -PjobEndpoint=localhost:8073 --tests="$TEST"
```

Parent tracker: #28187
Related: #31438

**Comment by lostluck** [comment]
The PR didn't implement allowed lateness, just permitting it to be set with the maximum timestamp. However, this smaller change feels safe enough WRT how the tests cared for allowed lateness.
