### ISSUE TITLE
[Feature Request]: Disable soft delete policy when creating a default bucket in Go SDK

### ISSUE THREAD

**Issue by shunping** [apache/beam#31605]
### What would you like to happen?

This is a follow-up FR of #31330 to disable soft delete policy in default bucket creation for Go SDK.

Java and Python implementation can be found at #31324 and #31344, respectively.

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by ljjulia** [comment]
.take_issue

**Comment by ljjulia** [comment]
.take-issue
