### ISSUE TITLE
[Bug]: ClickHouseIO - wrong JDBC dependency import

### ISSUE THREAD

**Issue by BentsiLeviav** [apache/beam#31634]
### What happened?

Starting of Beam version `2.52.0`, for some reason the jdbc library imported is the thin version, and not the `all` version.

Given this `pom.xml` file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>beam-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        

        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <beam.version>2.56.0</beam.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.beam</groupId>
            <artifactId>beam-sdks-java-core</artifactId>
            <version>${beam.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.beam</groupId>
            <artifactId>beam-runners-direct-java</artifactId>
            <version>${beam.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.beam/beam-sdks-java-io-clickhouse -->
        <dependency>
            <groupId>org.apache.beam</groupId>
            <artifactId>beam-sdks-java-io-clickhouse</artifactId>
            <version>${beam.version}</version>
        </dependency>

    </dependencies>


</project>
```

The imported ClickHouse JDBC is:
![image](https://github.com/apache/beam/assets/46030906/4af3edab-44f8-4290-a1a4-bb178954de15)

When using older version such as `2.51.0`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>beam-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        

        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <beam.version>2.51.0</beam.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.apache.beam</groupId>
            <artifactId>beam-sdks-java-core</artifactId>
            <version>${beam.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.beam</groupId>
            <artifactId>beam-runners-direct-java</artifactId>
            <version>${beam.version}</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.beam/beam-sdks-java-io-clickhouse -->
        <dependency>
            <groupId>org.apache.beam</groupId>
            <artifactId>beam-sdks-java-io-clickhouse</artifactId>
            <version>${beam.version}</version>
        </dependency>

    </dependencies>


</project>
```

The imported version is the correct one (the `all` version):

![image](https://github.com/apache/beam/assets/46030906/14d10c93-c8b9-4c42-8795-9350befff47e)

There was no change in `ClickHouseIO` [gradel file](https://github.com/apache/beam/blob/3d05eec17d4b8f87fc35458b6c54f0278f237383/sdks/java/io/clickhouse/build.gradle) between the broken versions (`2.51.0` <-> `2.52.0`)

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by damccorm** [comment]
It does definitely look like this changed.

2.52.0 - https://repo1.maven.org/maven2/org/apache/beam/beam-sdks-java-io-clickhouse/2.52.0/beam-sdks-java-io-clickhouse-2.52.0.pom
2.51.0 - https://repo1.maven.org/maven2/org/apache/beam/beam-sdks-java-io-clickhouse/2.51.0/beam-sdks-java-io-clickhouse-2.51.0.pom

My best guess is it has something to do with gradle dropping classifier (https://github.com/ConsenSys/teku/issues/6825) which might have manifested when we bumped to gradle 8 - https://github.com/apache/beam/pull/28756

@Abacn any ideas here?
