### ISSUE TITLE
[Bug]: The link "Getting Started with Apache Beam Quest" in https://beam.apache.org/get-started/resources/learning-resources/#certifications page is broken

### ISSUE THREAD

**Issue by dannikay** [apache/beam#31649]
### What happened?

The link to the quest is broken.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [X] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by liferoad** [comment]
It should be https://www.cloudskillsboost.google/course_templates/724
