### ISSUE TITLE
[Feature Request]: Increase the test coverage of pipieline_options.go

### ISSUE THREAD

**Issue by mls3odp** [apache/beam#31731]
### What would you like to happen?

There is no unit test for sdks/go/container/tools/pipieline_options.go.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by ljjulia** [comment]
.take-issue
