### ISSUE TITLE
[Feature Request][Prism]: Add test for StateKey_MultimapSideInput in State in worker.go 

### ISSUE THREAD

**Issue by mls3odp** [apache/beam#31756]
### What would you like to happen?

Add missing unit test for [StateKey_MultimapSideInput case](https://app.codecov.io/gh/apache/beam/blob/master/sdks%2Fgo%2Fpkg%2Fbeam%2Frunners%2Fprism%2Finternal%2Fworker%2Fworker.go#L495) in prism worker.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by mls3odp** [comment]
.take-issue

**Comment by lostluck** [comment]
Note: If you have Fixes #<issue number> on it's own line in the PR, it will automatically close the issue on merge. "Addresses" might work too, but I think it needs to be clearly on it's own line though, rather than in the middle of other sentences.
