### ISSUE TITLE
[Bug]: KafkaIO documentation gap

### ISSUE THREAD

**Issue by aaltay** [apache/beam#31839]
### What happened?

There is a documentation gap when kafkaio is used in multi-language mode and one wants to pass experiment flags to the IO.

context: https://lists.apache.org/thread/c9nlm9ffrh0vtmclgflc45dp62rnoz1j

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by jaehyeon-kim** [comment]
.take-issue
