### ISSUE TITLE
[Bug]: SolaceIO.Read - SEMP API queries fail for queue that has "/" in its name

### ISSUE THREAD

**Issue by ppawel** [apache/beam#32108]
### What happened?

Example log for a queue named `a/b/c`:

```
2024-08-08 14:58:05,226 INFO  [Test worker] o.a.b.s.i.s.b.BasicAuthSempClient : SolaceIO.Read: SempOperations: query SEMP if queue a/b/c is nonExclusive

com.google.api.client.http.HttpResponseException: 400 Bad Request
GET http://localhost:8080/SEMP/v2/monitor/msgVpns/default/queues/a/b/c
{"meta":{"error":{"code":535,"description":"No paths found for /msgVpns/default/queues/a/b/c","status":"INVALID_PATH"},"request":{"method":"GET","uri":"http://localhost:8080/SEMP/v2/monitor/msgVpns/default/queues/a/b/c"},"responseCode":400}}
org.apache.beam.sdk.Pipeline$PipelineExecutionException: com.google.api.client.http.HttpResponseException: 400 Bad Request
```

It looks like the queue name parameter is not URL-encoded so the web server thinks it is part of the path of the request. If I try to open `http://localhost:8080/SEMP/v2/monitor/msgVpns/default/queues/a%2Fb%2Fc/msgs` (note the URL-encoded name of `a/b/c`) manually, then it works.

CC @bzablocki 

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by bzablocki** [comment]
thanks!
.take-issue
