### ISSUE TITLE
[Task]: Replace JacksonFactory references with GsonFactory

### ISSUE THREAD

**Issue by damccorm** [apache/beam#32130]
### What needs to happen?

Per https://cloud.google.com/java/docs/reference/google-http-client/latest/com.google.api.client.json.jackson2.JacksonFactory this class has been deprecated. In theory it should just be a 1:1 switch

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by cutiepie-10** [comment]
Hi @damccorm,
I would like to contribute to this issue. Though, I would like some help as this is my first issue.

**Comment by cutiepie-10** [comment]
.take-issue

**Comment by cutiepie-10** [comment]
Hi @damccorm ,
I have opened a new pull request by mistake please look into the changes.
I need some help regarding this issue.
