### ISSUE TITLE
[Feature Request]: Protobuf 5+ support

### ISSUE THREAD

**Issue by steerlink** [apache/beam#32302]
### What would you like to happen?

Is it possible for the python sdk and image to support protobuf 5+?

I have a project that consumes protobuf files generated with version 5.27 of protoc. Those files introduce the following import which isn't understood by protobuf 4.26.0.

```
from google.protobuf import runtime_version as _runtime_version
```

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by liferoad** [comment]
Tracked here: https://github.com/apache/beam/issues/25590
