### ISSUE TITLE
[Bug]: How to run YAML pipeline from Python SDK rather than from command line

### ISSUE THREAD

**Issue by diptenduLF** [apache/beam#32416]
### What happened?

The examples run YAML pipeline from the command line:

`python -m apache_beam.yaml.main --pipeline_spec_file=pipeline-01.yaml 
`
However, I want to run the pipeline file from within a Python script like:

```
with beam.Pipeline('DirectRunner') as p:
......
```

How can this be done?

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [X] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by liferoad** [comment]
https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/python/src/main/python/yaml-template/main.py

```
from apache_beam.yaml import main

# parse your argv then do this

main.run(argv=your_argv)

```
