### ISSUE TITLE
[Bug]: SolaceIO Unit Test testRead flaky

### ISSUE THREAD

**Issue by Abacn** [apache/beam#32548]
### What happened?

Error message:

```
java.lang.AssertionError: expected:<20> but was:<30>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.apache.beam.sdk.io.solace.it.SolaceIOIT.testRead(SolaceIOIT.java:112)
```

See https://github.com/apache/beam/runs/30587784269

It's somewhat frequent (failed 5 times in the last 10 days)

https://github.com/apache/beam/actions/workflows/beam_PreCommit_Java_Solace_IO_Direct.yml?query=event%3Aschedule+is%3Afailure

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
@bzablocki @iht  could you please take a look?

**Comment by bzablocki** [comment]
Thanks for tagging @Abacn. I'll have a look
