### ISSUE TITLE
[Feature Request]: SolaceIO - publishing to dynamic topics (like TopicNameMapper in JmsIO)

### ISSUE THREAD

**Issue by ppawel** [apache/beam#32718]
### What would you like to happen?

We have a use case of publishing messages to "dynamic" topics, meaning the name of the topic is depending on the message being published, something like: `my/great/topic/{countryCode}/{someType}/{whatever}`. These placeholders depend on the payload that is being mapped to a message. This allows consumers to subscribe only to a subset of messages that are interesting to them.

In JmsIO this is easy to do by providing a custom lambda via the `topicNameMapper` property.

Would you consider adding this to SolaceIO in some form?

CC @bzablocki 

### Issue Priority

Priority: 2 (default / most feature requests should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by ppawel** [comment]
@bzablocki Could you give a hint if this feature would be included in any near-future roadmap?

**Comment by bzablocki** [comment]
We're currently finishing up the Write connector, and I believe it has the feature that you mentioned here - see the PR https://github.com/apache/beam/pull/32060/files#diff-b61373f75a4de5bdf91a94bd1d008285b883533994138b07a393a30377140b49R1064-R1065
You'll be able to set a destination for each record you send to Solace. This PR should be merged soon and be released in Beam 2.61 or 2.62.

**Comment by ppawel** [comment]
> We managed to release the Write connector in Beam 2.61. Feel free to test and close this request if no longer relevant.

Ah sorry for late reply... Thanks for the update, we are planning to switch publishing to SolaceIO from JmsIO as well so for sure is relevant. I will test it and report any issues in separate bugs if anything occurs.

Thanks again for support!
