### ISSUE TITLE
[Bug]: beam_Release_Python_NightlySnapshot workflow broken

### ISSUE THREAD

**Issue by Abacn** [apache/beam#32729]
### What happened?

The workflow is not publishing any nightly snapshots after April 13, 2024: https://github.com/apache/beam/actions/workflows/beam_Release_Python_NightlySnapshot.yml

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
cc: @shunping

**Comment by shunping** [comment]
.take-issue
