### ISSUE TITLE
[Failing Test]: PostRelease Nightly Snapshot is perma-red due to "connect timed out"

### ISSUE THREAD

**Issue by chamikaramj** [apache/beam#32824]
### What happened?

Seems like jar file resolution with Maven SNAPSHOT repo is somehow incorrect.

Successful run: https://github.com/apache/beam/actions/runs/11307102323/job/31448448902

```
[INFO] Archetype repository not defined. Using the one from [org.apache.beam:beam-sdks-java-maven-archetypes-examples:2.24.0] found in catalog remote
[INFO] Downloading from test.release: https://repository.apache.org/content/repositories/snapshots/org/apache/beam/beam-sdks-java-maven-archetypes-examples/2.61.0-SNAPSHOT/maven-metadata.xml
[INFO] Downloaded from test.release: https://repository.apache.org/content/repositories/snapshots/org/apache/beam/beam-sdks-java-maven-archetypes-examples/2.61.0-SNAPSHOT/maven-metadata.xml (1.7 kB at 3.3 kB/s)
[INFO] Downloading from test.release: https://repository.apache.org/content/repositories/snapshots/org/apache/beam/beam-sdks-java-maven-archetypes-examples/2.61.0-SNAPSHOT/beam-sdks-java-maven-archetypes-examples-2.61.0-20241012.122627-12.jar
[INFO] Downloaded from test.release: https://repository.apache.org/content/repositories/snapshots/org/apache/beam/beam-sdks-java-maven-archetypes-examples/2.61.0-SNAPSHOT/beam-sdks-java-maven-archetypes-examples-2.61.0-20241012.122627-12.jar (340 kB at 435 kB/s)
```

Failed run: https://github.com/apache/beam/actions/runs/11369820828/job/31628153369

```
[INFO] Archetype repository not defined. Using the one from [org.apache.beam:beam-sdks-java-maven-archetypes-examples:2.24.0] found in catalog remote
[INFO] Downloading from test.release: https://repository.apache.org/content/repositories/snapshots/org/apache/beam/beam-sdks-java-maven-archetypes-examples/2.61.0-SNAPSHOT/maven-metadata.xml
Warning:  Could not transfer metadata org.apache.beam:beam-sdks-java-maven-archetypes-examples:2.61.0-SNAPSHOT/maven-metadata.xml from/to test.release (https://repository.apache.org/content/repositories/snapshots): Connect to repository.apache.org:443 [repository.apache.org/65.109.119.155] failed: connect timed out
[INFO] Downloading from test.release: https://repository.apache.org/content/repositories/snapshots/org/apache/beam/beam-sdks-java-maven-archetypes-examples/2.61.0-SNAPSHOT/beam-sdks-java-maven-archetypes-examples-2.61.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by chamikaramj** [comment]
cc: @Abacn

**Comment by chamikaramj** [comment]
Seems like this is still broken after https://github.com/apache/beam/pull/32841.

@Abacn can you check ?

**Comment by chamikaramj** [comment]
I think the issue is:

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

- The deprecated "gradleEnterprise.buildScan.buildFinished" API has been replaced by "develocity.buildScan.buildFinished"
- The deprecated "gradleEnterprise.buildScan.buildScanPublished" API has been replaced by "develocity.buildScan.buildScanPublished"
- The deprecated "gradleEnterprise.buildScan.onError" API has been replaced by "develocity.buildScan.onError"

**Comment by chamikaramj** [comment]
https://github.com/apache/beam/actions/runs/11444459705/job/31839384547

**Comment by Abacn** [comment]
the number of failed task improved but still very flaky. The latest run fails one task.

This error is because client failed to fetch maven-metadata.xml for `beam-sdks-java-maven-archetypes-gcp-bom-examples:2.61.0-SNAPSHOT` from snapshot repo, it falls back to maven central, where 2.61.0-SNAPSHOT does not exist.

-----

In general it seems network condition changed recently and the availability of maven snapshot repo becomes worse than before. #32841 mitigated the issue (originally 8/8 task fail) but it still highly flaky (1-5 out of 8 task fail)

**Comment by chamikaramj** [comment]
Is it possible to push SNAPSHOTs to somewhere else ? For example, to a GCP Artifact Registry repository.

**Comment by chamikaramj** [comment]
Might be good to check with Apache INFRA first regarding why the SNAPSHOT repo became unstable.

**Comment by Abacn** [comment]
Opened https://issues.apache.org/jira/projects/INFRA/issues/INFRA-26230?filter=allopenissues

> For example, to a GCP Artifact Registry repository.

In theory we can, just need to invest in migrations.

**Comment by Abacn** [comment]
It is caused by maven service side issue that is resolved for now
