### ISSUE TITLE
[Task]: Document Jinja templatization for yaml

### ISSUE THREAD

**Issue by robertwb** [apache/beam#32873]
### What needs to happen?

This is mentioned nowhere in https://beam.apache.org/documentation/sdks/yaml/ or our other yaml docs. 

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [X] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [X] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by robertwb** [comment]
@Polber

**Comment by mravi** [comment]
@robertwb @Polber can I take this issue ?

**Comment by Polber** [comment]
> @robertwb @Polber can I take this issue ?

@mravi Feel free to take this on! Thanks

**Comment by mravi** [comment]
.take-issue

**Comment by robertwb** [comment]
Sorry, @mravi , I just now saw that you had signed up to do this. (I started writing the docs when I realized there was no place to document the new datetime availability I had just added.)

**Comment by mravi** [comment]
thanks for the heads-up @robertwb !  please feel free to take the issue
