### ISSUE TITLE
[Task]: Update Debezium test container back to latest

### ISSUE THREAD

**Issue by jrmccluskey** [apache/beam#32937]
### What needs to happen?

To fix #32936 the test container version for `debezium/example-postgres` was moved to a hard-coded version instead of latest, as the `latest` tag was no longer present on their container registry. This should be remedied once a `latest` container is tagged at https://hub.docker.com/r/debezium/example-postgres/tags

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [X] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by Abacn** [comment]
fixed by #32926
