### ISSUE TITLE
[Bug]: OnnxModelHandlerNumpy broken with latest onnx version

### ISSUE THREAD

**Issue by gariepyalex** [apache/beam#32998]
### What happened?

There is a runtime error when loading a ONNX model with `OnnxModelHandlerNumpy` when using ONNX's latest version:
```python
from apache_beam.ml.inference.onnx_inference import OnnxModelHandlerNumpy

model_handler = OnnxModelHandlerNumpy(
    "/tmp/model.onnx" # Also crashed with a remote model URI gs://...
)
```
Here is the error, which happens using the DirectRunner:
```
/3.10.14/lib/python3.10/site-packages/apache_beam/ml/inference/onnx_inference.py", line 119, in load_model
    model_proto_bytes = onnx._serialize(model_proto)
AttributeError: module 'onnx' has no attribute '_serialize' [while running 'RunInference/BeamML_RunInference']
```

```
pip freeze | grep onnx       
onnx==1.17.0
onnxruntime==1.19.2

pip freeze | grep beam
apache-beam==2.60.0
```

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by gariepyalex** [comment]
The error goes away by downgrading to ONNX 1.14.1 (Aug 2023).

**Comment by damccorm** [comment]
Thanks for calling this out - working on a quick fix here - https://github.com/apache/beam/pull/33000
