### ISSUE TITLE
[Bug]: KafkaIO maintains duplicate caches for record size and offset estimators caches

### ISSUE THREAD

**Issue by sjvanrossum** [apache/beam#33097]
### What happened?

Offset consumers are created and cached for every `KafkaSourceDescriptor` processed per `ReadFromKafkaDoFn` instance. Caching multiple open Kafka consumers for the same `KafkaSourceDescriptor` is expensive both on the client and server side and may exhaust connection limits on some Kafka clusters.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

**Comment by sjvanrossum** [comment]
Fixed provided in #32928.

**Comment by sjvanrossum** [comment]
@damccorm it's not a hard blocker, but since #32928 was approved last week (pending merge of #32921, now merged) I figured I'd flag it on the milestone for your awareness in case you'd like to see it included in 2.61.0.

**Comment by damccorm** [comment]
Closing since https://github.com/apache/beam/pull/32928 is merged
